### ISSUE TITLE
MARECO fails on this specific train schedule

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#10011]
### What happened?

This train works fine with linear margin but fails with MARECO
[bug_mareco_Cyril.json](https://github.com/user-attachments/files/18081520/bug_mareco_Cyril.json)

### What did you expect to happen?

MARECO should work here

### How can we reproduce it (as minimally and precisely as possible)?

Import the train schedule and set its margin to MARECO

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

94d3a84

**Comment by eckter** [comment]
Can't reproduce for now, on neither dev nor the given commit
