### ISSUE TITLE
After new TrainSchedule retrieval, SpeedSpace graph is not updated automatically

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1021]
**Describe the bug**
Considered as a regression. 

**To Reproduce**
Add a margin on a march. After computation, SpaceTime graph is updated, but not the SpeedSpace graph

**Expected behavior**
Every related graph are automatically updated after a schedule

**Smartphone (please complete the following information):**

**Additional context**

**Comment by flomonster** [comment]
Done
