### ISSUE TITLE
Document the current software architecture

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1026]
- [ ] document domain objects (https://dgexsolutions.github.io/osrd-website/fr/developers/internals/data-model/usage-example/)
- [ ] document domain operations
  - [ ] pathfinding
  - [ ] standalone simulation
  - [ ] timetable management and visualization
  - [ ] infrastructure edition (changes, full refresh, ...)
- [ ] document how the database is used across services
- [ ] document the motivating constraints behind current architecture choices
- [ ] document future architecture constraints
- [ ] front interactive documentation of components
- [ ] https://github.com/DGEXSolutions/osrd/issues/1100
- [ ] Sequence diagram for each user operation
- [ ] Improve `front/README.md`
  - Architecture introduction
  - List used technologies (React, mapbox, redux)
- [ ] Helpers functions should be well documented and listed to avoid code duplication.

**Comment by elzinko** [comment]
needs discussion : representation and localization of architectural diagrams (how and where)

**Comment by elzinko** [comment]
needs refinement on each steps

**Comment by flomonster** [comment]
This issue is too big we will split it into multiple simple tasks
