### ISSUE TITLE
I can apply linear allowance to a train

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1032]
## User

- [X] Study officer
- [ ] Manager
- [ ] Other (please write it here)

## Description

When applying an allowance to a train, the user needs to be able to chose between linear and eco distribution.

## Goal

Getting output results comparable with other internal SNCF simulation softwares.

## Acceptance criteria

- [x] The allowance distribution (linear vs eco) must be in a select cage near the value and unit input
- [x] The allowance distribution must be selectable for standard allowance as well as construction allowance
- [x] The allowance distribution must be selectable for every range of the standard allowance
- [x] When selecting a new standard allowance range or an engineering allowance, the default distribution must be the distribution of the default standard allowance
- [x] The user must be able to select standard allowance range or an engineering allowance from PR to PR

## Difficulty

- [ ] easy
- [x] normal
- [ ] difficult
- [ ] extreme

**Comment by elzinko** [comment]
@axrolld to be refined and closed

**Comment by axrolld** [comment]
@alexandredamiron i removed the mockup and the part of the criteria that corresponded to the rangeslider in order to close this story. We'll create a new one when we decide to implement the rangeslider.
