### ISSUE TITLE
Implement signaling simulation

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1046]
## Associated Feature / User Story

#1028 

## Description

Implement the API described [in the design document](https://dgexsolutions.github.io/osrd-website/fr/developers/internals/simulation-model/signaling/). It has to be modular.

```mermaid
flowchart TD
    
    railjson-integration[Integrate into RailJSON]
    signaling-lib[Core signaling library]
    signaling-infra[Signaling infrastructure loading and block creation]
    signaling-modules[Signaling modules]
    signaling-sim[Signaling simulation with interlocking]

    railjson-integration --> signaling-lib
    signaling-lib --> signaling-infra
    signaling-lib --> signaling-modules
    signaling-infra --> signaling-sim
    signaling-modules --> signaling-sim
```

- #2610
- #2397
- #2398
- #2399
- #2400

## Goal

Write unit tests for a simulation of routes, which relies on zone reservation

## Acceptance criteria

- [ ] Implementation is complete as per documented specification
- [ ] Unit tests for common use cases are written
- [ ] Make a toy visualization tool

## Difficulty

- normal

**Comment by axrolld** [comment]
I'm taking this out of the PI cause it needs more refinement.
