### ISSUE TITLE
[meta] Migrate standalone simulation to the new backend

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1053]
## Associated Feature / User Story

#1028

We currently simulate signaling independently for each train, and try to merge and project the result on whatever path the client
requests. This, unfortunately, does not work as intended.

The new workflow will be as follows:
 - resource usage is computed independently for each train, and saved into the database https://github.com/DGEXSolutions/osrd/issues/3505
 - when the client requests a space time diagram, resource usage of all trains is merged together, and used to drive signaling  https://github.com/DGEXSolutions/osrd/issues/3504
 - there will be no need for re-projection of signaling simulations. the current implementation can be removed, and the call to the new signaling simulation endpoint can be made in editoast https://github.com/DGEXSolutions/osrd/issues/3507

## Goal

Once this task is complete, the current temporary simulation engine can be dropped in favor of the fancy one.

## Acceptance criteria

- [x] space time diagrams can be queried just like before
- [x] signaling is computed using the new backend

**Comment by axrolld** [comment]
Deleted from PI board because it's not ready yet
