### ISSUE TITLE
Explore project management tools

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1068]
## Task description

Try several project management tools/software and see if they can suit our needs.

## Goal

There's an urgent need to get a project management tool to organize non-technical work and link it efficiently to development tasks. 

## Additional content

https://www.taiga.io/
https://www.zenhub.com/
https://clickup.com/
https://www.tuleap.org/fr/
https://www.wrike.com/fr/

## Difficulty

- easy

**Comment by elzinko** [comment]
Here is the first version of the project management tools benchmark : 


![Image](https://user-images.githubusercontent.com/5435839/170287920-b317259e-92c1-4689-98d6-49bc641ec734.jpg)
