### ISSUE TITLE
Define the User Stories writing, proofreading, and validation process

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1070]
## Associated Feature / User Story

This enabler will facilitate every future user story.

## Description

Right down how user stories will be written, proofread, and validated, who will be implied at which step, etc. Shortly, build the entire process of user stories creation, from writing to validating.

## Goal

The customers of the project want our interactions to be better organized, and also want more feedback on our work. This enabler will make communication much easier and faster to build user stories much more efficiently.

## Acceptance criteria

- [ ] The process of writing has been defined
- [ ] The process of proofreading has been defined
- [ ] The process of validation has been defined

## Difficulty

- normal

**Comment by flomonster** [comment]
not an issue
