### ISSUE TITLE
GET bug : train runs out block section

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#1088]
![image](https://user-images.githubusercontent.com/55697888/172347394-6a843384-f8c5-40f9-8367-8a4c3f5d2183.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by flomonster** [comment]
Done
