### ISSUE TITLE
Write a Tree of Components

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1101]
Enable https://github.com/DGEXSolutions/osrd/issues/598

**Comment by alexandredamiron** [comment]
https://docs.google.com/spreadsheets/d/1owHPA_QdTR3qM5_jbKn14DYmXX0gMNd3_A1PQ8CEaug/edit#gid=0

**Comment by axrolld** [comment]
Closing this issue because it was in the Done piepline of the board.
