### ISSUE TITLE
Write a action plan for Global Front Refacto

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1103]
### Description

Tasks which must be undertook to maintain and improve quality/sclability me be clear and prioritized

Enable https://github.com/DGEXSolutions/osrd/issues/598

### Description
Have a description and a way to monitor operations on ongoing codebase

**Comment by alexandredamiron** [comment]
https://docs.google.com/document/d/1dmYfpW41xnGy3boWUeePJBKWmn9lXr8IPyKcMlvjrtc/edit#

**Comment by axrolld** [comment]
I guess i can close this now that the document has been written ?
