### ISSUE TITLE
StoryBook Demo with one component

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1104]
### Description

Install stroyBook and Show it working with at least one component of the main UI

Enable https://github.com/DGEXSolutions/osrd/issues/598

### Description

- [ ] One component is dispalyable on storybook
- [ ] Proper storybook docs section has been added on READ.me

**Comment by axrolld** [comment]
Closing this issue because it was in the Done piepline of the board.
