### ISSUE TITLE
Build a database of signaling and interlocking scenarios

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1114]
## Associated Feature / User Story

This database would be tremendously helpful with building and verifying the behavior of the simulator in general.

## Description

Make a list of scenarios which describes how the simulation should behave in a given reference case:
Each reference case should have:
 - a track diagram
 - a list of trains, along with their path (and properties, if relevant)
 - a sequence of expected events (signal aspect changes, route activation, ...)

## Goal

- create a list of test cases to validate the simulator
- have a list of test cases which can be used to motivate the design of the simulator
- use these test cases as learning material for engineers

## Acceptance criteria

- [ ] Each test case should be motivated by one or more behaviors to validate (there can be multiple cases checking variations of same behavior)
- [ ] There should be a large and enough list to enable non-railway specialists (us) to be confident that their simulation works
- [ ] Each case should have a short explanation of what it tests
- [ ] Each case should have a track diagram
- [ ] Each case should have a defined context: trains, their path, and more
- [ ] Each case should have a sequence of expected events

## Difficulty

difficult

**Comment by flomonster** [comment]
Done e2e
