### ISSUE TITLE
Selection action "transform" for the infrastructure edition

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#1118]
## User

- [X] Study officer
- [ ] Manager
- [ ] Other (please write it here)

## Description

Select the "transform" icon in the list of action buttons that affect a selection 

## Goal

to transform, rotate or move the whole selection

## Acceptance criteria

- [ ] This button is only enabled when there is at least one selected item
- [ ] While it is on, the selection is surrounded by a rectangle, with a "rotate" icon outside each corner
- [ ] The panel with the selection summary is replaced by a panel with two buttons : "Validate changes" and "Cancel changes"
- [ ] Both buttons are disabled until the user changes something
- [ ] The "Validate changes" emits the new selection position to the backend when clicked
- [ ] The "Cancel changes" resets the selection position
- [ ] The user can drag and drop the rectangle sides or corners to transform the whole selection accordingly
- [ ] The user can drag and drop any "rotate" icon to start rotating the selection around its center
- [ ] If the user press the mouse on a selected item then move it and then release it, it moves the whole selection together

## Difficulty

- [ ] easy
- [ ] normal
- [x] difficult
- [ ] extreme

**Comment by clarani** [comment]
This issue is not relevant anymore
