### ISSUE TITLE
security: fix security vulnerabilities in your dependencies

### ISSUE THREAD

**Issue by elzinko** [OpenRailAssociation/osrd#1135]
**Describe the bug**
Dependabot gives a (long) list of security dependencies vulnerabilities.

**To Reproduce**
1. Go to https://github.com/DGEXSolutions/osrd
2. See warning message on top

**Expected behavior**
We need the vulnerabilities to be fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5435839/173009744-1a4cddc1-aac7-4854-abd6-fc3a2ab053a8.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by flomonster** [comment]
legacy
