### ISSUE TITLE
Isolate schemas

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#1150]
## Short description meaningful for devs and users 

- [ ] Isolate and create a importable python module.
- [ ] Find how it can be imported by poetry (with/without a registry)
- [ ] Add the dependency to `api` and `infra-generator`

**Comment by multun** [comment]
Once the django API will be merged with the edition backend, the schema will be all that remains in the api python module. It will thus be isolated, and may be published on a package registry.
