### ISSUE TITLE
Visualise the TVD sections 

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#1155]
## User

- [X] Study officer
- [ ] Manager
- [ ] Other (please write it here)

## Description

visualize the TVD sections on the map
## Goal

to know which TVD section is occupied during the simulation

## Acceptance criteria
- [ ] I can tick or untick an on/off button to visualize/devisualize the TVD sections (circuits de voie)
- [ ]  When changing the button state, the zoom level of the map should not change
- [ ] The button should be placed in the data layers part of the map settings
- [ ] This operation should not take longer than 1 sec

## Difficulty

- [x] easy
- [ ] normal
- [ ] difficult
- [ ] extreme

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Assumptions of User Story met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Legacy. Not an object anymore
