### ISSUE TITLE
I can reslove conflicts in the timetable by dragging & dropping trains in the timetable

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1156]
## User

- [X] Study officer
- [ ] Manager
- [ ] Other (please write it here)

## Description

If the time table has conflicts, the user must be able to slove them manually with a quick drag & drop in the space-time chart.

## Goal

A proper timetable mustn't have any conflict, so it is necessary to be able to slove them. The drag & drop is a very intuitive way to do so.

## Acceptance criteria

- [ ] When dragging and dropping a train with conflict in the space-time chart on an empty space, the corresponding conflict and all the warnings that came with it must disappear.
- [ ] When dragging and dropping a train with conflict in the space-time chart on another train, the initial conflict must disappear and a new one must be created with the same warning pop-up as in #903.

## Difficulty

- [ ] easy
- [ ] normal
- [ ] difficult
- [ ] extreme

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Assumptions of User Story met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Done
