### ISSUE TITLE
Generate the layer of TVD sections 

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#1157]
## User

- [ ] Study officer
- [ ] Manager
- [x] Front

## Description

have access to the TVD section layer

## Goal

to show them into the OSRD map

## Acceptance criteria

- [ ] The TVD section layer should be correctly created using detectors and buffer stops.
- [ ] The layer should be updated when a detector / buffer stop, track section or topology change.

## Difficulty

- [ ] easy
- [X] normal
- [ ] difficult
- [ ] extreme

## Definition of ready

- [x] The user story is well defined
- [x] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [x] The team should understand how to demonstrate the features
- [x] Does not depend on an missing feature
- [x] Negociable with the implementation team
- [ ] Valuable to the end users
- [x] Estimable by the implementation team
- [x] As small as it can be
- [x] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Assumptions of User Story met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
What is the value to the end user to be able to see all the tvd section of an infrastructure.
Isn't it useful only when a simulation is run?

**Comment by flomonster** [comment]
Legacy. Not an object anymore
