### ISSUE TITLE
I can visualize the timetable of my study

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1158]
## User

- [X] Study officer
- [ ] Manager
- [ ] Other (please write it here)

## Description

The timetable represents all the trains running during a specific period of time (typically one day) and in the area being studied. The user must be able to visualize the timetable with all the elements listed in the acceptance criteria.

## Goal

The timetable is a very important tool for study officers. It is necessary to have this feature in OSRD.

## Acceptance criteria

Coming soon.

## Additional content

Coming soon.

## Difficulty

- [ ] easy
- [ ] normal
- [ ] difficult
- [ ] extreme

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Assumptions of User Story met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Done
