### ISSUE TITLE
I can reslove conflicts in the timetable by manually changing the allowance(s) applied to a train

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1160]
## User

- [X] Study officer
- [ ] Manager
- [ ] Other (please write it here)

## Description

If the timetable has conflicts, the user must be able to slove them manually by manually changing the allowance(s) applied to the trains.

## Goal

A proper timetable mustn't have any conflict, so it is necessary to be able to slove them.

## Acceptance criteria

- [ ] When manually applying an allowance to a train in conflict in order to free it, the corresponding conflict and all the warnings that came with it must disappear.
- [ ] When manually applying an allowance to a train in conflict and it gets in a conflict with another train, the initial conflict and all the warnings that came with it must disappear, and a new one must be created with the same warning pop-up as in #903.

## Additional content

There should be no need for aditionnal content for this story.

## Difficulty

- [ ] easy
- [ ] normal
- [ ] difficult
- [ ] extreme

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Assumptions of User Story met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Done
