### ISSUE TITLE
Trains react to BAL3 signalization

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1161]
## User

- [X] Study officer
- [ ] Manager
- [ ] Other (please write it here)

## Description

The trains must take into account the state of signals when being simulated in OSRD. This first story is only about BAL3 signals because it is the easiest signalling system to simulate. The way the train is supposed to react is descibed in the acceptance criteria.

## Goal

Interactions between trains and signals are absolutely necessary in order to simulate a timetable with conflicts realistically. Without these interactions trains might collide.

## Acceptance criteria

Coming soon.

## Additional content

Coming soon.

## Difficulty

- [ ] easy
- [ ] normal
- [ ] difficult
- [ ] extreme

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Assumptions of User Story met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
legacy
