### ISSUE TITLE
Generate the layer of PK

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#1162]
## User

- [ ] Study officer
- [ ] Manager
- [x] Front

## Description

have access to the PK layer

## Goal

to visualise them into the OSRD map

## Acceptance criteria

- [ ] The Pk must be added to the model
- [ ] The Pk must be imported from Gaia
- [ ] The layer should be correctly created 

## Difficulty

- [ ] easy
- [ ] normal
- [x] difficult
- [ ] extreme

## Definition of ready

- [ ] The user story is well defined
- [x] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [x] The team should understand how to demonstrate the features
- [x] Does not depend on an missing feature
- [x] Negociable with the implementation team
- [x] Valuable to the end users
- [x] Estimable by the implementation team
- [ ] As small as it can be
- [x] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Assumptions of User Story met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
This US should be split and better defined about how the user can edit PK.

**Comment by flomonster** [comment]
The design is in progress. A new issue will pop with more details
