### ISSUE TITLE
Design an ETCS braking curves computation module

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1328]
## Description

This task should only be started once the initial [impact analysis of implementing ETCS level 2](https://github.com/DGEXSolutions/osrd/issues/1327) is fleshed out.

When a train responds to ETCS signaling, it computes braking curves using a fairly intricate process. We need to abstract these computations away. 

## Goal

Design a reusable ETCS braking curve computation module.

## Acceptance criteria

- [ ] The results of this research are documented on the website
- [ ] The design constraints are documented
- [ ] The inputs and outputs of this module are specified
- [ ] Update #1414

**Comment by celine-sncf** [comment]
@axrolld can we close this issue ?
