### ISSUE TITLE
CRUD caternaries

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#1331]
## Associated Feature / User Story
F2 : display layers
How to implement this US: #1410

## Description
Create the caternary layer (electric voltage value on the tracks)

## Goal
in order to dispay the caternary layer into OSRD map and in future to edit the caternary voltage values

## Acceptance criteria
- [ ] I can query creation / update / deletion of caternary voltage values.
- [ ] The query should return an error if something went wrong and the operation couldn't be applied.
- [ ] If a caternary voltage value is not attached to existing track, a meaningful, error should be reported in the error layer.

## Difficulty

- [X] easy
- [ ] normal
- [ ] difficult
- [ ] extreme

**Comment by flomonster** [comment]
done
