### ISSUE TITLE
Refactoring OSRD Front 

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#1357]
## Associated Feature / User Story

This is not linked to any US 

## Description

Resolution of several front bugs 

## Goal

to make the application more stable

## Acceptance criteria
All the bugs of the following list will be corrected
- [x] https://github.com/DGEXSolutions/osrd/issues/1076
- [ ] https://github.com/DGEXSolutions/osrd/issues/515
- [x] https://github.com/DGEXSolutions/osrd/issues/333
- [x] https://github.com/DGEXSolutions/osrd/issues/326
- [x] bump front dependencies (lié à  ces PR: https://github.com/DGEXSolutions/osrd/pulls
q=is%3Apr+is%3Aopen+label%3Ajavascript+label%3Adependencies+)

## Difficulty

- [ ] easy
- [X] normal
- [ ] difficult
- [ ] extreme

**Comment by axrolld** [comment]
I'm closing this issue as it is now about #515 only
