### ISSUE TITLE
Ask for a short Short Term DCM within a simulation

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1362]

**Comment by alexandredamiron** [comment]
PO to refine acceptance criterias

**Comment by elzinko** [comment]
@alexandredamiron @axrolld user story is not refined and not ready so we are moving it.
This is an important part of STDCM. We need a meeting between @flomonster @El-Youssef @elzinko to discuss design between services (interface) 
see #1413 that is an enabler of that story

**Comment by axrolld** [comment]
@carolnvg should be part of the meeting as well.

Should we schedule a meeting next week after the mockups being validated by @loic-hamelin ?

**Comment by axrolld** [comment]
## User



Train driver

## Description



Given a timetable, the user must be able to ask for a short-term DCM, _i.e._ a new train slot that can fit in the existing timetable, without generating any conflict with the planned trains.



See #1430 for mockups.

## Goal



Demonstrate that OSRD is able to compute Short-Term DCM.

## Acceptance criteria



- [ ] The new time slot must not generate any conflict with existing trains
- [ ] The running time of the new train slot must be greater or equal than the one with a standard allowance
- [ ] The computation time must not exceed 2mn
- [ ] The final running time calculcation must come from OSRD running time calculation algorithm
- [x] The UI/UX must follow the work done in #1430 

## Story points



5

## Definition of ready




- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done




- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated
