### ISSUE TITLE
Position of train on the map must be precise: Provide a test case

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1363]
The current representation of train position on the map seems to be unaacurate: at certain stops times, train is represented before or after the concerned PR.

**Comment by alexandredamiron** [comment]
Provide to back engineering a test cas with clear unaccurate position and screenshot

- [ ] describe the parameters of simulation
- [ ] provide screenshots

**Comment by alexandredamiron** [comment]
relate to #1365

**Comment by axrolld** [comment]
Closing this issue because it was in the Done piepline of the board.

**Comment by multun** [comment]
I can confirm it's been done
