### ISSUE TITLE
Visualy apply default BAL3 signal state on signals concerned by simulation

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1364]

**Comment by alexandredamiron** [comment]
- [ ] BAL 3 signals concerned by simualtion have a default state visible

**Comment by alexandredamiron** [comment]
implements #948

**Comment by multun** [comment]
When a signal is outside of the path of the currently active train, we just don't know how it looks over time, as we don't run this type of simulation. The issue you've linked in a comment has already been closed for this reason
