### ISSUE TITLE
Fix Feature Properties Format (eg Signals - Chartis)

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1386]
Signals (and certainely other) features properties format has been changed, at least for string properties. extra escapes quotes added. Properties are now unreadable by front on its current state, leading to signals disapearrance, unability to determine its side for angle computation, etc....

Please restore a proper format

Blocks #1364

![Image](https://user-images.githubusercontent.com/765626/177499047-0668bcb1-55f6-4a19-9780-24f6df967d03.png)

**Comment by multun** [comment]
Fixed by 85b4b3d3a1cbdf38bb0dd9c45cd7a141f75f13ca
