### ISSUE TITLE
Make code coverage visible by anyone

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1411]
## User

- [ ] Study officer
- [ ] Manager
- [X] Any developper interested in OSRD

## Description

Make code coverage data both available as a percentage and as a map.

## Goal

Demonstrate quality.

## Acceptance criteria

- [ ] The coverage is visible as a precentage, as well as a map
- [ ] A link to code coverage is added to developper's documentation
- [ ] A link to code coverage is added to the general page about project's quality on OSRD website (see #1330 )

## Difficulty

- 2

## Definition of ready

- [x] The user story is well defined
- [x] Acceptance criterias are defined
- [x] The individual responsible for validating the user story is assigned
- [x] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [x] Negociable with the implementation team
- [x] Valuable to the end users
- [x] Estimable by the implementation team
- [x] As small as it can be
- [x] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Assumptions of User Story met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Done
