### ISSUE TITLE
Implement an ETCS braking curves computation module

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1414]
## Associated Feature / User Story

Depends on #1328

## Goal

Make a reusable ETCS curve computation module.

## Acceptance criteria

- [ ] Implement the APIs defined by #1328
- [ ] Ensure the delivered APIs can be used to simulate any braking curve to a given location / speed

**Comment by celine-sncf** [comment]
@axrolld can we close this issue ?
