### ISSUE TITLE
Implement speed limits per train type in the backend

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1416]
## Associated Feature / User Story

Running time calculation with speed limits per train type

## Description

Simulations should handle speed limits per train type, as specified in #1326 

## Acceptance criteria

- [ ] The rolling stock format was changed to include labels
- [ ] Speed limits per train type are imported and stored
- [ ] Speed limits per train type are enforced

**Comment by axrolld** [comment]
Duplicate with #1470
