### ISSUE TITLE
Integrate the STDCM edges' weight estimation in the backend

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#1417]
## Associated Feature / User Story
Feature F3: "Tracer un sillon dans la capacité résiduelle"

## Description
Integrating the computation part of STDCM algorithm. This implies building a residual capcity graph and estimate the edges' weigths.

To do list :
- [ ] Build a residual capacity graph
- [ ] Calculate the weight of each edge in the graph
- [ ] Find a path within the digital capacity

## Goal
Integrating the STDCM algorithm and adapting the existing code to meet the project coding criteria.

## Acceptance criteria

- [ ] The integrated code must deliver the same results as the existing code
- [ ] The algorithm must deliver the right output format (see #1413)

## Story points

5

## Definition of ready

- [ ] The enabler story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the enbaler story is assigned
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by axrolld** [comment]
@El-Youssef  to merge in #1333.

**Comment by El-Youssef** [comment]
Merged into #1333
