### ISSUE TITLE
Editoast container crashes on certain environments

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#1429]
```
thread 'main' panicked at 'Error loading speed section refs:
DeserializationError(UnexpectedNullError)', src/infra_cache.rs:507:46
```

This doesn't seem to happen everywhere. I have the error when importing any infra in my windows computer, but not on the ubuntu one.

**Comment by eckter** [comment]
It seems to be fixed after removing every docker image *and* volume before restarting the service. I'll wait for a confirmation of @jacomyal

**Comment by multun** [comment]
@eckter this bug was fixed on master by https://github.com/DGEXSolutions/osrd/commit/f4db76f386a361dc506caf2d579bec875428e2d9#diff-2418fd10e94ea5550e4a5f5b66a07da9de1a4a2c4fe376681436f9723c9f0426R505
