### ISSUE TITLE
Initialize some documentation about OSRD software quality

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1437]
## Description

Write an overview of the quality strategy.
- [software quality](https://en.wikipedia.org/wiki/Software_quality)
- [built-in strategy](https://en.wikipedia.org/wiki/Software_quality#Definitions)
- [what is software quality](https://www.testbytes.net/blog/what-is-software-quality/)

## Goal

Increase public trust and reputation of the project.

**Comment by elzinko** [comment]
- First draft is available [here](https://docs.google.com/document/d/1Ft1kAqyFkP6XHHIIjd3l1sSY_kCaVBeARjbvEfsX_bA/edit?usp=sharing)
- Pull request is [here](https://github.com/DGEXSolutions/osrd-website/pull/44)
