### ISSUE TITLE
Implement speed limits per train type in the backend

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1470]
## Associated Feature / User Story

Running time calculation with speed limits per train type / category

## Description

#1326 defined a data model and updated railjson. The backend should take these speed limits into account.

## Acceptance criteria

- [x] Train labels are loaded by the backend
- [x] Speed limits are selected using train labels

## Story points

- [ ] 1
- [ ] 2
- [x] 3
- [ ] 5
- [ ] 8

## Definition of ready

- [x] The enabler story is well defined
- [x] Acceptance criterias are defined
- [x] The individual responsible for validating the enbaler story is assigned
- [x] Does not depend on an missing feature
- [x] Negociable with the implementation team
- [x] Valuable to the end users
- [x] Estimable by the implementation team
- [x] As small as it can be
- [x] Testable by the implementation team

## Definition of done

- [x] Acceptance criteria are met
- [x] Automated tests are written against acceptance criteria
- [ ] Story ok-ed by Product Owner
- [x] Documentation updated

**Comment by elzinko** [comment]
@axrolld needs validation
