### ISSUE TITLE
more documentation about OSRD software quality

### ISSUE THREAD

**Issue by elzinko** [OpenRailAssociation/osrd#1473]
## User

- [ ] Study officer
- [ ] Manager
- [X] Anyone interested in the project

## Description

Write an overview of the quality strategy.
-[built-in strategy](https://en.wikipedia.org/wiki/Software_quality#Definitions)
-[what is software quality](https://www.testbytes.net/blog/what-is-software-quality/)

## Goal

Increase public trust and reputation of the project.

## Acceptance criteria

- [ ] a norm for software quality strategy has been chosen
- [ ] an inventory of the existing quality metrics related to Software Quality Model and their related relevancy (simulation accuracy, bug tracking, ...) has been chosen

## Story points

- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 5
- [ ] 8

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned : @axrolld 
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Done
