### ISSUE TITLE
Isolate infra generator

### ISSUE THREAD

**Issue by elzinko** [OpenRailAssociation/osrd#1491]
## Short description meaningful for devs and users 

- externalize core/examples/generated/lib into a new python library outside of code
- use mono repo library requirement handling
- for now we keep the [scripts](core/examples/generated/scripts) inside core

## Motivation

This will avoid having weird import such as this: https://github.com/DGEXSolutions/osrd/blob/8bba27c247b826a3c74ae49247a6f4fad6c945dc/tests/run_integration_tests.py#L34

## Dependencies
- https://github.com/DGEXSolutions/osrd/issues/1150

**Comment by flomonster** [comment]
Done
