### ISSUE TITLE
Design of ERTMS V1.0.0

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1514]
## Associated Feature / User Story

First version of ERTMS ETCS 2

## Description

Design a way to adapt what has been done in #1510 to make it cleaner and more consistent with the signaling system in back-end.

## Goal

Prepare the implementation of V1.0.0

## Acceptance criteria

- [ ] The design should make ETCS 2 become a signalling system just like BAL3 is

## Story points

8

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Legacy
