### ISSUE TITLE
The front-end incorrectly parses the local backend setting

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1523]
**Context**

When REACT_APP_LOCAL_BACKEND is enabled, the front-end completly ignores authentication.

**Expected behavior**

I'd expect that the front-end only use a local backend when REACT_APP_LOCAL_BACKEND is True, 1 or something, not just exist.

**Why it matters**

This is an issue because if you set it to False, the front-end will still use the local backend setup. This is pretty confusing, and did cost us a lot of time and debugging.

**Comment by flomonster** [comment]
Fixed
