### ISSUE TITLE
Fix accuracy on train position on the map

### ISSUE THREAD

**Issue by elzinko** [OpenRailAssociation/osrd#1564]
## Acceptance criteria

- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria 3

## Story points

1 / 2 / 3 / 5 / 8

## Definition of ready

- [ ] The enabler story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the enbaler story is assigned
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by axrolld** [comment]
Duplicate with #1469
