### ISSUE TITLE
Editor: create a custom JSON Schema field for reference object

### ISSUE THREAD

**Issue by sim51** [OpenRailAssociation/osrd#1565]
**Describe the current situation**
When you add a signal for example, it must be attached to a track section.
This is the `ObjectReference` in the JSON Schema. 

For now we display this fields as a form, and we should not (user should not be allowed to change manually this value).

**Describe your improvement**

Perhaps we just need to hide those kind of field.

**Comment by jacomyal** [comment]
Closing as this is no more relevant.
