### ISSUE TITLE
Move BAL/ERTMS toggler to the home page

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#1638]
BAL/ERTMS toggler is currently placed in the simulation tab. This would lead in a global change in the signalling system when the toggler is switched : every train of the time-table would get a different signalling system.

The desired behavior is that every train has its own signalling system, so it has to be difned by the user when creating the train.

**Comment by multun** [comment]
This task was a temporary measure until proper signaling systems support was implemented
