### ISSUE TITLE
Editor: loading gauge cannot be left empty

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#1671]
## Current behavior

When we are trying to edit or create a new track section the front-end impose to have a loading gauge restriction that cover the whole range of the track section.

## Expected behavior

- We can keep empty the loading gauge restriction (In most cases this will be the case).
- We can have loading gauge restrictions with overlapping range.
- Since the type of loading gauge is finite we should be able to define restriction for each type of loading gauge

**Comment by sim51** [comment]
Fixed in PR

For gauge limit, we don't use the linear metadata component anymore, but just a the form component.
