### ISSUE TITLE
Bug on the edition (frontside) : whitescreen

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#1704]
**Describe the bug**
When we try to edit a line, clicking on the on the line edition button, it produces a whitescreen.

**To Reproduce**
1. Go to https://osrd.dev.dgexsol.fr/
2. Go to 'éditeur d'infrastructure'
3. Select an edition area
4. Click on the line button
5. See the whitescreen

**Expected behavior**
Could edit lines

**Screenshots**
![image](https://user-images.githubusercontent.com/27173221/185378069-331e86b6-dfa7-4758-aaaf-2771046bd449.png)
![image](https://user-images.githubusercontent.com/27173221/185377708-036f8723-82a4-4162-908f-b5991243e903.png)

**Environnement**
 - Browser : firefox (version : 103.0.2)

**Comment by sim51** [comment]
* Are there JS errors in the console ?
* Is it working on an other web browser (chrome or firefox) ?

FYI, I can't use the demo instance,  every call to the APIs fails (`403 Forbidden` for editaost & chartos).
Do you know what should I do to resolve this issue ?

**Comment by Tguisnet** [comment]
I fix my bowser name (it was not safari but firefox)
It doesn't not work on chrome either

console logs :
![image](https://user-images.githubusercontent.com/27173221/185393844-191f2bc2-2f0e-49c9-be0f-b33e97c009a0.png)

for your issue, florian answered et fix it :) !

**Comment by sim51** [comment]
Thanks to Florian, I have access now to the demo server, and I can reproduce the issue with Firefox.
