### ISSUE TITLE
Docker-compose error

### ISSUE THREAD

**Issue by axlFThn** [OpenRailAssociation/osrd#1731]
**Describe the bug**
Docker-compose generates ERROR: The Compose file './docker-compose.yml' is invalid.

**To Reproduce**
1. git clone https://github.com/DGEXSolutions/osrd.git
2. cd osrd
3. docker-compose up
4. Error

**Expected behavior**
docker containers get up

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Raspbian OS (Debian GNU/Linux 11 (bullseye))
 - Browser firefox
 - Linux version 5.15.56-v8+ 

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by flomonster** [comment]
Checkout the v0.1.3 it should work
