### ISSUE TITLE
Speed by categories not synced with infra selection

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#1753]
**Describe the bug**

Speed sections category doesn't match the selected infra.

**To Reproduce**
1. Go to https://osrd.dev.dgexsol.fr/osrd/settings
2. Select `small_infra`
3. Refresh the page
4. Select `france` infra
5. Pick a speed category (the list is empy)

**Expected behavior**

We should see all the available speed categories.

The list of categories should be refreshed when we changing infrastructure.

**Comment by nicolaswurtz** [comment]
Corrected in #1754
