### ISSUE TITLE
Missing panels on signals layer

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#1768]
In signals layer, panels are missing. I've verified with QGIS connected to chartos API, panels are missing too.

From OSRD : 
![image](https://user-images.githubusercontent.com/6003856/187407124-5617e901-5bce-40fa-a3ad-f75c8ef149b2.png)

From openData : 
![image](https://user-images.githubusercontent.com/6003856/187407286-0f93a84a-a966-4890-990f-a317beb01cad.png)

Version: 3dbd5632

**Comment by flomonster** [comment]
This is not a bug. OSRD doesn't handle these panels. We should create a feature for that.
