### ISSUE TITLE
Merge editoast, chartos and api

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1794]
### Discussed in https://github.com/DGEXSolutions/osrd/discussions/1782

<div type='discussions-op-text'>

<sup>Originally posted by **multun** August 31, 2022</sup>
# Description of the new architecture

![Image](https://user-images.githubusercontent.com/15349030/213433607-19479256-4737-4b41-a274-fd2ba189e7e9.png)

The only change to the previous architecture is the merge of chartos, editoast and the api into a single rust service.
This service would be responsible for handling storage and lifetime of all data related to the application.

The main rationales driving this change are fairly straightforward:
 - all 3 services generate cached data which must be invalidated when other cached data / source data changes. Having to deal with this issue in a single service and codebase is hard enough, dealing with it in a distributed manner is a show-stopper.
 - chartos is incredibly tiny, and the django api is shrinking in size

# Upsides

- there would be single web service queried by the front-end, unifying chartos, editoast and the django api service.
- the postgres database wont be shared by multiple services anymore
- no more invalidating the chartos cache from editoast
- easier refactorings across codebases
- less tech stacks: we would switch from django + fastapi + java + rust to just java + rust
- speedup all kind of processing currently done by the API, such as post-processing simulation results
- consistent policies / authentication are easier to implement

# Drawbacks

- migrating costs time
- no more django admin
- rust ORMs aren't yet as fancy as the django ORM
- no more django rest framework
- rust has a steeper learning curve than python

# Migration plan

- until the plan starts, avoid adding new code into the django api
- #1796
- #1795 
- port api to rust, merge it into osrd-webservice
  - #1797
  - #1798 
  - #1799
  - #1150

# Todo
- [ ] create a presentation for the migration of the services in Rust
- [x] create the enabler in the PM Board

**Comment by Castavo** [comment]
@multun Path finding is cited in both `core` and  `osrd-webserver` is it intended ?
