### ISSUE TITLE
Generate per-language schemas using openapi-generator

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1848]
## Description

Generate schema classes and api boilerplate from the openapi spec instead of trying to keep the spec up to date from the code.
It is a LOT of work, but brings immense benefits.

## Benefit Hypothesis

Improved ability to document API changes / detect API mismatches.

## Acceptance criteria

- [ ] The OpenAPI specifications is split into [separate files](https://swagger.io/docs/specification/using-ref/#syntax)
- [ ] Every component uses generated API boilerplate and classes

**Comment by flomonster** [comment]
We did setup utoipa.
