### ISSUE TITLE
STDCM: Ensure intersecting train are correctly represented

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1916]
## Description
Two or more trains can share the same path only for a portion of the path represented on the GET, which is the projection of the selected train. (Refers to updateProjection reducer operation)

## Goal
On STDCM project, check that is is the case

## Accceptance criteria

- [ ] Describe a use case which will provide two intersecting trains on a running infra in stdcm context. 
- [ ]  Create an stdcm train which will use or portion on the path employed by the other train. 
- [ ] Ensure that these train are partially represented on the GET and that the projection is the one from stdcm.

**Comment by clarani** [comment]
Already done.
