### ISSUE TITLE
Remove all warning on front startup

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1922]
## Description
We unified eslint - prettier configuration, it is time to make every launch warning disappear

## Goal
At react-script init, make sure every warning are treated.

## Acceptance criteria

- [x] No eslint/rpettier warnings at startup
- [ ] Once its done discuss how to make these rules more mandatory: in the CI

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by axrolld** [comment]
Second acceptance criteria moved to #2105
( @alexandredamiron update this)
