### ISSUE TITLE
Design an API for reporting signal state metadata to the frontend

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1925]
## Associated Feature / User Story

- #1028 

## Description

Design an API for reporting a signal state to the frontend

**Comment by axrolld** [comment]
I'm taking this out of the PI cause its needs more refinement.

**Comment by multun** [comment]
Fixed as part of the design of the new [signaling simulation model](https://dgexsolutions.github.io/osrd-website/fr/docs/reference/design-docs/signaling/)
