### ISSUE TITLE
Implement a BAL signaling module

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1926]
## Associated Feature / User Story

#1028 

## Description

Implement a BAL3 module which uses the new simulation API. This is required to replace the existing solution.

## Acceptance criteria

- [ ] Implementation is complete as per documented specification
- [ ] Unit tests for common cases are written
- [ ] BAL3 signals can report metadata as specified by #1925

**Comment by axrolld** [comment]
Removed from PI board because it was out of the objectives
