### ISSUE TITLE
White screen while editing a line

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#1932]
**Describe the bug**
In infrastructure edition, when one move a point of a line, a white screen appears.

**To Reproduce**

- Edition mode
- Select an area
- Select a line
- Edit line
- Select point
- Move point 
- See white screen instead of map

**Expected behavior**
No white screen expected

**Screenshots**

![image](https://user-images.githubusercontent.com/55697888/191221832-4b66e7e5-a38a-4e78-ad54-256da14e02db.png)
![image](https://user-images.githubusercontent.com/55697888/191221961-5e7b949b-b1e6-43cd-afc2-bc93c7845b01.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome 
 - Version Version 80.0.3987.149 (Build officiel) (64 bits)

**Additional context**
Appears in dev or staging environnement

**Comment by clarani** [comment]
This bug can not be reproduced today, it must have been already resolved :ballot_box_with_check:
