### ISSUE TITLE
Js refacto actions done: Slopes, TimeTable, TrainList

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1945]
## Description

Do the js refactoring actions listed in https://docs.google.com/spreadsheets/d/1owHPA_QdTR3qM5_jbKn14DYmXX0gMNd3_A1PQ8CEaug/edit#gid=0

## Goal
Accomplish 25% of the wight of actions

## Acceptance criteria
Action accepted

**Comment by nicolaswurtz** [comment]
Obsolete.
