### ISSUE TITLE
Résoudre les erreurs de layers MapGL qui polluent la console du navigateur dans l'editeur

### ISSUE THREAD

**Issue by jacomyal** [OpenRailAssociation/osrd#1990]
### Description

Aujourd'hui, il y a beaucoup de warnings et d'erreurs qui apparaissent dans la console de développement du navigateur lorsqu'on navigue dans l'éditeur. Elles sont essentiellement liées à MapGL et/ou WebGL. Elles ont un impact clair dans les informations dont ont besoin les développeurs, et un impact potentiel de performance.

### Objectif

Résoudre la ou les causes de ces warnings et erreurs.

### Definition of done

- [ ] Il n'y a plus de warning ni d'erreurs.

**Comment by sim51** [comment]
All the possible work has been done for this ticket, with the current situation (ie. version of MapGL).

We decided with the front team, to migrate to latest version of `MapLibre`, see this ticket #2188
