### ISSUE TITLE
ctrl+mouse for the interactions to manage the navigation in the map

### ISSUE THREAD

**Issue by jacomyal** [OpenRailAssociation/osrd#1991]
## User

Study officer

## Description

Use the mouse by default to handle the elements (selection, edition, selection of zones...), then, using the control key, to manage the navigation in the map.

Today, the default mouse behavior in the editor is always to move the map. The other interactions take place through other, less conventional operations. For example, to move an element, you have to click once to select, then a second time to move it. It's not very practical. 

### Objectif
Improve the user experience in the edition tool concerning the mouse behavior.

## Acceptance criteria

- [ ] The user can easily move an element in the edition tool 
- [ ] The user can easily understand how to create a rectangle 
- [ ] The user can easily move the map (drag and drop, zoom)

## Definition of ready

- [ ] The enabler story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the enbaler story is assigned
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by jacomyal** [comment]
With the current stack (ie until we handle #2188 at least), I did not find a simple enough way to assign panning and zooming the map to "a key + mouse interaction" (instead of mouse interaction only). Indeed, shift, ctrl and alt (as well as using the right button instead of the left button) are all attached to 3D rotation. And disabling rotation (using `dragRotate={false}`) simply disabled all interactions when alt, shift or ctrl is pressed.

I will try again once #2188 is solved.

**Comment by Tguisnet** [comment]
Waiting for a ux designer
