### ISSUE TITLE
Train starts backward and ends up forward

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#2028]
**Describe the bug**
During the simulation, on line 430000 (ligne du Mans à Mézidon). The train starts backward, the rear and the front of the train meet in the middle of the voyage, and the train finishes the trip going forward.

![Screenshot_20221005_113031](https://user-images.githubusercontent.com/24652545/194030020-0eb7df3f-40c1-4f85-83e6-54d6be91661d.png)

Length of the train goes to 0 :

https://user-images.githubusercontent.com/24652545/194030387-f8931fd4-27f4-4ddd-a2ea-550120a0744e.mp4

**To Reproduce :**
open OSRD and use this configuration :

![Screenshot_20221005_111530](https://user-images.githubusercontent.com/24652545/194025582-450db797-916f-4785-928f-2e256fb1ddcb.png)

Origin :
![Screenshot_20221005_111556](https://user-images.githubusercontent.com/24652545/194025717-ae377896-3e47-4d7b-92d7-337bbf3311b7.png)

Destination :
![Screenshot_20221005_111628](https://user-images.githubusercontent.com/24652545/194025780-ca2d79f8-185a-4192-86fd-7efb1276f965.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser: chrome
 - Version: 105.0.5195.102

**Comment by axrolld** [comment]
I tried to reproduce the bug and found something even weirder

![image](https://user-images.githubusercontent.com/86296016/194035955-c3f1a131-40be-4478-89f4-13087c4862bd.png)

**Comment by Castavo** [comment]
This bug appears to be fixed in version 3dbd5632

**Comment by Castavo** [comment]
This bug appears to be fixed in version 3dbd5632
