### ISSUE TITLE
stdcm: add stops when we need to add more delay than what allowances can provide

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#2169]
The main use case is when the current path is in front of another train, and we want to "park" on a secondary track until it passes us, and we can restart once it's in front of us.

This will actually be much more tricky than we initially thought, because when a train stops in such a setting it actually stops in front of a "carré" signal. This means we see a yellow signal before, but it's not a conflict because we plan on stopping. The same path without stopping could be considered as invalid.

To handle this, we must wait for the signaling post and conflict detection refactor.  We will probably have to rethink how we input the conflicts.

**Comment by eckter** [comment]
closed the wrong one

**Comment by flomonster** [comment]
Postponed
