### ISSUE TITLE
Add a parameter in railjson to specify if/how we can use the geo coordinates to estimate distances

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#2195]
We want to use A* with an heuristic based on the coordinates, but those values are arbitrary in generated infras. Some bugs appear if we use it.

We should probably have a field at the root of the railjson format specifying whether the coordinates can be used to estimate distance. It could also specify the coordinate system.

**Comment by multun** [comment]
can't we just check if the geometry makes sense?

**Comment by eckter** [comment]
We can, that would be much simpler indeed.
