### ISSUE TITLE
Implement effort curves per position simulation

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#2235]
## User

Study officer 

## Description

use the correct effort curve during the running time calculation to improve the simulations
## Acceptance criteria

- [ ] Once that the infrastructure and the rolling stock with its confort have been selected, depending on the position of the train the right effort curve is used 
- [ ] When the train runs on an infrastructure zone having a power class lower than the rolling stock maximum power class, the curves corresponding to the power restriction having the same power class of the infrastructure zone should been chosen
- [ ] When the train is on a specific level of the electric profile, the curve which corresponds to this level, for the power restriction needed to run on the selected infrastructure and the confort selected by the user, is used
- [ ] If no confort condition is selected, the SC curve should be chosen
- [ ] if no confort condition is selected and there is no SC curve, the ? curve should be chosen
- [ ] if the infrastructure data are not complete (power class or electric profile are missing) the nominal curve should be chosen (max rolling stock power class and 15 KV ou 25) 

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Stuff that wasn't implemented are delayed with the feature F21
