### ISSUE TITLE
Import the electric profile on the track

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#2236]
## Description

Import the power classes (MW) delivered by the substations on the infrastructure and the consequent electric profile on the track 
## Goal

to perform https://github.com/DGEXSolutions/osrd/issues/2235

## Acceptance criteria

- [ ] For all the substations in the actual infrastructure, the values of the power class should be import 
- [ ] The electric profiles for the current infrastructure should be imported.
- [ ] Each profile is composed between two substations by some levels with the following names in order of decreasing power: (M, N ?), 0, A, A1, B, B1, C, D, E, F, G, 
- [ ] If the data are nor complete, the nominal profile (1500 V ou 25 kV) should be taken 

## Definition of ready

- [ ] The enabler story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the enbaler story is assigned
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
Duplicate
