### ISSUE TITLE
Display levels of electric profile on the simulation results

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#2237]
## User

Study officer 

## Goal

Display levels of the infrastructure electric profile (`O`, `A`, `A1`...) on the time table, on the driver train schedule and on the map.

## Acceptance criteria

To be defined

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
We won't do it.
