### ISSUE TITLE
Study gaia to find RPUIS

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#2265]
## Description

Search all the data we need to modelise the infrastructure electrification in OSRD

## Goal

This is a preliminary work for a futur feature. 
## Acceptance criteria

Find the answers to the following questions:
- [ ] Are the positions of substations included in Gaia DB? 
- [ ] Are the power classes of substations included in Gaia DB? In wich format?
- [ ] Are the electric profiles included in Gaia DB? in which format? 
- [ ] Are informations about RPUISS included in Gaia DB? in which format? 

## Definition of ready

- [ ] The enabler story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the enbaler story is assigned
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by Tguisnet** [comment]
We find "RPUIS" in SIPH infra, mmaybe we could searf for it in gaia too
This will be new feature for the next PI
