### ISSUE TITLE
front: projections: the path ID used for projection in the simulation tab seems arbitrary

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#2268]
When we have a timetable with several trains and a different path for each, the path ID used for the projection in the `/osrd/simulation` tab seems rather arbitrary. It *seems* like it takes the path ID of the first train that has been added in the timetable. This gives little control of what we can display.

I would expect it to either project on the current path in the `/osrd/settings` tab (the one highlighted in green), or use the path of the train that was added last.

I don't know if this can be considered a bug and the expected behavior isn't quite clear yet, but it's annoying to be limited to one single path for projections.

**Comment by axrolld** [comment]
Moved as a new feature [here](https://github.com/osrd-project/osrd-confidential/issues/334).
