### ISSUE TITLE
bug: front: in the stdcm tab, some train IDs are missing from the result request

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#2269]
When we receive a response to the stdcm request, we send a request on `/train_schedule/results` to get the new projections. In this request, there can be some missing trains. It *seems* to only pick the trains that are already visible in the space-time graph (but I'm not sure about the exact behavior). Sometimes there are no train ID at all, which makes the whole thing crash.

We need to include every train of the given timetable in this request, otherwise we can have delays without displaying the trains that caused them. If it's more convenient we can change the API to have a timetable ID as input instead of a list of trains.

**Comment by eckter** [comment]
To reproduce : given an infra and 4 arbitrary points on a line going `a` -> `b` -> `c` -> `d`

* Add a train from `a` to `b` called `begin`
* Add a train from `c` to `d` called `end` (the paths don't overlap)
* Open the stdcm tab and set start point near `a` and end point near `d` (covering both previous paths)
* The GET only displays the `begin` train as it was the first one added (ideally it should display both but that's a detail)
* Request an STDCM, the projection is updated to a path going from `a` to `d`

At this point we should see all 3 trains: `begin`, `end` and the one from the stdcm response.

But only the train that was already present on the GET has been updated: `begin` is displayed but `end` is missing

**Comment by El-Youssef** [comment]
add details @eckter pls :)
