### ISSUE TITLE
Station list not compliant with path

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#2278]
**Describe the bug**
On staging environment the list of the proposed stations are not compliant with the path of the train
**To Reproduce**
1. Create a train (departure and arrival station
2. Click on 'add stops'
3. See the list of the stations

**Expected behavior**
The station or operational points have to be compliant with the path

**Screenshots**
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/55697888/200496182-831870e7-364d-48be-8540-0f72b9433151.png">

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Version [105.0.5195.125 (Build officiel) (x86_64)]

**Additional context**

**Comment by eckter** [comment]
Can't reproduce
