### ISSUE TITLE
Front : `interpolateOnTime` usage 

### ISSUE THREAD

**Issue by sim51** [OpenRailAssociation/osrd#2281]
This is about `interpolateOnTime` define here : https://github.com/DGEXSolutions/osrd/blob/dev/front/src/applications/osrd/components/Helpers/ChartHelpers.ts#L271

interpolateOnTime is  used here : https://github.com/DGEXSolutions/osrd/blob/dev/front/src/reducers/osrdsimulation/index.ts#L323 
with a a parameter of type `SimulationTrain` (defined here https://github.com/DGEXSolutions/osrd/blob/dev/front/src/reducers/osrdsimulation/index.ts#L153)

interpolateOnTime is also used on other places with a parameter of type `Regime` (defined here https://github.com/DGEXSolutions/osrd/blob/dev/front/src/reducers/osrdsimulation/index.ts#L110)

`Regime` and `SimulationTrain` has no key in common.

**Comment by anisometropie** [comment]
@sim51 I have completely typed the function `interpolateOnTime`.
`src/applications/operationalStudies/components/SimulationResults/ChartHelpers/ChartHelpers.ts
`let me know if we need to reopen
