### ISSUE TITLE
Solve the OSRDSimulation base component overrendering issue on simulation update

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#2370]

**Comment by alexandredamiron** [comment]
Update on simulation cause rerendering because:
- Use of simulation.train.length to check if getTimeTable should be GET
- Buld consolidated simulation then dispatch it, do that in reducer.

Consequent performance issue

**Comment by clarani** [comment]
This will be fixed with the refacto of the GET
