### ISSUE TITLE
TrainList refacto

### ISSUE THREAD

**Issue by Math-R** [OpenRailAssociation/osrd#2379]
## Description

Create new component to simplify and isolate each row in TrainList. 

## Goal

Make the DOM lighter in prevision of further inputs integration.

## Acceptance criteria

- [ ] This component must handle 2 states Edition/Native
- [ ] Inputs must be displayed only if the component is in Edition state
- [ ] Informations must be displayed only if the component is in Native state
- [ ] In Edition state, a validation Button must be displayed at end of raw
- [ ] The validation button must be disabled if no modification in stage
- [ ] In Edition state, a cancel Button must be displayed next to validation button, to reset the state and discard the change
- [ ] In Edition state, if there are errors, after validation the state will stay in Edition, and a toast is fired
- [ ] If the validation succeed , a validation toast is fired, the train schedule is recalculated, and the state change for Native

## Definition of ready

- [ ] The enabler story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the enbaler story is assigned
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by nicolaswurtz** [comment]
Scope has changed, has been intraged in another way.
