### ISSUE TITLE
Speed limit tags are considered as sets in `core`, it should be a single value

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#2396]
The standalone simulation API takes a collection of speed limit tags as parameters, and it's handled as a set in all of `core`. But it should never contains more than a single value. The `API` service only takes a single parameter and transforms it into an array with one element. 

We should update `core` so that it takes a single value. It should also be renamed.

**Comment by Khoyo** [comment]
Should these test cases be dropped then ?

https://github.com/DGEXSolutions/osrd/blob/a4ca87f2cf886568a7a72cff1732aedac5f370b3/core/src/test/java/fr/sncf/osrd/envelope/MRSPEnvelopeBuilderTest.java#L148-L149

**Comment by eckter** [comment]
> Should these test cases be dropped then ?

Yes, they should
