### ISSUE TITLE
GET projections aren't displayed properly when the trains are going in opposite ways

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#2419]
The bug is most likely located in the `api` service, but it could also be from the front. I haven't investigated yet. 

![image](https://user-images.githubusercontent.com/3882074/203748470-e3b5b69d-53f2-4e80-8618-57ad61bb1afb.png)

**Comment by eckter** [comment]
We'll wait for https://github.com/DGEXSolutions/osrd/issues/2573 before moving further with this one.

**Comment by younesschrifi** [comment]
This will be fix with the new signaling system.
