### ISSUE TITLE
refactor SpeedDirective

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#242]
Currently, SpeedDirective has two fields:
 - allowedSpeed, which is the minimum speed, or NaN if coasting
 - lowestNotNaNSpeed, which contains the speed limit even if allowedSpeed is NaN

This doesn't make a lot of sense: it would be much simpler to have a boolean for whether the train should coast or not, as well as a double for the speed limit

**Comment by axrolld** [comment]
Done !
