### ISSUE TITLE
Releases should be done with anotated tags

### ISSUE THREAD

**Issue by Khoyo** [OpenRailAssociation/osrd#2488]
Releases are done with lightweight tags. This is bad for multiple reasons (eg. there is no tracking of the release date). The intended mechanisms to tag releases in git is annotated tags.

We should make sure our release mechanism uses annotated tags, and potentially fix the previous releases tags.

**Comment by flomonster** [comment]
- I fixed the previous releases.
- Creating a release with the github interface, creates a lightweight tag by default (see https://github.com/community/community/discussions/4924). 
- I didn't find a way to trigger the CI only if the tag is annotated.

Finally, I don't see how to ensure we have annotated tags. Except to be careful creating a new release. If open to ideas...
