### ISSUE TITLE
front: edition - errors on save

### ISSUE THREAD

**Issue by sim51** [OpenRailAssociation/osrd#2503]
# On creation 

## tracksection 

* [x] Error `length is required`, even if its filled ...
*  [x] missing field `loading_gauge_limits` at line 1 column 2313 : resposne from the backend server. Sending an empty array is valid
* [x] Just after the item is created, if I click on save, we send to the backend a query to recreate the object 
* [x] a newly created tracksection disappear when creating a new line
*  [x] id :  the id is never changed, so we send `osrd/editor/new-signal-id`

## buffer stop 

* [x] don't know how to add a buffer stop, or it doesnt work ...

# On unchanged items

## Signal 

* [x] Fields `Values` & `Comment` are required in the jsonschema, but the backend allows empty strings (which is not the case on the frontend. 
* [x] if field has a value `null`, the validation failed because the form except to have undefined or a value, but not null

## TrackSection 

* [x] `Length` field comes from the database, but in frontend we have a rule that if the `Length` is not equals to length of the geojson linestring (+/- 1%), then an error message appears. It doesn't block the save, but the message should be a warning instead.

## Switch

* [x] Field `Label` in `SwitchSncfExtension` is required  in the jsonschema, but generally we have an empty value from the backend

**Comment by sim51** [comment]
@flomonster we need to be align between the front & back on those two points : 

- a field which is an **array** and **not mandatory** : can I omit for the creation it or should I send an empty array ?
- a field which is a **string** and **mandatory** : is an empty string  valid ?

**Comment by flomonster** [comment]
- Fields that are marked as not mandatory can be omitted for the creation (array included)
- String that are mandatory shouldn't be left empty.

--------

**Notes**:
- Some array (such as `loading_gauge`) are not mandatory and yet must be given to editoast. This will be fixed soon
- We should adapt the schema to explicitly indicate that string shouldn't be left empty.

**Comment by sim51** [comment]
[Bug Edition Infra.pptx](https://github.com/DGEXSolutions/osrd/files/10237349/Bug.Edition.Infra.pptx)

- [x] bug 1 & 2 : issue when changing the position of a signal, it stay at the same place because we don't recompute the geojson when the field position changed
- [x] bug 3  : issue on the temporary ID which is displayed on the map (and should not)
- [x] bug 3 - bis  : click on a line is not working when creating a signal
- [x] bug 4 : tooltip on button in edit form for selecting a tracksection
- [x] bug 4-bis : white page when clicking on the button 
- [ ] bug 5 : on signals, the label seems to be displayed twice -> should be fixed when the zone will be removed
- [ ] bug 6 : when a switch is selected, the button "delete" do nothing . This feature is not implemented -> https://github.com/DGEXSolutions/osrd/blob/dev/front/src/applications/editor/tools/switchEdition/tool.ts#L43-L46
- [x]  bug 7 : moving an item is not working ?

**Comment by sim51** [comment]
@jacomyal @flomonster  the interpolation of an item's position based on a line plus a distance has been fixed ?

**Comment by flomonster** [comment]
## Signal

- Field `comment` and `value` are required but can be left empty

## Switch

- Field `label` cannot be left empty or `null`. The label is part of the "sncf extension" that can be `null`.

Example of valid payload:

```json
{
  "id": "PA0",
  "ports": {
    "base": {
      "track": "TA1",
      "endpoint": "END"
    },
    "left": {
      "track": "TA3",
      "endpoint": "BEGIN"
    },
    "right": {
      "track": "TA4",
      "endpoint": "BEGIN"
    }
  },
  "extensions": {
    "sncf": null
  },
  "switch_type": "point",
  "group_change_delay": 0
}
```
