### ISSUE TITLE
Add missing endpoints API on editoast from main api

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#2550]
## Description

Migrate endpoints from api to editoast

- [ ] `POST` `/infra/railjson/` Import an infra from railjon
- [ ] `GET` `/infra/{id}/railjson/` Serialize an infra to railjon
- [ ] `GET` `/infra/{id}/speed_limit_tags/` List all speed limit tags
- [ ] `GET` `/infra/{id}/voltages/` List all voltages
- [ ] Add it to the `openapi.yaml` from editoast

**Comment by flomonster** [comment]
Duplicate #2560
