### ISSUE TITLE
Better timetable selector

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#2563]
Add functionnalities & correct behaviour of timetable selector & creator

> WAIT FOR #2561 (& rebase frequently)

- [x] Move component to `common/` & make it independant
- [ ] When modifying (create or delete), disable whole modal until done
- [x] Adapt design with infra selector style (do *not* use same classes but create new ones, with a new `timetable.scss`), more details below

## Details about design

This component will be a bit different than InfraSelector : 
- New timetable button has to be on main page (without railjson import)
- When created, it has to be selected and modal closed
- Keep two views (standard/edition) as found in InfraSelector
- Not all modification buttons are necessary

### Buttons to keep
- `delete`
- `rename`
- `duplicate`

**Comment by flomonster** [comment]
Won't do
