### ISSUE TITLE
Front: Optim: Hover on map (train move / position-value) is sluggish

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#2572]
### What happened?

In the simulation tab, hovering on the map is moving the trains around, but it is very not smooth. The representation of the train seems too demanding for the performances of the map.

### What did you expect to happen?

The movement of the trains should be rather smooth. And there should be a way to make it better with maplibre.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the simulation tab
2. Scroll down until the map
3. Hover on the map to move the trains around

### What operating system and browser are you using? (if applicable)

- Windows 10
- Google Chrome 22

### OSRD version

1482e8c

**Comment by axrolld** [comment]
If i understand correctly the idea here is to keep the visualization of the train but increasing the performance ?

**Comment by axrolld** [comment]
### What happened?

In the simulation tab, hovering on the map is moving the trains around, but it is very not smooth. The representation of the train seems too demanding for the performances of the map.


### What did you expect to happen?

The movement of the trains should be rather smooth. And there should be a way to make it better with maplibre.


### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the simulation tab
2. Scroll down until the map
3. Hover on the map to move the trains around


### What operating system and browser are you using? (if applicable)

- Windows 10
- Google Chrome 22


### OSRD version

1.0

**Comment by axrolld** [comment]
Can't move the train on the map anymore
