### ISSUE TITLE
core: mareco: coasting parts sometimes don't rejoin the base envelope

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#2584]
https://github.com/DGEXSolutions/osrd/pull/2582#discussion_r1046909631_

[This assert ](https://github.com/DGEXSolutions/osrd/blob/dev/core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/CoastingGenerator.java#L83)sometimes fails because of float inaccuracies. It happens very rarely but it can be reproduced in the fuzzer (on a real infra).

This is really hard to fix without entirely removing floating point operations, which we will eventually do for positions. This bug will likely remain until this refactoring.

**Comment by axrolld** [comment]
Just to make sure i get it well : is the removal of floating points operations done yet ? Otherwise isn't it too early to start this task ?

**Comment by eckter** [comment]
It's not done yet (and not planned soon), it is too early
