### ISSUE TITLE
Pathfinding error messages include missing rollingstock

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2601]
## Description

When pathfinding is failing, the user need to be informed why. A missing rolling stock can be the cause of a failing pathfinding. If that's so, warn the user of the specific failing cause.

## Goal

Improve the user experience.

## Acceptance criteria

- [x] When the user asks for a path without specifying a rolling stock, the following message must appear : "Veuillez sélectionner un matériel roulant pour rechercher une chemin"

**Comment by anisometropie** [comment]
Do we have error codes/key to identify errors returned (it’s not reliable to use to the string directly)

**Comment by nicolaswurtz** [comment]
Warning ! Speed limit category (aka « code de composition ») should *not* be a failure reason for pathfinding. If no speed limit is available for a chosen category on a track section, max line's speed limit is used.

**Comment by axrolld** [comment]
Thanks for that precision ! For some reason i thought the pathfinding was sometimes failing withouth the train category and i took it for granted. My bad !

**Comment by axrolld** [comment]
It's fixed :)

**Comment by anisometropie** [comment]
I added the french translation for gauge & electrification in here too

**Comment by axrolld** [comment]
Yup i saw that ! Good for me 👍

**Comment by axrolld** [comment]
@anisometropie i ended up moving the translation to #2647 to get more visibility

**Comment by anisometropie** [comment]
Deleted, replaced by #2699
