### ISSUE TITLE
Checkboxes in rollingstock selection modal are not properly clickable

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2623]
## Describe the bug

In the rollingStock selection modal, when ticking one of the checkboxes "Electrique" or "Thermique", it only works when clicking on the text next to the box, and not the box itself.

## Expected behavior

A click on either the text or the box itself should tick/untick the box.

## Screenshots

When the pointer is over the text :
![image](https://user-images.githubusercontent.com/86296016/208085034-e5f03aa9-c54a-4a42-a722-ec1892cfe81f.png)

And when it's hovering the checkbox:
![image](https://user-images.githubusercontent.com/86296016/208085164-fa6dee7c-bb71-4acb-ad90-059d2e424ed9.png)

## Desktop
 - OS: Windows
 - Browser: Chrome

**Comment by nicolaswurtz** [comment]
Corrected with https://github.com/DGEXSolutions/osrd/pull/2638/commits/072f33a1696549b232e9e396a32c1bd76315a347
