### ISSUE TITLE
Rolling stock select button is hidden because the rolling stock info take too much space

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2624]
## Current situation

When selecting a rolling stock, we need to "unfold" the rollingstock information. This makes  the rolling stock info component so big that select button is hidden (and some important information with it, like the length, mass, and speed). This makes the user intuitively click on the "Close" button of the modal window to validate its choice.

![image](https://user-images.githubusercontent.com/86296016/208085613-8b044da5-e618-4cca-bff9-79179225f539.png)

## Improvement idea(s)

Here are a few ideas to improve that :

- Making the rolling stock info smaller to fit entierely in the modal
- Replace the "Close" button at the bottom-right corner by an X at the top-right corner to close the modal, or just delete this button, as clicking outside the modal window already closes it.

## To-do

If you want to help the person that will take charge of this issue, you can write down some steps to complete it.

**Comment by nicolaswurtz** [comment]
- Removed close bottom button & footer space
- Added cross top button
- Reduced header in one lone line
- Reduced margins on curves
- Taller min-height of list

See https://github.com/DGEXSolutions/osrd/pull/2638/commits/c5a4a8f20a9734d71e6998c32e5340123f261795
