### ISSUE TITLE
STDCM train remains for a few seconds when switching to the Train Scheduling Tab

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2630]
**Describe the bug**
After creating a train in STDCM tab, when switching to the train schedule one, the forementioned train is visible in the space-time chart for about 2-3 seconds, then disappears.

**To Reproduce**
1. Go to STDCM tab
2. Create a new train
3. Go back to "Grilles horaires" and to the simulation tab
4. Watch the space-time chart and you should see the STDCM train appear briefely then disappear.

**Expected behavior**
The STDCM train should never appear in the Train Schedule tab.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by younesschrifi** [comment]
This issue has been resolved.
