### ISSUE TITLE
Translate pathfinding error messages in french

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2647]
## Description

Translate pathfinding error messages in propoer sentences in french.

## Goal

Improve frenchies user experience 🐓 

## Acceptance Criteria

- [x] Error messages relative to gauge & electrification have been translated
- [ ] Every error message relative to the pathfinding must be in french.
- [ ] Backend **must always send simplified english error messages** like `uncomplete-catenaries`, `missing-tracksection-data`, `unknow-reason`, etc.
- [ ] Messages must be perfectly understandable although concise (avoid spaces and special chars in message content, use "-")
- [ ] In frontend, use a dedicated translation file, like `pathfinding.json` in which you create a sub section dedicated to errors
- [ ] In frontend, translation has to be concise too, don't be "sorry", tell what's happening, no more, no less

**Comment by nicolaswurtz** [comment]
Updated acceptance criteria to precise translation method.

**Comment by anisometropie** [comment]
to be discussed https://github.com/DGEXSolutions/osrd/issues/2697
