### ISSUE TITLE
CRUD rolling stock

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2661]
## Description

**Who is this feature for?**

Study officer

**What should the user be able to achieve?**

The user must be able to create, update, duplicate, and delete rolling stock.
Some rolling stocks must remain locked, disabling any modification or deletion.

**Why do you think this feature would be valuable?**

- It would enable studies to be carried out with new rolling stocks.
- It would enable the creation of freight rolling stocks for STDCM
- It would facilitate the creation of battery-powered or other innovative rolling stocks in the future.

## Acceptance criteria

- [ ] It is possible to create new rolling stock
- [ ] It is possible to delete rolling stock
- [ ] It is possible to edit a rolling stock
- [ ] It is possible to lock a rolling stock, making it impossible to modify or delete
- [ ] It is possible to duplicate a rolling stock
- [ ] Two rolling stocks cannot have the same name

The UX/UI need to be refined before starting this story.

## Technical details
- A rolling stock should have the following properties
  - name (string, max-length 255)
  - effort_curves (2d arrays)
  - length (float)
  - max_speed (float)
  - startup_time (float)
  - startup_acceleration (float)
  - comfort_acceleration (float)
  - gamma (float) : standard deceleration of the train, in m/s²
  - inertia_coefficient (float)
  - features (list)
  - mass (float)
  - lauding_gauge (enum)
- Endpoints
  - /rolling_stock/{id}/ PUT (update)
  - /rolling_stock/{id} DELETE

**Comment by multun** [comment]
@axrolld isn't it done?

**Comment by axrolld** [comment]
Yes it is, my bad !
