### ISSUE TITLE
Train speed-effort curve seems to be a bit weak.

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2691]
### What happened?

With RollingStock 1TGV2N2 between Paris and Marseille, the space-speed chart of the train looks like that :

![image](https://user-images.githubusercontent.com/86296016/208960640-728402a4-0ab2-4d66-8769-d8b5692f6575.png)

It seems like the train is far too weak and in unable to maintain its speed. There must be a problem either in the gradients values, or in the train effort values (i suppose a missing conversion from daN to N, which is quite frequent)

### What did you expect to happen?

We expect the train to be able to maintain its speed on most of its journey.

### How can we reproduce it (as minimally and precisely as possible)?

1. Simulate a train from Paris to Marseille with 1TGV2N2  rollingStock.

### OSRD version

1.0

**Comment by bloussou** [comment]
related to #2825

**Comment by axrolld** [comment]
It's fixed now.
![image](https://user-images.githubusercontent.com/86296016/216032435-e59bd624-f1cf-4df4-b774-20270200932c.png)
