### ISSUE TITLE
Design 30, 60, and movable speed signs deceleration

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2705]
## Description

Elements indicating 30km/h, 60km/h and movable speed signs decelerations are infrastructure signals. It is therefore necessary to design this new feature and how it will co-exist with the new signalling module.

## Goal

This design is necessary in order to know how to implement 30km/h, 60km/h and movable speed signs decelerations in a way that's compatible with other signals.

## Acceptance criteria

- [ ] The resulting design must co-exist with the new signalling module
- [ ] The implementation steps must be clear

**Comment by flomonster** [comment]
Done check https://osrd.fr/en/docs/reference/design-docs/signaling/speed-limits/
