### ISSUE TITLE
Harmonize RollingStock data model

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2706]
See front/src/applications/osrd/components/RollingStock/consts/rollingstockDetailDB.json

What must be done:

- [ ] Adapt model (add needed fields)
- [ ] Adapt rolling stock import (check `/osrd-dags/import_rolling_stock`)

-------

"Code engin" is the rollingStock ID.

To be added to the rolling stock model :
- detail : colum H
- nb : colum I
- reference : colum K

To be added if the info is available :
- family : A
- type : B
- grouping : C
- series : D
- subseries : E
- unit : G

The API and front need to be adapted.

**Comment by multun** [comment]
@axrolld I'm very confused as to why all of this is needed. It was previously there, and got removed, as it was not used:
 - why do we need so many fields? I get that users would like to run searches on the content of these fields, but can't it be made simpler? what would `detail`, `nb` and `reference` be used for? what is it?
 - what some of these fields is supposed to contain is unclear. the family, type, grouping, series, subseries and unit fields are often empty in the source database, and are not used consistently. it's a big issue as we cannot properly document what should be there.
 - adding these fields makes it harder to add new rolling stocks from other sources. I doubt foreign, or even other french databases have the same fields.

In the past, we took a very lax approach to data modeling: shove in everything we might need, and sort out what we actually do need later on. We've reached a point where we can figure out what's needed and what's superfluous, and our latest efforts reflect that.

**Comment by clarani** [comment]
# Implementation details
- should add only one unique meta_data fields, which will be a simple dict (stored in q JSON field in DB)
- we won't keep the row detail in the end

For information, all this data will only be used in the frontend to display the rollingStock
