### ISSUE TITLE
Add a search facility for rolling stock

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#2707]
## Description

We should make rolling stocks searchable by their:
- Name
- Detail
- Reference
- Series
- Type
- Grouping 

## AC

- [ ] We should search with case insensitivity

## How to implement

- Create a search table for rolling stock
- Create triggers that insure the search table is always up to date
- Add the object to the `search.yaml` config file

**Comment by axrolld** [comment]
@nicolaswurtz i think this issue needs more details in order for @clarani to take it in charge.

**Comment by axrolld** [comment]
Apparently this is dependant on the work being done by @Math-R about searching in the data. We should wait for his task to be completed before working on this issue.

**Comment by flomonster** [comment]
Postponed
