### ISSUE TITLE
Implement 30km/h, 60km/h and movable speed signs decelerations in running-time calculation algorithm

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2716]
## Description

Implement the design from #2705 to take into account these deceleration in running-time calculation.

## Goal

Significately increase the accuracy of our running-time calculation algorithm.

## Acceptance criteria

- [ ] A warning signal, a reminder signal and a downward-pointing chevron must be imported from infrastructure data
- [ ] If the downward-pointing chevron is not present in the data, it must be placed by default in line with the first point encountered, regardless of its position)
- [ ] The direction of the switch affected by the slowdown must be imported from infrastructure data
- [ ] The running-time calculation algorithm must take into account signal those decelerations
- [ ] The speed limit must be respected at the bottom of the first chevron

**Comment by flomonster** [comment]
Outdated
