### ISSUE TITLE
editoast: Create an Infra cache from a railjson

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#2745]
When importing a railjson, we need to load the infra_cache and add it to the existing infra_caches. To do this, we currently load all the infra objects. 

This could be optimised as we already have the full railjson which has the same objects as the infra_cache with a few fields. 

The goal would be to create an infra_cache from this railjson to avoid loading the whole infra.

files to study :

- [https://github.com/DGEXSolutions/osrd/blob/dev/editoast/src/infra_cache.rs](url)
- [https://github.com/DGEXSolutions/osrd/blob/dev/editoast/src/views/infra/railjson.rs](url)
etc...

**Comment by flomonster** [comment]
We don't need this feature anymore
