### ISSUE TITLE
Study timestep sensitivity on running-time calculation

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2775]
### Description and goal

Running-time calculation algorithm is based on numerical integration with a given timestep.
The lower the timestep, the more precise the computation is, but the longer it takes.

The idea is to study how sensitive the result of running-time calculation is to the time step value, in order to select a value that's good enough in terms of computation time and precision.

This could significantly increase the computation time of STDCM.

### Acceptance criteria

- [ ] A study of running-time vs time-step has been done on a long train path (ex. Brest-Nice)
- [ ] A study of running-time vs time-step has been done on a short train path with lots of stops
- [x] The different time-steps studied must be at least : 0.01s (reference), 0.05, 0.1s, 0.5s, 1s, 2s, 4s, 10s, 30s

### Details

- [x] Find where the time step is specified in the code
- [x] Potentially look for duplicates and centralize to only one value if necessary
- [ ] Run a train between Brest and Nice (or some other long train run) with the different time steps listed above and plot a running-time vs time-step
- [ ] Same with a short path with ~5 stops (ex. Paris St Lazare - Versailles Chantiers)
- [ ] Document the study on the website

**Comment by flomonster** [comment]
Done https://osrd.fr/en/docs/explanation/running_time_calculation/numerical_integration/
