### ISSUE TITLE
Redundant display of values on the graph axes

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#2845]
### What happened?

On the graph axis, each value is displayed twice.

![image](https://user-images.githubusercontent.com/62556370/211782539-b3dac958-6959-478c-a58b-97cc1d9e1871.png)

### What did you expect to happen?

The values on the axes must be displayed only once in black color.

### How can we reproduce it (as minimally and precisely as possible)?

1. Select a time table containing at least one train, or create it
2. Go to the simulation tab

### What operating system and browser are you using? (if applicable)

- Windows 10
- Google Chrome 108.0.5359.125

### OSRD version

1.0

**Comment by younesschrifi** [comment]
This issue has been resolved
