### ISSUE TITLE
Rework `layers_description.yml` to keep only fields used by the front

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#2848]
### Description and goal

The idea is to address this comment https://github.com/DGEXSolutions/osrd/pull/2832#discussion_r1065965029 to have a cleaner code once chartos is ported in editoast.

Related to #2896 

### Acceptance criteria

- [ ] Must have a test to check that every fields use by the front are present

**Comment by flomonster** [comment]
Done
