### ISSUE TITLE
Improve getMaxEffort by using binary search

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#2851]
### Who would benefit from this feature?

End users

### What is this feature about?

In the running-time calculation algorithm the maximum effort of the train is retrieved in the `getMaxEffort` method in `RollingStock.java`.
The way it is currently implemented is a search scanning the entire effort-speed curve each time :
https://github.com/DGEXSolutions/osrd/blob/1a5ee3a49db4f5203f8b7a9648350b5a091de1e4/core/src/main/java/fr/sncf/osrd/train/RollingStock.java#L208-L221

The idea is to replace this scan with a binary search.

### Why is this feature valuable?

This feature matters because it will improve the computation time of the overall running-time calculation algorithm.

### Anything else people should know?

A binary search algorithm has already been implemented and is located [here](https://github.com/DGEXSolutions/osrd/blob/7471ba36a25899a1fd71116c3be4c04b11ad57b4/core/src/main/java/fr/sncf/osrd/utils/DoubleBinarySearch.java).

**Comment by flomonster** [comment]
We can use the guava implementation of binary search: https://guava.dev/releases/15.0/api/docs/com/google/common/collect/Ordering.html#binarySearch(java.util.List,%20T)
