### ISSUE TITLE
Fix the railjson operational point model

### ISSUE THREAD

**Issue by Khoyo** [OpenRailAssociation/osrd#2875]
### Description and goal

Currently, operational point locations are a simple list of points. However, a lot of actual operational points are rather a list of pairs of points (ie. begin and end).

We should fix that.

### Acceptance criteria

- [ ] The railjson schema can have pairs of points as operational point locations.
- [ ] All the services accept the new format
- [ ] The data import scripts export the new format.

**Comment by flomonster** [comment]
Postponed
