### ISSUE TITLE
Interaction with main container is blocked after leaving a page with the Rolling stock modal opened

### ISSUE THREAD

**Issue by carolnvg** [OpenRailAssociation/osrd#2898]
### What happened?

When I click on Grille horaire and click on "Choisissez un matériel roulant" and display the modal and then click on a button to access another page
I can't interact with the page because of a grey background

![image](https://user-images.githubusercontent.com/108059811/212684021-2d654392-dbc4-4de9-85e2-eb3bd686b996.png)
![image](https://user-images.githubusercontent.com/108059811/212685456-886d1043-e792-4bcc-9ad2-29b3a6f0f6ee.png)

### What did you expect to happen?

When I go to another page, I should be able to interact with the page.

![image](https://user-images.githubusercontent.com/108059811/212685389-5adf5463-2824-4c16-9c9f-9e9e404ba1f7.png)

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to 'https://osrd.dev.dgexsol.fr/'
2. Click on 'Grilles horaires'
3. Click on 'Choisissez un matériel roulant' to display the modal
4. Click on OSRD logo
5. The grey background of the modal remain

### What operating system and browser are you using? (if applicable)

- Windows 10
- Google Chrome 22

### OSRD version

1.0

**Comment by nicolaswurtz** [comment]
Will be corrected with new modal from @Math-R https://github.com/DGEXSolutions/osrd/pull/2870 ;-)

**Comment by nicolaswurtz** [comment]
New modal must be propagated into others modals (including rolling stock's one) before closing

**Comment by younesschrifi** [comment]
Should create other issues for others modals.
