### ISSUE TITLE
Affichage in GEV (Grille horaires - Simulation Page) checkboxes display but do not check/uncheck

### ISSUE THREAD

**Issue by carolnvg** [OpenRailAssociation/osrd#2899]
### What happened?

When I display the page Simulation with an existing timetable and I use the GEV, I tried to add a kind of "Affichage" by checking the checkbox "Vitesse de ligne". The line appears but the checkbox does not appears as checked.
Same behavior by unchecking the checkbox.

![image](https://user-images.githubusercontent.com/108059811/212692153-8108ea33-ce7d-48b6-9109-48ea99819789.png)

### What did you expect to happen?

When I clicked on the checkbox, the checkbox should appeared as checked. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to 'https://osrd.dev.dgexsol.fr/osrd/settings'
2. Select any infra
3. Select a timetable with some trains
4. Scroll to the GEV
5. Click on the expand icon  to display the menu "Affichage"
6. Check "Vitesse ligne"
7. The line appears on the GEV
8. The checkbox should be checked but it is not

### What operating system and browser are you using? (if applicable)

- Windows 10
- Google Chrome 22

### OSRD version

1.0

**Comment by younesschrifi** [comment]
This issue has been resolved
