### ISSUE TITLE
Add `url` dependency to editoast

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#2918]
## Description and goal

It would be nice to manipulate urls using https://crates.io/crates/url.  This is because currently we have to be super careful to check whether they end with a `/` or not, as we consider as just strings. 

Places where the type `Url` should be used instead of `String`:
1. Manipulation of url for postgres server [starts in `client/postgres_config.rs`](https://github.com/osrd-project/osrd/blob/19a77208b5a0a4da830889608cc6efec3f357590/editoast/src/client/postgres_config.rs#L28C7-L28C7)
2. Manipulation of url for redis server [starts in `client/redis_config.rs`](https://github.com/osrd-project/osrd/blob/19a77208b5a0a4da830889608cc6efec3f357590/editoast/src/client/redis_config.rs#L13)
4. In one of the `layers` views we return urls. [See here](https://github.com/osrd-project/osrd/blob/19a77208b5a0a4da830889608cc6efec3f357590/editoast/src/views/layers/mod.rs#L83)
5. There might be more, if you see more places where `String` should be `Urls`, feel free to add some changes

## Acceptance criteria
- [ ] The url crate is added as a dependency
- [ ] The modifications mentioned above are included

**Comment by multun** [comment]
yes please

**Comment by flomonster** [comment]
I'm okay with this change. Note that we still have to be carefull in `openapi.yaml` and queries. An endpoint with or without a trailing `/` won't be the same for cerbere.
