### ISSUE TITLE
Display electrical profiles in GEV

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#2919]
### Description and goal

Electrical profiles have to be shown on GEV like horizontal bars using color values from existing catenaries voltage colors (purple for 25000V, red for 1500V, cyan for 15000V, green for other voltages.

### Acceptance criteria

- [x] The display of electrical profiles & modes is composed of horizontal bars, with color from traction mode (or black #333333 for diesel mode)
- [x] The main/high profile has vivid/source color, next steps (more restricted) have same color but become lighter and lighter. The filling of the rectangle must correspond to the mode `used`.
- [x] The value of mode `seen` is displayed inside white rounded (4px radius) inside bar if there's enough space, else it isn't displayed. The text inside always has the main color of voltage mode (doesn't become lighter with profiles step).
- [x] If the value `seen` is differend than the value `used`, the rectangle must be hashed. The rules above still apply (color of hashes = color of mode `used`, text inside the box = mode SEEN with the corresponding color).
- [x] In case of 25000V, only the voltage must be displayed (25000V, 22500V & 20000V).
- [x] In case of 1500V, the voltage **and the step** must be dispayed (for example "1500V A1")
- [x] A popup pops when hovering bar giving color, step value & voltage value/mode
- [x] A checkbox is available in config to switch display of electrical profiles. Off by default.
- [x] A legend is available to explain link between colors &  voltages/modes, displayed on top of the component (not a modal) and activated by an additional round button on bottom right of the chart (try to use same look&feel than map's legend)
- [x] If enough time, please use reference colors from SNCF design (and apply same colors in catenaries in map's representation & legend)

![image](https://user-images.githubusercontent.com/6003856/213734952-301dad63-01c8-4e00-99c6-fc1db25293c0.png)
![image](https://user-images.githubusercontent.com/6003856/213734990-2d99d23f-c944-4be1-af68-078746cec09a.png)
![image](https://user-images.githubusercontent.com/6003856/213735063-09357b55-35b1-4efe-a839-8f6559bd6697.png)

**Comment by axrolld** [comment]
I have 2 comments :
- how will the legend be visible ? Do we need to click or hover something ?
- do we want those extra info inside the chart or under it ? What if we want to display other info in the future (e.g. signals) ?

**Comment by nicolaswurtz** [comment]
- It was explained but not enough clearly, I've added some details (a round button on bottom right btw)
- Inside for now. When we'll build line linear schematic graph, all those informations will move in this new graph (with signals, especially electrical signals for our purpose)

**Comment by Yohh** [comment]
about the legend, why not display it with a hover on a '?' icon ?

**Comment by Castavo** [comment]
The endpoint you'll want to use to retrieve the hierarchy of electrical profiles per mode is `EDITOAST_URL/electrical_profile_set/<id>/level_order` with `<id>` being the identifier of the electrical profile set chosen for the current timetable

**Comment by Yohh** [comment]
at this moment, it looks like that:

- in storybook: 

![Image](https://user-images.githubusercontent.com/20640252/216400070-ac17a067-81c8-456c-beba-83f8b74b4e2e.png)

- in app (Paris - Saint Malo):

![Image](https://user-images.githubusercontent.com/20640252/216399929-da497365-0a79-4aec-b5f6-2a79ad60f322.png)
