### ISSUE TITLE
Check if the application correctly displays the rollingstock's list

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#2971]
## Description & Goal

Implement an E2E test that verifies that the rollingstock list is displayed correctly.

## To do

- [ ] Implement axios request interceptor 
- [ ] Fulfill respons with test data
- [ ] Test if every rollingstock is properly displyed 

## Acceptance criteria

- [ ] CI tests must pass  
- [ ] The rollingstock list must be displayed correctly

**Comment by celine-sncf** [comment]
done
