### ISSUE TITLE
Implement a convenient way to specify the track number when selecting origin/destination

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#2984]
### Who would benefit from this feature?

End users

### What is this feature about?

Find a way to easlity selectd the path (mybe by default the same path as the one selected)

### Why is this feature valuable?

On higher level of detail it is impossible to see the difference between the available tracks so it is placed 'randomly' for the user. And pathffinding could be impossible for strange reasons

**Comment by clarani** [comment]
It will be done with the new UX
