### ISSUE TITLE
When `PATCH` on `project/{id}/study/{id}/` error with `type` field

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#3028]
### What happened?

When `PATCH`  or `UPDATE` on `project/{id}/study/{id}/` error with `type` field as this :

`Error: {"type":["\"Type de l'étude\" is not a valid choice."]}`

### What did you expect to happen?

Update a study without error, of course !

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a study (with or without a type)
2. Update a study with same or new type
3. Get an error
4. Read the error
5. Write an issue about the error
1. Create a study (with or without a type)
*INFINITE LOOP DETECTED ABORT ABORT ABORT*

### What operating system and browser are you using? (if applicable)

- Solaris 9
- Netscape 7.0

### OSRD version

1.0

**Comment by younesschrifi** [comment]
Thanks Nicolas, I'm on it :)

**Comment by Uriel-Sautron** [comment]
Can not reproduce
