### ISSUE TITLE
Adapt Rollingstock model from Qualesi to OSRD

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#3031]

**Comment by lmuria** [comment]
# Description
· Adapt Rolling Stocks model to account for new/differents energy sources parameters (e.g fuel tank volume, type of fuel, battery capacity)

· Validate description with team and update JSON Schema of rolling stock

# Goal

To enable implementation of QUALESI's energetic simulation

# Acceptance Criteria
- [x] New Rolling Stock model must work with existing features
- [x] New rolling stock model must follow this model :

![Image](https://user-images.githubusercontent.com/51412079/220075550-22891823-5ad8-4f43-920a-4cdbf4baee3b.svg)

**Comment by clarani** [comment]
# Current models
RollingStock -> energy_sources: EnergySource[]


EnergySource: can be a Catenary, a PowerPack or a Battery

Catenary:
- energy_source_type: "Catenary"
- max_input_power: power-speed curve
- max_output_power: power-speed curve
- efficiency: float

Battery/PowerPack
- energy_source_type: "Battery"/"PowerPack"
- max_input_power: power-speed curve
- max_output_power: power-speed curve
- efficiency: float
- energy_storage: EnergyStorage

EnergyStorage:
- capacity: float
- soc: float
- soc_min: float
- soc_max: float
- refill_law: null | RefillLaw

RefillLaw:
- tau: float
- soc_ref: float
