### ISSUE TITLE
front: The web app defaults to French, regardless of browser locale

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#3033]
### What happened?

My browser and OS are set to en_US.UTF-8, and the web app still displays in french

### What did you expect to happen?

I would have expected:
 - the app to automatically to english
 - to have the option to switch manually

I found neither options

### How can we reproduce it (as minimally and precisely as possible)?

1. Set your browser locale to english
2. Open the app
3. It's all in french

### What operating system and browser are you using? (if applicable)

- FF on Linux, shouldn't matter

### OSRD version

dev

**Comment by nicolaswurtz** [comment]
Locale is stored in localeStorage, you have to remove it and voilà !
