### ISSUE TITLE
Restore signal change on Map using MapLibre possiiblities

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#3034]
## Description

Signal changes on time according to signal Aspects are not working anymore. 

## Goal

We can fix that in a more consistent way by using new dynamic sprite property on maplibre implementation

## Acceptance criteria

- [ ] Only one layer for signals (no red and light)
- [ ] Dynamic sprite identifier update on signalAspect changes

**Comment by flomonster** [comment]
We disable this feature temporarily. We might add it properly later.
