### ISSUE TITLE
Isolate Full Margins selection component

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#3037]
## Description

Isolate the complete margin settings component (used in simulation)

## Goal

Only standard allowance settings is isolated. Isolated the complete component (with partial margins e.g. engineering). The important and agnostic feature is the abolity to extend a propertie within a subset

## Acceptance criteria

- [ ] The component runs on storybook
- [ ] The component allow to set up a value within different types on a subset within limits (and a type), and trigger then a callback to HOC

**Comment by nicolaswurtz** [comment]
Beware, it will be removed from simulation to be part of configuration. We should have dedicated component either for operational studies and STDCM (each of them need specific & different UI/UX).

**Comment by clarani** [comment]
The component Margins will be refactored in the coming months
