### ISSUE TITLE
map Performance, moving the train in simulation is not smooth

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#3060]
- Proposal with Deck.GL layer
- memoization
- do not recompute the mediator everytime

**Comment by bloussou** [comment]
What do you mean by map performances ? Is it time to display the infra, signals, ... ?

**Comment by anisometropie** [comment]
@bloussou More like when we hover over the map, to move the train, or over the graphes, it’s not always smooth

**Comment by axrolld** [comment]
Duplicate of #2572
