### ISSUE TITLE
Editor "Switch" page crashes

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3069]
### What happened?

In the infrastructure editor, the "switch" tool crashes the application

### What did you expect to happen?

The page should load without crashing

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to editor page
2. Click on "Aiguillage" (third button on the left panel)
3. The page does not load

### What operating system and browser are you using? (if applicable)

- Windows 10
- Firefox 102.7.0 ESR

### OSRD version

1.0

**Comment by Uriel-Sautron** [comment]
Can not reproduce
