### ISSUE TITLE
Simplify `map_layers.yml` config file

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#3077]
### Description and goal

This file could be shorten a lot https://github.com/DGEXSolutions/osrd/blob/dev/editoast/map_layers.yml by moving duplicate part under the layer instead of the view. For all `views` only the `on_field` is different from the `sch` view to the `geo` view.

### Acceptance criteria

File would be shorter and code simpler.

**Comment by flomonster** [comment]
Done
