### ISSUE TITLE
Refactor simulation classes

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#3086]
## First Pitch
We could split data more intuitively between `PhysicsPath` and `SimContext`, and avoid strange practices like using `RollingStock.Comfort` in the signature of methods of the interface `Physics.RollingStock` with a little reorganisation of the data.

I am thinking about making a class `TrainMission` (or a more fitting name) which would represent an actual train on a given path (and not a kind of rolling stock).

## Decision

- [x] Make `fr.sncf.osrd.envelope_sim` and `fr.sncf.osrd.envelope` independant modules (like `fr.sncf.osrd.railjson.schema`)
- [x] Move all mentions of mode, profile or comfort out of the above modules
- [ ] Remove `EnvelopeSimContext` from `Allowances`
- [ ] Maybe rename `EnvelopeSimContext` to something more explicit ?

**Comment by multun** [comment]
Looks good to me!
