### ISSUE TITLE
Front: Normal click on a train on GET become unwanted drag

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#3104]
### Description

When you click on a train on the GET, without movement, just to select, the train remains "hooked" as if you were dragging it.
Linked to #3100 ?

### Version

3dbd56326a0bf67d9b2902f1017295ec17c19250

**Comment by clarani** [comment]
I can check this one, I already have done a PR to fix some bugs on the GET (see https://github.com/DGEXSolutions/osrd/pull/3134)
