### ISSUE TITLE
Memory spike when we retrieve a railjson (can lead to an OOM)

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#3122]
### What happened?

When the endpoint `GET` `/infra/{id}/railjson` is used on a big infra such as france. We have a spike of memory usage.

An idea to fix it could be to query and deserialize the infra in multiple parts (object by object).

A real issue is that the memory consumption stay high even after the service response. 

Check massif report here: [massif.tar.gz](https://github.com/DGEXSolutions/osrd/files/10683876/massif.tar.gz)

This could be a leak of one of our dependencies or it's an expected behavior (keeping a large alloc for future requests).

### What did you expect to happen?

The memory usage should fall back close to 0 after answering the request.

### How can we reproduce it (as minimally and precisely as possible)?

- Build editoast in debug
- Run `valgrind --tool=massif target/debug/editoast runserver`
- Make some requests

### OSRD version

46306e0e41ee8648e103697a2a58ae1e71ca4ba0

**Comment by celine-sncf** [comment]
@flomonster can you reproduce this bug today ?

**Comment by flomonster** [comment]
Yes I can. This bug is almost identified.

**Comment by flomonster** [comment]
I investigate this issue by doing the following things:

- Run the server with: `valgrind --trace-children=yes --tool=massif target/debug/editoast runserver`
- Request 3 times to serialize a large infra (waiting 30 seconds between each call)

```sh
curl --location --request GET 'http://localhost:8090/infra/8/railjson/?exclude_extensions=true' > /dev/null  && sleep 30 && \
curl --location --request GET 'http://localhost:8090/infra/8/railjson/?exclude_extensions=true' > /dev/null  && sleep 30 && \
curl --location --request GET 'http://localhost:8090/infra/8/railjson/?exclude_extensions=true' > /dev/null
```

### Current state

[massif_current.tar.gz](https://github.com/DGEXSolutions/osrd/files/11151173/massif_current.tar.gz)

![2023-04-04-191517_1474x890_scrot](https://user-images.githubusercontent.com/15349030/229876494-2d1542aa-500c-45f8-a068-78dbbdcc8b55.png)

We can see that 500MiB are not free between each call. This memory is allocated by **libpq**. To free this allocation the connection has to be close. The thing here is that we have a pool of 32 connections on hold. There close (and reopen) after 10 minutes of idle or 30 minutes of life.

Let's say we have 5 connections that have to do a large query in a 30-minute time window (which is highly probable) we can have a spike of 2GiB + 1.5GiB. 

## Hot fix

I tried to configure the pool of connection to instantiate a connection only when needed and free it once used.

https://github.com/DGEXSolutions/osrd/blob/ae732bbd01b1d00ec718026ebfe45758b3a55b01/editoast/src/main.rs#L104-L107

```diff
    let pool = Pool::builder()
        .max_size(pg_config.pool_size)
+       .min_idle(Some(0))
+       .idle_timeout(Some(Duration::from_micros(1)))
        .build(manager)
        .expect("Failed to create pool.");
```

I tried the same experience:

[massif_fixed.tar.gz](https://github.com/DGEXSolutions/osrd/files/11151250/massif_fixed.tar.gz)

![2023-04-04-193058_1724x886_scrot](https://user-images.githubusercontent.com/15349030/229876658-550bc88c-fae6-486e-94df-82b698c1e57f.png)


The whole memory is free between each request. The issue here is that we have poor performance since creating a connection is an expensive operation.

## What now ?

### Stop being greedy! :whale: 

Maybe we should just avoid having to do large query.
We should be able to list and split queries that are likely to carry a lot of data

*Ex: Instead of having a single query to retrieve a serialized infrastructure we could make several queries (one per type of object) and rebuild the document afterward.*

### A tradeoff? :balance_scale: 

Maybe we have to find the sweet spot between freeing psql allocations fairly regularly and having enough connection available in the pool.
