### ISSUE TITLE
front: points aren't always placed under the mouse, making it hard to set origin/destination

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3150]
Sometimes it works, sometimes it doesn't. It's unpredictable and unreliable, but it still works *most of the time*.

[Screencast from 10-02-2023 10:49:43.webm](https://user-images.githubusercontent.com/3882074/218060283-1fec4018-77c0-4631-a77d-c676e873c672.webm)

**Comment by anisometropie** [comment]
@eckter fixed by https://github.com/DGEXSolutions/osrd/pull/3214
