### ISSUE TITLE
front: carto modals do not close automatically when another one is opened

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#3152]
### What happened?

See the screencast : 
[Screencast from 10-02-2023 10:45:47.webm](https://user-images.githubusercontent.com/32448554/218059806-81fe13da-71a2-424e-9ffa-11c864b4b36d.webm)

### What did you expect to happen?

That when switching from one settings to the other the previous open settings is closed (in the case of the screencast: when settings are opened search should be closed and when search is opened, if settings is opened search should be closed).

### How can we reproduce it (as minimally and precisely as possible)?

Go to the map, click on search then on settings then on search and so on....

### What operating system and browser are you using? (if applicable)

- Windows 10
- Google Chrome 22

### OSRD version

1.0

**Comment by leovalais** [comment]
May be related to #2831

**Comment by bloussou** [comment]
fixed by https://github.com/DGEXSolutions/osrd/pull/2876
