### ISSUE TITLE
impossible to add a point on electrified rail

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#3162]
https://user-images.githubusercontent.com/24652545/218151420-c044fe38-c347-4475-8537-161eb677f5ab.mp4

**Comment by eckter** [comment]
It's likely related to https://github.com/DGEXSolutions/osrd/issues/3150, but it's not juste electrified track sections

**Comment by Castavo** [comment]
It's a duplicate of #2927
