### ISSUE TITLE
Incorrect MVT tile encoding (line rendering when zooming is strange)

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#3164]
### What happened?

When you zoom in on a line the rendering is sometimes strange.

https://user-images.githubusercontent.com/24652545/218152171-3db2dd3d-e88b-4e1e-b6a1-3007f6852294.mp4

### What did you expect to happen?

Track should be continuous.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to 'Cartographie'
2. Zoom somewhere

Example of tile query that render weird:

https://gateway.dev.dgexsol.fr/editoast/layers/tile/track_sections/geo/17/67118/44971/?infra=1

### What operating system and browser are you using? (if applicable)

- Env: Dev
- Firefox

### OSRD version

3dbd5632

**Comment by multun** [comment]
I've never seen this stuff before, can you still reproduce it?

**Comment by anisometropie** [comment]
![Screenshot_20230217_151253](https://user-images.githubusercontent.com/24652545/219678617-7a20aabe-0247-4b19-8561-56c062b60472.png)

![Screenshot_20230217_151423](https://user-images.githubusercontent.com/24652545/219678937-65f1b490-0c56-4a40-99a7-53e39250713f.png)

**Comment by multun** [comment]
Looks like it's a bug in https://github.com/DougLau/mvt

**Comment by multun** [comment]
I believe the encoder does not properly cut geometries https://github.com/DougLau/mvt/blob/527f4d57c503c8550553b03449bffe6d533e195f/src/encoder.rs

**Comment by multun** [comment]
Ok, the encoder we're using just does not implement clipping, and rejects point too far out the tile's coordinate system.

**Comment by ttsirkia** [comment]
When you provide the data for the tile, is it cut exactly to the boundaries of the tile? Mapbox/MapLibre cannot draw the lines correctly if the lines won't overlap a bit in adjacent tiles. So the tile must contain a short boundary also outside of the exact coordinates of its boundary, see https://github.com/mapbox/mapbox-gl-js/issues/8951#issuecomment-551925489

**Comment by multun** [comment]
@ttsirkia it's much worse than that, geometries aren't cut at all, and a point is discarded when it cannot be encoded in tile space coordinates. This works fine, except at high zoom levels, where the end points of long track sections cannot be encoded

We were previously properly cutting geometries, but it got lost in translation when we migrated the service to rust, and nobody noticed at the time. I believe we should go back to using `ST_AsMVTGeom` to encode geometries.

**Comment by ttsirkia** [comment]
It seems that your server hosts the tiles up to zoom level 18. Typically with vector tiles this is unnecessary unless there are some features which become visible only with very high zoom levels. You could change the tile generation to have max zoom such as 12 or 13 and indicate in MapLibre config that UI allows zooming still up to 18. Then MapLibre will interpolate the higher zoom levels.

In this way, the number of requested tiles is much smaller and moving in UI is quicker. Also there is less tile boundaries causing problems. This reduces the server load although the single responses are a bit larger but normally contain very little unnecessary data.
