### ISSUE TITLE
CORS errors in browser console

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#3184]
### What happened?

Errors in browser console in dev environment:
![image](https://user-images.githubusercontent.com/32448554/219401567-2d0b473d-87ae-401b-a5ed-5267989c7c12.png)

### What did you expect to happen?

No errors in console

### How can we reproduce it (as minimally and precisely as possible)?

Open dev and the console

### What operating system and browser are you using? (if applicable)
Firefox and ubuntu

### OSRD version

3dbd5632

**Comment by bloussou** [comment]
I think this was due to `Add blocker ultimate`. After deactivation I don't have the error anymore. @anisometropie I think we can close this if you agree.

**Comment by Khoyo** [comment]
Indeed, sentry urls are blocked by (at least) Easylist Easyprivacy (the patterns are `/?sentry_key=` and `/?sentry_version=`)
