### ISSUE TITLE
Add a train to the path different from the path of the first train, the train does not appear in the list 

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#3185]
### What happened?

When a train is added which has a different path from the first added train, it does not appear in the list of trains in the scenario. 

Here are the line in the code that causes this issue : https://github.com/DGEXSolutions/osrd/blob/3dbd56326a0bf67d9b2902f1017295ec17c19250/api/osrd_infra/views/train_schedule/train_schedule.py#L111-L112

### What did you expect to happen?

When adding a train with a different path, it should be displayed in the train list but its GET should not be added.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Scenario
2. Add a train 
3. Add a second train with a different path
4. You will see that your second train won't be added

### What operating system and browser are you using? (if applicable)

- Macbook M1
- Google Chrome 22

### OSRD version

1.0

**Comment by celine-sncf** [comment]
Oops, I opened a duplicate here : https://github.com/DGEXSolutions/osrd/issues/3274

**Comment by bloussou** [comment]
it is added in the database but not displayed or queried

**Comment by Tguisnet** [comment]
This bug happens when the path are exclusively differents
If the paths shared parts of their path, this bug doesn't appear.

**Comment by Khoyo** [comment]
Closed by https://github.com/DGEXSolutions/osrd/pull/3871

**Comment by Khoyo** [comment]
Editoast no longer have the behavior, the bug should be fixed as soon as the front switches over.

This also means some trains may have no head_positions, the front must be able to handle that.
