### ISSUE TITLE
Can not uptade a Scenario

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#3186]
### What happened?

The button to modify a scenario is not displayed properly. Moreover, when I want to update a scenario, a grey filter appears on the screen and nothing can be done. (see the video) 

https://user-images.githubusercontent.com/75369238/219408553-943b1a53-4e3a-4f05-9d52-84c834188274.mov

### What did you expect to happen?

Be able to update a scenario

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Scenario
2. Click on the button to update a scenario (pencil) 

### What operating system and browser are you using? (if applicable)

- Macbook Pro M1
- Google Chrome 22

### OSRD version

1.0

**Comment by nicolaswurtz** [comment]
Fixed with #3212
