### ISSUE TITLE
tests: fuzzer: find a way to add stdcm tests as regresion tests

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3206]
When the fuzzer detects an error, a json file is generated so that it can be included in the regression test suite.

But stdcm tests depend on the current state of the timetable, they can't easily be reproduced in a vacuum. We could look for a way to generate a timetable with a predefined set of trains, to run reproducible stdcm tests.

**Comment by shenriotpro** [comment]
To clarify: the issue is that the timetable may be altered from previous seeds (then conflicts are hard to reproduce without the full history). Note that we don't want to over-simplify tests so that we can still cover complex cases.

**Comment by shenriotpro** [comment]
relevant code: https://github.com/osrd-project/osrd/blob/dev/tests/fuzzer/fuzzer.py and https://github.com/osrd-project/osrd/blob/dev/tests/tests/test_regressions.py to reproduce

**Comment by shenriotpro** [comment]
since importing/exporting a timetable may not be easy, here are a few other ideas:
1. store, export, and reproduce the "new train" requests in regressions, along with the STDCM request, so we can restore the state of the fuzzer test
2. design a more deterministic set of trains for STDCM tests, independent from "new train" tests, and reuse them in regressions
3. generate, export, and reproduce a set of trains for each STDCM test

**Comment by shenriotpro** [comment]
A good first step would probably be to make regression tests independent

**Comment by eckter** [comment]
I'd have a preference for option 1.

Option 2 would lead to train schedules that are too regular and "clean", while the purpose of the fuzzer is to test unlikely cases we don't think of when writing tests. 

Option 3 would be nice but it would take a lot more planning and work to make it functional

**Comment by shenriotpro** [comment]
It turns out regression tests *are* independent, thanks to temporary fixtures, as shown by `$ poetry run pytest -k test_regressions --setup-show`

**Comment by shenriotpro** [comment]
Since exports may grow quite large (about 1KB per seed increment), we may want to reset the fuzzer timetable now and then.

**Comment by shenriotpro** [comment]
Consistently using fast_rolling_stock is helpful for reproductibility, so Eloi suggests we look it up from the fuzzer, and load it if we can't find it.
