### ISSUE TITLE
core: stdcm: `TOO_MUCH_TIME` errors can happen in some cases

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3233]
It can be reproduced in the fuzzer, but because it's an STDCM request that depend on the rest of the timetable, it's harder to reproduce in a regression test.

**Comment by eckter** [comment]
What actually happens:

When applying the mareco standard allowance, we first try to apply it over the whole path and then fix points in space/time to avoid any new conflict.

While doing this, we may create allowance ranges that only covers a speedup or braking curve. It's not possible to find a valid solution in such setting.

Fixing this isn't that easy. Ideally we'd need to move time from one range to another. A partial "fix" could be to add margin while avoiding conflicts, to avoid having to fix too many points.

**Comment by celine-sncf** [comment]
@eckter

**Comment by eckter** [comment]
Fixed by #5330
