### ISSUE TITLE
front: simulation sticky bar flashes when train is moving

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3240]
### What happened?

When the train is moving, the sticky bar at the top of the screen flashes :
https://user-images.githubusercontent.com/115472753/220132008-142fe0ce-4aed-4e7c-aeb1-b4aaef43bc25.mp4

### What did you expect to happen?

The bar should not flash

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario https://osrd.dev.dgexsol.fr/operational-studies/scenario
2. Hit the "Play" button on the top sticky bar

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: Dev

### OSRD version

1232050d

**Comment by anisometropie** [comment]
unable to reproduce

**Comment by celine-sncf** [comment]
seems fixed
