### ISSUE TITLE
front: scenario-timetable-trains component is too big in smaller screens

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3244]
### What happened?

When reducing the screen size, there is a big empty space in the scenario-timetable-trains component : 
![image](https://user-images.githubusercontent.com/115472753/220135061-c068d607-247c-4487-9a65-25a154217d18.png)

### What did you expect to happen?

The empty space should be smaller

### How can we reproduce it (as minimally and precisely as possible)?

1. go to any scenario and add 1 train
2. Reduce screen size

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: Dev

### OSRD version

1232050d

**Comment by clarani** [comment]
@nicolaswurtz I think it's for you :)
