### ISSUE TITLE
front: scenario-timetable-train-button-update does not work

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3247]
### What happened?

Nothing happens when clicking the highlighted button : 
![image](https://user-images.githubusercontent.com/115472753/220139051-d53b37a1-3df4-40ab-ad40-260a5e786e67.png)

### What did you expect to happen?

Not sure, edit the selected train ?

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Add a train and move the pointer over the train in the list
3. Click the third button that appears

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: Dev

### OSRD version

 1232050d

**Comment by clarani** [comment]
I can hide the button for the moment, the functionality is not ready yet (Nicolas is going to develop it in the coming weeks). What do you think ?

**Comment by younesschrifi** [comment]
Sorry, I made mistake. I thought it was fixed

**Comment by nicolaswurtz** [comment]
Feature incoming please be patient 😘
