### ISSUE TITLE
front: graph units overlaps content

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3249]
### What happened?

In the graphs, the unit of each axis overlaps content, making it hard to read
![image](https://user-images.githubusercontent.com/115472753/220141336-f691da2a-139f-4c6e-af19-b8b9f37893af.png)
![image](https://user-images.githubusercontent.com/115472753/220141432-c8618d2f-5b0a-4cc8-b44e-86a174328de9.png)
![image](https://user-images.githubusercontent.com/115472753/220141919-150b1585-6964-4484-ad78-87197c4309a6.png)

### What did you expect to happen?

Units symbol should be moved outside the graph 
![image](https://user-images.githubusercontent.com/115472753/220142151-201dd621-4157-4c87-afba-dd7db3383213.png)

Additionally, the right symbol should be used for the units : 
- "m" instead of "M" for meters
- "km" instead of "KM" for kilometers
- "h" instead of "H" for hours

### How can we reproduce it (as minimally and precisely as possible)?

1. go to any scenario
2. add a train
3. scroll down to the graphs

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: Dev

### OSRD version

1232050d

**Comment by alexandredamiron** [comment]
First check if it is really what we want to @nicolaswurtz

**Comment by nicolaswurtz** [comment]
Yes to use right units.
For the placement, put them outside graph will take precious useless space, we should find another way to display units without taking space.

**Comment by nicolaswurtz** [comment]
It's an enhancement: moved to PM Team board, should be refined (along new GET design).

**Comment by axrolld** [comment]
Will be refctored with the rest of the space-time chart.
