### ISSUE TITLE
front: scenario-details-modify-button does not work

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3254]
### What happened?

Nothing happens when using this button :
https://user-images.githubusercontent.com/115472753/220145833-7c7e212d-1523-43bf-adfb-3f367d3966eb.mp4

### What did you expect to happen?

Open the edit scenario window ?

### How can we reproduce it (as minimally and precisely as possible)?

1. go to any scenario page
2. click on the top button "Modifier le scénario"

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: Dev

### OSRD version

 1232050d

**Comment by nicolaswurtz** [comment]
Fixed with #3212 3212
