### ISSUE TITLE
Properly credit front-end libs

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#3255]
### What happened?

Many licenses require being mentioned / credited in the final software. We aren't doing it (because we forgot), and we should fix that at some point

### What did you expect to happen?

Credit libraries

### OSRD version

e6976222

**Comment by celine-sncf** [comment]
Il faudrait aussi ajouter « les pictogrammes des trains en pixel art sont de Marc LeGad [mlgtraffic.net](http://mlgtraffic.net/) » @nicolaswurtz

**Comment by Yohh** [comment]
does it make sense to put them in informations?



![Image](https://user-images.githubusercontent.com/20640252/224036355-361354fc-2b85-4898-bb00-3569c52c7643.png)


@multun @nicolaswurtz @celine-sncf

**Comment by Yohh** [comment]
impossible to use license-checker (outdated) or license-checker-rseidelsohn (updated but incompatible with node v16)
it is possible to extract a decent json file with `license-checker-rseidelsohn --json --production --direct --excludePackagesStartingWith "@types" --relativeLicensePath > licenses.json`
