### ISSUE TITLE
front: study budget should show error message when inputing letters

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3271]
### What happened?

When inputing letters instead of numbers in the budget field, the study cannot be saved but no error is shown : 
![image](https://user-images.githubusercontent.com/115472753/220404941-12c507e4-3680-4d47-8245-87fa2ec5be01.png)

### What did you expect to happen?

An error message should inform "Le budget doit être en chiffres"

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the operational studies page 
2. Create a new project or edit an existing one
3. Input letters instead of numbers in the budget field

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

62637c93

**Comment by clarani** [comment]
@nicolaswurtz ? :)
