### ISSUE TITLE
Create the list of errors in editoast

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3303]
# Description

Create the list of errors editoast will eventually be able to manage.

# Goal

Improve error management in OSRD

# Acceptance criteria

- [ ] All the editoast  errors must be present in the list

**Comment by anisometropie** [comment]
Editoast command to generate a json file (rust macro)

**Comment by flomonster** [comment]
Done by https://github.com/osrd-project/osrd/pull/6632
