### ISSUE TITLE
Pathfinding doesn't seem to take the shortest path

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#3319]
### What happened?

When we search for a path to do a simulation, on the generated infra 5 on dev, the pathfinding doesn't seem to take the shortest path : 
![image](https://user-images.githubusercontent.com/27173221/220870830-e93d429f-c489-43eb-a2af-ff31df9fa47c.png)

### What did you expect to happen?

We expect to have : 
![image](https://user-images.githubusercontent.com/27173221/220871022-09db7e3c-b100-482d-89b0-f9bff23332a3.png)

### How can we reproduce it (as minimally and precisely as possible)?

1. Go on a operational-studies, and create/open a project
2. Create/Open a scenario
3. Create/Open a study with the infra 5 (tiny_infra)
4. search for a path like the picture above

### What operating system, browser and environment are you using?

- **Browser**: Chrome V110
- **OS**: Windows 10
- **Env**: Dgex dev

### OSRD version (top right corner `Account` button > `Informations`)

22a23a45

**Comment by eckter** [comment]
What actually happens:

There was a bug where weights weren't properly considered when the origin and destination were on the same edge. Fixed in https://github.com/DGEXSolutions/osrd/pull/3334 (not merged yet).

But there's a deeper problem: the A* heuristic sometimes gives wrong estimations. Something is wrong in geo distance computations, and it's not 100% clear what.

**Comment by laggron42** [comment]
Reproduced this bug on the French infra when looking for a path between Quiberon and le Croisic.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/23153234/223691250-b58d45d1-9eea-4883-b41f-5b80f46b7eb8.png">

After adding a step to try to enforce the obviously shorter path, a considerable detour is still taken, while showing that the track is perfectly usable
<img width="529" alt="image (1)" src="https://user-images.githubusercontent.com/23153234/223691589-d5ae5fc9-dd93-4334-bf3b-9fce532a58f8.png">

Both origin and destination have single tracks. Tried using different rolling stocks.
