### ISSUE TITLE
Editor : routes through buffer stop

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#3349]
### What happened?

When we try to create a route, the pathfinding could proposes paths going through buffer stops (without any problems, errors or warnings).

![2023-02-27-173147_927x551_scrot](https://user-images.githubusercontent.com/27173221/221624282-44929be4-80c6-4d80-8b1e-e1d1c6bbb741.png)

### What did you expect to happen?

We choose to have this behavior : 
You could create a route through a buffer stop.
However we should have a warning/error to precise that we have a buffer stop which is not on an edge in our infra.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go on the editor
2. Create a route through a buffer stop

### What operating system, browser and environment are you using?

- **Browser**: Chrome v110
- **OS**: Windows 10
- **Env**: Dgex Dev

### OSRD version (top right corner `Account` button > `Informations`)

7bf87858

**Comment by flomonster** [comment]
We should not stop pathfinding when crossing a buffer stop. Ideally, we must check buffer stops and trigger warnings if their position is suspicious (such as the middle of a track).

**Comment by flomonster** [comment]
Checkout #3607
