### ISSUE TITLE
The origin/destination window stops appearing after clicking on the dot to close it

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3357]
### What happened?

When selecting origin/destination for a pathfinding, the following window appears (normal behavior so far) :
![image](https://user-images.githubusercontent.com/86296016/221926128-d4998642-42d6-4a40-9828-e67bc555dce7.png)

But here, if I click on the dot to close that window, it indeed closes the window but then i can never get it to appear anymore.
![image](https://user-images.githubusercontent.com/86296016/221925938-df33baec-3af8-496f-82f6-0d7f8bb1dc67.png)

No matter where i click on the infrastructure, the origin/destination selection window never appears, i need to refresh the page.

### What did you expect to happen?

The window is supposed to appear anytime the user clicks on the infra when it's not already open, else licking anywhere should close it.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Open the origin/destination window by clicking on the infratructure on the map
3. Click on the small dot to close the window
4. Try to open the window anywhere else ont he map, or even at the same spot

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 110.0.5481.178
- **OS**: Windows 10 Professionnel version 21H2
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

1cf46117

**Comment by nicolaswurtz** [comment]
Corrected in https://github.com/DGEXSolutions/osrd/pull/3341
