### ISSUE TITLE
Origin/destination window sometimes gets hidden by the small map frame

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3364]
### What happened?

When trying to set destination in Nice, the origin/destination window pops as follows:
![image](https://user-images.githubusercontent.com/86296016/222165787-33f76586-737a-469e-ae6a-030642bd40ff.png)

This is quite problematic as it becomes impossible to set the destination.

I guess the underlaying problem is the size of the map. In this confiruration the origin/destination window cannot fit neither above the selected spot on the infra nor under it.

### What did you expect to happen?

The map frame is supposed to be big enough to fit the entire origin/destination window.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario page
2. Open the train creation window
3. Try to scale the map as it is on the screenshot
4. Try to select destination

### What operating system, browser and environment are you using?

Browser: Chrome Version 110.0.5481.178
OS: Windows 10 Professionnel version 21H2
Env: dev

### OSRD version (top right corner `Account` button > `Informations`)

eb5d4eac

**Comment by nicolaswurtz** [comment]
Is corrected with #3341 (I'll link this issue) ;-)
