### ISSUE TITLE
timetable import: some characters are not supported in the search field

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3372]
### What happened?

When typing the "-" or "+" character in the search field of the timetable import, the character is not entered and the search is launched. 
For example in this video I try to type "Paris-Nord" : 

https://user-images.githubusercontent.com/115472753/222403623-69f52c54-d72c-4abe-8bca-ec5e6ae7c0fb.mp4

This is especially annoying as it makes it difficult to find stations with a "-" in their name.

### What did you expect to happen?

When typing the "-" or "+" character, they should be entered in the search as any other character

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario https://osrd.dev.dgexsol.fr/operational-studies/scenario
2. Click on "Importer"
3. Click on the "Origine" or "Destination" search field
4. Enter "Paris-Nord" or any station name with a "-" or "+"

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

401ac318

**Comment by Uriel-Sautron** [comment]
When typing the "-" or "+" character, opens the modal window of the space-time graph to update departure time by second.

**Comment by younesschrifi** [comment]
This bug has been fixed
