### ISSUE TITLE
Zooming with the touchpad on the origin/destination component zooms more than the map

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3396]
### What happened?

When selecting origin/destination in the train creation map, zooming with the touchpad on the origin/destination component (which is on the map) zooms the entire screen and not just the map, leading to this display (the screenshot is my entire screen) :
![image](https://user-images.githubusercontent.com/86296016/223057095-8d4596f8-985d-497e-9fea-c9967d978afc.png)

### What did you expect to happen?

Zooming on any component inside the map should zoom on the map.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Open the new train creation window
3. Select a spot on the railway network to open the origin/destination component
4. Try to zoom **with the touchpad**, with the pointer hovering the origin/destination component

### What operating system, browser and environment are you using?

Browser: Chrome Version 110.0.5481.178
OS: Windows 10 Professionnel version 21H2
Env: dev

### OSRD version (top right corner `Account` button > `Informations`)

42dfe5c9

**Comment by nicolaswurtz** [comment]
Don't agree ! Zooming with CTRL+wheel or finger gestures, on anything else than the map (eg the popup) HAS to set the interface bigger. This is how it's intended to be, among others for accessibility issues.
