### ISSUE TITLE
Allowance components overlap with train creation window

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3397]
### What happened?

On a created train, unfolding the allowances component lead to :
![image](https://user-images.githubusercontent.com/86296016/223058323-ae39ea83-50ae-401c-b808-289845df9660.png)

From here, opening the train creation window created this weird overlap :
![image](https://user-images.githubusercontent.com/86296016/223058540-d8e00366-1e23-4e71-bc02-0d142a9e637f.png)

### What did you expect to happen?

The allowance components should be hidden by the train creation window

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario with at least one train
2. Scroll down to the allowances component
3. Unfold it
4. Try to create a new train

### What operating system, browser and environment are you using?

Browser: Chrome Version 110.0.5481.178
OS: Windows 10 Professionnel version 21H2
Env: dev

### OSRD version (top right corner `Account` button > `Informations`)

42dfe5c9

**Comment by nicolaswurtz** [comment]
I take it, it will soon be deleted from this page ! Perhaps in iteration 3.

**Comment by axrolld** [comment]
This bug has looks fixed. I'm closing the issue.
