### ISSUE TITLE
Blue circle after searching a station never disappears

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3398]
### What happened?

After searching for a specific spot, the map displays the correct area on the map, with a blue circle indicating the location that has been searched.

The problem is this blue circle never disappears, even when unzooming a lot, or working on another area.

![image](https://user-images.githubusercontent.com/86296016/223059788-3f53c8d0-fd6e-4788-b10b-149836082cc6.png)

### What did you expect to happen?

The blue circle and the corresponding text should disappear at a point. Either when moving around the map too much, or unzooming too much, or after a certain amount of time.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Open the train creation window
3. Search for a specific location on the map
4. Try to make the blue circle disappear

### What operating system, browser and environment are you using?

Browser: Chrome Version 110.0.5481.178
OS: Windows 10 Professionnel version 21H2
Env: dev

### OSRD version (top right corner `Account` button > `Informations`)

42dfe5c

**Comment by clarani** [comment]
@Math-R and @Uriel-Sautron, do you want to take it ? :)
