### ISSUE TITLE
front: memory leak in TrainHover

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#3414]
![Image](https://user-images.githubusercontent.com/45000526/223126257-4f116a16-55dd-4e5f-bcb9-764f13ae86dc.png)

**Comment by SharglutDev** [comment]
Could you add some context to reproduce this @clarani ?

**Comment by sim51** [comment]
Can't reproduce it and the ticket is older than a year.
I think we can close it

**Comment by clarani** [comment]
Same, I think this bug was solved ealier ! Thanks for checking that ! :pray:
