### ISSUE TITLE
Allowance unit selector can hide the input field

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3448]
### What happened?

When applying an allowance to a train, the user must select a unit (%, mn/km, or s).
If the unit selected is "Pourcentage", the input field is hidden and it become impossible to see what has been written.
![image](https://user-images.githubusercontent.com/86296016/223788056-09bfb388-af1b-4c16-8ce2-facbbcb550c0.png)

Same for "Temps/Distance" :
![image](https://user-images.githubusercontent.com/86296016/223788809-c1faa351-2ac9-4a34-846e-d94133d8f5e4.png)

Because of this it become impossible to set an allowance on some screen sizes.

### What did you expect to happen?

The unit selector should not hide the input field.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario with at least one train
2. Scroll down to the allowance component
3. Unfold it
4. Try to ad an enginnering allowance with percentage or time per distance unit

### What operating system, browser and environment are you using?

Browser: Chrome Version 110.0.5481.178
OS: Windows 10 Professionnel version 21H2
Env: dev

### OSRD version (top right corner `Account` button > `Informations`)

fdf7608f

**Comment by leovalais** [comment]
@kmer2016
