### ISSUE TITLE
map: map generalization makes OSM tracks appear disconnected at higher zoom levels 

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3477]
### What happened?

When zooming on the OSM tracks layer, sometimes the edge of a track seem to be disconnected from the network. When checking the OSM data, there is no error. The error seems to come from the map generalization that should not be used at this zoom level. 

### What did you expect to happen?

The data should be shown as in the "OSM data" in the following examples:
Example 1: 
https://osrd.staging.dgexsol.fr/carto/48.8192/2.2937/22/0/0
https://www.openstreetmap.org/edit#map=22/48.81925/2.29371 
OSRD map:
![image](https://user-images.githubusercontent.com/115472753/224114636-936ba990-d4d1-4543-a42e-67626f39713c.png)
OSM data:
![image](https://user-images.githubusercontent.com/115472753/224114678-f4e8b5fe-957f-4463-99a3-e8c4b408b72c.png)

Example 2: 
https://osrd.staging.dgexsol.fr/carto/48.8211/2.2959/22/0/0
https://www.openstreetmap.org/edit#map=24/48.82110/2.29591
OSRD map:
![image](https://user-images.githubusercontent.com/115472753/224116244-061db642-d033-4c43-9c7a-916834f8fe17.png)
OSM data:
![image](https://user-images.githubusercontent.com/115472753/224114979-9bc9bd5d-bf05-4ff3-937f-02fb2480537d.png)

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map
2. Display OSM tracks
3. Zoom to the following coordinates : 48.8211/2.2959/22/0/0

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows10
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

1f69491d

**Comment by nicolaswurtz** [comment]
New generation of data done ;)
