### ISSUE TITLE
core: allowances: binary search errors builds up over the ranges

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3482]
When we compute an allowance with many small ranges, the error of each binary search can build up. We have a tolerance of one time step for each search, but the total error can be much higher.

Ideally, if the first range had a target time of `x` seconds and we find an envelope that takes `x - y` seconds, the second range should take `y` seconds more than if we found the exact value.

Reproduced in a unit test on the branch `ech/reproduce-bug-1`.

Causes a few STDCM bugs.

**Comment by axrolld** [comment]
Is there a way we could change the target of the second range to add `y` to the second range in your example ?

**Comment by eckter** [comment]
Not from the "outside" of the allowance code, because we don't know any of this process until we get the final result. We can't iterate as the errors aren't fixed.

**Comment by axrolld** [comment]
I meant inside of the allowance code, when computing the ranges

**Comment by celine-sncf** [comment]
@bloussou is interested for the next PI, as it will take time to understand this part of the app

**Comment by celine-sncf** [comment]
@eckter is this bug still happening ?

**Comment by eckter** [comment]
Yes

**Comment by eckter** [comment]
Updating the severity to critical: this can cause STDCM to output trains with conflicts in a way that wasn't properly caught. When fixing this, the STDCM requests actually fail very often (it can't be merged as it is).

Blocking for https://github.com/osrd-project/osrd/issues/4484 (through https://github.com/osrd-project/osrd/issues/6285)
