### ISSUE TITLE
core: allowances: we sometimes fail to find solutions when the ranges are small

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3483]
When an allowance has a lot of small ranges, sometimes we compute them in an order that prevents us from finding a solution.
For example, if a range only covers a braking part, we may compute it last with an imposed start speed. This can make it impossible to add any time. 

Reproduced in a unit test on the branch `ech/reproduce-bug-2`.

This is the cause of this bug: https://github.com/DGEXSolutions/osrd/issues/3233

**Comment by celine-sncf** [comment]
@eckter can we close ?

**Comment by eckter** [comment]
No, it's still relevant. But it's not planned to be fixed soon.

**Comment by axrolld** [comment]
Should be solved by https://github.com/osrd-project/osrd/pull/6404.

If not, feel free to re-open.
