### ISSUE TITLE
Compare services errors with errors managed by frontend, and block CI if they don't match

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3500]
# Description

Thanks to this list of preriquisite enablers ( #3230 , #3302 , #3303 , #3304  ), each service has a list of managed errors, and all errors are following a given format. Now that this is done, the list of errors should remain up to date with upcoming modifications. One way to guarantee that is to add a comparison in the CI between the errors sent by the differents services and the list of errors that can be managed, and block the CI if they don't match.

# Goal

Keep a clean error management.

# Acceptance Criteria

- [ ] All the errors sent by the different services must be part of the list of the errors managed
- [ ] The comparison between the errors sent and the errors managed but be part of the CI
- [ ] When the errors sent differ from the list, the CI must block merging

**Comment by flomonster** [comment]
Done by https://github.com/osrd-project/osrd/pull/6632
