### ISSUE TITLE
stdcm: implement adaptation to the new signalling module

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3502]
# Description

The new signalling module changes the way STDCM algorithm manage conflicts detection. The objective is to implements what has been designed and prototyped here : #2889  #3223 

# Goal

Make detection conflict in STDCM more realistic and reliable.

# Acceptance Criteria

- [ ] The design from #2889 have been implemented

**Comment by flomonster** [comment]
Duplicated of another issue
