### ISSUE TITLE
core: export basic resource usage in standalone sim

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#3505]
# Description

To integrate the new simulation engine, and eventually conflict detection, we need to export the resource usage of individual simulations. For now, zone occupancy will suffice.

# Goal

Complete #1053 

# Acceptance Criteria

- [x] add zone occupancy to the standalone simulation result
- [x] update the openapi spec

**Comment by Khoyo** [comment]
Closed by #3473.
