### ISSUE TITLE
core: the block generator generates bugs with no zonepaths

### ISSUE THREAD

**Issue by Khoyo** [OpenRailAssociation/osrd#3506]
### What happened?

The block generation algorithm sometimes generate zero size blocks.

### How can we reproduce it (as minimally and precisely as possible)?

1) Load the new infra.
2) Try to run a simulation

### What operating system, browser and environment are you using?

- **Env**: Local / signaling-sim branch (the generator is not currently called on dev)

### OSRD version (top right corner `Account` button > `Informations`)

bc2f735

**Comment by celine-sncf** [comment]
part of mononoke's 10% bugs
