### ISSUE TITLE
Migrate TrainScheduleView to editoast

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#3507]
### Description and goal

Part of https://github.com/DGEXSolutions/osrd/issues/1053

As we migrate simulations to the new engine, there will be no need for re-projection of signaling simulations. the current implementation can be removed, and the call to the new signaling simulation endpoint can be made in editoast.

### Acceptance criteria

- [ ] a new endpoint implementation in editoast calls the signaling simulation endpoint
- [ ] the python code is removed
- [ ] the openapi specs are updated
- [ ] an integration test is written

**Comment by multun** [comment]
TODO:
- [ ] migrate `POST /train_schedule/standalone_simulation/` (batch creates train schedules)
- [ ] migrate `GET /train_schedule/{id}/` retrieve a train schedule
- [ ] migrate `DELETE /train_schedule/{id}/`
- [ ] migrate `PATCH /train_schedule/{id}/`
- [ ] migrate `GET /train_schedule/{id}/result/`
- [ ] migrate `GET /train_schedule/results/`(which projects multiple train schedules onto a path)

**Comment by Khoyo** [comment]
Closed by #3871
