### ISSUE TITLE
Wrong projection on space-time chart after deleting a train

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#3515]
### What happened?

When you delete a train and you create a new train, the new train is displayed on the space-time chart with the previous projection

### What did you expect to happen?

The new train is displayed with its own projection

### How can we reproduce it (as minimally and precisely as possible)?

Create a train
Delete it
Create a new train with a different path
See in the space time chart the issue

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: iOS
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

375d926c

**Comment by clarani** [comment]
Solved by #5438
