### ISSUE TITLE
Search into signals (back)

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#3546]
### Description and goal

Add the search object "signal" that exposes the following columns: name, line_code, line_name, aspect.

### Acceptance criteria

We can search for signals with the following criteria 

- [ ] name
- [ ] line_code
- [ ] line_name
- [ ] aspect

**Comment by flomonster** [comment]
Using `aspect` criteria is not a good idea since this field will be removed with the new signaling system.
Checkout the documentation [here](https://osrd.fr/fr/docs/reference/design-docs/signaling/#signal-non-charg%C3%A9)
