### ISSUE TITLE
Import: Electrical Profiles are not imported correctly

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#3561]
### What happened?

When we try to run a simulation with electrical profiles, the simulation never found any electrical profiles.
I suppose that now, we can't import correctly the electrical profiles

### What did you expect to happen?

We could run a simulation with some electrical profiles.

### How can we reproduce it (as minimally and precisely as possible)?

Try to run a simulation with electrical profiles

### What operating system, browser and environment are you using?

- **Browser**: Chrome v110
- **OS**: Windows 10
- **Env**: Dgew Dev

### OSRD version (top right corner `Account` button > `Informations`)

70580ece

**Comment by Castavo** [comment]
Closed by https://github.com/DGEXSolutions/osrd-dags/pull/46
