### ISSUE TITLE
core: we try to build an empty part builder if the train can't (re)start

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3628]
### What happened?

If a train starts or has an intermediate stop on a place where the slope is too high to start, an assertion is triggered. We try to build an empty envelope part. 

### What did you expect to happen?

An `ImpossibleSimulationError` to be thrown. 

### How can we reproduce it (as minimally and precisely as possible)?

A unit test will come soon. Otherwise, it can be reproduced with the fuzzer on France, but it seems quite uncommon.

### What operating system, browser and environment are you using?

- **Browser**: Firefox 
- **OS**: Windows
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

de31346b81472fc266805e8f0566514644103545

**Comment by axrolld** [comment]
I'm very surprised such configuration exist on the network. I guess there are some high slopes but then some trains can't drive there

**Comment by axrolld** [comment]
Is there a way we could send a specific error for this ? It's not a common running-time calculation error, it would be nice to know if the computation crashed because the rollingstock isn't powerful enough somewhere
