### ISSUE TITLE
Setup test fixture for editoast

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#3637]
### Description and goal

Simplify integration test with editoast using [rstest](https://crates.io/crates/rstest) fixture.

### Acceptance criteria

- [x] Drop `ntest` dependency for `rstest`
- [x] Have a fixture that set up an empty infra, project and scenario...
- [x] Have a fixture that set up an example infra (like small_infra). The teardown should drop the created infra.

**Comment by bloussou** [comment]
We can take example of fixtures defined in `conftest.py` :tada: . It is going to be nice :100:

**Comment by flomonster** [comment]
Done
