### ISSUE TITLE
Infrastructure caching is broken

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#3654]
### What happened?

When an infrastructure is requested, it can either be a request for a specific version, or any version. When a request for any version is performed and the infrastructure is not cached, there version stored in the cached entry, which causes it to be re-downloaded later on if a further request asks for a specific version

### What did you expect to happen?

The version number should be returned along with the infrastructure rather than inferred from the request.

See https://github.com/DGEXSolutions/osrd/blob/dev/core/src/main/java/fr/sncf/osrd/api/InfraManager.java#LL158C24-L158C39

### How can we reproduce it (as minimally and precisely as possible)?

It can only be done by re-using paths, which cannot be done easily in the front-end

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

223483dc2bd151191dfb29c6a0b461c5ada7de74

**Comment by celine-sncf** [comment]
@multun

**Comment by multun** [comment]
fixed by f0731d7fb6f68817e7215ad9b9616ca14a31401a
