### ISSUE TITLE
Names are incorrect when adding multiple trains and front behavior is strange: LocalStorage issue

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#3657]
### What happened?

When adding two trains names are incorrect (NaN instead of increments) and local storage must be cleared to have correct names...

### What did you expect to happen?

Correct train names

### How can we reproduce it (as minimally and precisely as possible)?

1. Create trains with OSRD version https://github.com/DGEXSolutions/osrd/commit/5f238be57a32a9126f336e9ea5c35e851523380a
2. Update your version to https://github.com/DGEXSolutions/osrd/commit/df555821acb226a4df8e54cebf95a9f6558a3f08
3. CReate a new project, study and scenrio and create new trains

Versions:

df555821

**Comment by flomonster** [comment]
Fixed with https://github.com/DGEXSolutions/osrd/pull/4047
