### ISSUE TITLE
front: new routing system (slug)

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#3661]
### Description and goal

We should have the project, study, scenario ids in the url:
`project/{project_id}/study/{study_id}/scenario/{scenario_id}`

Benefits
- avoid bugs with local storage
- allow users to send a direct link to a scenario
- separation stdcm/eex

### Acceptance criteria

- [ ] user is able to send a direct link to a scenario

**Comment by Math-R** [comment]
https://github.com/osrd-project/osrd/issues/5428
