### ISSUE TITLE
Front: flush localstorage when project is updated

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#3691]
### Description and goal

Find a way to flush localstorage when his data or structure has changed

### Acceptance criteria

- [ ] Test version of localstorage/project OR if structure/data has changed
- [ ] Automatically flush localstorage on local browser when necessary

**Comment by axrolld** [comment]
@bloussou @nicolaswurtz @alexandredamiron i'm removing this from PI board because it wasn't planned for PI 5

**Comment by axrolld** [comment]
Done
