### ISSUE TITLE
front: stdcm: even if a request stdcm fails, the request status is SUCCESS

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#3706]
### What happened?

The request fails (see the console), but the request status is SUCCESS and the results are displayed.
[Capture vidéo du 2023-03-28 13-49-50.webm](https://user-images.githubusercontent.com/45000526/228228146-e411ea5e-1ab4-45bf-8ce3-a0340dfb3f24.webm)

### What did you expect to happen?

The request status should not be SUCCESS, the user should be informed of the failure and the results should not be displayed.

### How can we reproduce it (as minimally and precisely as possible)?

1. Modify one of the requests in StdcmRequestModal (for instance, remove s to results in the url of the api call)
2. Try to run a stdcm request

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

34769e8f

**Comment by axrolld** [comment]
I can't reproduce this bug right now

**Comment by Yohh** [comment]
can't reproduce this bug

**Comment by clarani** [comment]
I close this bug since it has been solved by a previous PR
