### ISSUE TITLE
front: ReleaseInformations: about modal refacto

### ISSUE THREAD

**Issue by Yohh** [OpenRailAssociation/osrd#3708]
About section has to be enhanced

- [x] scss file should be well located in /styles/scss/common & classes have to be renamed (.informations -> .informations-modal).
- [x] add `withCloseButton` flag and remove modal-header.
- [x] set ReleaseInformations modal in 2-sides display, infomations on the left & licenses on the right, beware of scroll behavior & responsive display.
- [x] don't break anything & have fun.

**Comment by SharglutDev** [comment]
1) Should I also change the strange size of the modal close button ? Border, revealing the dimensions, appearing on focus or when clicking the button.
2) Also the dropdown button color when hovering is almost invisible with darkblue on black background
