### ISSUE TITLE
front: simulation: error message is shown after going back to simulation results

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#3710]
### What happened?

Error messages on the train selection window are not shown directly but only after going back to simulation results.
https://user-images.githubusercontent.com/115472753/228265227-e389257d-9142-4095-9c20-a4d8ea20dd16.mp4

### What did you expect to happen?

Error messages should be shown when trying to create a train, and not after closing the window.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Create a train without inputing a departure time
3. Click "Add a train"
4. Click "Go bakc to simulation results"

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.8
- **OS**: Windows10
- **Env**: dev 

### OSRD version (top right corner `Account` button > `Informations`)

34769e8f

**Comment by nicolaswurtz** [comment]
# What is the problem ?
Error notifications are shown bet BELOW train selection window

# How to correct ?
Change z-index value of notifications toast to the highest value necessary to be shown ABOVE ALL components (including modals — it could be a good reference to determinate the good value).

This choice have to be made globally, in corresponding `.scss` file in `styles/` directory.

**Comment by clarani** [comment]
I think this bug is already solved :) To confirm with Nicolas and Céline

**Comment by celine-sncf** [comment]
Works for me :)
