### ISSUE TITLE
Front sends NaN as departure time to the standalone_simulation endpoint

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#3720]
### What happened?

The front sends NaN as departure time to the standalone_simulation endpoint, no matter what I input

### What did you expect to happen?

The front does not send NaN

### How can we reproduce it (as minimally and precisely as possible)?

Create a Scenario and try adding a train.
It gives a white page because api gives a 500, because it stored a NaN and when serializing it, it fails

### What operating system, browser and environment are you using?

- **Browser**: Firefox 111.0.1
- **OS**: Ubuntu 22.10
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

0a754f9b

**Comment by Castavo** [comment]
The problem doesn't occur on Chrome

**Comment by clarani** [comment]
I think this bug is solved by now

**Comment by Castavo** [comment]
It's still there, but not exactly the same tho, when running a sim, no matter the time given as departure time, there is this error in the browser's console (firefox)
```
Uncaught (in promise) RangeError: invalid date
    sec2time https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:154
    submitConfAddTrainSchedules https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:1031
    onClick https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:1031
    Nb https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    Tb https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    Ub https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    nf https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    se$2 https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    hd https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    Rk https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:40
    Jb https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    hd https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    fd https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    ed https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:37
    lt https://osrd.dev.dgexsol.fr/assets/index-0b3cced7.js:90
index-0b3cced7.js:154:217627
```

**Comment by Castavo** [comment]
Fixed by deleting and reinstalling firefox

**Comment by celine-sncf** [comment]
I get the same error as @Castavo bug I can't reinstall Firefox :( (no admin rights on my SNCF computer), any other possible fix ?
Here is my Firefox version : Version 102.9.0esr (64 bits)

**Comment by celine-sncf** [comment]
Solved by deleting cookies on my Firefox, sorry !!
