### ISSUE TITLE
Wrong heigh of the frame to display the profile in length of the track

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#3723]
### What happened?

The red line representing the longitudinal profile of the track goes out the chart

### What did you expect to happen?

The vertical scale of the chart should be adapter to the total heigh of the vertical profile

### How can we reproduce it (as minimally and precisely as possible)?

Create a train and see what happened in the gradient/radius chert
![image](https://user-images.githubusercontent.com/55697888/228551966-ba79f7e1-6327-402f-b523-05f7e134a6b2.png)

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: IOS
- **Env**: DEV

### OSRD version (top right corner `Account` button > `Informations`)

0a754f9b

**Comment by axrolld** [comment]
dupliacte with #4312
