### ISSUE TITLE
core: signaling: change the semantic to make trains free up their ressources at the end of their schedule

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3731]
### Description and goal

Follow-up of this discussion: https://github.com/DGEXSolutions/osrd/pull/3473#discussion_r1152889181

For now, we consider that the resources used by a train at the end of its schedule are never freed up. It's only when computing the signalization and projecting the path that we make all signals go back to their "free" state at the end of the schedule. This semantic feels off: this should be done at the resource step, not when computing the signalization.

### Acceptance criteria

Trains that have reached the end of their schedule should not use any resource.

**Comment by multun** [comment]
I don't think it was intended in the first place: it's a bug
