### ISSUE TITLE
Simulation fails: `assert(completePaths.isNotEmpty())`

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#3746]
### What happened?

When trying to run trains anywhere, the back returns a response 500

### How can we reproduce it (as minimally and precisely as possible)?

Make any simulation ("Ajouter un train")

### What operating system, browser and environment are you using?

- **Browser**: Firefox 111.0.1
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

ac44ab47

**Comment by Castavo** [comment]
Error message from the browser's network inspector:
```
type	        "core:assert_error"
assert_message	"Assertion failed"
cause	        "INTERNAL"
message	        "Assertion failed"
stack_trace	[ 
  "LoadedSignalingInfra.kt:169",       
  "LoadedSignalingInfra.kt:184", 
  "ScheduleMetadataExtractor.kt:44", 
  "StandaloneSim.java:61", 
  "StandaloneSimulationEndpoint.java:103", 
  "FkRegex.java:153", "FkRegex.java:217", 
  "FkChain.java:72", "TkFork.java:98", 
  "TkFallback.java:84", … 
]
trace	[]
```

**Comment by eckter** [comment]
It doesn't happen *all the time*, but it's easily reproduced using the fuzzer on France (any recent version but I used the `2023_04_19` one). It happens quite often. 

Doesn't appear to be reproducible on `small_infra`.

**Comment by eckter** [comment]
I couldn't finish it today (and I'll likely drop it next week with the start of the next PI)

It happens on routes that go from buffer stop to buffer stop. It's significantly less frequent than before (especially on human-picked paths) so I'll lower the severity.

**Comment by multun** [comment]
This assert is known to fail when routes are inconsistent with signaling: all routes must have proper signaling setup, and routes must end with either a buffer stop, or a route delimiter signal (such as a french non-franchissable signal).

This will be fixed when pathfinding finally takes blocks (cantons) into account, instead of just routes.
