### ISSUE TITLE
Front: RollingStocks: list order is not logical

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#3756]
### What happened?

The rollingstocks must be sorted first by reference, then by name. Or only by name if no reference.

You have to add `.metadata` before `reference` on rollingStockModal in sorter code: 
```
filteredRollingStockListNew = filteredRollingStockListNew.sort((a, b) => {
      if (
        a.metadata.reference &&
        b.metadata.reference &&
        a.metadata.reference !== b.metadata.reference
      ) {
        return (
          a.name.localeCompare(b.name) && a.metadata.reference.localeCompare(b.metadata.reference)
        );
      }
      return a.name.localeCompare(b.name);
    });
```

### What did you expect to happen?

Sort is logical

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

0123456

**Comment by clarani** [comment]
Solved by #3820
