### ISSUE TITLE
Front: displaying rollingstocks list is too slow (1000ms from middleware api)

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#3758]
### What happened?

The request on middleware API for all rollingstock is very slow, about 1000ms to fetch all data.

If we use new editoast API, it is faster than light !

Testing with RTK query confirms the idea.

### What did you expect to happen?

Fetching all data should be < 100ms.

### How can we reproduce it (as minimally and precisely as possible)?

1. open modalof rollingstock
2. wait
3.  ...
4.  *whispering*
5. ...
6. Rage quit, it's too slow

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

0123456

**Comment by celine-sncf** [comment]
@clarani @younesschrifi

**Comment by axrolld** [comment]
I assigned @clarani and @younesschrifi as this should be fixed by #3698
