### ISSUE TITLE
Front: rollingstock list doesn't scroll to already selected rollingstock

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#3772]
### What happened?

When opening rollingstock modal, with an already selected rollingstock, it stays at the top of the list.

### What did you expect to happen?

When opening rollingstock modal, with an already selected rollingstock, it should **scroll** to the right rollingstock.

(we HAVE TO see the scroll as a microinteraction, it informs the user that the item is not on the top of the list)

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

0123456

**Comment by Akctarus** [comment]
Problem fixed, I think we can close this issue

**Comment by clarani** [comment]
I agree :)

**Comment by clarani** [comment]
Cannot reproduce this bug

**Comment by nicolaswurtz** [comment]
I can, I'll show you
