### ISSUE TITLE
Check the validity of the openapi.yaml files

### ISSUE THREAD

**Issue by laggron42** [OpenRailAssociation/osrd#3786]
### Description and goal

Make sure all `openapi.yaml` files are compliant with the reference and are still up-to-date with the applications.

### Acceptance criteria

- [ ] `core/openapi.yaml`
- [ ] `editoast/openapi.yaml`
  - Trying to dynamically generate openapi, see #3625
- [x] `python/api/openapi.yaml`
  - Will be removed soon in favour of editoast

**Comment by flomonster** [comment]
Already checked by the CI
