### ISSUE TITLE
Write `project` fixture and use it for editoast tests

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#3788]
### Description and goal

this test https://github.com/DGEXSolutions/osrd/pull/3780/files#diff-cad4750c35e916fdd2450414a14f1387f8b37f1d2eea3cd363f01709dce8ea8aR285 and other project tests should use the fixture mecanism 

### Acceptance criteria

no more Project::delete() in tests to cleanup

**Comment by flomonster** [comment]
Done
