### ISSUE TITLE
Migrate POST endpoint for /pathfinding/op/

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#3789]
# Description

Migrate POST /pathfinding/post endpoint to editoast.

# Goal

Drop API service.

# Acceptance Criteria

- [ ] the frontend uses the editoast endpoint
- [ ] the endpoint doesn't exist anymore in API

**Comment by flomonster** [comment]
Won't do. This endpoint won't be used. The idea is to use the search engine to retrieve operational points and then call the pathfinding.
