### ISSUE TITLE
Front: Cache invalidation Strategy

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#3801]
A preliminary appraoch made here: https://sncf.sharepoint.com/:b:/r/sites/OSRD644GrpO365/Documents%20partages/Architecture/Browser%20Cache%20Invalidation%20Thoughts,%20Fev%202022.pdf?csf=1&web=1&e=sXHFZi

We need to go further and describe an implementable solution. 

mainly conf and simulation have to be flushed in case of infra model change

**Comment by celine-sncf** [comment]
@alexandredamiron should we close this issue ?

**Comment by Math-R** [comment]
https://www.freecodecamp.org/news/how-to-use-redux-persist-when-migrating-your-states-a5dee16b5ead/
