### ISSUE TITLE
front: when draging a train throught midnight, everything breaks

### ISSUE THREAD

**Issue by Khoyo** [OpenRailAssociation/osrd#3819]
### What happened?

The train arrive before it departs and the curve breaks down

### What did you expect to happen?

The train depart earlier.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a train starting at 00:00
- Drag it back a little
- ????

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

869d7036039850ef236d69cccca1ef887db87353

**Comment by nicolaswurtz** [comment]
It's a complex bug needing whole refacto of GET component: it'll be corrected with new GET flavour.

**Comment by axrolld** [comment]
Fixed since the new GET
