### ISSUE TITLE
Train appears in reverse in GET when starting, then goes back straight

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3823]
### What happened?

The beginning of a train in GET often looks like this :

![image](https://user-images.githubusercontent.com/86296016/230107011-3e04904f-f031-433d-b8eb-e8a23d3185ec.png)

The tail of the train goes before the head, until the train reached its length, then it slowly reverses (at a point the head and the tail are located at the same position !!) until reaching agin its length, this time in the right direction.

### What did you expect to happen?

The train head should start going forward until the train reached it's length, then the tail must follow.

### How can we reproduce it (as minimally and precisely as possible)?

1. Pathfinding : 
![image](https://user-images.githubusercontent.com/86296016/230110716-2b6d634e-cd0a-44d9-a040-6cbf34e14170.png)

### What operating system, browser and environment are you using?

Browser: Chrome Version 111.0.5563.147
OS: Windows 10 build 19045.2728
Env: Dev

### OSRD version (top right corner `Account` button > `Informations`)

6cf0ea12

**Comment by Khoyo** [comment]
Looks like this has been fixed
