### ISSUE TITLE
Warning message for incompatibility between power restriction and electrification mode

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#3835]
## Now

The user can select a restriction on a whole path. For each rolling stock all the restriction codes are proposed without filtering on the elctrification mode of the path. This could lead to an invalid selection (restriction mode not compatible with the electrification mode). In this case, the running time calculation will be performed without taking into account the restriction.

## The goal

We want to notify that the selected restriction code is not compatible with the electrification mode of the infrastructure on this path.
We also want to have a message if no restriction code is selected.

### Situation

When the user clicks on "code de restriction de puissance" and selects the code (for example C12S), if some parts of the path have an electrification mode wich is not compatible with the selected code (for example 25000), a message should appear saying "the restriction code C1US is not compatible with electrification at 25000 V"

**Comment by flomonster** [comment]
Done
