### ISSUE TITLE
core: max effort envelopes sometimes have a discontinuity

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3851]
Reproduced in a unit test on branch `ech/reproduce-bug-3`

**Comment by celine-sncf** [comment]
@eckter is this still a bug ?

**Comment by eckter** [comment]
It seems to be fixed, likely by [this commit](https://github.com/osrd-project/osrd/commit/b0d61181ac83a30e46d596d3e7e9c24ede33f0a1)
