### ISSUE TITLE
Rolling stock selection fails

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#3852]
### What happened?

The application fails to list rolling stocks. We get a 500 from editoast:

```json
{
  "type": "editoast:DieselError",
  "context": {},
  "message": "unknown field `rolling_stock_type`, expected one of `detail`, `family`, `type`, `grouping`, `series`, `subseries`, `unit`, `number`, `reference`"
}
```

Here is the sentry error: https://sentry.shared.dgexsol.fr/organizations/pdi/issues/3672/?project=55&query=is%3Aunresolved&referrer=issue-stream

### What did you expect to happen?

We should be able to query the list of rolling stocks.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open a scenario
2. Click on "Add a train"
3. Try to select a rolling stock

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

9e13d588

**Comment by clarani** [comment]
This is an problem of data, we need to use the new dump

**Comment by flomonster** [comment]
Problem was solved after restoring the new dump.
