### ISSUE TITLE
Pathfinding is really slow

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#3867]
### What happened?

Running pathfinding is really slow ~20s on a big infra (even if the infra is loaded in `core`)

### What did you expect to happen?

It should takes less than a second.

### How can we reproduce it (as minimally and precisely as possible)?

1. Use a big infra (like France)
2. Run pathfinding with multiple intermediate points.
3. Wait for 20s and you have your valid path.

Here is a payload:

```json
{
  "infra": 8,
  "steps": [
    {
      "duration": 0,
      "waypoints": [
        {
          "track_section": "XXXXX_1",
          "geo_coordinate": [
            2.3777653162394587,
            48.84254893127819
          ]
        }
      ]
    },
    {
      "duration": 0,
      "waypoints": [
        {
          "track_section": "XXXXX_2",
          "geo_coordinate": [
            2.439633020325416,
            48.77055557702664
          ]
        }
      ]
    },
    {
      "duration": 0,
      "waypoints": [
        {
          "track_section": "XXXXX_3",
          "geo_coordinate": [
            2.720160896370318,
            48.68861459978964
          ]
        }
      ]
    },
    {
      "duration": 0,
      "waypoints": [
        {
          "track_section": "XXXXX_4",
          "geo_coordinate": [
            2.721859384991697,
            48.59410768845767
          ]
        }
      ]
    },
    {
      "duration": 0,
      "waypoints": [
        {
          "track_section": "XXXXX_5",
          "geo_coordinate": [
            4.398223349757142,
            47.018203760098096
          ]
        }
      ]
    },
    {
      "duration": 1,
      "waypoints": [
        {
          "track_section": "XXXXX_6",
          "geo_coordinate": [
            4.86040437376958,
            45.75776877868395
          ]
        }
      ]
    }
  ],
  "rolling_stocks": [
    117
  ]
}
```

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

e74dc523

**Comment by eckter** [comment]
Severity changed to critical: the problem is amplified for STDCM requests, which becomes impossibly slow

**Comment by axrolld** [comment]
This bug is actually the most critical one we're facing right now, as pathfinding is one of the basic features of OSRD. It need to be fixed firtsly 😕
