### ISSUE TITLE
Front: restore X axis only zoom

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#3877]
### What happened?

Impossible to zoom on X axis only on GET/GEV/etc.

### What did you expect to happen?

Use CTRL+SHIFT+Mousewheel to zoom inside GET/GEV/etc. **on X axis only**

(OS specific keyboard shortcuts will be assigned later)

**Comment by clarani** [comment]
We spent a lot of time on this issue, without any success. This issue is postponed to the refacto of the GET

**Comment by clarani** [comment]
Will be done with the GET refacto
