### ISSUE TITLE
Infrastructure changes do not invalidate simulation results / paths

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#3878]
### What happened?

When an infrastructure changes, even if the change affects simulation results / paths, previous results are not discarded, and there is not way to refresh it manually.

### What did you expect to happen?

Pathfinding and simulation results should be treated as cached data, which can be discarded at any time. These cache entries should be keyed depending on computation inputs.

### How can we reproduce it (as minimally and precisely as possible)?

1. Simulate a train along a path
2. Change the infrastructure along the path
3. Go back to that train
4. The change was not taken into account

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

aa09b49e

**Comment by flomonster** [comment]
A feature that will invalidate trains when changing infra or rolling stock is in progress. #4551
