### ISSUE TITLE
DELETE /infra/{id}/ does not work

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#3880]
### What happened?

> update or delete on table \"osrd_infra_infra\" violates foreign key constraint "osrd_infra_scenario_infra_id_1f77a8c1_fk_osrd_infra_infra_id" on table "osrd_infra_scenario"

It seems like the new project management stuff does not cascade-delete properly.

### What did you expect to happen?

The request should complete. Deletion also is very, very slow.

### How can we reproduce it (as minimally and precisely as possible)?

`curl -X DELETE http://localhost:8090/infra/${YOUR_INFRA_ID}/`

### OSRD version (top right corner `Account` button > `Informations`)

 d0098d1

**Comment by younesschrifi** [comment]
Hello Victor, it's not a bug. If an infra is used by a scenario, you can't delete the infra bc a scenario must have an infra.

**Comment by multun** [comment]
I have multiple issues with the current state of things:
 - The request takes a very, very long time, as indexes on foreign keys are missing
 - The backend just crashes with a 500

**Comment by flomonster** [comment]
The expected behavior is to delete cascade scenarios. The query is indeed very very slow.
A new feature should be to shallowly delete infra. This feature will allow fast deletion and recover of an infra.

**Comment by Tristramg** [comment]
I was quite surprised by the duration when deleting from psql with a very simple `delete from osrd_infra_infra where id=42`.

It seems to spend a lot of time on the `osrd_search_track__del_trig_fun` trigger (I think it’s the only trigger on deletion). Maybe there is a quickwin here
