### ISSUE TITLE
editoast: ElectricalProfileSet is implemented in views/ and doesn't implement common model traits

### ISSUE THREAD

**Issue by Khoyo** [OpenRailAssociation/osrd#3885]
### Description and goal

ElectricalProfileSet implement custom `retrieve` and `create` methods, instead of implementing `Retrieve` and `Create` (potentially through the `Model` derive), with different signatures.

It is also implemented directly in `views/` instead of `models/` (even though it is backed by a DB table)

### Acceptance criteria

- [ ] `ElectricalProfileSet` is consistent with other editoast models
- [ ] It is implemented in model

**Comment by leovalais** [comment]
Done a while ago
