### ISSUE TITLE
editoast: signals are not cached for search during import 

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#3887]
### What happened?

During an infra import, track sections are imported after signals so when the insertion triggers of osrd_infra_signalmodel is triggered, the track section of the new signal doesn't exist yet and therefore the signal is not cached in osrd_search_signal.

### What did you expect to happen?

The new signals should all be cached after the import completes.

### How can we reproduce it (as minimally and precisely as possible)?

1. Import a new infra
2. Check osrd_search_signals
3. The signals of the new import are not there

### What operating system, browser and environment are you using?

N/A

### OSRD version (top right corner `Account` button > `Informations`)

dev

**Comment by celine-sncf** [comment]
@leovalais
