### ISSUE TITLE
Zone updates contain updates for zones trains never enter

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#3889]
### What happened?

When a train's path start at the end of a block, simulation generated occupancy events for a number of zones which the train never enters

### What did you expect to happen?

Zone occupancy events should be accurate

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a train
2. Inspect its zone occupancy events

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

651c40a

**Comment by leovalais** [comment]
@Khoyo

**Comment by Khoyo** [comment]
No longer a bug
