### ISSUE TITLE
Infra generator fails if a signal has its linked detector on a other track

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#392]

**Comment by Castavo** [comment]
@eckter Could you maybe provide a bit more information on this ? 

I generated an infra with a script containing essentially this: 
```python
t0 = builder.add_track_section(length=1000)
t1 = builder.add_track_section(length=1000)

builder.add_link(t0.end(), t1.begin(), ApplicableDirection.BOTH)

detector = t0.add_detector(position=500)
t1.add_signal(500, ApplicableDirection.START_TO_STOP, detector)
```

And it did not trigger any error, the script did not fail

**Comment by eckter** [comment]
This issue is quite old, if this script didn't trigger an error I assume it has been fixed
