### ISSUE TITLE
editoast: add test on endpoint POST rolling_stock/{id}/livery

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#3931]
### Description and goal

The endpoint `POST rolling_stock/{id}/livery` allows to add a livery for a rolling stock and accepts multipart requests (with array of images). As TestRequest does not support multipart request, we decided to merge the endpoint without test and to take some time to add the test later (maybe should open an issue or contribute on TestRequest).

### Acceptance criteria

- [ ] the endpoint is tested

**Comment by flomonster** [comment]
Won't do
