### ISSUE TITLE
front: GEV: some display options are broken when zooming

### ISSUE THREAD

**Issue by Yohh** [OpenRailAssociation/osrd#3933]
### What happened?

when using altitude, eletrical profiles or power restrictions options while zooming:

- altitude vanish from the chart
- electrical profiles and power restriction don't zoom with the chart

### What did you expect to happen?

all options should follow the zoom action

### How can we reproduce it (as minimally and precisely as possible)?

1. create a scenario
2. add train
3. select one of those options in the GEV
4. zoom in the GEV

### What operating system, browser and environment are you using?

- **Browser**: Firefox 113.0b4
- **OS**: Ubuntu 22.10
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

32c4965f

**Comment by Castavo** [comment]
Also, when moving the chart, the altitude disappears.
Interestingly, after the chart is zoomed, toggling altitude twice forces the electrical profiles to redraw so they are now zoomed.
