### ISSUE TITLE
Cannot edit slopes and curves

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#3974]
### What happened?

**NOTE**: This bug can be reproduced only with IOS and Chrome.

When creating or editing a track section. We cannot edit slopes and curves. When we click on the curves chart nothing happens.

### What did you expect to happen?

We should have a form to specify slopes and curves.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. Create a new line
3. Click on the slopes chart

Nothing should happen.

### What operating system, browser and environment are you using?

- **Browser**: Chrome only
- **OS**: IOS Ventura 13.2.1 (22D68)
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

f4d197b2

**Comment by sim51** [comment]
I can reproduce only when I create a track section with only one segment.

![image](https://github.com/osrd-project/osrd/assets/231657/954459d6-695c-45f9-ac09-fa96888a8e8e)

To reproduce the issue : 

* go to the editor 
* click on the  track section tool 
* click on the map for the start point 
* click somewhere else for the second point
* press `escape`

The length of the track section is not computed, and so the charts are not initialized
