### ISSUE TITLE
[CLI stand-alone] Route occupancies "time_tail_free" not correct

### ISSUE THREAD

**Issue by ed-rhilbert** [OpenRailAssociation/osrd#3975]
### What happened?

When launching a stand-alone simulation via the CLI with the following inputs:

- [infra.json.txt](https://github.com/DGEXSolutions/osrd/files/11293773/infra.json.txt)
- [simulation.json.txt](https://github.com/DGEXSolutions/osrd/files/11293774/simulation.json.txt)

the results for `route_occupancies` are not correct, for all routes but the first, as `time_tail_free` is equal to `time_head_occupy`:
```
        "route_occupancies": {
          "rt.buffer_stop.0->DA_out": {
            "time_head_occupy": 0.0,
            "time_tail_free": 54.183
          },
          "rt.DA_out->DB_in": {
            "time_head_occupy": 31.034,
            "time_tail_free": 31.034
          },
          "rt.DB_in->buffer_stop.1": {
            "time_head_occupy": 289.464,
            "time_tail_free": 289.464
          }
        },
```

This is the case for both `base_simulation `and `eco_simulation`

### What did you expect to happen?

`time_tail_free` > `time_head_occupy`

### How can we reproduce it (as minimally and precisely as possible)?

1. Rename attached files to `.json` (`txt `was needed for github to accept them as attachments)
2. Go to `osrd/core`
3. `poetry --directory=../python/railjson_generator install`
4. `./gradlew processTestResources shadowJar`
5. `java -jar /build/libs/osrd-all.jar standalone-simulation --infra_path infra.json --sim_path simulation.json --res_path results.json`

### What operating system, browser and environment are you using?

- **OS**: Windows 10/WSL2/Ubuntu
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

f4d197b2d0a71c5caf65ae8fe3bb54006e0dba30

**Comment by Khoyo** [comment]
Both those route are never released by the train, and hit a stupid bug. It should be fixed by that PR.

Note they will have a release time equal to the end of the simulation. (Here, 313.144)

**Comment by ed-rhilbert** [comment]
👍
