### ISSUE TITLE
stdcm: we rarely find engineering allowances because of the longer routes

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#3992]
### What happened?

When requesting an stdcm that needs an engineering allowance, it's not uncommon to find it.

We can only find an engineering allowance that start and end on route transitions. This wasn't a problem when routes aligned with occupancies, but now the whole path can fit on a single route. 

This is both a bug (it's a regression) and a step for a new feature (integration with new signaling system).

### What did you expect to happen?

We should be able to find allowances that only cover parts of a route. 

### How can we reproduce it (as minimally and precisely as possible)?

Try to find stdcm trains with engineering allowances

### What operating system, browser and environment are you using?

Any

### OSRD version (top right corner `Account` button > `Informations`)

5213be6b55f0706a257f79203ff0f277e71b0253

**Comment by celine-sncf** [comment]
@eckter should this bug still be open ?
