### ISSUE TITLE
Add DELETE to rollingStock upsert Payload API

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#3995]

**Comment by Erashin** [comment]
# Description
Add DELETE to rollingStock payload api. 

# Goal
Allow the users to delete the rollingStocks.

# Acceptance Criteria
- [ ] the rollingStock can be deleted

# Technical refinement
## Implementation
- editoast
  - [x] add and implement DELETE /rolling_stock/{id} endpoint
  - [x] add tests

## Tests for the reviewers
- Postman: 
  - [x] test DELETE /rolling_stock/{id} to delete a rolling_stock
