### ISSUE TITLE
Add copy-paste button and textaera for csv import in rolling stock editor

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4019]
## Description

In the rolling stock editor, the user must be able to edit the speed-effort curve, that will be represented as a table. It is very important to be able to copy-paste this table from/into a csv.

![Image](https://github.com/DGEXSolutions/osrd/assets/86296016/6a8f5dff-f517-4491-914b-b3cf1d13174c)

Global implementation:

![Image](https://github.com/DGEXSolutions/osrd/assets/765626/e81b8cdd-18f6-486d-a220-e6a2f02aeff1)

## Goal

Gain a lot of time when editing a rolling stock

## Acceptance criteria

- [ ] The copy-paste actions are functionnal with a simple text area with tabs
- [ ] The csv import/export can be done later if necessary

**Comment by axrolld** [comment]
Need to refine if we want a copy-paste or an import of a csv.

**Comment by axrolld** [comment]
Update : copy paste of text with tabs for now. It works well on excel for windows and google sheets.
