### ISSUE TITLE
Get and store possible power restrictions on a path when finding it

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4020]
## Description

When a path is found, depending on the electrification mode, only some power restrictions can be applied on a given range. Before implementing the interface for the user to select the power restrictions along the path (need the interval editor designed in #4094, that will be implemented in #4030), we first need to know which power restrictions the user will be able to select with the different electrification modes. 

endpoint: /pathfinding/{path_id}/catenaries/

## Goal

Ease the implementation of the interval editor applied to power restrictions selection (#4030).

## Acceptance Criteria

- [ ] The possible power restrictions along the path are gathered from the path and stored for further use.

**Comment by axrolld** [comment]
The purpose of this issue is not very clear, need to be discussed with @alexandredamiron and @Yohh
