### ISSUE TITLE
Migrate necessary data for pathfinding in kotlin

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4022]
## Check to do 26/06/23
Is this descriptor meta still necessary ?

## Description

Migrate necessary data (@anisometropie can you specify it here please ? 🙏 ) in kotlin for the pathfinding.

Needs #4064 to be completed first and will enable #4027, as represented here :

![Image](https://github.com/DGEXSolutions/osrd/assets/86296016/0bd4814d-a72b-47ca-9c3d-b7b1ba598f26)

## Acceptance criteria

**Comment by anisometropie** [comment]
@multun 
is there something here that is not already done here ?
https://github.com/DGEXSolutions/osrd/issues/4064#issuecomment-1544035427

https://github.com/DGEXSolutions/osrd/issues/4253
