### ISSUE TITLE
Check if front-end can use a schema to automatically set constraints (items min/max...) in standard forms

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4023]
## Description

In the rolling stock editor, there are gonna be multiple input fields with numerical values that correspond to the physical properties of the rolling stocks (_e.g._ length, mass...). We need to check if it is possible to add constraints to this fields using a schema.

## Goal

Only allow physically reasonable values in the rolling stock editor.

## Acceptance Criteria

- [x] Explore rjsf/core solution (and extensions) used in editor
- [x] Study formik capabilities
- [x] Study react-hook-forms capabilities
- [x] Explore other third parties, consider automatic form generation vs automatic formv validation
- [x] Consider easyness of openapi -> jsonschema OR a schema for a resolver in react-hook-form

**Comment by Yohh** [comment]
## react-hook-form vs formik vs rjsf vs redux-form

|  | react-hook-form | formik | jsonschema | redux-form |
| - | - | - | - | - |
| dependencies | ✅️ 0 | ❌️ 7 | ✅️ 0 | ❌️ 8 |
| rendering | ✅️ few | ❌️ numerous | ☑️ depending on integration | ❌️ numerous |
| mounting | ✅️ fast | ❌️ slow | ✅️ fast | ❌️ slow |
| validation | ✅️ object in the input or custom | ❌️ needs more logic or other validator | ✅️ from schema or custom or HTML5 | ❌️ needs more logic or other validator |
| actively maintained | ✅️ yes | ❌️ no (last 2  years) | ✅️ yes | ✅️ yes |
| license | ✅️ open-source | ✅️ free | ✅️ free | ✅️ open-source |
| generate from schema | ❌️ no | ❌️ no | ✅️ yes | ❌️ no |
| complexity | ✅️ easy | ☑️ moderate | ❌️ tough | ☑️ moderate |

- react-hook-form: ***better perfomances*** and easy to setup
- formik: slower, not-maintained and validation incomplete
- jsonschema: harder to apprehend but ***generate form from schema***
- redux-form: slow and validation incomplete

## react-hook-form and resolver

- consider [using](https://github.com/react-hook-form/resolvers#ajv) react-hook-form with [ajv-validator](https://github.com/ajv-validator/ajv)
    - seems to be the fastest solution.
    -  seems easy to implement with openAPI yaml file structure.
    - we can generate a json schema with [this lib](https://www.npmjs.com/package/@openapi-contrib/openapi-schema-to-json-schema)
