### ISSUE TITLE
Allow edition of rolling stock parameters (except speed-effort curve)

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4025]
## Description

Allow user to edit the values of a given rolling stock :

![Image](https://github.com/DGEXSolutions/osrd/assets/86296016/1fd015b8-1f6f-4ef5-a5c2-45667f9f4c07)

The speed-effort curves edition will be implemented in #4026 

Global implementation

![Image](https://github.com/DGEXSolutions/osrd/assets/765626/49b9c358-cb8b-4a6a-baf4-a97318ddea5a)

## Goal

First half of the rolling stock editor

## Acceptance criteria

- [ ] The list of rolling stocks must be placed on the 1/3 left of the screen
- [ ] It must be possible to filter the rolling stocks as it is done when creating a train (should this be another issue ?)
- [ ] Clicking on a rolling stock must open the parameters / speed-effort curves on the 2/3 right of the screen and not unfold the card, as displayed above
- [ ] The edit / duplicate / delete buttons must be moved to the right of the rollingstock card
- [ ] Every field of the following table is editable with the ad hoc form
- [ ] The units are selectable by the user with dropdown lists

| Type| Name               | Range            | Unit |
|------------------------------------------------------|--------------------|------------------|------|
| String | id |                  |      |
| double | length | [0, 2000]        | **m**    |
| double | mass | [0, 100 000 000] | [kg, **t**]   |
| double | inertiaCoefficient | [1, 2] |no unit|
| double |a| [0,                 |[N, daN, **daN/t**]|
| double |b| [0,                 |[N/(m/s), daN/(km/h), **daN/(km/h)/t**]|
| double |c| [0,                 |[N/(m/s)², daN/(km/h)², **daN/(km/h)²/t**]|
| double |maxSpeed|[0, 600]|**km/h**|
| double |startUpTime| [0,                |**s**|
| double |startUpAcceleration| [0,                 |**m/s²**|
| double |comfortAcceleration| [0,                 |**m/s²**|
| double |gamma|[-2, -0.1]|**m/s²**|
| Dropdown_List |gammaType |[CONST; MAX]|      |no unit|
| Dropdown_List  |loadingGaugeType |[G1; G2; GA; GB; GB1; GC; FR3_3; FR3_3_GB_G2]|no unit|
| Map    |modes|[Thermique; 1500V; 3000V; 15000V; 25000V] |      |
| String |defaultMode|                  |      |
| Table | speed-effort | [**(km/h, kN)**, (km/h, daN)] | |

**Comment by alexandredamiron** [comment]
Drops down list for units is feasable in v1 but values won't update immediatly

**Comment by axrolld** [comment]
Alright, we'll stick to that for now
