### ISSUE TITLE
core: add a way to access tracks from the kotlin infra

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#4064]
### Description and goal

The infra objects in the kt version don't have an interface to access the underlying track section. We need to add a convenient way to do this, ideally as lists of track section views.

This is required for https://github.com/DGEXSolutions/osrd/issues/4027, https://github.com/DGEXSolutions/osrd/issues/4022 and https://github.com/DGEXSolutions/osrd/issues/4003., as represented here :
![image](https://github.com/DGEXSolutions/osrd/assets/86296016/68f1b2b6-6ba2-40be-a620-d0a8ffd5bf23)

### Acceptance criteria

We can access track elements from kt infra elements. At least from the ZonePath elements, but possibly the blocks and routes as well.

**Comment by multun** [comment]
The following has to be migrated into the next-gen API :
 - [ ] base track graph API
 - [ ] gradients
 - [ ] speed sections
 - [ ] geo / sch geoms
 - [ ] operational points
 - [ ] loading gauge constraints
 - [ ] voltages

**Comment by multun** [comment]
Re-opening, as the task isn't quite complete enough yet: not all track properties are available
