### ISSUE TITLE
Warn user before deleting/updating rollingstock

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#4133]
## Description

In the current state of the rolling stock management in db, the deletion or update of a rollingstock will be propagated on every train that uses it.
Before allowing the user to delete or updatee a rolling stock, we need to retrieve the trains names and their project/study/scenario linked to it in order to warn the user.

This requires some work in the backend : #4179 

## Goal

Prevent users from deleting trains unintentionnaly

## Acceptance criteria

- [ ] An `Edit` button must be placed next to the `duplicate` and `delete` button

![Image](https://github.com/osrd-project/osrd/assets/86296016/9f692c1a-f523-47d8-9cd4-81260e1f1336)

- [ ] This button must be disabled if the rolling stock is locked

![Image](https://github.com/osrd-project/osrd/assets/86296016/ac8dc97e-5361-4089-8b8c-73f214937fd9)

- [ ] When the user clicks on the "delete" button, a pop-up window must appear explaining that deleting this rolling stock will delete all the trains using this rolling stock, with the list of the trains number and their project/study/scenario if any.
- [ ] If the rolling stock is used nowhere, only a small pop-up window must appear, asking the user if he/she really wants to delete this rolling stock.
- [ ] For the edition, a warning must appear when the user validates the updates, only if the rolling stock is used somewhere. In this case, user must be netified that already done computation won't be updated

**Comment by Erashin** [comment]
Potentially problematic multi-user case:
User 1 - Delete rolling_stock => call rolling_stock usage endpoint => no uses found => confirm deletion popup in front.
User 2 - Uses specific rolling_stock for something.
User 1 - confirms deletion => rolling_stock gets deleted, without warning user it is used now, and with its corresponding impacts.

**Comment by axrolld** [comment]
After discussing with @SarahBellaha @anisometropie @Yohh @Erashin , we agreed on modifying the acceptance criteria as follows :

- [ ] When the user clicks on the "delete" button, a confirmation pop-up window must appear.
- [ ] If the user confirms deletion of the rolling stock, the list of the train numbers and their project/study/scenario that use this rolling stock must appear, if any, and block the deletion. It should be possible to access the corresponding scenarios quickly with a link.
- [ ] If the rolling stock is used nowhere, just delete it after the user's confirmation.
- [ ] For the edition, a warning must appear when the user validates the updates, only if the rolling stock is used somewhere. In this case, user must be notified that already done computation won't be updated
