### ISSUE TITLE
docker-compose-host.yml doesn't work on anything besides Linux

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#4148]
### What happened?

Host networking is apparently only available for Linux so the `docker-compose-host.yml` doesn't work on macOS (and shouldn't either on Windows).
https://docs.docker.com/network/host/

And to make things worse docker compose doesn't show any warning on these platforms.

### What did you expect to happen?

The containers should be reachable from the host.

### How can we reproduce it (as minimally and precisely as possible)?

1. Get a non-linux computer
2. `docker compose -f docker-compose-host.yml up --build`
3. Try to access a container on `localhost:PORT`
4. Helplessly watch it fail

### What operating system, browser and environment are you using?

- **Browser**: N/A
- **OS**: macOS Ventura
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

dev

**Comment by celine-sncf** [comment]
by design, no workaround available
