### ISSUE TITLE
Conserver l'acquis des efforts de stabilisation

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4167]
continuer les bonnes pratiques pour remonter vite, corriger vite et ne plus creuser de la “dette d’instabilité”

Il faudrait assigner à uelqu'un le rôle de QA 

- En dehors des tests manuels et de la recherche de bugs:
- qualification
- suivi des metrics: Bugs: séverité, occurrence, nombre, rapidité de traitement. Perf Back vs usage, stress tests, core web vitals

RAPPEL:
[10:52] DURUPT Celine (EXT PORTALIA)

- Liste des scénarios de tests E2E qui a été transmise pour vérification de la faisabilité technique à Brieuc, Flo & Nicolas > Il faut maintenant la partager & tester à la main

- Faire des tests E2E à la main puis les automatiser !!!

- Le focus doit être sur l'automatisation au niveau de la France le plus vite possible, pas sur les tests à la main

- Tant qu'on n'a pas les tests E2E, lister les dépendances qu'on va toucher quand on fait une tâche pour savoir grâce aux mainteneurs ce qu'on doit tester

- Même une fois qu'on a les tests E2E on pourrait lister dans les PR ce à quoi on a touché pour faciliter le travail de test du reviewer

- Il faut absolument qu'on teste l'application à la main (tous les composants de l'application) dès qu'on commence à toucher à des choses qui sont susceptibles d'en impacter d'autres

- Ça va être trop long, grosse charge de travail pour les gens qui review

- On pourrait jouer tous les test E2E à la main seulement juste avant la release & pas après chaque PR

- Avoir des humains qui testent > une personne dédiée à la quality assurance ?

- Débat sur est-ce qu'il faut des testeurs pros ou pas ?

- C'est beaucoup de travail en plus pour les devs d'expliquer ce qu'on a fait & ce qu'il faut tester, accompagnement métier également

- Les devs ne testent pas assez et ça irait mieux si les devs testaient plus, pas besoin de testeurs

- Les testeurs ne font pas forcément leur travail correctement

- Les testeurs pourraient nous amener des idées de tests qu'on aurait pas eues, sortir l'application de ses retranchements

- L'application évolue trop vite pour que ça vaille le coup d'avoir un testeur à plein temps : ça pourrait être utile plus tard quand l'application sera plus stable

- Si on prend un testeur il faut en prendre un bon, qui est autonome & qui a pas besoin d'aide de la part des devs > crée son scénario de test, sait lire le repo git, a déjà une formation de dev, etc.

- Solution proposée : Alex bloque du temps dans son emploi du temps & on en reparle quand l'application sera plus stable

- Poster le nouveau dump (infra) sur Slack & demander aux gens de tester de manière intensive

- Tester en priorité l'éditeur & ST-DCM

- Dans quelle mesure les contraintes de performance sont prises en compte dans les tests E2E ? (ex : pathfinding trop long car l'infra France est grande)

- Plusieurs pistes

- Import OSM (grosses infras open sources)

- CI à faire tourner sur le déploiement interne où on pourrait mettre nos données privées où on pourrait faire tourner les tests e2e > on a déjà une CI sur la zone interne de DgexSol mais il faut s'en occuper

- On commence par tests automatisés mais qu'on lance en local > Ticket enabler à préparer pour le prochain PI > Flo

- Respecter les standards sur les durées de réponses des API

NEXT STEP: with total Flo, comment communiquer sur le sujet, next step, question de Quality Insurance permanente

**Comment by celine-sncf** [comment]
- le feature freeze pourrait disparaître si on a des tests complets, logique de staging & tag de modules/repo

**Comment by axrolld** [comment]
Isn't this partially answered with the thursday afternoon Q&A meeting ?

**Comment by flomonster** [comment]
This is not an issue
