### ISSUE TITLE
Editor: French text instead of English in speed sections edition tool

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#4202]
### What happened?

When we edit a speed limits:

![Image](https://github.com/DGEXSolutions/osrd/assets/55697979/2ef1c7f1-47d0-4ceb-8ee4-b980b6906abe)

The same bug is in the electrification tool
### What did you expect to happen?

we should have "Linked track sections" instead of "Sections de lignes liées"

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2.  Select a speed section and edit it

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows 10
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

4c97ff1

**Comment by celine-sncf** [comment]
This bug also happens in the project creation window:


![Image](https://github.com/DGEXSolutions/osrd/assets/115472753/470d2374-e21b-4ee7-9c84-5df4662d88d8)
