### ISSUE TITLE
Load infrastructures asynchronously from other operations.

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#4225]
Linked to [#4017](https://github.com/DGEXSolutions/osrd/issues/4017)

## Acceptance criteria
- [ ] Modify core endpoints to not block the patfinding or simulation (return 200) if the infra is not loaded 
- [ ] The front loads the infrastructure in the back when an infra is selected in the front.

**Comment by multun** [comment]
@younesschrifi This does not quite work, as the back-end may restart due to deployments or crashes. editoast has to be able to detect that the infrastructure needs to be loaded, and start the load
