### ISSUE TITLE
front: RollingStockModal maximum update depth exceeded

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#4238]
### What happened?

Errors are printed in the console. This can affect perf

### How can we reproduce it (as minimally and precisely as possible)?

1. Open the console
2. Navigate to a scenario page
3. Click on add
4. Click on the rolling stock selector (the error should appear in the console)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

4c97ff14

**Comment by axrolld** [comment]
Duplicate with #4451 . I'm closing this issue.
