### ISSUE TITLE
Bug in route reservation approval depending on start location

### ISSUE THREAD

**Issue by tpopescux17** [OpenRailAssociation/osrd#427]
In the example infra and simulation generated by gen_base.py below, the function simulation.get_tst in interactive mode returns different lists of approved trains depending on the start location of the trains on their start track section. If the location is <=150, the trains appear as approved (they appear in the list passed_trains) when reaching the breakpoint before the convergence point, whereas they should not be. If the location is >= 151, the bug does not occur
[Bug reservation.zip](https://github.com/DGEXSolutions/osrd/files/7720229/Bug.reservation.zip)
.

**Comment by flomonster** [comment]
legacy
