### ISSUE TITLE
core: ZoneUpdate isEntry is not serialized as is_entry

### ISSUE THREAD

**Issue by Khoyo** [OpenRailAssociation/osrd#4294]
### What happened?

isEntry is not serialized as is_entry.

### What did you expect to happen?

isEntry should be serialized as is_entry.

### How can we reproduce it (as minimally and precisely as possible)?

Look at any ResultTrain in the DB (In SimulationOutputs).

# How should we fix it

Just add `@Json(name = "is_entry")`. We should wait for an invalidation of current simulations though, its not worth it otherwise.

**Comment by younesschrifi** [comment]
will be fIxed by : #4350
