### ISSUE TITLE
Block occupation should follow the standard working

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#4309]
### What happened?

![image](https://github.com/DGEXSolutions/osrd/assets/55697888/5456169c-d4e8-4cc3-9d16-e19ed91d6420)
The block occupation in the GEV is displayed on the shortest running even if MARECO or any allowances is used.

### What did you expect to happen?

The block occupation should follow the shortest running time only if no allowances are added
The block occupation in the GEV should follow the standard workin (shortest running time + allowances)

### How can we reproduce it (as minimally and precisely as possible)?

Create a train
Add allowances
See the GEV

### What operating system, browser and environment are you using?

- **Browser**: Firefox v113.0.2
- **OS**: Ventura 13.3.1 (a) (22E772610a)
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

Application 	 Version Editoast 	 e5481800 Core 	 e5481800 API 	 e5481800 Front 	 e5481800

**Comment by Khoyo** [comment]
Looks like a front end bug. The backend responds with the block occupations for both the base (no allowance) and the eco (with allowance) simulations.

**Comment by alexandredamiron** [comment]
Duplicate #5495
