### ISSUE TITLE
Creation of the linear

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#4317]
## Description

Create a linear graph who can display all the information who only need an horizontal axis

## Acceptance criteria
- [ ] The component must handle multiple data source
- [ ] Each data source must be display on a single line
- [ ] Data source can be toggled to display the one the user want to see

**Comment by axrolld** [comment]
[Here](https://github.com/osrd-project/osrd-confidential/issues/336)
