### ISSUE TITLE
operational-studies/project: text appers in french instead of english

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#4362]
### What happened?

In the project page, even when selecting "english" language, text in operational studies is still in french : 
![image](https://github.com/osrd-project/osrd/assets/115472753/9353101a-f454-4c1a-a3a4-d9a68be973d0)

### How can we reproduce it (as minimally and precisely as possible)?

1. Switch the application to english
2. Go to any project page

### What operating system, browser and environment are you using?

- **Browser**: Firefox 102.11esr
- **OS**: windows 10
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

d4d87379

**Comment by Akctarus** [comment]
Will be solved when the file is available on transifex

**Comment by celine-sncf** [comment]
@multun
