### ISSUE TITLE
Improve the signals layer

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#444]
- [ ] geo and sch angle
 - [ ] linear positioning system positions encoded in a list: `["sncf_pk00:ligne:voie:pk"]`
 - [ ] signal type code
 - [ ] type of physical support (metal pole, zen bamboo, hemp rope)
 - [ ] whether the signal in service
 - [ ] whether the signal is lightable
 - [ ] whether the signal is operational
 - [ ] a comment
 - [ ] the physical organization group (line, track)
 - [ ] the group responsible for the signal (railway station, "poste" (fr))

**Comment by flomonster** [comment]
legacy
