### ISSUE TITLE
front: stdcm: some margins are wrong

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#4481]
![image](https://github.com/osrd-project/osrd/assets/6003856/7191b176-0df7-404d-80e9-2faf3b49bf2c)

- margin between infra loading & pathfinding is missing (should be `0.5rem`)
- margins of allowances labels are wrong (should be `0.25rem`)

**Comment by axrolld** [comment]
Seems like a good first issue to me

**Comment by tykayn** [comment]
@nicolaswurtz j'ai constaté un espace en dessous du bloc rouge du chargement des infra, donc pas reproductible

**Comment by tykayn** [comment]
should we change the margins of these elements around the red rectangle ?

![Image](https://github.com/osrd-project/osrd/assets/3931245/a35b8caa-41da-48b6-b946-7414dbe06e3a)
