### ISSUE TITLE
Editor : Overlapping catenaries warning is not handled correctly by the front

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#4494]
### What happened?

![image](https://github.com/osrd-project/osrd/assets/27173221/a209d5e2-7c1d-45fc-8171-c7e41c30d8c6)

### What did you expect to happen?

Have a correct error format like the other warnings/errors (example below for the overlapping tracklinks) :
![image](https://github.com/osrd-project/osrd/assets/27173221/164f7b52-2831-411a-a115-9207c05ceef5)
 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the Editor
2. Have 2 overlapping catenaries

### What operating system, browser and environment are you using?

- **Browser**: Firefox v114.0.2
- **OS**: Windows10
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

20916ce1

**Comment by sim51** [comment]
It has been fixed in the commit b15191fa45263410896240161f55b5b29160a273
