### ISSUE TITLE
Invert addStep return in OverlayEnvelopeBuilder

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#453]
Currently, the boolean method addStep returns false when a step has been added, and true when it cannot be added. This behaviour is counter-intuitive when calling the method, so we should invert it.

**Comment by Krishpandya682** [comment]
Hi, I am just a beginner here. Is the task here simply to invert the true and false in the addStep method? If so can I implement the change?

**Comment by multun** [comment]
@Krishpandya682 I'm really sorry, we somehow missed your message, and now this issue is obsolete :(

**Comment by multun** [comment]
@Krishpandya682 you can try this one if you're still interested #467
