### ISSUE TITLE
UX/UI improvements and fixes of the rolling stock editor

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#4556]
# Description

The beta version of the rolling stock editor has been released but it has a few aspects that would need to be fixed or improved.

# Goal

Improve user experience.

Unlocks a bunch of other issues :

![Image](https://github.com/osrd-project/osrd/assets/86296016/6606323d-efc3-498f-9d25-284fa8a97272)

# Accepatnce criteria

- [x] change the default rolingstock image, use an existing one as a full-grey placeholder
- [x] #4564 
- [x] remove confirm modal for duplicate
- [x] add new filter for locked rollingstock
- [x] display locked icon at the left side of rollingstock-reference (same gray color)
- [x] adapt modal to the project modal style, confirm annulation by yes/no
- [x] think about the messages in modal, need smarter one for each case
- [x] bugfix several duplication (adapt new-name with date in milliseconds, the last 5 numbers) 
- [x] white background for text-input filter
- [x] fix responsive issues if any

**Comment by Yohh** [comment]
needs refinement with @nicolaswurtz
