### ISSUE TITLE
front: refacto E2E tests: rs editor

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4569]
# Description

Writing end-to-end tests for the new module of rolling stock editor

# Goal

Increase stability of the module

# Acceptance criteria

- [ ] The basic workflows (creation, edition, deletion) of the rolling stock editor have been tested
 
# Notes:
**Create a new RS :**
Click on the button “Nouveau materiel roulant”
Insert all the general parameters 
Click the button confirm 
Click on “courbe effort Vitesse” 
Put values about speeds (on km/h) and traction force (on daN) on the table

_Points deleted , out of test scope_
~~Check that points are added on the curve. Check that they have the good value.~~
~~Check that the function copy/paste works for one line or for the value on a case~~
~~Check that we can delete one line and that the linked point is deleted from the curve~~ 

Click on confirm
Assert that the new rolling stock is created (we can find it by searching into the RS list). Assert that all the properties have the expected value.

**Change an existing RS :** 
Click on the button “duplicate” on a certain RS, assert the message appears (“sohuaitez-vous confirmer cette action?”, click on yes
Assert a new material is created with the same name + “copie”
Click on the button to edit 
Repeat all the actions above 
Should we test also the different curves for all the profiles??

**Comment by axrolld** [comment]
I see that some notes have already been written above, what's the status of this now ? Is there something else i need to do ?
