### ISSUE TITLE
Creating a new infrastructure does not appear until after a page reload

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#4602]
## What happened?

When we create a new infrastructure, the user gets no feedback. They don't see the new infra in the list unless they refresh the page.

## What did you expect to happen?

**Important (it's a bug)**

- We should see the infra in the list.

**Small improvement**

- We can have a notification saying the creation went well
- The name field can be wiped once the infra created.
- We could have the infra sorted by modification date (so when we create a new one it appears first in the list)
  - The list is currently sorted by name 

## How can we reproduce it (as minimally and precisely as possible)?

1. Go to "Map Viewer"
2. Click on the "Infra" button
3. Click on "EDIT" top right corner
4. Fill the name of the new infra
5. Click on "Create an infrastructure"

Refresh the page to see the new infra.

## What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Nixos v23.05
- **Env**: Local

## OSRD version (top right corner `Account` button > `Informations`)

2421cbdb7d8085f6a541b0b2ffc053f51e1a9988

**Comment by younesschrifi** [comment]
Just tested and it's already fixed !
