### ISSUE TITLE
_train_schedule_summaries[0] is undefined due to removing all trains

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#4617]
### What happened?

![2023-07-19_17-07-1689782069](https://github.com/osrd-project/osrd/assets/5047140/b3502d5f-9a25-41c2-8025-186a5d5c5ddc)

### What did you expect to happen?

No error

### How can we reproduce it (as minimally and precisely as possible)?

1. Add a train in an empty timetable
2. Remove it
3. Error ensues

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115.02
- **OS**: Nixos v23.05
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

8a7ba0c25681c06f4c7875a4696ff98485730994

**Comment by flomonster** [comment]
Regression of this one: https://github.com/osrd-project/osrd/issues/4521?
