### ISSUE TITLE
Autocompletion import modal UI

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#4633]
### Description and goal

UI is lacking visual clarity. Looks like it’s a sequence of steps and that there is 4 steps.
After reading the text of course we know, but visually we get lost

1,2 and 1&2 would rather be put side by side, or even in tabs so that we can really see that they are not part of the same sequence.

![Screenshot_20230720_183042](https://github.com/osrd-project/osrd/assets/24652545/ed5aed58-b12c-44c5-97f3-24959c244a30)

**Comment by axrolld** [comment]
This component will be reworked at a point. @nicolaswurtz @clarani and I think we can close this for now.
