### ISSUE TITLE
Flaky end to end tests

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#4647]
### What happened?

On [this workflow](https://github.com/osrd-project/osrd/actions/runs/5624091891) and many more, some tests are not deterministic. This is often caused by incorrect timing assumptions.

```
[28/24] (retries) [webkit] › 008-project-delete.spec.ts:8:7 › Test is operationnal study: study creation workflow is working properly › Delete project
  1 failed
    [webkit] › 005-operational-studies.spec.ts:11:7 › Testing if all mandatory elements simulation configuration are loaded in operationnal studies app › Testing pathfinding with rollingstock an composition code 
  1 flaky
    [webkit] › 007-pathfinding.spec.ts:9:7 › Testing pathfinding › Test pathfinding: no electrified rolling stock for this path throws error 
```

### What did you expect to happen?

Tests should either consistently pass or fail

### How can we reproduce it (as minimally and precisely as possible)?

Either:
1) Run the CI a bunch of times
2) Run the tests on a slow computer, or with decreased resource availability

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: NixOS 23.05 (Stoat)
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

3b56198d2fc24dafef0e59d2a6c2876b7bd08f79

**Comment by clarani** [comment]
It should be fixed by https://github.com/osrd-project/osrd/issues/5024

**Comment by SharglutDev** [comment]
Tests are now consistent since the last e2e PRs.
