### ISSUE TITLE
Change the semantics of envelopes to always be space continuous

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#467]
The current definition doesn't have any practical use for the laxer definition, which makes things slightly harder

See https://github.com/DGEXSolutions/osrd/blob/dev/core/src/main/java/fr/sncf/osrd/envelope/Envelope.java

 - [ ] Remove the spaceContinuous property
 - [ ] Assert that the envelope is space continuous on build
 - [ ] Remove / adapt tests which exercised this "feature"

**Comment by JohnOiko** [comment]
Hello, I am new to open source software but I would like to try to tackle this issue.

**Comment by multun** [comment]
@JohnOiko Hello and welcome to the opensource world :)

First, sorry for taking a bit of time to answer, I have to admit I forgot to. I'll do my best to mentor you through this task.

Here's what this issue is about: Envelopes are a framework to perform computations on speed / position curves. An envelope is some kind of curve, which can be made up of multiple parts, such as accelerating, maintaining a speed, or anything you like, really. Envelopes really are a collection of curves, which must not have overlapping position ranges.

An envelope can be discontinuous:
![2022-01-13_19-01-1642099974](https://user-images.githubusercontent.com/5047140/149391577-fe85a8f6-8f7a-425c-bba3-e75ea66f7194.jpg)

Or discontinuous:
![2022-01-13_19-01-1642100066](https://user-images.githubusercontent.com/5047140/149391750-4449953f-dd8f-4cb6-93ef-f4d34ab23358.jpg)

Currently, envelopes can even have gaps in position:
![2022-01-13_20-01-1642100423](https://user-images.githubusercontent.com/5047140/149392577-ea4b9956-f430-4467-8bd9-bf981db386d4.jpg)

The ability to have position gaps is not needed, and makes envelopes slightly harder to work with. The goal of this issue is to assert that there's no position gap in the constructor of the envelope class, and remove the spaceContinuous property, which was previously used to determine whether an envelope has this oddball property.

This change has to be done in the `core/` subfolder, which contains the code for the java simulation program. If you don't have your favorite java IDE already, I'd suggest using Intellij IDEA community edition.

If you get stuck, comment this issue so we can sort it out together!
