### ISSUE TITLE
Invalid train position path projection

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#4707]
### What happened?

![2023-07-31-151627_444x400_scrot](https://github.com/osrd-project/osrd/assets/5047140/167daba7-ee90-4b09-9985-7b7d7e64203a)
![2023-07-31-151239_402x160_scrot](https://github.com/osrd-project/osrd/assets/5047140/8fc2df13-e633-4b07-b3de-4f9428801952)
![2023-07-31-151534_448x59_scrot](https://github.com/osrd-project/osrd/assets/5047140/c778a106-df6d-458f-90f0-94fff77b7c82)

### What did you expect to happen?

Train position should increase monotonically, as least in this case

### How can we reproduce it (as minimally and precisely as possible)?

It's pretty hard to reproduce: I couldn't really manage to make it happen reliably with public data.

I can reproduce it between Champagné and Brécé, near Rennes, with a BB 64700

![2023-07-31-152643_780x319_scrot](https://github.com/osrd-project/osrd/assets/5047140/be8977c2-a915-422a-a8e5-97af4503b233)
![2023-07-31-152615_503x340_scrot](https://github.com/osrd-project/osrd/assets/5047140/714da3b9-1d19-4b8e-8695-c6fc290a67da)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Nixos v23.05
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

55a0bb00

**Comment by celine-sncf** [comment]
@multun @Khoyo

**Comment by flomonster** [comment]
This was fixed with train schedule v2
