### ISSUE TITLE
editoast: invalid rolling stock: major version mismatch

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#4724]
### What happened?

I tried to make myself a custom rolling stock, and when trying to use it i had this bug :
![image](https://github.com/osrd-project/osrd/assets/86296016/b104c819-3e7d-4849-be1a-fa1cc00c3ad9)

It's a bit sad if `Alex Roulant` can't roll :(

### What did you expect to happen?

There should be either no error, or if there's something wrong with my inputs i should be warned and unable to save my rolling stock as it is.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Try to find a path with `Alex Roulant` as rolling stock

### What operating system, browser and environment are you using?

- **Browser**: Chrome 115.0.5790.110
- **Env**: dev
- **OS**: Windows 10

### OSRD version (top right corner `Account` button > `Informations`)

Editoast 0a9ca097 Core 0a9ca097 API 0a9ca097 Front 9f61f8fd

**Comment by multun** [comment]
The root cause is that the `railjson_version` column is empty in the database
