### ISSUE TITLE
Invalid spacing conflicts 

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#4735]
### What happened?

Spacing conflicts are reported even though the trains are clearly sufficiently spaced.

![2023-08-03-113906_1911x1016_scrot](https://github.com/osrd-project/osrd/assets/15349030/13941b13-1924-4d8e-9944-67f22e5e71e4)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a new timetable
2. Add two trains (I used Paris -> Lyon)
3. Separate them by 50min
4. 200 and more conflicts are reported

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Nixos v23.05
- **Env**: Local & dev

### OSRD version (top right corner `Account` button > `Informations`)

b8b4a320c24d070b728e70e32d7210e36501a474

**Comment by multun** [comment]
This is caused by TVM being implemented as "always open", which confuses resource generation. We planned a two phase fix:
 - make spacing resource generation more robust to faulty signaling
 - eventually, properly implement TVM
