### ISSUE TITLE
Importing train schedules doesn't work

### ISSUE THREAD

**Issue by Akctarus** [OpenRailAssociation/osrd#4768]
### What happened?

A problem appears when trying to import train schedules. 

### What did you expect to happen?

Train schedules should be well displayed.

### How can we reproduce it (as minimally and precisely as possible)?

- Go to scenario
- Click on "import"
- After selecting an origin and a destination, click on the "search" icon
- A toast saying "Impossible de convertir les données en TrainSchedule" appears after few seconds (It should be translated too).

### What operating system, browser and environment are you using?

- **Browser**: Firefox v116
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

8684ff50

**Comment by clarani** [comment]
The import is broken because the data sent by Graou are not in the correct format. @nicolaswurtz can you fix this on Graou side ? :) Thanks

**Comment by nicolaswurtz** [comment]
Yes ! There was problem inside osrd code too (mandatory property that shouldn't be ;)
Corrected with #4850
