### ISSUE TITLE
Rolling stock editor : 4 small bugs

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#4786]
### What happened?

There are a few small bugs on the current version of the rolling stock editor : 
1. The mass unit is displayed in kg instead of tons:
![image](https://github.com/osrd-project/osrd/assets/86296016/060269f6-cd95-4fd4-99e7-8299aa8ac0a3)
And actually changing the unit does not work, the input will automatically be interpreted as tons

2. Trying to change the unit of drag coefficient lead to this:
![image](https://github.com/osrd-project/osrd/assets/86296016/d76d3171-514e-4af2-a6c0-bbbcbb853a3f)
The choices go under the next input field, and it creates a horizontal scroll because the dropdown list makes the component wider.

3. Changing one of the drag coefficient units make it impossible to update the rolling stock:
![image](https://github.com/osrd-project/osrd/assets/86296016/4fdda01a-8a14-4d24-b715-ba9dc9fd3a27)

4. Some speed values are displayed with absurd float precision:
![image](https://github.com/osrd-project/osrd/assets/86296016/994d4c06-0b2f-4237-85d6-0dfe24acb0fd)

### What did you expect to happen?

1. The unit selector must be tons by default, and if the user decides to set a mass in kg it should be interpreted as kg in the backend. If this does not work yet the unit selection should be disabled.
2. There should never be a horizontal scroll on this component. And the dropdown list must come in front of other input fields so that the user can see it entirely
3. It should be possible to update a rollingstock with other units for the drag coefficients. If that's too long to implement for now, the unit selector should be disabled for the moment.
4. No matter the input, the value should not be displayed with more than 2 digits after coma, and 60.00 should be displayed 60.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the rolling stock editor
2. Try to edit an existing rollingstock

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 115.0.5790.171
- **OS**: Windows 11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast 467ea7bc Core 467ea7bc API 467ea7bc Front 467ea7bc

**Comment by clarani** [comment]
The value should not be displayed with more than 2 digits after coma

**Comment by Akctarus** [comment]
We've broken down the remaining bugs into new issues for greater clarity, so can therefore close this issue.
