### ISSUE TITLE
No Space-Speed Chart on some trains

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#4790]
### What happened?

I can't see the space-speed chart of this train, for no visible reason:

https://github.com/osrd-project/osrd/assets/86296016/c425e18c-c5d8-45f5-95e7-4e57be66a0c4

It happened to me on some other trains as well, i can't see any correlation between those. It's pretty weird.

### What did you expect to happen?

The chart should be visible for every train.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the scenario that's in the video
2. Try to reproduce the bug

### What operating system, browser and environment are you using?

- Browser: Chrome Version 115.0.5790.171
- OS: Windows 11
- Env: dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast 467ea7b Core 467ea7b API 467ea7b Front 467ea7b

**Comment by flomonster** [comment]
Not a bug.

When a train path doesn't intersect the GET projection path it's normal not to see the train.
