### ISSUE TITLE
Value of energy consumption isn't display for pasted train

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#4800]
### What happened?

When you create a train with MARECO margin, OSRD displays the energy consumption (in green)
![image](https://github.com/osrd-project/osrd/assets/55697888/75bda357-28fe-430e-9cb8-256cbf107c6b)

### What did you expect to happen?

When you copy paste an existing train already calculated with MARO margin, the value of energy consumption is not displayed
![image](https://github.com/osrd-project/osrd/assets/55697888/e04f7fe3-8297-40de-a4d2-ce90562bcf93)

### How can we reproduce it (as minimally and precisely as possible)?

Create a train with MARECO margin
Duplicate the train
See the energy consumption

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 115.0.5790.170
- **OS**: Ventura 13.5 (22G74)
- **Env**: [dev](https://osrd.dev.dgexsol.fr/)

### OSRD version (top right corner `Account` button > `Informations`)

711f7ef2

**Comment by clarani** [comment]
Can not reproduce, this bug must have been solved :white_check_mark: I close this bug, with Loïc's approval
