### ISSUE TITLE
front: allowance parameters are not validated when loaded from cache

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#4842]
### What happened?

Allowance parameters are saved between session and shared between projects. This is an issue, as per-interval allowance bounds are only valid for a given path.

### What did you expect to happen?

Allowance parameters should be:
- either re-validated when loaded from the cache
- or not saved at all

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a train with per interval allowances from offfset A to offset B
2. Create another train with a different path, preferably shorter than the first one
3. The allowance parameters of the first train are reused, and can cause the backend to crash

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Nixos v23.05
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

2626967d61c8445e4cf7f6ed0d2f15429436e8e1

**Comment by clarani** [comment]
Fixed by https://github.com/osrd-project/osrd/pull/5643
