### ISSUE TITLE
editoast: regenerate simulation outputs as needed

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#4848]
### Description and goal

Sometimes, an API change requires all simulation outputs to be re-generated. Pretty much the only way to do it is as follows:
1) create a migration that drops all simulation outputs
2) when attempting to retrieve a simulation output, re-generate it if missing

Currently, a missing simulation output causes the train to be seemingly missing.

### Acceptance criteria

- [ ] When a simulation output is missing, it's generated on demand

**Comment by flomonster** [comment]
A missing simulation output means that the train schedule is invalid somehow:

- There is an API change
- The train couldn't be imported from a data source
- Maybe some other cases? :shrug: 

What should be done:

- The front should display these trains as invalid
- Invalid trains should be editable
- We should be able to regenerate the simulation output of an invalid train

Note: A train can be invalid cause it doesn't have a pathfinding output.

**Comment by flomonster** [comment]
Design with train schedule v2
