### ISSUE TITLE
Ability to specify unmovable extremities in Intervals Editor

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4854]
# Goal

In some cases of integration the interval editor must enforce some values to be specified on whole imperative ranges

# Acceptance Criteria

- [ ] Intervals Prop should be expanded in order to specify extremities which cannot be moved.
- [ ] Intervals Prop should be expanded in order to specify Intervals which cannot be removed.
- [ ] Splitted Intervals created from theses kind of intervals should inherits these properties except from new extremities created

**Comment by clarani** [comment]
We will not continue the development of this component for the moment
