### ISSUE TITLE
front: impossible to select power restrictions when selecting electrical rolling stock

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#4866]
### What happened?

When creating a train, if you select some electrical rolling stocks and click on "simulation parameters", sometimes you can not select power restrictions

### What did you expect to happen?

You should always be able to select power restrictions if the selected rolling stock is electric

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario, click to add a train
2. Select rolling stock 1600
3. Select a path
4. Click on "Simulation parameters"
5. You should not be able to see the intervals editor

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

9c781be3

**Comment by Akctarus** [comment]
It seems that not all electrical trains have restriction codes

**Comment by Yohh** [comment]
did you mean 16000? if so, this one has no power restrictions

**Comment by axrolld** [comment]
I moved this to PI8 to keep track of it. If not relevant anymore feel free to remove it.

**Comment by axrolld** [comment]
Agree with @Akctarus and @Yohh , not all electrical RS have power restriction codes. I'm not sure this behavior is a bug.

**Comment by clarani** [comment]
In the end, this is not really a bug, but I'm going to add a message if a rolling stock doesn't have any power restrictions to inform the user that the rs lacks power restrictions

**Comment by axrolld** [comment]
I tried this, the fix is visible but there are two warning pop ups showing up saying the electrification is not compatible with power restrictions. We need those pop ups to be removed in the case the rolling stock has no power restriction.
