### ISSUE TITLE
Tracks disappear from the map when zoomed in sufficiently

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#4872]
### What happened?

At zoom level 13 or more tracks under buildings disappear but can be selected:

Here screenshots of Berlin main station:

### Zoom ~12:
![image](https://github.com/osrd-project/osrd/assets/15349030/3e4c6bb0-6faa-4d17-8bde-07a8c488cf3e)

### Zoom ~13:
![image](https://github.com/osrd-project/osrd/assets/15349030/3425e493-2974-4991-bd30-c9fb2e4c0e25)

### What did you expect to happen?

See tracks above the map at all zoom level

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to "Map viewer"
2. Select an infra
3. Zoom in

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

9c781be3fb88eebb3a9f535c99338f3a9dd5eef4

**Comment by alexandredamiron** [comment]
Can' reproduce

**Comment by nicolaswurtz** [comment]
Can reproduce (look for Paris-Nord)
