### ISSUE TITLE
Poetry venv do not contain railjson_generator module on Manjaro

### ISSUE THREAD

**Issue by ldesauw** [OpenRailAssociation/osrd#4874]
### What happened?

I was following the "Getting Started" section on a fresh manajro linux installation. 
I run the docker-compose. The osrd-api container was flaged unhealthy, I stoped it and rerun the build and it worked. 

After the container was up I run started the venv with `poetry --directory=python/railjson_generator shell`
And then runned `./scripts/generate-infra.sh small_infra`. 

At this moment I had the following error displayed 
```sh
$ ./scripts/generate-infra.sh small_infra
Loading small_infra
running generation script small_infra
Traceback (most recent call last):
  File "/home/lauric/Desktop/osrd/python/railjson_generator/railjson_generator/scripts/examples/small_infra.py", line 7, in <module>
    from railjson_generator import (
ModuleNotFoundError: No module named 'railjson_generator'
Traceback (most recent call last):
  File "/home/lauric/Desktop/osrd/python/railjson_generator/railjson_generator/scripts/generate.py", line 39, in <module>
    main(args.scripts, args.output_dir)
  File "/home/lauric/Desktop/osrd/python/railjson_generator/railjson_generator/scripts/generate.py", line 24, in main
    run_script(gen_script, output_dir)
  File "/home/lauric/Desktop/osrd/python/railjson_generator/railjson_generator/scripts/generate.py", line 16, in run_script
    subprocess.run([sys.executable, gen_script, script_output], check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/lauric/.cache/pypoetry/virtualenvs/railjson-generator-85mCTqiW-py3.11/bin/python3', PosixPath('/home/lauric/Desktop/osrd/python/railjson_generator/railjson_generator/scripts/examples/small_infra.py'), PosixPath('/tmp/generated_infras/small_infra')]' returned non-zero exit status 1.
```

I tried changing the directory to start the poetry env. I went to osrd/python/railjson-generator/railjson_generator directory to start the venv. Each time the environement was free from any module and so the script could not find the module. 

I tried building the environment with poetry but it did not resolved the issue.

As people are already using the tool I guess that there must be a way to make it work and I may do something wrong. 

When running the web application everything that can be tested seems to work, but no infrastructure is loaded. 

This was tested with the version from that commit : f54c4dcad1d3af53b4d843369c7750c6cded43cd
I'm testing it with the last one : 9c781be3fb88eebb3a9f535c99338f3a9dd5eef4

### What did you expect to happen?

I expected the script to load the small_infra in the tool. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Checkout the repository
2. Go to osrd/
3. run `docker-compose up -d --build `
4. run `poetry --directory=/python/railjson_generator shell`
5. Now in the venv `railjson-generator-py3.11`, run `./scripts/generate_infra.sh small_infra`

### What operating system, browser and environment are you using?

- **Browser**: Firefox v116.0.2
- **OS**: Manajro Linux 23.0.0
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

f54c4dcad1d3af53b4d843369c7750c6cded43cd

**Comment by flomonster** [comment]
Hello, thank you for your feedback. There is indeed a problem in the readme file. Here's a [PR](https://github.com/osrd-project/osrd/pull/4903) that should solve your problem.
