### ISSUE TITLE
generate-infra.sh: small_infra not generating layers

### ISSUE THREAD

**Issue by ed-rhilbert** [OpenRailAssociation/osrd#4883]
### What happened?

I followed the instructions in the main README 
```
# build and run the entire stack
docker-compose up -d --build

# generate and load an example infrastructure
poetry --directory=python/railjson_generator shell
./scripts/generate-infra.sh small_infra
```
and encountered the following rust error:

```
Import succeful! New infra has id: 1
Generate layers
[2023-08-24T13:41:05Z INFO  editoast] 🍞 Infra small_infra[1] is generating:
thread 'main' panicked at 'invalid track section geometry: Error("Encountered non-array value for a 'bbox' object: `null`", line: 0, column: 0)', src/infra_cache/mod.rs:221:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
In the GUI, `small_infra` is visible, but I can't do anything with (a stop icon appears on hover)

![image](https://github.com/osrd-project/osrd/assets/74606040/f9f76497-a0f6-49cc-a0f8-4f62a2c74298)

### What did you expect to happen?

No error and/or the possibility to load the infra in the GUI.

### How can we reproduce it (as minimally and precisely as possible)?

...

### What operating system, browser and environment are you using?

- **Browser**: Chrome 116.0.5845.98
- **OS**: Ubuntu 20.04.6 LTS / WSL2/ Windows 11
- **Rust**: rustc 1.71.0 (8ede3aae2 2023-07-12)

### OSRD version (top right corner `Account` button > `Informations`)

4a8f78f67c92cc173141f482c812e32a07a616d1

**Comment by multun** [comment]
Fixed as a side effect of #4985 and #5048, feel free to reopen if it happens again. We switched database migration system in #4985, which means you'll have to delete your database and import back your stuff.
```
docker compose down
docker volume rm osrd_psql_data osrd_redis_data
```
