### ISSUE TITLE
E2E tests timeout issue on CI pipe investigation

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4895]
# Analysis
Analyse of the last failures: https://docs.google.com/spreadsheets/d/1qffGX3J2IW2YFXepQuQoEQzNB9LZvs3ixvg63dN0tEw/edit?usp=sharing

![Image](https://github.com/osrd-project/osrd/assets/45000526/09accd2c-1ae0-4263-94ce-29b248e0e8b4)

Even after I increased the timeout of the tests, some still fail. Those tests should be corrected: 
- 007 pathfinding origin: the map does not load correctly and the test can not finish
- 009 stdcm : the stdcm request fails

**Comment by clarani** [comment]
This issue is not relevant anymore :white_check_mark:
