### ISSUE TITLE
front: import: trainschedules are refreshing simulation results for each calculation

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#4898]
When calculating trainschedules, simulation results are refreshed for each calculation.

It should only refresh at the end of all calculations.

![Image](https://github.com/osrd-project/osrd/assets/6003856/da46e89d-815f-4dd2-9f4c-19a035fd248c)

Linux / Firefox
OSRD Front a7bf4b66

**Comment by clarani** [comment]
closed by #5243
