### ISSUE TITLE
Routing conflicts: wrong time range

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#4919]
### What happened?

When we have a routing conflict the time range shown is not the expected one.

### What did you expect to happen?

We expect to have the time range when the trains overlap on the same TVD section.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Create two trains with a routing conflict

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

1e94853a31ec9e9ed87f7534f1ea27018c4d511e

**Comment by celine-sncf** [comment]
fixed
