### ISSUE TITLE
front: migrate SimulationResults/ChartHelpers files to typescript

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#4956]
### Description and goal

Migrate the following files to typescript :
- [x] `drawCurve.jsx`
- [x] `drawElectricalProfile.jsx`
- [x] `drawPowerRestriction.jsx`
- [x] `svgDefs.jsx`

**Comment by axrolld** [comment]
I moved this to PI8 to keep track of it. If not relevant anymore feel free to remove it.
