### ISSUE TITLE
Speed limit with no composition code are all dark

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#4983]
### What happened?

All Speed limit with no composition code are black on the map.

![2023-09-06-164225_954x839_scrot](https://github.com/osrd-project/osrd/assets/27173221/d9fef126-8d44-4237-a52a-18239e0c9529)

### What did you expect to happen?

We expect to have different colors in connection with the speed.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map viewer (or somewhere with the map)
2. Display the speed limit with no composition code

### What operating system, browser and environment are you using?

- **Browser**: Chromium v105
- **OS**: Nixos v22.11
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

3e1b54cb

**Comment by Yohh** [comment]
can't reproduce this bug

Also, this part of the code is complex and requires comments
