### ISSUE TITLE
editoast+openApi: automatedly generated openApi file is not valid

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#4994]
### What happened?

OpenApi is broken and cannot be used to generate types for the frontend anymore.

This is likely because of the automatic generation of TimetableImportPathLocation, because "Discriminators require references, not inline schemas".
We should either modify the automated generation of the OpenApi or write the description of the concerned endpoint manually (and not automatedly).

### What did you expect to happen?

The automated generation of the openApi should generate a valid openApi file.

### How can we reproduce it (as minimally and precisely as possible)?

1. cd front
2. yarn generate-types

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

e0ad0648

**Comment by flomonster** [comment]
I have some ideas about fixing this issue [here](https://github.com/osrd-project/osrd/pull/4802#issuecomment-1711722364)
