### ISSUE TITLE
front: refacto RollingStockEditorCurves component

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#5007]
Simplified and consolidate the code of RollingStockEditorCurves

To refine

4 j max x 2

# Details
- [x] le composant devrait prendre en argument curves qui correspond uniquement à `currentRsEffortCurve.modes` (aucun besoin du mode par défaut)
- [x] passer les selectors dans le state et pas dans le store pour supprimer le store (`selectedComfortLevel`, `selectedElectricalProfile` et `selectedPowerRestriction`)
- [x] renommer `rollingstockParams` en `curveParams`
- [x] ajouter le bouton + au composant générique Selector

- [x] la donnée des courbes doit être stockée dans le composant parent (RollingStockEditorForm). Lorsqu'on update les courbes (via le spreadSheet ou en ajoutant un nouveau comfort/mode de traction/profil électrique/restriction de puissance), l'update doit se faire via le setter du parent (et la donnée mise à jour ruisselle sur le composant)

Flux de données:
- lorsque les courbes sont mises à jour ou que les paramètres d'affichage sont modifiés:
  - on réinitialise/met à jour les paramètres d'affichage si besoin (comfort, mode de traction...)
  - on met à jour les courbes à montrer (curvesToDisplay) dans le graphique
  - on met à jour la courbe affichée dans le spreadsheet (curveForSpreadsheet)
- lorsqu'on modifie le spreadsheet:
  - on ordonne les lignes par la 1ere colonne
  - on met à jour la courbe sélectionnée dans le composant parent
  ⚠ attention, il est maintenant nécessaire de filtrer les lignes incomplètes au moment de préparer le payload pour le backend

Finalement, le fichier ne devrait comporter que:
- props: 
  - curves (les courbes du rollingStock)
  - setCurves (pour mettre à jour les courbes dans le composant parent)
- state:
  - selectedMode (on ne devrait pas en avoir besoin dans le composant parent) 
  - selectedComfortLevel, selectedElectricalProfile, selectedPowerRestriction
- const avec useMemo:
  - rollingStockParams: liste des paramètres à afficher dans les sélecteurs ([selectedTractionMode, selectedElectricalProfile, selectedComfortLevel, curves)
  - selectedCurveIndex: l'index de la courbe sélectionnée dans le tableau de courbe du mode sélectionné ([selectedTractionMode, selectedElectricalProfile, selectedComfortLevel, selectedRestrictionPower, curves]
  - curveForSpreadsheet: courbe à afficher dans le tableur ([selectedCurveIndex, curves])
  - curvesToDisplay: les courbes à afficher dans le graphique ([selectedTractionMode, selectedElectricalProfile, selectedComfortLevel, curves])
- fonctions
  - fonction pour ajouter un nouveau rollingStock param (comfort, mode de traction, profil électrique, restriction de puissance): génération de la nouvelle courbe, puis mise à jour des courbes dans le composant parent (les fonctions de génération de nouvelles courbes peuvent être dans un helper ?)
  - fonction retirer une courbe
  - fonction pour ordonner le spreadsheet
  - fonction pour mettre à jour les courbes après modification du spreadsheet

**Comment by axrolld** [comment]
I moved this to PI8 to keep track of it. If not relevant anymore feel free to remove it.
