### ISSUE TITLE
Design a way to add java signalization modules

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#502]

**Comment by eckter** [comment]
The way I imagine it: we add a new interface

```java
public interface SignalingModule {
    Set<Aspect> getAspects();
    void update();
    Set<Signal> getSignalDependencies();
    Set<Route> getRouteDependencies();
}
```

Signals each have one instance of this interface, railjson format is slightly modified to make it polymorphic

We create a new class `RailScriptSignaling` that implements `SignalingModule` using what we already have

We can then create any new signaling module and write all the logic there

**Comment by multun** [comment]
We have to pick between creating event sourcing changes for all signal state types, or having a generic event state change signal. , which implies that signal states are immutable.

This immutable functional programming interface allows for arbitrary signal state, as long as you can convert the signal state to an aspect set:
```java
/** The stateless, static and immutable infrastructure signal. It has an associated SignalState per simulation */
public interface Signal {
      List<Signal> getSignalDependencies(Infra infra);
      List<Route> getRouteDependencies(Infra infra);
      SignalState getInitialState();

      /** The return value of this signal will be used to update its associated SignalState */
      SignalState processDependencyUpdate(InfraState infraState, SignalState previousSignalState);
}

/** An immutable signal state. It would be serializable in an event log somewhere. */
public interface SignalState {
      Set<Aspect> getAspects();
}

public interface InfraState {
     SignalState getSignalState(Signal signal);
     RouteState getRouteState(Route route);
}
```

This immutable functional programming slimmer interface defines the state of all signals as a set of aspects:

```java

/** PUBLIC MODULE INTERFACE */

/** The stateless, static and immutable infrastructure signal. It has an associated SignalState per simulation */
public interface Signal {
      List<Signal> getSignalDependencies(Infra infra);
      List<Route> getRouteDependencies(Infra infra);
      SignalState getInitialState();

      /** The return value of this signal will be used to update its associated SignalState */
      Set<Aspect> processDependencyUpdate(SignalInfraState infraState, Set<Aspect> previousState);
}

/** Implemented by InfraState */
public interface SignalInfraState {
     Set<Aspect> getSignalState(Signal signal);
     RouteStatus getRouteState(Route route);
}

/** PRIVATE IMPLEMENTATION */

public final class SignalState {
    private Set<Aspect> currentState;
}
```

Delays can be implemented by adding a `getDelayedSignalDependencies` and a `getDelayedRouteDependencies` method to Signal, where the lag of each link can be directly specified.

**Comment by flomonster** [comment]
```java
public abstract class SignalState {
     private Set<Aspect> aspects;
     protected final void setAspects(Set<Aspect> aspects, Simulation sim) {
        // ...
    }

     public void update(Simulation sim);
}
```

**Comment by eckter** [comment]
Oh we forgot about a way to define aspects, I don't think it should be defined in railjson if we remove railscript. Whatever solution we chose, we could add some kind of `Set<Aspect> getAllAspects()` to the interface

edit: a global registry would be better

**Comment by multun** [comment]
I just noticed we do not yet have a nice way to link each signal dependency to its associated route. It's not required by the framework, but would be a plus IMO.

**Comment by multun** [comment]
it seems like a global registry [will need some thought to be implemented properly](https://stackoverflow.com/questions/28287749/java-use-static-initializer-blocks-to-register-classes-to-global-static-registr)

**Comment by flomonster** [comment]
This issue can be close since we elected a new model. 
The issue related to the implementation can be found here: https://github.com/DGEXSolutions/osrd/issues/512
