### ISSUE TITLE
[META] front: refacto, new nomenclature, new code organization

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#5022]
### Description and goal

The aim of this issue is to completely rethink the code organization of the project for the front part.

Some guidelines have been (or are currently) written.

## Themes (order is important)

1. Nomenclature & architecture
  1.1. Really isolate STDCM from EEX
2. Routing / Slug
3. Redux & store
4. SCSS setup
5. Using typescript
6. E2E Tests writing

## Linked issues, task or *meta* tasks

- Routing #3661 
- Tests e2e #5024
- STDCM #5074 
- Migration typescript (feature front refacto - migration typescript)
  - #4957 
  - #4958
  - #4951 
  - #4715 
  - #4961 
  - #4960 
  - #4959 
  - #4952 
  - #4955 
  - #5018 
  - #4844 
  - #5100 
  - #4956 
  - #5156 
- Scss reorganisation (feature front refacto - réorganisation scss)
  - #5170

### Acceptance criteria

A list of conditions which define when this task shall be considered complete

**Comment by clarani** [comment]
Finally done :tada:
