### ISSUE TITLE
Implement BAL and BAPR in a new java module

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#503]

**Comment by eckter** [comment]
The way I imagine it: we add a new interface

```java
public interface SignalingModule {
    Set<Aspect> getAspects();
    Set<Signal> getSignalDependencies();
    Set<Route> getRouteDependencies();
}
```

Signals each have one instance of this interface, railjson format is slightly modified to make it polymorphic

We create a new class `RailScriptSignaling` that implements `SignalingModule` using what we already have

We can then create any new signaling module and write all the logic there

**Comment by axrolld** [comment]
@eckter i found this issue, is is still relevant ?

**Comment by eckter** [comment]
It's not exactly outdated, but not planned anytime soon
