### ISSUE TITLE
impossible to create a train on certain parts of the infrastructure

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#5037]
### What happened?

A path is found but the train cannot be added.

### What did you expect to happen?

A new train is created and added to the study.

### How can we reproduce it (as minimally and precisely as possible)?

Create a project using "france locked" as infrastructure
Select 2X725003 (X-TER 2X(M+R+M) 354T- 8DIESELS DE 300KW) as a rolling stock
Departure: Invalides voie 2
Arrival: Invalide voies 1

![PfNotFound](https://github.com/osrd-project/osrd/assets/62556370/ff149962-6cd1-47df-99e8-9dbeb7828a11)

press "add one or several trains"

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 117.0.5938.63 
- **OS**: windows 11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

cdd21e97

**Comment by Castavo** [comment]
Editoast returns a 400 with message:
```json
{
  "type":"editoast:coreclient:Forward",
  "context":{
    "core_error":{"cause":null,"message":"TrackLocation isn't included in the path","trace":null,"type":"invalid_schedule"},
    "url":"http://dev-core-service.osrd-team-dev.svc.cluster.local:8000/standalone_simulation",
    "status":400},
  "message":"TrackLocation isn't included in the path"
}
```

**Comment by Castavo** [comment]
This feels related to #4246
