### ISSUE TITLE
editoast: delete openapi_legacy.yml and drop merging support

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#5057]
Part of #4580 

Once every endpoint is annotated using `#[utoipa::path]`, delete the old `openapi_legacy.yaml` and drop the OpenAPI merging feature in `views::openapi`.

Additionally:

- [ ] Maybe remove the trailing slash at the end of each endpoint (not OpenApi compliant) if unnecessary anymore
- [ ] Replace each `Path<(i64` by `Path<ThingIdParam` to improve readability
- [ ] Add OpenApi header information to `OpenApiRoot`

**Comment by clarani** [comment]
Closed by https://github.com/OpenRailAssociation/osrd/pull/7686
