### ISSUE TITLE
editoast: core 500 responses are forwarded as 400 responses

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5058]
### What happened?

`core` crashed, the response was a 400

### What did you expect to happen?

a 500 response

### How can we reproduce it (as minimally and precisely as possible)?

Make `core` crash and check the error code

### What operating system, browser and environment are you using?

- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

04b21aa27c6f5f27c976d43360f5027124b88860

**Comment by leovalais** [comment]
@eckter In #5118 we decided to forward core's status code to keep things simple for now.

However I'd argue that should core return a 502 (or any 5xx), editoast should return a 500 with core's status code in the error payload.  If for any reason, the status code of a core error changes from 5xx to 5yy, from editoast's perspective it's just a backend internal service that failed, so a 500.

Wdyt?

**Comment by eckter** [comment]
Reopening, the errors are forwarded as 400

**Comment by leovalais** [comment]
fixed by #5352
