### ISSUE TITLE
Front: Importation: no tracks on map

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#5067]
### What happened?

When using importation and choose manually the points on map before pathfinding, no tracks are displayed.

### What did you expect to happen?

Tracks should be displayed and clickable.

### How can we reproduce it (as minimally and precisely as possible)?

0. Go importation
1. Select O/D
2. Choose manually point on map

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Arch
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

bf64384f

**Comment by clarani** [comment]
Duplicated with #5295
