### ISSUE TITLE
front: adapt STDCM tree to refacto & isolate it from operational studies

### ISSUE THREAD

**Issue by Yohh** [OpenRailAssociation/osrd#5074]
### Description and goal

STDCM app must follow the new tree and routing ruled by the front refacto

it should be totally isolated from Operational Studies app

### Acceptance criteria

- [x] add STDCM folder in /modules, move STDCM components in it
- [x] move STDCM consts from /applications/operationalStudies/consts.ts to /applications/stdcm/consts.ts
- [x] set manageTrainSchedule i18n translation json out of operationnal studies folder

**Comment by celine-sncf** [comment]
part of #5022
