### ISSUE TITLE
front: rolling-stock-editor: when creating a new rolling-stock, it has by default an electrical mode ''

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#5077]
### What happened?

When creating a rolling stock, it has by default an electrical mode without any name

### What did you expect to happen?

It should not have any mode

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. Click on "Create a new Rolling Stock"
3. You can see in the effort curves tab the weird mode

![image](https://github.com/osrd-project/osrd/assets/45000526/702df9ee-0420-47a9-8a6b-9ba7215505fa)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

87022614

**Comment by Castavo** [comment]
I don't even have the "+" button under "Modes de traction"


![Image](https://github.com/osrd-project/osrd/assets/47494402/d50d11e8-55c1-4bc0-81f1-eece4cd53ea0)
