### ISSUE TITLE
Impossible to change traction mode in rolling stock editor

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5090]
### What happened?

I can't do anything with the box under `Modes de tractions` 
![image](https://github.com/osrd-project/osrd/assets/32448554/09014030-a03e-437c-a3aa-fcfe3a7a910c)

### What did you expect to happen?

Possibility to specify a traction mode

### How can we reproduce it (as minimally and precisely as possible)?

Try to create a new rolling stock and then you won't be able to add a traction mode

### What operating system, browser and environment are you using?

- mozilla

### OSRD version (top right corner `Account` button > `Informations`)

16870c41

**Comment by clarani** [comment]
This is a deployment issue

**Comment by Castavo** [comment]
So should it be closed ?

**Comment by bloussou** [comment]
Fixed
