### ISSUE TITLE
Can't save rolling stock after editing

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5107]
### What happened?

I can't confirm the edition of my rolling stock, clicking the button won't do anything, i can only cancel.

https://github.com/osrd-project/osrd/assets/86296016/ad16cf3a-cab8-4f6b-b677-1d50acc79676

### What did you expect to happen?

The button should work and save the rolling stock.

### How can we reproduce it (as minimally and precisely as possible)?

Try to reproduce the video.

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows 11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast 0c30c76f Core 0c30c76f Front 0c30c76f

**Comment by clarani** [comment]
Solved with https://github.com/osrd-project/osrd/pull/5098
