### ISSUE TITLE
Invalid train after changing rolling stock

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5117]
### What happened?

I want to compare two trains with the same itinerary but a different rolling stock. One rolling stock is the original, the other one is a duplicate, with no modification at all.
After saving the new train, it is immediately invalid :

https://github.com/osrd-project/osrd/assets/86296016/869335c0-358e-4846-b9c9-cc1d8ae0802b

### What did you expect to happen?

The new train should be valid.

### How can we reproduce it (as minimally and precisely as possible)?

You can reproduce what i'm doing in the video to see what's going on

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows 11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast ee04bf08 Core ee04bf08 Front ee04bf08

**Comment by axrolld** [comment]
Update :
It works fine when creating the duplicate from scratch, so only the train modification creates this bug.

**Comment by hamz2a** [comment]
The bug doesn't happen anymore, and it looks like it got fixed in the meantime.
