### ISSUE TITLE
front: "About" popup is not responsive

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5133]
### What happened?

On a company computer with the default resolution popup is not clean
![image](https://github.com/osrd-project/osrd/assets/32448554/b9d24f30-773c-43ef-99ae-bfd52cf47af4)

### How can we reproduce it (as minimally and precisely as possible)?

.

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109

### OSRD version (top right corner `Account` button > `Informations`)

in the image

**Comment by flomonster** [comment]
# How to fix this

We should adapt github CI to assign `git describe` to `OSRD_GIT_DESCRIBE` instead of the `sha`
