### ISSUE TITLE
front: timeline on a complex timetable is impossible to understand

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5134]
### What happened?

See : 
![image](https://github.com/osrd-project/osrd/assets/32448554/9ab226cf-10d1-4ebb-b587-0a702c7ea656)

### What did you expect to happen?

?

### How can we reproduce it (as minimally and precisely as possible)?

Create a complex timetable with train having different paths

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109

### OSRD version (top right corner `Account` button > `Informations`)

6a3c342c47949251321dd83f536045bfe670df5f

**Comment by nicolaswurtz** [comment]
Timeline is not supposed to be understandable but just to indicate the viewport of the GET, like a minimap.
I close the issue until UI refactoring if needed ;-)
