### ISSUE TITLE
front: allowances information stays in timetable details when removing all of them for a train

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#5140]
### What happened?

In a scenario, when we remove all allowances from a train, old allowances informations stay visble.

### What did you expect to happen?

Allowances details shouldn't be visible when no allowance exists.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Remove all allowances from a train
3. 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v117
- **OS**: Ubutntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dea017a1

**Comment by Akctarus** [comment]
Fixed and closed by #5609
