### ISSUE TITLE
front: an older pathfinding request may override the newest result

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#515]
If we move both the origin and destination points, both moves trigger a pathfinding request. If the first one takes longer to compute, we end up with the correct path first, instantly overwritten by the (new origin -> old destination) path

**Comment by axrolld** [comment]
I just tried to reproduce this bug and it is indeed still not working properly. The Pathfinding goes so fast that is actually hard to reproduce but still, it's an unwanted behavior.

**Comment by axrolld** [comment]
But actually i'm not sure this will be a problem anymore as the pathfinding module now prevents the user from asking for multiple pathfindings in a row. @anisometropie can you attest this ?

**Comment by flomonster** [comment]
Fixed with https://github.com/DGEXSolutions/osrd/pull/2854
