### ISSUE TITLE
front : be able to enter the base power class of an RS in "general characteristics"

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#5175]
## Description

When editing/creating a rolling stock, user need to be able to set a default power class which will be associated with the "Non Specified" power restriction code. 
The user needs also to see the default power class when selecting a rolling stock.

## AC

- [ ] A new field should be displayed next to "gauge" when looking at a rolling stock details
- [ ] A new field should be added under the "gauge" field in the general characteristics tab
- [ ] The field should be called "Power Class" / "Classe de puissance" 
- [ ] The field should be a string and not required

**Comment by Math-R** [comment]
Just added an acceptance criteria, and change the field from text to number

**Comment by SharglutDev** [comment]
Changed it back after discussion with PO's
