### ISSUE TITLE
Track names are different on editors map vs scenario map

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5184]
### What happened?

Scenario:
![MicrosoftTeams-image (5)](https://github.com/osrd-project/osrd/assets/32448554/a3c7305e-0b1c-4a4a-9dcd-6d736be41dbf)

Editor:

![MicrosoftTeams-image (6)](https://github.com/osrd-project/osrd/assets/32448554/8e255edc-f03e-49ee-aa8a-8ed6f70f332e)

### What did you expect to happen?

Should be the same with full track names.

### How can we reproduce it (as minimally and precisely as possible)?

.

### What operating system, browser and environment are you using?

.

### OSRD version (top right corner `Account` button > `Informations`)

6fc6ddb1

**Comment by nicolaswurtz** [comment]
I think the problem is a bit different : we used to display only line name when track name was not present OR invalid (too long).
It has been corrected back side, so we can today display all information on map. I'll take care myself about this, thx for reporting !
