### ISSUE TITLE
Fix CORS and session storage

### ISSUE THREAD

**Issue by Khoyo** [OpenRailAssociation/osrd#5211]
### Description and goal

Currently, we have to use CORS headers to allow passing cookies around from javascript.
This is insecure, as authentication secrets are accessible from javascript and stored in local storage. As the front-end is large and vulnerable, it's best to keep authentication secrets out of its realm.

There are two improvements we can go for:
 - use http only secure cookies
 - move the front-end and back-end into the same origin (protocol + domain + port)

These two improvements are best implemented together: unless the front-end and back-end are on the same origin, [`credentials=include` has to be passed to fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included).

These changes should allow for tightening the CORS policy enough to satisfy accepted security standards.

### Acceptance criteria

- [x] We can specify editoast alllowed origins #5276
- [ ] Use http-only secure cookies
- [ ] Tighten CORS policy to a bare minimum
- https://github.com/osrd-project/osrd/issues/5339

**Comment by bloussou** [comment]
No need with the new gateway deployment
