### ISSUE TITLE
Error undefined when mareco allowance is defined in the interval interface

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5223]
## Reproduction step

Create a train with 60% of mareco margin. If the margin is entered in the bar to define different values for different intervals this error is displayed :  

![Image](https://github.com/osrd-project/osrd/assets/32448554/f2c6d76d-ea09-4a12-8778-9e61da94153c)

When the same margin is entered in the first line (not in the different intervals bar) the train is correctly added. 

![Image](https://github.com/osrd-project/osrd/assets/55697979/0699f50a-7270-4917-8562-295a95718e87)

Error message:
```json
{"type":"editoast:coreclient:Forward","context":{"status":400,"core_error":{"cause":null,"message":"We could not go slow enough in this setting to match the given allowance time","trace":null,"type":"allowance_convergence"},"url":"http://"},"message":"We could not go slow enough in this setting to match the given allowance time"}
```

Version `cb78a63b`

**Comment by bloussou** [comment]
Still broken, make this interval editor not very friendly

**Comment by bloussou** [comment]
Must use path length given by the backend and not recompute the length in the frontend

**Comment by bloussou** [comment]
Default must be displayed in the allowances viewer, otherwise the user think that the value entered in the first input field is not taken into account

**Comment by alexandredamiron** [comment]
New Diagnostic:
- [x] Do not use front distance computation but the new one returned bu pathfinding
- [x] Margin by default, if set, is not represented (but the component can do that)
- [x] The end value in the output is probably rounded to sup, so it overlaps possible range and the partial range newly created is not valid causing the error
- [x] Interface: you can create partial interval in ascendent order (0>10, then 15->25, etc...) but you cant start by the end
- [ ] Red rounding is for conflicts: ok but not clear
- [x] length updates often wrong
