### ISSUE TITLE
Create 10 trains without margin and modify one to add margin add mareco margin to all train on the SpaceTimeChart

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5225]
Step to reproduce:

1. Create multiple trains without margin
2. Modify one train to add some mareco margin
3. Then check the display on the space time chart, all trains have mareco margin displayed even if they are not supposed to have margin setup...

Only the highlighted train is supposed to have mareco margin setup:
![Image](https://github.com/osrd-project/osrd/assets/32448554/8a8a7a31-2de5-4193-9feb-c06c72aff3fe)

version: `cb78a63b`

**Comment by bgiuliana** [comment]
fixed in version e32e129131ada79b92704fc7ca6bf137888e8489
