### ISSUE TITLE
editoast: core errors are forwarded with very little context

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5244]
### What happened?

Core errors don't include the context when forwarded from editoast. 

For example, core may send a response such as: 

```json
{
    "context": {
        "stack_trace": [
            "STDCMStandardAllowance.java:60",
            "STDCMPostProcessing.java:48",
            "STDCMPathfinding.java:79",
            "STDCMEndpoint.java:95",
            "FkRegex.java:153",
            "FkRegex.java:217",
            "FkChain.java:72",
            "TkFork.java:98",
            "TkFallback.java:84",
            "TkFallback.java:66",
            "TkWrap.java:58",
            "TkSlf4j.java:110",
            "BkBasic.java:123",
            "BkBasic.java:99",
            "BkSafe.java:46",
            "BkWrap.java:51",
            "BkParallel.java:81",
            "ThreadPoolExecutor.java:1136",
            "ThreadPoolExecutor.java:635",
            "Thread.java:833"
        ],
        "message": "conflict offset is already on a range transition"
    },
    "message": "assert check failed",
    "type": "assert_error"
}
```

editoast will send a response looking like this: 

```json
{
    "type": "editoast:coreclient:Forward",
    "context": {
        "status": 500,
        "core_error": {
            "cause": null,
            "message": "assert check failed",
            "trace": null,
            "type": "assert_error"
        },
        "url": "http://localhost:8080/stdcm"
    },
    "message": "assert check failed"
}
```

The actual message of the assertion error is lost.

### What did you expect to happen?

More context to be included, at least the actual assert error

### How can we reproduce it (as minimally and precisely as possible)?

The simplest way to reproduce would be to edit core to add an `assert false : "foobar";` line somewhere, and look for `foorbar` in the response from editoast

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: ubuntu
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

12f29b0f150197c6eff3aa9679095b1f1b83ba55

**Comment by leovalais** [comment]
This happens because when receiving an error, editoast only tries to deserialize the error using the old core error format. To fix this, in `core/mod.rs`, just before trying to deserialize the error as a `CoreErrorPayload`, editoast should try to deserialize it using `InternalError`.

**Comment by eckter** [comment]
Reopening, the context isn't included anymore
