### ISSUE TITLE
Front - Refacto E2E tests : operationnal studies, stdcm page, pathfinding

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5245]
# Description

Refactor operationnal studies, stdcm page, pathfinding e2e tests according to what's been defined in #5022

# Goal

- [ ] add apiContext in each test to make them parallelisable
- [ ] add missing tests fore each user action

# Acceptance criteria

The following e2e have been refectored :
- [ ] operationnal studies
- [ ] stdcm page
- [ ] pathfinding

**Comment by Yohh** [comment]
done in other refacto issues
