### ISSUE TITLE
Update the dependencies of the front regarding CI warnings

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#527]
Currently, the dependencies of the javascript front-end are very out of date, to the point where updating is a week long effort.
I've tried and failed (no surprise here, I don't even write javascript).

Here is what I know:

 - a bunch of dependencies have conflicting requirements, in part due to unmaintained dependencies
 - the SNCF front-end stuff module is pretty out of date

**Comment by alexandredamiron** [comment]
Objective: no warning on github CI
No diminution of requirements (typescript)

**Comment by alexandredamiron** [comment]
#41 56.95 warning " > @nivo/circle-packing@0.61.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning " > @nivo/circle-packing@0.61.0" has incorrect peer dependency "react@>= 16.8.4 < 17.0.0".
#41 56.95 warning "@nivo/circle-packing > @nivo/colors@0.61.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning "@nivo/circle-packing > @nivo/colors@0.61.0" has incorrect peer dependency "react@>= 16.8.4 < 17.0.0".
#41 56.95 warning "@nivo/circle-packing > @nivo/core@0.61.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning "@nivo/circle-packing > @nivo/core@0.61.0" has incorrect peer dependency "react@>= 16.8.4 < 17.0.0".
#41 56.95 warning "@nivo/circle-packing > @nivo/tooltip@0.61.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning "@nivo/circle-packing > react-motion@0.5.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
#41 56.95 warning "@nivo/circle-packing > recompose@0.30.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
#41 56.95 warning " > @nivo/line@0.61.1" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning " > @nivo/line@0.61.1" has incorrect peer dependency "react@>= 16.8.4 < 17.0.0".
#41 56.95 warning "@nivo/line > @nivo/annotations@0.61.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning "@nivo/line > @nivo/annotations@0.61.0" has incorrect peer dependency "react@>= 16.8.4 < 17.0.0".
#41 56.95 warning "@nivo/line > @nivo/axes@0.61.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning "@nivo/line > @nivo/axes@0.61.0" has incorrect peer dependency "react@>= 16.8.4 < 17.0.0".
#41 56.95 warning "@nivo/line > @nivo/legends@0.61.1" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning "@nivo/line > @nivo/legends@0.61.1" has incorrect peer dependency "react@>= 16.8.4 < 17.0.0".
#41 56.95 warning "@nivo/line > @nivo/scales@0.61.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning "@nivo/line > @nivo/voronoi@0.61.0" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
#41 56.95 warning "@nivo/line > @nivo/voronoi@0.61.0" has incorrect peer dependency "react@>= 16.8.4 < 17.0.0".
#41 56.96 warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
#41 56.96 warning "deck.gl > @deck.gl/carto@8.4.16" has unmet peer dependency "@loaders.gl/core@^2.3.0".
#41 56.96 warning "deck.gl > @deck.gl/extensions@8.4.16" has unmet peer dependency "gl-matrix@^3.0.0".
#41 56.96 warning "deck.gl > @deck.gl/geo-layers@8.4.16" has unmet peer dependency "@loaders.gl/core@^2.3.0".
#41 56.96 warning "deck.gl > @deck.gl/layers@8.4.16" has unmet peer dependency "@loaders.gl/core@^2.3.0".
#41 56.96 warning "deck.gl > @deck.gl/mesh-layers > @luma.gl/experimental@8.4.5" has unmet peer dependency "@loaders.gl/images@^2.3.0".
#41 56.96 warning "deck.gl > @deck.gl/mesh-layers > @luma.gl/experimental@8.4.5" has unmet peer dependency "@luma.gl/engine@^8.4.0".
#41 56.96 warning "deck.gl > @deck.gl/mesh-layers > @luma.gl/experimental@8.4.5" has unmet peer dependency "@luma.gl/gltools@^8.4.0".
#41 56.96 warning "deck.gl > @deck.gl/mesh-layers > @luma.gl/experimental@8.4.5" has unmet peer dependency "@luma.gl/webgl@^8.4.0".
#41 56.96 warning " > drei@2.2.21" has unmet peer dependency "react-three-fiber@>=5.0".
#41 56.96 warning "drei > troika-three-text > troika-three-utils@0.34.0" has incorrect peer dependency "three@0.103.x - 0.121.x".
#41 56.96 warning " > react-dom@16.14.0" has incorrect peer dependency "react@^16.14.0".
#41 56.96 warning " > react-map-gl-draw@0.17.7" has incorrect peer dependency "react@^16.x".
#41 56.99 warning " > better-docs@1.4.13" has incorrect peer dependency "react@^16.0.0".
#41 56.99 warning " > better-docs@1.4.13" has incorrect peer dependency "typescript@^3.6.4".
#41 56.99 warning "better-docs > react-ace@6.6.0" has incorrect peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.1 || ^16.0.0".
#41 56.99 warning "better-docs > react-frame-component@4.1.3" has unmet peer dependency "prop-types@^15.5.9".
#41 57.00 warning " > eslint-plugin-react-hooks@1.7.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
#41 57.00 warning " > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".

**Comment by multun** [comment]
Dependencies aren't yet up to date

**Comment by axrolld** [comment]
This isse had been re-written and seperated in two issues, enabling to close this one.
