### ISSUE TITLE
front: LPV are displayed without color

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#5287]
![Image](https://github.com/osrd-project/osrd/assets/45000526/edd034d0-49e6-4d07-990f-4414d2f8ebae)

**Comment by nicolaswurtz** [comment]
Sorry to re-open issue, but the colors are always missing when selecting any composition code
![image](https://github.com/osrd-project/osrd/assets/6003856/9a04964e-6396-495d-854f-03e837eae75f)
