### ISSUE TITLE
Tracks are not display on the map for timetable import

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#5295]
### What happened?

![image](https://github.com/osrd-project/osrd/assets/55697888/f4ad37ab-e38a-4283-b9d6-12ac977b5643)

### What did you expect to happen?

I need to see the trarck to choose the starting or ending point

### How can we reproduce it (as minimally and precisely as possible)?

Go to the main page in the operation studies.
Try to import trains like Dijon Lyon
click on Start the import
click on Complete the coodonnates
See th map without track

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 117.0.5938.149
- **OS**: Windows 10
- **Env**: osrd.dev.dgexsol.fr

### OSRD version (top right corner `Account` button > `Informations`)

e32e1291

**Comment by flomonster** [comment]
The call to `[...]/editoast/layers/layer/track_sections/mvt/geo/?infra=X` doesn't contain the token in it's header.
