### ISSUE TITLE
Different modals and different ux for map layers modals

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5306]
### What happened?

In the infrastructure editor you must validate once radio button are activated
![image](https://github.com/osrd-project/osrd/assets/32448554/6217d44f-5c1b-47bf-ad35-921fcea48b3c)
it is not the case on the map
![image](https://github.com/osrd-project/osrd/assets/32448554/f2dd932c-6445-4f9d-bba0-4838e307e4fd)

### What did you expect to happen?

Not to have to validate the choices, it is redundant and not user friendly

### How can we reproduce it (as minimally and precisely as possible)?

.

### What operating system, browser and environment are you using?

firefox

### OSRD version (top right corner `Account` button > `Informations`)

e32e129131ada79b92704fc7ca6bf137888e8489

**Comment by Castavo** [comment]
Is it not more a feature change than a bug ?

**Comment by axrolld** [comment]
I'm considering this as an enhancement, but i think we should fix this before v1

**Comment by flomonster** [comment]
The modals are still different. Even if the content is closer, isn't it possible to use the same modal?

**Comment by flomonster** [comment]
Since it requires a huge code refactoring we won't consider this as a small bug fix.
