### ISSUE TITLE
Double click is necessary to enter value in rolling stock editor

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5307]
## Description

When typing a value for the speed/effort curve it is nessecary to double click before entering a numeric value :

![Image](https://github.com/osrd-project/osrd/assets/32448554/395dea38-369b-45d6-a364-5d10c8b5e354)

## Expected

just one click should be enough

**Note: This is only on firefox**
Version: `e32e129131ada79b92704fc7ca6bf137888e8489`

**Comment by bgiuliana** [comment]
fixed in version 358b34a7

**Comment by bloussou** [comment]
Not fixed, reopening

**Comment by clarani** [comment]
Fixed by the new library introduced by https://github.com/osrd-project/osrd/pull/6788 :tada:
