### ISSUE TITLE
GET: in some cases, train is _à côté de la plaque_

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#531]
**Describe the bug**
Train trace in GET may be outside blocks

**To Reproduce**
Behaviour seen with Brest<>Rennes path

![image](https://user-images.githubusercontent.com/6003856/152380815-5ef66e85-df7a-4b94-a077-38689178e523.png)
![image](https://user-images.githubusercontent.com/6003856/152380914-2d6b5da0-5986-4fa6-9c5c-7b3132d760be.png)

**Comment by multun** [comment]
@nicolaswurtz I think I might have just fixed the issue, can you try to rebase? This occurs on #481 right?

**Comment by flomonster** [comment]
I can't reproduce the bug either.

**Comment by multun** [comment]
I assume it got fixed, we can reopen this issue if it comes back
