### ISSUE TITLE
"About" modal window is not responsive

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5310]
### What happened?

![image](https://github.com/osrd-project/osrd/assets/86296016/2a2e81c7-62f0-48bf-ab7d-df181ce8a1f2)

### What did you expect to happen?

It should be responsive.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to `About` window

### What operating system, browser and environment are you using?

Browser: Chrome
OS: Windows 11
Env: staging (internal)

### OSRD version (top right corner `Account` button > `Informations`)

e32e129131ada79b92704fc7ca6bf137888e8489

**Comment by celine-sncf** [comment]
Duplicate of #5133

**Comment by axrolld** [comment]
My bad !
