### ISSUE TITLE
Zoom in zoom out animation is not efficient

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5311]
Since commit `13035f7ffda63f3b2db7a479624d12700f302859` there is an animation that is not very efficient and some people like and other don't... 
I don't find it usefull, it should be disabled by default at least. We can choose what should be done with @thibautsailly advices.

**Comment by flomonster** [comment]
Fixed by https://github.com/osrd-project/osrd/pull/5812
