### ISSUE TITLE
initial position for the interval is proposed at the end of the interval

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5312]
When we define an interval corresponding to the whole path, a new begin position for a new interval is proposed at the end of the interval. This position will be out of the path.

![Image](https://github.com/osrd-project/osrd/assets/55697979/4fcf08ee-158e-4590-a12d-cef8bb8615f3)

**Comment by clarani** [comment]
Fixed by https://github.com/osrd-project/osrd/pull/5643
