### ISSUE TITLE
front: timetable deceleration is positive when creating a rolling stock but displayed as negative in rolling stock details

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5314]
Postive:

![Image](https://github.com/osrd-project/osrd/assets/32448554/59925454-2bb2-4794-b02b-361dedc5ccba)

Negative:

![Image](https://github.com/osrd-project/osrd/assets/32448554/e1d06063-7c23-4655-a86e-d10eaa95e1e8)

Expected behavior:
Enter a negative value.

Version: `e32e129131ada79b92704fc7ca6bf137888e8489`

**Comment by axrolld** [comment]
We get our rolling stock data with a positive value. It makes sense because rolling stocks have a "positive deceleration", which in the end is a "negative acceleration".

In order to stick to our data source i would keep in positive and display it as positive if that's ok with you @bloussou ?

**Comment by nicolaswurtz** [comment]
So the correction to appy is: put "Timetable deceleration" as a positive value in the rolling stock card, right?
