### ISSUE TITLE
front: train length incorrectly displayed in the space time diagram

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#5327]
### What happened?

Head line and tail line start at the same point as if the train length start form 0 to train length. 
<img width="562" alt="image" src="https://github.com/osrd-project/osrd/assets/55697888/32dbde44-a594-4bd4-bcda-8954c1a226ea">

### What did you expect to happen?

Head line and tail line have to start at the Y axis separated by the train length

### How can we reproduce it (as minimally and precisely as possible)?

Create a train and zoom on the space time diagram

Head line and tail line have to start at the Y axis separated by the train length

### Analysis (Clara)
This bug is not a frontend one but a core one since the data returned by core is incorrect: the tail position is at 0 at the beginning of the simulation, just as the head position. This should be fixed in the backend.
![Image](https://github.com/osrd-project/osrd/assets/45000526/130772a5-e0e2-42db-b0a9-edfc9582221f)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

1bd551d79b60fddc57aec879899e9394b82e6e59

**Comment by axrolld** [comment]
We don't display the train length anymore
