### ISSUE TITLE
front: typos in infra-editor

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#5335]
### What happened?

Outil "aiguillage" : 
![image](https://github.com/osrd-project/osrd/assets/115472753/3a684163-80c8-44c0-9bd3-4f6452561f74)

Outil "vitesse limite et électrification" :  
![image](https://github.com/osrd-project/osrd/assets/115472753/aabad2b2-aa73-43b6-a45c-0f6ca46f4c8e)

### How can we reproduce it (as minimally and precisely as possible)?

1. go to infra editor
2. go to "aiguillage" tool
3. look at the bottom of the map
4. go to "vitesse limite" or "électrification" tool
5. look at the left panel

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102
- **OS**: win10
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

087973a0

**Comment by axrolld** [comment]
🧑‍🏫
