### ISSUE TITLE
Handle non-sorted rolling stock effort curves

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#5345]
### Who would benefit from this feature?

Both

### What is this feature about?

Today if we create a rolling stock with curves which have non-monotonic speeds (like [(0, 100), (100, 80), (50, 90)]) editoast does not give a 400, and core will give a 500 when used.

We may want to either prevent/correct the creation of such rolling stock or fail gracefully in core with a 400.

### Why is this feature valuable?

This feature matters because it:
- Would prevent bug reports which are just wrong user input that the user can't know

**Comment by bgiuliana** [comment]
Fixed in other issue
