### ISSUE TITLE
Infra editor: better handling of infra errors

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#5348]
## BH

Improve the user experience for the infrastructure editor. 
Help the user to identify and fix infrastructure errors and warnings. The errors make the infrastructure invalide. This happens when it lacks the infos needed to perform running time calculation. 

## AC

- [x] The error messages should be clear for the users 
- [x] The error types should be clear for the users

### List of errors and warnings

1. W: Duplication de groupe a changer avec « Duplication configuration d’aiguille » 
Le type d’aiguille « bla bla » contienne un doublon de la configuration « bla bla » (Pour l’instant on ne peut pas le corriger dans l’éditeur)

2. W: Objet vide (Catenaires, speed section, operational point)
L’objet « bla bla » a le champ « bla bla » vide

3. E: Position d’aiguille invalide 
L'itineraire « bla bla » a l’aiguille « bla bla » qui a la configuration « bla bla » qui n’existe pas 

4. E: Reference invalide 
L’object « bla bla » référence l’objet « bla bla » qui n’existe pas 

5. E: Itinéraire invalide
La route « bla bla » est invalide, le chemin demandé entre-le détecteur/heurtoir « bla bla » et le détecteur/heurtoir « bla bla » n’est pas consistant (voir ce qui est faisable dans le code)

6. E: Port d’aiguille invalide a changer avec « Branche d’aiguille ou de nœud invalide » 
L’aiguille/le nœud « bla bla » présente une branche qui n’est pas compatible avec son type d’aiguille/nœud (qui n’existe pas dans son type d’aiguille/nœud)

7. W: Route manquante a changer avec « itinéraire manquant » 
La voie « bla bla » n’a aucun itinéraire associé 

8. W: Buffer stop manquant a changer avec « heurtoir manquant »
extrémité d’une voie sans heurtoir 

9. E: Objet en dehors de l’itinéraire 
L’aiguille/le nœud ou le détecteur « bla bla » de l’itineraire « bla bla » n’est pas contenu/contenue dans le chemin correspondant 

10. W: Position d’heurtoir étrange 
Le hertoir « bla bla » se trouve dans une position étrange 

11. E: Valeur invalide  
L’objet “ bla bla” a un champ avec une valeur invalide (out of range)

12. W: Superposition de limite de vitesse 
La limite « bla bla » se superpose à la limite « bla bla » 

13. E: Superposition d’aiguilles/nœuds
L’aiguille/le noeud « bla bla » et l’aiguille/le noeud « bla bla » connectent les mêmes extrémités de voies 

14. E: Nome de port inconnu à changer avec « nome de branche inconnu »
Le type d’aiguille/de nœud « bla bla » présente la brache "bla bla " qui n’existe pas 

15. W: Port non utilisé à changer avec « branche non utilisée »
La branche « bla bla » déclarée dans le type d’aiguille/nœud « bla bla » n’est pas utilisée dans les configurations de ce type 

16. W: Superposition de catenaires
La catenaire « bla bla » se superpose à la catenaire « bla bla » 

### List/Filter the errors 

- [x] The user can filter the errors by types 
- [ ] The user can search the errors in the list  (research bar) 
- [x] When the user select the error in the list, the object linked with the error is displayed in the map
- [x] The arrow brings directly to the object (just one click)
- [x] Change the filter (`All`, `Errors`, `Warnings`) with an option  (Voir doc [ICI](https://designmetier-bootstrap.sncf.fr/docs/4.3/components/checkboxes-and-radios/#options))
- [x] The list of the types schould be adapted with the filter `Errors|Warnings`

![Image](https://user-images.githubusercontent.com/15349030/268288607-86e10a48-3231-46e9-89fc-3b22dab57c00.png)

### Display the errors in to the map 

- [x] The user can distinguish between errors and warnings 
- [x] Display in a different way point and linear objects
- [x] The errors/warnings displayed in the map should be adapted with the filter selected by the user
- [ ] 
Note: Le layer is already availaible (as well as the button to activate the layer)

![Image](https://user-images.githubusercontent.com/15349030/268283834-00c886ea-2d17-4804-8fc5-3cb1c6e4a36f.png)

### Number of errors in the map/ error field 

- [x] The number of errors and warning is displayed in the map to know that the infrastructure contains errors while editing it
- [ ] The fiels affected by the error is indicated in the edit mode of the concerned object 

![Image](https://user-images.githubusercontent.com/15349030/268290072-d51e632c-4978-437d-a576-7b406fa68b56.png)

###
![Image](https://github.com/osrd-project/osrd/assets/55697979/a03d68a0-7277-4991-b20f-20ba0647f54b)

- [x] The title of erreur list should be replaced by "liste des problemes"
- [x] In the first line, "niveau d'erreurs" should be replaced by "niveau"
- [ ]  In the second line, "type d'erreurs" should be replaced by "type"
- [x] The sentence "N erreurs trouvés" should be replaced by "N problèmes trouvés"

## Sketches 

**Note**: These pictures are here to better understand. Not to be copied in detail.

### Back
-> Done, geometrical infos and object names are correctly sent 
- If research bar, pay attention to this  bug: https://github.com/osrd-project/osrd/issues/5089

### Front

- Arrow icone to go directly to the map
- Open the pannel edition of the object with info about the error
- Display the help info on the map 
- Change the button to filter with a switch for  All/Error/Warnings
- Should we display pages in the front or continue with the infinity scroll (hard to search currently)

**Comment by sim51** [comment]
I found some tiny issues (that I fixed) while developing this feature : 

* The infraID used when saving an object was the one for the simulation, not the one of the map 
* The interval dataviz component did too many renders
* Lost focus while editing a switch
* When relief is disabled (set to zero), the infra was possibly under buildings (see Montparnasse for example).

**Comment by thibautsailly** [comment]
The term error is used twice:
```
Errors
|- errors
|- warnings 
```

To avoid communication issues and improve interface clarity, we should use another term for one or the other. I'm not familiar enough with the subject, but could one of these work?
```
Errors
|- major
|- minor

Issues
|- errors
|- warnings
```

**Comment by sim51** [comment]
Following our discussion with @Tguisnet & @bgiuliana it's important to keep the wording  "error" & "warning" for the type, so I renamed all the "error" wording by "issue" like your purpose @thibautsailly (and "anomalie" in french).

**Comment by sim51** [comment]
A review of error message with what I can/can't do : 

* **5 - invalid_route** : I don't have access to the start/end point, so message is the following : `La route « {{object_id}} » est invalide, le chemin demandé n’est pas consistant`
* **8- heurtoir manquant** : I can add the extremity => `"L'extrémité « {{endpoint}} » de la voie « {{object_id}} » n'a pas de heurtoir"`
* **11- out_of_range** : I have the `position` and the `expected range` in the error which are not used in the message
* **14 - unknown_port_name** : I don't have the configuration of the switch, just its id and the name of the port which is not known. So I changed by `L’aiguille/le noeud « {{object_id}} » présente la branche « {{port_name}} » qui n’est pas existante`

**Comment by sim51** [comment]
FYI, on routes I have no geographical information, so I can't focus the map on it ...
Moreover, a Route is only displayed when you edit it (not in selection mode).

**Comment by Tguisnet** [comment]
Done (need research bar to search in the error list, another issue is created)
