### ISSUE TITLE
Drag & drop a train in the space-time chart causes it to accelerate

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5360]
### What happened?

I was building a scenario for STDCM and when moving the train in the space-time chart with drag & drop the train appears to accelerate a lot (at least visually in the chart)

https://github.com/osrd-project/osrd/assets/86296016/1e558c9c-f2e3-4202-a6e3-345378115f21

### What did you expect to happen?

The train should keep the same pace.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to my scenario and try to reproduce the video

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

74e4c511

**Comment by flomonster** [comment]
Should be fixed by: https://github.com/osrd-project/osrd/pull/5609
