### ISSUE TITLE
Hyphen required in open-data import module

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5366]
### What happened?

Looking for Paris Montparnasse train station, the result doesn't show up without the hypen :

![image](https://github.com/osrd-project/osrd/assets/86296016/fe202044-507e-428b-90d3-27a812d66ebe)

But with the hyphen it works (though the green background component is too big for only one result).

![image](https://github.com/osrd-project/osrd/assets/86296016/ca4407b2-feda-4117-90e8-9fa7c048edd2)

### What did you expect to happen?

As a user i'm expecting to find the result with a space and not an hyphen.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the open data import module

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

a6b9322e

**Comment by Uriel-Sautron** [comment]
Import module call graou api for data.
Bug close with agreement of @axrolld @nicolaswurtz
