### ISSUE TITLE
Editor: Create new Electrification

### ISSUE THREAD

**Issue by sim51** [OpenRailAssociation/osrd#5371]
It is possible to create an electrification without selecting track sections.
=> Should it be possible ? 

There is no help/hint on the panel that tells you how to add track sections.  You have to hover a tracksection and read the popin to know how to add it.
=> Should we display a placeholder when there is no data that says to the user how to add a track (or perhaps in the hint bar at the bottom) ?

**Comment by bgiuliana** [comment]
I think it is ok to allow saving the new electrification even if any track section range is linked. The same behavior is permitted for speed sections. However, it is a good idea to add a message to help the user to know that it should add some track section ranges. 

![Image](https://github.com/osrd-project/osrd/assets/55697979/6cf456e3-ac04-401f-a300-a328c765b640)

In addition, the creation of an empty electrification will create a warning as in the case of an empty speed section. Schould we put a message to notify this to the user for electrification too?
