### ISSUE TITLE
editoast: stdcm: thread panick, "train schedule should have a path"

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5398]
### What happened?

```
osrd-editoast  | thread 'actix-rt|system:0|arbiter:8' panicked at src/views/train_schedule/simulation_report.rs:69:10:
osrd-editoast  | Train Schedule should have a path
```

### How can we reproduce it (as minimally and precisely as possible)?

Reproduced in a regression test in this branch: https://github.com/osrd-project/osrd/pull/5397. It appears that the test passes in the CI despite failing consistently on my PC. 

Edit: after further investigations, it seems to be reproducible when editoast is run in a docker container, not when run natively. This makes it harder to debug on top of making it quite unlikely to cause problems in actual use cases. Tagging minor and I won't investigate further for now. 

### What operating system, browser and environment are you using?

- **OS**: ubuntu
- **Env**: Local, editoast in docker

### OSRD version (top right corner `Account` button > `Informations`)

4931c4b585b838949a378c88db5cccfa098641ff

**Comment by celine-sncf** [comment]
can't reproduce

**Comment by eckter** [comment]
I can still reproduce with the regression test on [that branch](https://github.com/osrd-project/osrd/pull/5397).

But it doesn't happen in every environment. I can't reproduce when editoast isn't in a container, and it's not reproduced on the CI.
