### ISSUE TITLE
Editing an imported train doesn't work

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#5401]
### What happened?

When we import a train from open data and try to modify the train, we have a `400` error (not shown to the user).

## What is happening

When we import trains we provide a field name `scheduled_points`. This feature is not supported yet by the front (we should be able to visualize and modify them.

## Hotfix

I suggest that when editing a train we force this field to be an empty list `[]` so we can still simulate the train.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Import some trains
3. Edit a train changing its path
4. When clicking on `Edit` nothing happens (check your browser debugger, we received a 400)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Staging & Local 

### OSRD version (top right corner `Account` button > `Informations`)

358b34a7

**Comment by nicolaswurtz** [comment]
Not be able to reproduce as today (I think it has already be corrected). Thx anyway!
