### ISSUE TITLE
front: ux: project creation modal (scenario or study) closes immediately when clicked next to

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#5404]
### What happened?

The project creation modal (scenario or study) closes immediately when clicked beside.

### What did you expect to happen?

The project creation modal (scenario or study) does not close.

### How can we reproduce it (as minimally and precisely as possible)?

Open a project creation modal
Click next to the modal

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 117.0.5938.150
- **OS**: windows 10
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

358b34a7

**Comment by loic-hamelin** [comment]
Check with UX if closing the modal when we click beside is not the expected behaviour

**Comment by flomonster** [comment]
We could do the same as the rolling stock editor (a pop-up appears asking if we can close the form).
Nice to have: We could only display this pop-up when the user has filled in a few fields.

**Comment by nicolaswurtz** [comment]
Simple way: implement flag to prevent outside click from closing modal
Complex way: save state of closed modal, if user reopened it, it should display the field as the were left — including after close & open browser
