### ISSUE TITLE
Electrical profile O is not put in the right order

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5412]
When we enter the profile O, this is put in the end of the list.

![Image](https://github.com/osrd-project/osrd/assets/55697979/ab6106fe-6b43-4f31-a87a-f5bd133ef2c5)

It should be before the A profile.

version 358b34a7

**Comment by axrolld** [comment]
The profiles appear in the right order for me, except when i delete O profile and re-create it.

**Comment by flomonster** [comment]
This is more than just a display bug. The RS editor doesn't enforce curve order given an electrical profile. It can lead to an unwanted behavior.
