### ISSUE TITLE
front: the effort speed curve displayed in the description of the RS is not the default curve

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5414]
1. When modifing a RS, in the case where no power restriction are defined
2. We delete an electrical profil
3. We add the same electrical profile (in the exemple G)

![Image](https://github.com/osrd-project/osrd/assets/55697979/37b18092-1d25-459e-a094-33bf56a0b880)

4. The curve effort-speed displayed in the page of the modified RS is the new one (the curve for the profile G
in the exemple) 

![Image](https://github.com/osrd-project/osrd/assets/55697979/dce9edbb-0848-4259-8365-2b4e65db680c)

The curve displayed should be the default curve

version 358b34a7

**Comment by axrolld** [comment]
This is postponed because this bug rarely appears and a clean fix would take too much time for now.

**Comment by SharglutDev** [comment]
Seems to be fixed. @bgiuliana can you check again please ?
