### ISSUE TITLE
The buffer stops layer is not displayed

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5422]
When we activate the buffer stop layer into the map, no buffer stop is displayed.

![Image](https://github.com/osrd-project/osrd/assets/55697979/be0d3756-f4d2-4517-9f03-8683ce460273)

version dev cffaa088

**Comment by flomonster** [comment]
It is a front-side error. Requests work and the response isn't empty.

Note: The signal layer doesn't work as well this is a deployment error. Once fixed it might also fix the error on the buffer stops.

**Comment by axrolld** [comment]
Is this bug fixed now ? It looks like it to me

**Comment by nicolaswurtz** [comment]
Fixed by #5472 ;-)
