### ISSUE TITLE
Making editoast tests independent

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#5441]
### Description and goal

This task is about rewriting tests that aren't independent:

- Use unique ids for objects.
- Avoid checks that count items (check membership or subset instead)
- ...

Note: If we find tests that can't be adapted, an alternative is to create a database for each test.

### Acceptance criteria

- Parallel execution of tests
- Shorter execution time

**Comment by shenriotpro** [comment]
Ideally the tests should not rely on the state of the DB and should clean up (e.g. running twice in a row shouldn't be an issue).

**Comment by shenriotpro** [comment]
I expect a 2x speedup (90s -> 45s on my computer).

**Comment by shenriotpro** [comment]
This is likely needed to avoid duplicate pathfinding on electrical profiles test https://github.com/osrd-project/osrd/pull/5033

**Comment by shenriotpro** [comment]
AFAIK the remaining issue is with `simple_pathfinding`.

**Comment by shenriotpro** [comment]
check https://docs.rs/crate/serial_test/latest with Jean

**Comment by flomonster** [comment]
Duplicate of https://github.com/osrd-project/osrd/issues/5886
