### ISSUE TITLE
multiple infra api calls

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#5444]
### What happened?

When going in a scenario with at least one train in it, some endpoints are called very frequently and endlessly.

![image](https://github.com/osrd-project/osrd/assets/113104137/c3b25599-b9ca-4de5-b57c-238d2160407f)

### What did you expect to happen?

These endpoints should be called only the necessarily amount of time.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a not empty scenario
2. Open the network tab in the dev tools

### What operating system, browser and environment are you using?

- **Browser**: Firefox v118
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

ac1eaf49

**Comment by sim51** [comment]
I found an issue in the code on how we are using RTK initiate query that may be related to this issue.

In some places in the code we are using the following pattern : 
```
const { data: newSwitchTypes = [] } = await dispatch(
    osrdEditoastApi.endpoints.getInfraByIdSwitchTypes.initiate(
      { id: infraID }
    )
  );
```

By doing this, RTK do a subscription on the query itself. 

Don't really know how (the RTK doc is not really useful on this topic),   but when you call it again (like when the infraID changed), RTK is also doing queries for all previous infraID saved in its cache.

To avoid that, we need to change the code like that : 
```
const rtkResponse =  dispatch(
    osrdEditoastApi.endpoints.getInfraByIdSwitchTypes.initiate(
      { id: infraID }
    )
  );
rtkResponse.unsubscribe()
const result = await  rtkResponse;
console.log(result.data)
```
