### ISSUE TITLE
editoast: replace serde_json::Value occurrences by actual structs where appropriate

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#5457]
### Description and goal

* Remove the `serde_json::Value` usage where serializable structs should be used (some are defined, some you will have to define).
  * To define the missing structs, you can either look at the openAPI or at the python `osrd-schemas` library.
*  Here are the areas where `serde_json::Value` is still used where it shouldn't (I might have missed some 🙈)
    * in the models RollingStock and LightRollingStock, for power restrictions
    * in the schemas RollingStock and LightRollingStock, for power restrictions
* ~some `serde_json::Value` remain in /infra related views, but that's expected since they're yet to be annotated with utoipa~

### Acceptance criteria

- [ ] No `serde_json::Value` is left

**Comment by leovalais** [comment]
~#5700 will cover some area described here. I'll update this issue once the pr gets merged.~ Updated.
