### ISSUE TITLE
front: change "no train schedule" message in scenario page

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#5468]
### What happened?

When just creating the scenario, the first message to be seen is "No available data" or "Aucune donnée disponible"
![image](https://github.com/osrd-project/osrd/assets/47494402/7be38b9b-7565-4c09-b0f9-760201ceee36)

This proved to be misleading for new users, which thought something was wrong with the dump

### What did you expect to happen?

Have a more explicit message, or no message at all (EDIT NicolasW)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a new scenario

### What operating system, browser and environment are you using?

- **Browser**: Firefox 
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

ac671b42

**Comment by nicolaswurtz** [comment]
I propose to not display anything when there's no trains in timetable.
