### ISSUE TITLE
Number format in budget field

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#5477]
### What happened?

![Image](https://github.com/osrd-project/osrd/assets/55697888/51539538-d6a9-4e21-ac3e-2a22b84a2f92)

### What did you expect to happen?

When you type a amount, you don't expect a 0 in front of the number

### How can we reproduce it (as minimally and precisely as possible)?

Create a project and fil the fields budget
Delete the budget and type a new budget if necessary, a zero remain in front 

### What operating system, browser and environment are you using?

- **Browser**: Version 118.0.5993.96 
- **OS**: Sonoma 14.0 (23A344)
- **Env**: rec-osrd.reseau.sncf.fr
- 

### OSRD version (top right corner `Account` button > `Informations`)

1280353d6bb501ba1b4ad3c1ffe91927c6a6cfd0

**Comment by bloussou** [comment]
Related to [#5221](https://github.com/osrd-project/osrd/issues/5221)
