### ISSUE TITLE
Inconsistent dates can be entered

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#5479]
### What happened?

It is possible to enter inconsistent dates in the study form. end can be before start

### What did you expect to happen?

The application have to check the consistency of the dates

### How can we reproduce it (as minimally and precisely as possible)?

Create a project
Create a study
Enter inconsistent dates and see that there is no verification

### What operating system, browser and environment are you using?

- **Browser**: Version 118.0.5993.96
- **OS**: Sonoma 14.0
- **Env**: rec-osrd.reseau.sncf.fr

### OSRD version (top right corner `Account` button > `Informations`)

1280353d6bb501ba1b4ad3c1ffe91927c6a6cfd0

**Comment by loic-hamelin** [comment]
>

**Comment by Khoyo** [comment]
Reopen for the front-end validation part
