### ISSUE TITLE
Buffer stop positioning is terribly slow in infra editor

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5488]
### What happened?

https://github.com/osrd-project/osrd/assets/86296016/6e666794-85b1-49f9-b35d-a33cad70909a

### What did you expect to happen?

I'm expecting the buffer stop icon to follow my pointer rather quickly.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the buffer stop editor

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

74fc2523

**Comment by sim51** [comment]
I tried to find a way to speedup it, but so far it's a fail...

@axrolld I have two questions : 
- in your video, I don't see the text popin (which is also a bug for me, the popin  should not be able to be closed). Do you have also a lag on the popin location or not ? 
- do you have the same behavior with detectors ?

**Comment by jacomyal** [comment]
@axrolld I just took this ticket, but I can't reproduce it: The icon is following the cursor quite fastly, not like in your example. Can you check that this issue hasn't "magically solved itself" somehow?

**Comment by sim51** [comment]
From what I saw when I tested this issue, it can be related to the display of the icon on the map, which has been solved with the new architecture last friday.

**Comment by axrolld** [comment]
Yes it is indeed solved ! 🥳
