### ISSUE TITLE
The line search does not center the map on the searched line.

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#5492]
### What happened?

When you use the line search tool, the map does not center on the searched item.

### What did you expect to happen?

When you use the line search tool, the map centers on the searched item.

### How can we reproduce it (as minimally and precisely as possible)?

Create a project/study/scenario
Search for a line.

### What operating system, browser and environment are you using?

Google chrome : Version 118.0.5993.89

### OSRD version (top right corner `Account` button > `Informations`)

1280353d6bb501ba1b4ad3c1ffe91927c6a6cfd0

**Comment by alexandredamiron** [comment]
On what point it is supposed to center ? Begin, end, middle, whole with zoom/dezoom ?
