### ISSUE TITLE
Labels/tags in study/project/scenario require to press "Enter" to be validated

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5493]
### What happened?

Labels/tags in study/project/scenario require to press `Enter` to be validated, but there is no indication or anything explaining the user to do it.

Several persons discovering the project interface tried to add labels and didn't press `Enter`, so their labels weren't saved.

### What did you expect to happen?

There should be a way to improve the UX/UI here. I don't have specific ideas yet but opening this issue to start a discussion.

### OSRD version (top right corner `Account` button > `Informations`)

74fc2523

**Comment by bloussou** [comment]
Normal behavior
