### ISSUE TITLE
Operational point not displayed in the modal

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#5505]
### What happened?

When you import timetable from the open data base, I can''t know which operationnal point is missing if I have to complete the path.
![image](https://github.com/osrd-project/osrd/assets/55697888/78989527-e720-45de-91d2-3ca87c262274)

### What did you expect to happen?

If you need to locate the operational point by completing the path, the OP should be displayed on the top of the map

### How can we reproduce it (as minimally and precisely as possible)?

Go to scenario and import train from open data base.
Chose : complete the path 
See "locate" on the top of the map

### What operating system, browser and environment are you using?

- **Browser**: Version 118.0.5993.96
- **OS**: Sonoma V14.0
- **Env**: dev-osrd.dgexol

### OSRD version (top right corner `Account` button > `Informations`)

19a77208

**Comment by clarani** [comment]
Cannot reproduce this bug, need to wait for Loïc's precisions.

**Comment by alexandredamiron** [comment]
Any way i do not think it's a good first issue

**Comment by celine-sncf** [comment]
@loic-hamelin ?

**Comment by flomonster** [comment]
This view doesn't exists anymore
