### ISSUE TITLE
core: building a `DistanceRangeMap` has very poor time complexity

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5513]
[`DistanceRangeMapImpl.kt`](https://github.com/osrd-project/osrd/blob/dev/core/kt-osrd-utils/src/main/kotlin/fr/sncf/osrd/utils/DistanceRangeMapImpl.kt)

When inserting a value, we linearly look for the location of the given offset, then insert/remove elements into an array. Both of those operations are unreasonably expansive and result in a O(n^2) complexity, which gets noticeable on long paths. This is the cause of #5452.

To fix this, we have several options:
1. ~Use a lib such as `RangeMaps`, we already use it in parts of the code~
    1. edit: not an option, we try to move away from `RangeMaps` because of its memory footprint
3. Write a builder that wouldn't use arrays like this
4. Values are always added from start to finish in practice, we could enforce this and use this property for easier optimizations

**Comment by shenriotpro** [comment]
I started implementing a larger test to measure performance. In addition to reverse lookup tricks, it seems our case could be improved by reducing redundant checks from putOptional and mergeAdjacent.

**Comment by shenriotpro** [comment]
If it fits memory, we would likely benefit from a tree-like structure, offering O(log n) time complexity for most operations (sometimes amortized), if we use a builder we can likely sort the array once (similar total O(n log n)).

**Comment by eckter** [comment]
We moved away from a tree-like structure here (guava's `RangeMaps`), the memory footprint of cached infras were too large and range maps were the main problems.

A builder can make sense if it helps. Instances are meant to be read-only once the infra is loaded. In fact we *could* use guava `RangeMaps` in a builder to avoid implementing complex logic here, the memory footprint isn't a problem when building individual instances.

---

The focus should be on concatenation though, it's the only place where we end up with a significant number of entries. It's also the only time `DistanceRangeMaps` are build after the infra is loaded. (the exact context is when concatenating track data over a whole train path)

I just thought about another option for concatenation: we could write another class implementing the interface `DistanceRangeMap` that would use a `List<DistanceRangeMap>` internally. That way the infra data wouldn't even be duplicated, it would be a simple view.

**Comment by shenriotpro** [comment]
How would you feel about adding this to the interface ("many" here basically means more than log n)?

```
/** Sets many values more efficiently than many `put` calls. */
fun putMany(entries: List<RangeMapEntry<T>)
```

**Comment by eckter** [comment]
Sounds good. Though in practice we would likely use it by instantiating an empty map and calling `putMany` once on it.

The interface to instantiate new maps is `distanceRangeMapOf()`, we could also add an overload that has a list of entries as parameters.

**Comment by shenriotpro** [comment]
A bit of benchmarking

| n       | put  | putMany |
|---------|------|---------|
| 10 000  | 4s   | <1s     |
| 20 000  | 10s  | <1s     |
| 50 000  | 58s  | <1s     |
| 100 000 | 231s | <1s     |

**Comment by shenriotpro** [comment]
Note that the PR doesn't update existing calls.
