### ISSUE TITLE
Improve edition save endpoint performance

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5516]
## Description

- [x] Benchmark edition endpoint
- [ ] Try to improve the speed

## Ideas

- The error and layer generation of speed section might be the reason why it's slow
- Reduce the number of speed section

**Comment by younesschrifi** [comment]
the error generation takes a lot of time and in particular the insertion of errors in db :
(time in s)
graph load : 0.350125
track sections: 0.035972
signal: 0.052589
Speed section: 2.699122
Switch Type: 0.000092
Detector: 0.103124
BufferStop: 0.174181
OP: 0.032635
Route: 2.051347
Switch: 0.400066
Catenary: 0.193777
Insert errors: 24.603119
