### ISSUE TITLE
"Core returned an error in an unknown format" when running pathfinding

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5541]
### What happened?

Tried to run a PF on a track that i created, with the right electrification and a tracklink, and this happened:
![image](https://github.com/osrd-project/osrd/assets/86296016/e4a1b3ce-ffc4-4001-b000-fa43ae0e3a69)

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to my scenario Alex>Nouveau MR Bordeaux-Marseille>Test2
2. Try to run a pathfinding in the curve before Sète train station

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Win 11
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

1280353d

**Comment by axrolld** [comment]
Edit: it seems like it's because of remaining buffer stops here :
![image](https://github.com/osrd-project/osrd/assets/86296016/8cec1927-be1e-49e8-bef8-7a29b40ba349)

**Comment by eckter** [comment]
Couldn't reproduce for now, it seems related to the infra editor which isn't easy to use. Can't reproduce on a non-edited infra.

I'll leave it open still, there is probably a bug but it's just harder to reproduce now

**Comment by axrolld** [comment]
I tried to reproduce it but got stuck because of this bug : https://github.com/osrd-project/osrd/issues/6159

**Comment by flomonster** [comment]
Legacy train schedule v1
