### ISSUE TITLE
Infinite computing when creating new route

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5543]
### What happened?

I'm trying to fix a hole in the infrastructure so i created a track link and now i want to add a new route, but looking for compatible routes between start and stop has been computing for 5mn without finding anything
![image](https://github.com/osrd-project/osrd/assets/86296016/3d04e0cb-7e3c-410e-a6e0-775737b2bc0a)

### What did you expect to happen?

It should either find a route or return an error.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to infra editor
2. Select `France_en_qualite`
3. Try to create a new route between this detector
![image](https://github.com/osrd-project/osrd/assets/86296016/1c10dec7-710d-48cf-ab22-8a09e2e8e12e)
And this one
![image](https://github.com/osrd-project/osrd/assets/86296016/972d5c98-c848-4958-a507-b53aa003ddf3)

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Win 11
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

1280353d

**Comment by axrolld** [comment]
Edit: it appears that this bug came from an editoast crash (not 100% sure). But i can't reproduce it right now. This needs to be investigated.

**Comment by younesschrifi** [comment]
I've tried to reproduce this bug but it's impossible at the moment. As we discussed with @axrolld, it must have happened at a time when Editoast crashed.

**Comment by axrolld** [comment]
Bug reproduced on staging near Sète train station


![Image](https://github.com/osrd-project/osrd/assets/86296016/759805f0-3bfd-49a3-9f93-a9d8dcf15710)



![Image](https://github.com/osrd-project/osrd/assets/86296016/3e78b56f-12e6-4e0b-b73c-ec868f5dac3b)

**Comment by Tristramg** [comment]
I can reproduce the bug.
Only in the infra editor, not in a simulation.
Editoast is at 100% CPU but in the end it finds a solution.

The pathfind makes a huge loop. The computation ends, but it takes a very long time and might timeout.
![image](https://github.com/osrd-project/osrd/assets/12235/987aa33f-eade-4afc-aff9-968d66143d22)

![image](https://github.com/osrd-project/osrd/assets/12235/e5ede597-e29f-4ea5-9109-3cd5075a9c2e)



When asking a path starting in the inverse direction we find the solution we want.

![image](https://github.com/osrd-project/osrd/assets/12235/1a8d2f1d-6240-4c52-8a33-8209b1a7cff3)

Both detectors are ApplicableDirections=BOTH

The signals are all in the same direction at the station
![image](https://github.com/osrd-project/osrd/assets/12235/d2f178fa-67a8-4edb-9f0f-78c8dde62f4c)

![image](https://github.com/osrd-project/osrd/assets/12235/f6932204-57f0-4e01-b3d7-27776b592ba4)

**Comment by younesschrifi** [comment]
suggestions: 

- add 2 additional limits on the number of steps and the maximum cost of the path
- potentially remove the start direction field and have editoast find the best direction
