### ISSUE TITLE
Fail to create a train in an empty timetable

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5563]
To reproduce:
- create an empty scenario
- Try to create a STDCM train in the scenario
- EDitoast is rejecting train creation with this error : `{"status":400,"type":"editoast:train_schedule:NoTrainIds","context":{},"message":"No train ids given"}`

Expected behavior:
1. Should be successful with the easiest path

Version: `8ecea1c4`

**Comment by axrolld** [comment]
I'm closing this as it is a duplicate with https://github.com/osrd-project/osrd/issues/5448
