### ISSUE TITLE
Legend is `Baissez Panto` instead of `Baissez pantographe`

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5566]
See 

![Image](https://github.com/osrd-project/osrd/assets/32448554/bbfcc183-367c-4c0b-9193-685c1e932193)

Expected value:
- `Baissez Pantographe`

Version: `8ecea1c4`

**Comment by nicolaswurtz** [comment]
It's the right term, no need to change this.

**Comment by clarani** [comment]
After discussions, it was decided to have these terms:
- `zone « baissez panto »` in french
- `"baissez panto" zone ` in english (since baissez-panto is a term specific to the French railway system)

**Comment by flomonster** [comment]
I close this issue as the term used is the right one
