### ISSUE TITLE
Can't modify a train when adding some engineering allowance 

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5570]
### What happened?

Tried to add some engineering allowance to my train, but the "Modify" button does nothing.
https://github.com/osrd-project/osrd/assets/86296016/ebaea62f-ecae-4a28-9709-b3a494544f10

### What did you expect to happen?

I should be able to modify my train.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Try to modify a train and adding some engineering allowance

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

c2b9acd3

**Comment by Yohh** [comment]
the real bug is that no error message is displayed to the user when he sets wrong parameters while updating a train, the succes message is still displayed and the edit view is closed

fixed in #5727
