### ISSUE TITLE
Responsiveness problems in rolling stock editor

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5573]
### What happened?

The Davis formula collapses when the screen become too small here.
![image](https://github.com/osrd-project/osrd/assets/86296016/97e69c51-318d-47fe-a125-a47dc4a19a52)

Also in the rolling stock curves editor the 4 blocks collapse in 3-1 and not 2-2 when the screen's too small:

![Image](https://github.com/osrd-project/osrd/assets/86296016/c367d97e-dce9-4023-bf99-d7dc88c50948)

### OSRD version (top right corner `Account` button > `Informations`)

c2b9acd3

**Comment by thibautsailly** [comment]
There's a problem with the last bloc title label which character count isn't compatible with the expected responsive behaviour. The bloc width should be set by the largest content to display, and this title takes us in a situation where there too much waste in available width.
How could we shorten it? Here are some propositions:
1. Codes de restriction & classes de puissance
2. Codes restriction & classes puissance
3. Restrictions & puissances
4. Codes de restr. & classes de puiss.
5. Codes restr. & classes puiss.
I would point to number 3 as it's shorter, not specific to a railway company, and still gives a good clue when user want to set "restrictions de puissance" for example.

**Comment by Wadjetz** [comment]
After discutions:
Limit the size of the rolling stock list panel (it very complicated and need lot of refactoring)
Reduce the size of the rolling stock curves items

**Comment by SharglutDev** [comment]
RollingStock Selector size adn responsiveness will be changed in a different issue as it's a bigger refacto
