### ISSUE TITLE
Operational points names are wrong in STDCM

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5589]
### What happened?

Those labels in space-time chart are wrong in stdcm, they all display `stop-...` :

![image](https://github.com/osrd-project/osrd/assets/86296016/08ff6712-7498-4ad2-b9d3-9e2a34a618b7)

### How can we reproduce it (as minimally and precisely as possible)?

1. Run STDCM

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

c39e6996

**Comment by bloussou** [comment]
Frontend issue after checking back responses

**Comment by flomonster** [comment]
I checked that the back response contains all the information to display stop names.
