### ISSUE TITLE
Infra editor usability enhancement: tooltip and loader display

### ISSUE THREAD

**Issue by thibautsailly** [OpenRailAssociation/osrd#5591]
Here is the current experience when hovering the infrastructure on the map:
https://github.com/osrd-project/osrd/assets/870509/d6706141-932a-43aa-9a98-dd9fe1712d81

This display stuttering is happening because :
- the tooltip toggles between two sizes: one with the loader and one with infrastructure informations,
- the loader appears and disappears quickly because the informations are available… quickly.

The loader is a visual indication for "if you thought I was idle I'm not, and I'm currently working". When data can be displayed under a second, it's not necessary.

The tooltip should have one fixed size, and the loader should only be displayed after 700ms (this is a ballpark value we can fine-tune together) if the infra data isn't available.

**Comment by jacomyal** [comment]
The size of the tooltip currently depends on its content, how should we address this if we switch to a fixed size?
More precisely :
- How do we display content too small for the tooltip's fixed size?
- How do we display content too large for the tooltip's fixed size?

**Comment by sim51** [comment]
I put a min width (200) & height (100) on the popup content (only for the selection tool). 
So for bigger content it's handle., and for smaller one we will see the default min, but I choose default value to not have smaller content.
With this config, we avoid the "blink" effect we had with the use of the tiny popup  .

About the loader, I display it only after 500ms
