### ISSUE TITLE
front: editor: slopes and curves can't be empty

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5592]
### What happened?

When creating a track, the slopes and curves can't be empty. This is especially weird for curves, as the semantically correct way to have straight tracks (other that not having value) is to have an infinite radius. Inputting 0 works as well but that's mostly by chance (core avoiding a division by 0)

### What did you expect to happen?

Slopes and curves should accept empty lists

### How can we reproduce it (as minimally and precisely as possible)?

Edit a track and try not to input curves

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Ubuntu
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

c39e6996

**Comment by clarani** [comment]
Solved by #5581, duplicated with https://github.com/osrd-project/osrd/issues/3479
