### ISSUE TITLE
front: edition: when turning map layers off, there are still things showing up

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5594]
### What happened?

Weird artifacts show up even when turning all layers off.  This screenshot is near Saint Jean train station at Bordeaux (requires to zoom in)

![image](https://github.com/osrd-project/osrd/assets/3882074/e723f238-00f4-4958-8657-73fb871702ab)

### What did you expect to happen?

Nothing to show up

### How can we reproduce it (as minimally and precisely as possible)?

Turn all layers off except OSM. Find Saint Jean train station at Bordeaux and zoom in. Turn off OSM.

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Ubuntu
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

c39e6996

**Comment by sim51** [comment]
We have the same behavior on the reference map. 
It comes from the `Platforms` layer which is always displayed.  This layer uses OSM data, so I'm agree you, it should be disabled if OSM layer is not selected (we don't care to see it with cadastral or ortho background layer).

@nicolaswurtz is there a reason why this layer is always enabled ?

**Comment by nicolaswurtz** [comment]
Yes, this is a specific object that needs to be displayed but not included in all osm layer.
It should stay as a specific "layer" but with a dedicated switch in mapsettings (near Signals, BufferStops, etc.).
Thx!

**Comment by sim51** [comment]
@nicolaswurtz I need an icon or a symbol , do you know which one I should use ?

**Comment by sim51** [comment]
On the editor : 
![image](https://github.com/osrd-project/osrd/assets/231657/082a9ada-d263-43a3-87eb-ca0233f5d3c9)

On the map : 
![image](https://github.com/osrd-project/osrd/assets/231657/cb959088-9605-4f4d-9201-cfb510fac0e4)

For the icon, I choose one.
