### ISSUE TITLE
core: unclear error when assertion at `BlockInfraBuilder.kt:29` is triggered

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5600]
### What happened?

This assertion was triggered when trying to load a newly edited infra. If the infra is actually invalid, the error message needs to be clearer. It may also be a bug if the infra is valid.

### What did you expect to happen?

Either no error or a clearer description of what is wrong in the infra

### How can we reproduce it (as minimally and precisely as possible)?

I *think* this was caused by routes that reach a signal before reaching a detector. Or something like that, I haven't investigated that much.

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Ubuntu
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

c39e6996

**Comment by Khoyo** [comment]
It should only trigger when there is no detector between two block delimiting signals (and thus a block with no ZonePath)

If it triggers in those cases, the infra is invalid.

If it triggers when the path between a bufferstop and a signal has no detectors (but there is a detector after the signal), then yes, it's a bug.
