### ISSUE TITLE
front: typo in data layers detail

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#5605]
### What happened?

![image](https://github.com/osrd-project/osrd/assets/115472753/4179a287-9b12-4d09-a4b6-064894f6f124)
 "signals" should be "Signals"

### How can we reproduce it (as minimally and precisely as possible)?

1. go to map
2. open map settings and unwrap data layers

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102
- **OS**: win11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

49d621de

**Comment by flomonster** [comment]
This can be done with [transifex](https://www.transifex.com/osrd/osrd/dashboard/)

**Comment by loic-hamelin** [comment]
Can't find in [transifex](https://www.transifex.com/osrd/osrd/dashboard/) :/
