### ISSUE TITLE
Platforms over tracks are making the map unreadable

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5619]
### What happened?

See there is a lot of tracks under platform here:
![image](https://github.com/osrd-project/osrd/assets/32448554/fd3dd90d-be31-45bc-8ea4-f58601d6aec2)
Platforms are over the tracks and cannot be disabled., I can't see where are the tracks...

### What did you expect to happen?

Deactivate the platform layer or having it under tracks.

### How can we reproduce it (as minimally and precisely as possible)?

1. Check the situation in Paris Nord for instance

### What operating system, browser and environment are you using?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

7b37385f

**Comment by axrolld** [comment]
Is this the same bug as https://github.com/osrd-project/osrd/issues/5571 ?

**Comment by axrolld** [comment]
I feel like in both cases tracks must always appear above the background

**Comment by SharglutDev** [comment]
For the #5571 @bloussou said he's fine with it because the OSM layer can be disactivated (but maybe he didn't know there was an issue for that)

**Comment by nicolaswurtz** [comment]
We decide that it's not fine finally, linked to https://github.com/osrd-project/osrd/issues/4872 too.

The rule: for MVP (we'll discuss about this later in 2024) tracks HAVE TO be **over** everything from background on **every** map.

Simple.
Basic.
Thank you @SharglutDev ;-)
