### ISSUE TITLE
Remove message and icon when the infrastructure has no errors and warnings  

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5632]
### Who would benefit from this feature?

End users

### What is this feature about?

- Delete the message and the icon when the infrastructure does not contain errors and warnings 
![image](https://github.com/osrd-project/osrd/assets/55697979/da49cad2-392e-4f09-8261-b7abeca8db64)

### Why is this feature valuable?

delete useless informations

**Comment by sim51** [comment]
On this, I would like to have the advise of @Tguisnet 

If I do that, the UI will be the same if I enable/disable the error layout (except for error layer button), which can be weird (at least for me) .  And saying that the infra is OK is an information for me, but maybe I'm wrong.

**Comment by jacomyal** [comment]
I understand @sim51 's point. I think replacing the red by the text grey would make the information more clear and less stressful.

**Comment by sim51** [comment]
BTW we also discussed between us to remove the transparent background of the element, I have no pros & cons on that

**Comment by tykayn** [comment]
@bgiuliana i made a PR to completely hide the message saying that there is no anomaly on the infrastructure. Is it what you wanted ?
