### ISSUE TITLE
envelopes: we don't properly handle cases where slopes change the acceleration sign

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#565]
When we brake but still accelerate, or try to accelerate but still slow down. The overlay builders stop too early.

**Comment by axrolld** [comment]
The case where we brake but still accelerate should neevr be valid as trains always have an option to brake if needed. There should be nowhere on the network where a train cannot decelerate if it wants to.
I agree on the other issue though, it is linked to #539 . Have a look to see if this is not a duplicated issue.
