### ISSUE TITLE
front : editor : objects appear and disappear depending on the zoom

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5650]
### What happened?

Depending on the zoom level, some detectors and buffer stops could appear or disappear. This makes the object selection impossible to do. 

### What did you expect to happen?

When the user zoom on the map, the detectors and the buffer stops displayed should not disappear. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Enter the "Selection tool" in the editor.
2. Select detectors and bufferstops layers on the map.
3. Try to zoom to select on of them 

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

26007378

**Comment by sim51** [comment]
@bgiuliana I found a location where I can reproduce the issue for buffer stops  (small infra on the full left). But for detectors, I can't reproduce it, and I can always see all the detectors, independently of the zoom level.

![image](https://github.com/osrd-project/osrd/assets/231657/b5cf394a-db60-49a6-be3c-bdd7ed49c785)

**Comment by bgiuliana** [comment]
here for example : 
![image](https://github.com/osrd-project/osrd/assets/55697979/62931a0a-5fc1-41fe-9b35-22dab80df2cc)
I have the impression that it comes from the overlap between detectors and track name

**Comment by sim51** [comment]
It's exactly that, the track name is on top of the detector ....
Don't know how to solve that (yet)

**Comment by sim51** [comment]
There is no way to says to maplibre to not display a text from one layer that hide an  item of an other layer. 

On the ref map, it appears that the dectector layer is always on top of the track section, so we don't have this issue :
![image](https://github.com/osrd-project/osrd/assets/231657/58fcd940-8824-471e-af60-a78ccd9b0479)

We have an issue on the editor with layer's order : #5611 

By fixing this issue, it will solved the detector issue.
