### ISSUE TITLE
front : editor : track editor : impossible to add a point at the end of the track

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#5658]
### What happened?

when you try to add a point at the end of a track section and you save it, the added point is not displayed in the map

### What did you expect to happen?

the point should be there

### How can we reproduce it (as minimally and precisely as possible)?

1. Enter the "selection tool" in the editor and select a track 
2.  Click on the button to edit it
3. Add a point at the end of the track 
4. Push the botton to save the modification. A message says that the modifictions are saved.
5. Go to the "selection tool". The added point is not there.
 
### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

26007378

**Comment by sim51** [comment]
Same as #5659
