### ISSUE TITLE
front: missing attribution

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#5666]
### What happened?

We use data from http://www.mlgtraffic.net/ (rolling stock pictures) without attribution. The work is licensed under CC BY-NC-SA 3.0 https://creativecommons.org/licenses/by-nc-sa/3.0/
"You must give[ appropriate credit ](https://creativecommons.org/licenses/by-nc-sa/3.0/#), provide a link to the license, and[ indicate if changes were made ](https://creativecommons.org/licenses/by-nc-sa/3.0/#). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your us"

I suggest adding the link to the website in the "Libraries & licenses" list.

### How can we reproduce it (as minimally and precisely as possible)?

1.open "about" window
2. attribution is missing

### What operating system, browser and environment are you using?

- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

8ad8eaf

**Comment by Akctarus** [comment]
not a priority, will be part of a larger issue to add all the libraries used, not just those on the front.
