### ISSUE TITLE
No limit in tag lengths for project, studies, and scenarios

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5715]
### What happened?

> This is a very minor bug because it only happens if the user is pretty extreme. There is no urge to fix that.

But, here's what's happening :

https://github.com/osrd-project/osrd/assets/86296016/9b275512-7dc2-4c74-b101-c7680cbddc06

![image](https://github.com/osrd-project/osrd/assets/86296016/9feb29d0-7cd6-41db-8538-ef67b2473c41)

### What did you expect to happen?

There should be a limit in length for each idividual tag (proposal : 30 max), and the card should only show one line of tags, followed by `...`

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a project, study, or scenario with a lot of creativity for tag names

### What operating system, browser and environment are you using?

dev

### OSRD version (top right corner `Account` button > `Informations`)

c482536c

**Comment by nicolaswurtz** [comment]
I propose to not limit input field to 30 chars, but limit display to 30 chars with ellipsis. I prefer not to coerce user, but restrain display capabilities instead. What do you think ?

If we limit input field, we would have to inform user of this restriction somewhere...

**Comment by axrolld** [comment]
I don't think that limiting the length of a tag field is really constraining for the user, but limiting the display also works, i just thought it was more complicated.

I'm ok with both solutions !
