### ISSUE TITLE
front: search focus lost  when using specific character (+ and -)

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#5716]
### What happened?

When we're searching for a station, line, or signal. If you type `-` or `+` the focus is lost on the GET.
This bug can only be reproduced in the "Operational studies" and "Short term path request" module.

### What did you expect to happen?

We expect the character to be taken into account in the search bar.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM
2. Select a project
3. Search for a station named "Hey-+"

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v23.05
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

c482536c

**Comment by loic-hamelin** [comment]
Bug accepted until the GET refacto

**Comment by celine-sncf** [comment]
also happens when inputing in this field 
![image](https://github.com/osrd-project/osrd/assets/115472753/f706cbad-c2a3-4988-8751-312426bf742c)

**Comment by nicolaswurtz** [comment]
Proposed quick solution:
- remove keydown listener from useEffect
- add the listener to `onMouseEnter` of GET div
- remove the listener when mouse leaves GET div with `onMouseLeave`

Easy peasy!
