### ISSUE TITLE
Pathfinding fails when inverting origin/destination with intermediate waypoints specified

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5719]
### What happened?

I started with a properly working pathfinding on a single track:
![image](https://github.com/osrd-project/osrd/assets/86296016/bc17b9da-2f44-4275-89ef-1deb04da0e16)

And i reversed origin/destination :
![image](https://github.com/osrd-project/osrd/assets/86296016/5340ca9c-5798-44ca-bcbf-e487ddb7efe4)

The order of the waypoints kept the same, which lead to the pathfinding failing.

### What did you expect to happen?

Intermediate steps should be inverted too

### How can we reproduce it (as minimally and precisely as possible)?

1. Find a single track and try to reproduce this

### What operating system, browser and environment are you using?

- dev

### OSRD version (top right corner `Account` button > `Informations`)

c482536c

**Comment by alexandredamiron** [comment]
Not sure it is not front-managed as for the order or steps.
