### ISSUE TITLE
Drag thought the curves/declivity graph makes curvatures and altitude disappear

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5725]
### What happened?
Curvatures and altitude disappear when doing this :

https://github.com/osrd-project/osrd/assets/86296016/36aa7b36-8936-48bc-8c1d-f717eea9a06f

### What did you expect to happen?

The differents curves should still be visible

### How can we reproduce it (as minimally and precisely as possible)?

1. Move the declivity graph on any train

### What operating system, browser and environment are you using?

dev

### OSRD version (top right corner `Account` button > `Informations`)

6e7fc8df

**Comment by alexandredamiron** [comment]
Problem occur in all curbs in SpeedSpaceChart too. It is a keyValues problem in redraw
