### ISSUE TITLE
core: mareco fails if it generates coasting that don't cross the base curve

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#574]
We generate the coasting curves until it crosses with the base curve (without physical limits). If it goes until the beginning of the RoI we drop it to avoid a curve discontinuity at the beginning of the RoA. This causes a discontinuity in the dichotomy search.

This is reproduced in a unit test in the `ech/fix-fuzzer-errors` branch.

**Comment by multun** [comment]
It would be fixed by #538
