### ISSUE TITLE
Gateway fails to build URI with special characters

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#5749]
### What happened?

The gateway panic when URI contains special characters

Gateway stack trace:

```
thread 'actix-rt|system:0|arbiter:15' panicked at actix_proxy/src/lib.rs:120:14:
failed to build uri: http::Error(InvalidUri(InvalidUriChar))
```

### What did you expect to happen?

Forward the request.

### How can we reproduce it (as minimally and precisely as possible)?

1. Run the stack
2. Run `curl 'http://localhost:4000/api/sprites/BAPR/S%20VL.svg'`

### What operating system, browser and environment are you using?

- **Browser**: Firefox v119
- **OS**: Nixos v23.05
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

c5fb150447c2877b7f9e9279a9f2ae4c236e7c8d

**Comment by multun** [comment]
Fixed by 45e4c972e7b82f89a683ee54e15a629b44810f6b
