### ISSUE TITLE
core: generated collections need to implement a few interfaces

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5764]
When migrating modules from java to kotlin, we changed some `List<Integer>` to `StaticIdxList<T>`. When doing this, we figured out that we need or want a few things:

We'd need:

1. `list.stream()`
3. collecting a stream of `StaticId<T>` into a `StaticIdxList<T>`
2. `HashSet(list)`

What would be nice:

1. `Collections.reverse(list)`
2. `list.sortWith(Comparator...)`

I *expect* all of these requirements to be handled by making `StaticIdxList<T>` implement `List<T>` and `MutableList<T>` when relevant, but I haven't looked that much into it.

**Comment by Erashin** [comment]
Found a couple of solutions without needing to implement stream in the end, by using the methods present in Collections.kt :)
- `list.stream().map().flatmap()` => `list.map{}.flatmap{}`. No direct equivalent for `stream().findfirst().orElseThrow`, but this works `list.firstOrNull{} ?: throw ...`
- `HashSet(list)` => `list.toSet()`
- `Collections.reverse(list)` => `list.reversed()`
- `list.sort(Comparator...)` => `list.sortedWith(comparator...)` (i see `list.sortedBy` as well)
- collecting a stream of `StaticId<T>` into a `StaticIdxList<T>` => haven't looked into this one yet, but might not be needed anymore with previous solutions

**Comment by eckter** [comment]
Not actually needed thanks to @Erashin's finds
