### ISSUE TITLE
Selecting a PSL in infra editor emits MapLibre errors

### ISSUE THREAD

**Issue by jacomyal** [OpenRailAssociation/osrd#5789]
### How to reproduce

1. Open the editor
2. Display the PSL layer
3. Select a PSL
4. Move the mouse hover the map

### Current behaviour

Many errors are displayed in the console, with a content like:
```
Error: layers.editor/selected/geo/psl-signs-kp.filter[1][2][2]: string, number, or boolean expected, array found
```

### Expected behaviour

No error should be visible

**Comment by Tguisnet** [comment]
Done in https://github.com/osrd-project/osrd/pull/5791
