### ISSUE TITLE
When downsizing a PSL, original shape still rendered

### ISSUE THREAD

**Issue by jacomyal** [OpenRailAssociation/osrd#5790]
### What happened?

![image](https://github.com/osrd-project/osrd/assets/144846/a2988ab5-8e30-457c-9789-176d63c01df1)

When moving an extremity closer to the other extremity, the PSL should only be drawn between the two new extremities. It joins the original extremity instead.

### What did you expect to happen?

The displayed PSL should only join the two extremities.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to editor, display PSL layer
2. Select a PSL, and start editing it
3. Select an extremity, and move it closer to the other extremity

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

0e2b8b5

**Comment by Tguisnet** [comment]
Done in https://github.com/osrd-project/osrd/pull/5791
