### ISSUE TITLE
Cannot save a new PSL

### ISSUE THREAD

**Issue by jacomyal** [OpenRailAssociation/osrd#5792]
### What happened?

I cannot save a new PSL, because Editoast returns a 400 error:

```json
{
  "status": 400,
  "type": "editoast:JsonError",
  "context": {
    "cause": "Json deserialize error: invalid type: null, expected a string at line 1 column 517"
  },
  "message": "Json deserialize error: invalid type: null, expected a string at line 1 column 517"
}
```

It looks like the front sends `"value": null` for the `"z"` panel, when it should either send a string or nothing instead.

### What did you expect to happen?

Since the front allows clicking the "Save" button, the new PSL should have been properly saved.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to infra editor
2. Go to speed sections edition
3. Select a track section, and check "Permanent speed limit"
4. Click the "Save the new speed limit" button

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

0e2b8b5

**Comment by jacomyal** [comment]
Update: I tried sending nothing instead of `"value": null`, but it sent a different 400:

```json
{
  "status": 400,
  "type": "editoast:JsonError",
  "context": {
    "cause": "Json deserialize error: missing field `value` at line 1 column 438"
  },
  "message": "Json deserialize error: missing field `value` at line 1 column 438"
}
```

I find it odd, because this `"value"` field is not required, according to the JSON schema:
https://github.com/osrd-project/osrd/blob/17ca23c078bd79af7cf16248e2cce169580302b7/front/src/reducers/osrdconf/infra_schema.json#L1011-L1015

**Comment by Tguisnet** [comment]
Front end doesn't follow the default values of the schema for the PSL.
We have to correct the specific front schema of the PSL to have the field pk,
and we have to ensure that all the fields of all objects with default value are correcly handled.

(required means thats we cannot provide a default value for this field)

**Comment by SharglutDev** [comment]
Except some specific fields for PSL and Catenary, all other forms seems to be handled correctly thanks to the autogenerating form.
