### ISSUE TITLE
When searching a line the focus zoom can be too large

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#5826]
### What happened?

When searching for a long line (like Paris-Lyon `830000`) the focus is done but the zoom is too large `z < 5`. It's an issue since tracks are not displayed at this level of zoom.

### What did you expect to happen?

Center the camera on the searched object but limit the z value to `5`.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the "Map viewer"
2. Select an infra
3. Search for a big line

### What operating system, browser and environment are you using?

- **Browser**: Firefox v119
- **OS**: Nixos v23.05
- **Env**: Staging

### OSRD version (top right corner `Account` button > `Informations`)

2019297

**Comment by nicolaswurtz** [comment]
Solution proposed: if zoom < 5 after bounding box of features, zoom will stay to 5
