### ISSUE TITLE
Signals not displayed on a duplicated infra

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5828]
### What happened?

Trying to fix a route issue near Sète train station, i displayed the signals but only the names are being dispayed, not the objects. This only happens on the infra that i duplicated, not the original one.

![image](https://github.com/osrd-project/osrd/assets/86296016/b4b2c5a7-4420-44bc-ba9a-f4ed706a8391)

Same bug on the map module.

### What did you expect to happen?

The signals should be displayed, not only the names.

### How can we reproduce it (as minimally and precisely as possible)?

1. Duplicate france_snapping
2. Go to the map or infra editor
3. Display signals layer
### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging degexsol

### OSRD version (top right corner `Account` button > `Informations`)

2019297

**Comment by axrolld** [comment]
Edit: they re-appeared for no reason, i don't know what happened...

**Comment by axrolld** [comment]
Re-edit : they only show up on the original infra, but they aren't displayed on my duplicated infra. I'm editing the description and title of the bug.

**Comment by celine-sncf** [comment]
it's most likely an issue with the duplication of layer_signals

**Comment by shenriotpro** [comment]
signal in the locked infra: 

```
~/osrd (dev)$ docker exec osrd-postgres psql -d osrd -c $'select * from infra_layer_signal where infra_id=7 and obj_id LIKE \'c007ab%\';'
   id   |                obj_id                |                     geographic                     |                     schematic                      | infra_id |     angle_geo     |     angle_sch      | signaling_system | sprite
--------+--------------------------------------+----------------------------------------------------+----------------------------------------------------+----------+-------------------+--------------------+------------------+--------
 362601 | c007ab14-4964-11e4-9bff-012064e0362d | 0101000020110F0000B783CF75C12419414CAF638C30815441 | 0101000020110F000013AD8109B2D51E41CE5993411C195441 |        7 | 434.9414926393884 | 449.99998843231964 | BAL              | CARRE
```

signal in the unlocked infra:

```
~/osrd (dev)$ docker exec osrd-postgres psql -d osrd -c $'select * from infra_layer_signal where infra_id=8 and obj_id LIKE \'c007ab%\';'
   id   |                obj_id                |                     geographic                     |                     schematic                      | infra_id |     angle_geo     |     angle_sch      | signaling_system | sprite
--------+--------------------------------------+----------------------------------------------------+----------------------------------------------------+----------+-------------------+--------------------+------------------+--------
 390901 | c007ab14-4964-11e4-9bff-012064e0362d | 0101000020110F0000B783CF75C12419414CAF638C30815441 | 0101000020110F000013AD8109B2D51E41CE5993411C195441 |        8 | 434.9414926393884 | 449.99998843231964 |                  |
```

(signaling_system and sprite are missing)

**Comment by shenriotpro** [comment]
here is a very suspect line https://github.com/osrd-project/osrd/blob/d41c4c3982c6b8891fce29fb791fb5dd2a452ab4/editoast/src/models/infra.rs#L212

**Comment by shenriotpro** [comment]
![image](https://github.com/osrd-project/osrd/assets/142150521/13b5db20-e282-45d2-9a9d-804d97d18cc0)
