### ISSUE TITLE
Creating two trains at the exact same departure time doesn't cause any conflict

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5832]
### What happened?

I created the two same trains, same rolling stock, itinerary, and departure time, but no spacing conflict was detected
![image](https://github.com/osrd-project/osrd/assets/86296016/ae3f9f12-0ee1-48db-b7fa-998bbcb2abbe)

### What did you expect to happen?

There should be at least one big spacing conflict

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Create a train
3. Create another train without changing anything
4. See that there's no conflict detected

### What operating system, browser and environment are you using?

stagin dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

2019297

**Comment by Khoyo** [comment]
Reloading the page fixes it. The front doesn't call the conflict endpoint after creating the second train...
