### ISSUE TITLE
OSM map needs to be retoggled to be displayed

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#5849]
### What happened?

When opening the map in operational studies or the map tool, the map is white, even though the OSM toggle is toggled. You have to untoggle and retoggle for it to show up

[bug_no_osm_map.webm](https://github.com/osrd-project/osrd/assets/47494402/1f166346-97b7-429a-8dc3-8afc7244872d)

### What did you expect to happen?

The map is shown if the toggle is on

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map tool
2. Witness the whiteness

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Ubuntu
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev b6ead5b

**Comment by sim51** [comment]
It happens only if you have no infra selected (reproduce it in private mode)

**Comment by axrolld** [comment]
Similar bug found here, in scenarios (so with an infra selected)
https://github.com/osrd-project/osrd/issues/6037

**Comment by axrolld** [comment]
I have the same bug on the map, even with an infra being selected
![image](https://github.com/osrd-project/osrd/assets/86296016/acf5658c-1f7f-4a1f-976d-796010c9f9ec)
