### ISSUE TITLE
No anomalies displayed on bottom-right indicator though there are some clear anomalies

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5855]
### What happened?

I edited non-sense tracks, creating anomalies, that are visible on the map, but the bottom-right anomalies counter isn't clickable, and displays no anomalies.
![image](https://github.com/osrd-project/osrd/assets/86296016/aa191370-20d7-4458-bb45-206f44df1c1d)

### What did you expect to happen?

The number of anomalies should be correct and the component should always be visible.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to infra editor
2. Selected an unlocked infra
3. Create anomalies
4. See bug

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

3141a01

**Comment by sim51** [comment]
Backend returns a 400 when we ask a page with a page_size at `0` : https://osrd.dev.dgexsol.fr/api/infra/20/errors/?page=1&page_size=0&level=all

By changing the `page_size` to `1` it works again.

**Comment by axrolld** [comment]
Thanks for taking this in charge ! :)
