### ISSUE TITLE
Tooltip sometimes not displayed when hovering anomalies counter on firefox

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5882]
### What happened?

The `Configure display of issues` tooltip is displayed when hovering anomalies counter with zero anomalies on firefox
![image](https://github.com/osrd-project/osrd/assets/86296016/b967a6ad-0473-4b62-b67b-eba457d86607)

But it won't show up anymore when there are some anomalies in the infra.

### What did you expect to happen?

The tooltip should always show up

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to infra editor on firefox
2. Hover the anomalies counter, with or without anomalies on the infra
3. Notice that the tooltip isn't displayed when there are some anomalies in the infra

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

f755dc9

**Comment by Yohh** [comment]
can't reproduce this bug
