### ISSUE TITLE
editoast(test): use 'serial_test' crate for improving test performance

### ISSUE THREAD

**Issue by woshilapin** [OpenRailAssociation/osrd#5886]
### Description and goal

What's this task about, and what is it for?

Today, `editoast` tests all rely on an existing database and race conditions can happen during test execution, making the test failing. Therefore, tests are run with `--test-threads 1` to avoid these race conditions... but at the price of a longer time to run the test suite.

We could use https://crates.io/crates/serial_test to force only the needed tests to run in isolation, and keep the rest of the test suite running concurrently.

Related to https://github.com/osrd-project/osrd/issues/5441.

### Acceptance criteria

A list of conditions which define when this task shall be considered complete

The suite of tests on `editoast` run faster. If not, then we probably do not want to keep `serial_test` since it would add additional dependency and complexity for no gain.

**Comment by Wadjetz** [comment]
Method: I added serial_test to every test and then identified the tests that don't need it, measuring the time for each. I also ran tests without serial_test to compare the results. Running without serial_test with 5 threads produced random errors, but when there were no errors, the results were very similar to those obtained with serial_test.


| Threads number   | Without serial_test  | With serial_test |
| ---------------- | -------------------- | ---------------- |
| cargo test          | 57.38s               | 56.58s           | 
| --test-threads 1 | 56.59s               | 56.62s           |
| --test-threads 5 | 57.34s               | 56.44s           |

**Comment by shenriotpro** [comment]
> Method: I added serial_test to every test and then identified the tests that don't need it, measuring the time for each. I also ran tests without serial_test to compare the results. Running without serial_test with 5 threads produced random errors, but when there were no errors, the results were very similar to those obtained with serial_test.
> 
> Threads number	Without serial_test	With serial_test
> cargo test	57.38s	56.58s
> --test-threads 1	56.59s	56.62s
> --test-threads 5	57.34s	56.44s

Those results are surprising to me.

On dev (without serial_test), I get 25s, 76s, and 26s.

I'm also surprised many tests need serial_test, I would recommend we check why they're failing, add a few serial_test (I would expect <5), and probably set a thread limit for db_pool (4 or 5)

**Comment by shenriotpro** [comment]
![image](https://github.com/osrd-project/osrd/assets/142150521/884929e9-ae1c-4e8a-bc9a-9ea05f884a0d)

**Comment by shenriotpro** [comment]
I'm getting good results so far by setting --test-threads=6 and isolating the following 2 tests, I think it's a promising alternative (unless it's flaky somehow).

https://github.com/osrd-project/osrd/blob/fffca59af020515a3e6284941aa1e788b0703d6e/editoast/src/views/pathfinding/electrical_profiles.rs#L241
https://github.com/osrd-project/osrd/blob/fffca59af020515a3e6284941aa1e788b0703d6e/editoast/src/views/pathfinding/catenaries.rs#L280

**Comment by Wadjetz** [comment]
Yes, something went wrong with my measures of times. I think that it better to improve and isolate tests instead of using serial_test

**Comment by shenriotpro** [comment]
It's totally fine IMO to use serial_test on those two.
