### ISSUE TITLE
front: refacto edition and creation forms for routes

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5903]
# Description
For now, the route creation forms looks like this, with buttons allowing the user to select begin/end on the map:
![image](https://github.com/osrd-project/osrd/assets/86296016/c6100b24-9c44-4993-808d-97a1471fc5ee)
When the begin/end have been selected, the tool proposes all the different possible routes. You can select one of them and specify if the transit is rigid or not. This is the process to create a new route. 

When you select a detector and you go in edition mode, you can see the routes linked to this detector. If you select one of these, you arrive to a form like this, with buttons to go to the begin/end detector, a delete button, a button to compute an alternative route and a button to change the transit from not rigid to rigid: 
![image](https://github.com/osrd-project/osrd/assets/86296016/72e43c07-d2d1-4f7a-8d6b-9c1c5a35a675)

**The only actions you can actually do on an existing route are deleting it or enable rigid transit (be careful you can not do the opposite).** 
Moreover, the creation and edition forms are very similar, so we'd like to merge them into one single form.

# Goal

1. Enable route edition
2. Avoid duplication in code and weird UI differences between both forms

# AC
- [x] Route edition and creation are merged into a single form displaing `Route` as a title.
- [x] When we click on the route tool the form contains the two selectors for the begin/end detectors
- [x] The following buttons for generic actions are showed as in the other object tools
![image](https://github.com/osrd-project/osrd/assets/55697979/630ebf9b-76de-4239-bd94-1a141dc57afd)

- [x] When a detector is selected, there is a button to change it if we want (we dont need to delete it before)
- [x] Once the two detectors are entered, the button `Search for compatible routes` should be activated
- [x] When a route is selected, the button to choose if the transit is rigid or not will be activated
- [x] When we click on an existing route from the list in a detector form, the same route form is diplayed but in this case the button to delete is activated
- [x] `Search for alternative routes` in the current route edition tool will be renamed in #6124

**Comment by axrolld** [comment]
We should decide between modification or creation/deletion. If i'm correct the modification isn't possible for now, so i guess only creation/deletion whould work ?

**Comment by sim51** [comment]
Normally I did the job. 
My work is available here : https://github.com/osrd-project/osrd/pull/6207

I would like to test it a little more,  before to finalize the PR. 
FYI  I'm in vacations till the 2nd of January, so I will do it in 2024.
