### ISSUE TITLE
Search in studies does not work

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5918]
### What happened?

Search a specific studies using the search bar. It will fail with 
```
{"status":400,"type":"editoast:pagination:InvalidPageSize","context":{"provided_page_size":1000,"max_page_size":100},"message":"Invalid page size (1000), expected an integer 0 < page_size <= 100"}
```

### What did you expect to happen?

Have the correct page size for the search to work

### How can we reproduce it (as minimally and precisely as possible)?

.

### What operating system, browser and environment are you using?

.

### OSRD version (top right corner `Account` button > `Informations`)

dev 35c113a

**Comment by leovalais** [comment]
The `/search` endpoint is configured to allow page_size <= 100, so either:

- implement an infinite scroller in the front-end to properly deal with the pagination
- increase the pagination limit of the /search endpoint in editoast/src/views/search/mod.rs

**Comment by flomonster** [comment]
Fixed by another PR. We should implement an infinite scroll.
