### ISSUE TITLE
Search in project does not work

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#5923]
### What happened?

When we search in the projects nothing happens

### What did you expect to happen?

the search to work

### How can we reproduce it (as minimally and precisely as possible)?

write something in the searchbar --> Nothing happens
![Image](https://github.com/osrd-project/osrd/assets/75369238/efe271ad-f31d-4fa2-acc7-653d2838e7b5)

### What operating system, browser and environment are you using?

- **Browser**: Chrome v109
- **OS**: MacOS Venture 13.4.1
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

3df6fbc

**Comment by leovalais** [comment]
Same bug as #5918

**Comment by Akctarus** [comment]
I will take it too so

**Comment by flomonster** [comment]
We increased the page_size limit in editoast ([here](https://github.com/osrd-project/osrd/pull/5941)) cause we have the same issue importing train from open data.
We can still make the project (and studies) page an infinite scroller.

**Comment by Tguisnet** [comment]
When we search for something, if the backend send multiple results, the front is not able to filter the data
