### ISSUE TITLE
Editor: Changing the track geometry result in invalid values

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#5934]
### What happened?

When we change the track section geometry some range values are updated. The new value can be invalid such as negative numbers. 

### What did you expect to happen?

These values shouldn't be changed

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Editor
2. Select a track section and edit it
3. Change its geometry
4. Some fields were updated (sometimes with invalid values)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v119
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

3df6fbc

**Comment by clarani** [comment]
I think this bug is solved, can you check ? If it's solved for you also, then, you can close the issue

**Comment by jacomyal** [comment]
I tried multiple cases:
- Enlarging a track from its start
- Enlarging a track from its end
- Shortening a track from its start
- Shortening a track from its end

I've had no invalid value at all yet. As @clarani I'm not sure this ticket is still relevant.

**Comment by jacomyal** [comment]
@flomonster I assign this ticket to you, so that if at some point you get some time, you can check whether or not this ticket is still relevant.

**Comment by SharglutDev** [comment]
Bug has been fixed.

**Comment by SharglutDev** [comment]
Bug has been fixed.
