### ISSUE TITLE
front: weird shadows when displaying the mountain

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#5936]
### What happened?

![Image](https://github.com/osrd-project/osrd/assets/55697888/0ceb16d2-945c-464d-9b3f-fbc524dc09eb)

Weird shadows 

### How can we reproduce it (as minimally and precisely as possible)?

Go to map
Enable OSM background
Enable relief
Disable OSM background
Enable OSM background

### What operating system, browser and environment are you using?

- **Browser**: Version 119.0.6045.159 (Build officiel) (x86_64)
- **OS**: Sonoma 14.1.1 (23B81)
- **Env**: (https://rec-osrd.reseau.sncf.fr/)

### OSRD version (top right corner `Account` button > `Informations`)

staging 3df6fbc

**Comment by nicolaswurtz** [comment]
It's a relief shadow order problem: it should be displayed AFTER OSM background. So it could be corrected to by tidy with the ordered layers.

**Comment by SharglutDev** [comment]
Happens only in simulation results map and manage train schedule map

**Comment by axrolld** [comment]
Seems fixed, as we can see on this magnificent Mont Blanc
![image](https://github.com/user-attachments/assets/2214ef42-799d-46a9-98b1-3626cbc2fa20)
