### ISSUE TITLE
Focus on a train with conflict when clicking on the conflict list

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5944]
### Description and goal

When clicking on the conflict nothing happens:
<img width="1505" alt="image" src="https://github.com/osrd-project/osrd/assets/32448554/3a3ee92b-f291-4adb-9c7b-208c67a26d30">

### Acceptance criteria

- [ ] When we click on a conflict, the map is focused on the path of the first train involved in the conflict
- [ ] When we click on a conflict, the GET is focused on first train involved in the conflict

We should focus on train in conflict

**Comment by axrolld** [comment]
There are many ways to do this, I think this requires more refinement from end users. Also we've been informed that this enhancement was not a priority for now. Maybe we should condiser postponing it ?

**Comment by bgiuliana** [comment]
The feature is important to debug STDCM. We will developpe it in its most simple version. New AC are added.

**Comment by axrolld** [comment]
There could be a further step projecting the space-time chart immediately, not only selecting the train. But what's been done is good enough for now, i'm moving this to Done.
