### ISSUE TITLE
front: OSRD ICONS PROJECT

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#5948]
# Goal

Have a decent lib to spread icons across whole project. Our icons come from [Github's Octicons](https://github.com/primer/octicons). Some are not included, some are originals created by our master UX/UI wizard — glory to him.

# Technical implementation

From scratch.
Icons are proposed as React Components

## Points to watch
- lock sizes: 16 or 24 pixels (exceptions possible, we've to discuss about it with our UX/UI master)
- svgo & picoSVG (cleans up and optimizes the svg)
- add utilities for components (list below)
- write documentation: icons pairs, do/don't, etc. see https://primer.style/components/icon#states
- build should only include the icons that are used, as `react-icons` do
- adding an svg icon is enough to update the IC, filename in kebab-case becomes CamelCase, size at the end (see examples below)
- include tests

## Utilities
- override colours if needed (bg, fg), use props named `color-bg` and `color-fg`
- arias for accessibility
- sizes are fixed: 16px or 24px. The size is chosen at the design stage and is not relative to the inherited font-size. The size must be abstracted with sm/lg, dictionary 16->sm, 24->lg

## Examples

**Filenames:**
`compass-filled-16.svg`
`compass-filled-24.svg`
`electric-train-head-16.svg`
`electric-train-head-24.svg`

**Components:**
```js
<>
  <CompassFilled size="sm" />
  <CompassFilled size="lg" />
  <ElectricTrainHead size="sm" />
  <ElectricTrainHead size="lg" color-fg={osrdRed50} />
</>
```

## CI

Use "github packages" (you need to add a `.npmrc conf` file to the OSRD/Front project to configure the use of "github packages").

Each time the main branch is updated, svg is cleaned up with svgo and svgs are optimised with picoSVG, which produces a new PR to be validated (see https://github.com/primer/octicons/blob/main/.github/workflows/optimize.yml).

Release flow will work via version tag which triggers the CI.

**Comment by axrolld** [comment]
The plan above is still a proposal for now. I think we should make this clearer before the next PIP.

**Comment by nicolaswurtz** [comment]
> The plan above is still a proposal for now. I think we should make this clearer before the next PIP.

We had to discuss about it today, it's much detailed now ;)
