### ISSUE TITLE
Weird electrification values in RS editor

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#5957]
### What happened?

Some weird electrification value appear in the list when chosing a new electrification mode 

![image](https://github.com/osrd-project/osrd/assets/47494402/dfcd099b-a8ab-4ead-a522-c4a00b246f9e)

There are plenty with semi-colons in them, and they are not actual modes used by trains.

### What did you expect to happen?

Only the modes actually used by trains should appear

### How can we reproduce it (as minimally and precisely as possible)?

0. (Hypothetical) Have a db with RS which have several modes
1. Go to the rolling stock editor
2. Edit a train
3. Click on the "+" button under traction modes
4. Witness

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Ubuntu
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

7796e6d

**Comment by Castavo** [comment]
It appears that it's the `infra/voltages` endpoint which is not working:
![image](https://github.com/osrd-project/osrd/assets/47494402/708d7da3-0360-4229-800f-94e07bee276e)

**Comment by flomonster** [comment]
It comes from the OSM import. Importing germany infra generates some catenaries with weird voltages like : `"750;15000"`.

**Comment by bougue-pe** [comment]
(Relates a little to https://github.com/osrd-project/osrd-dags/issues/135: migrated those fields adding V to each value).

It's not clear to me how to fix this.
I see 2 leads (not exclusive) :
1. We could probably split the concerned infra catenary into multiple overlapping catenaries, or keep only one of them (dags + PG migration?)
2. ~We could make rolling-stock edition independent of infra, as it prevents creation of complete rolling-stock if no infra has catenaries. How precisely to do that is not so simple (parameter file containing allowed `traction mode`, `comfort` and `electrical profiles` for RS, a free field, both?).~ EDIT: no issue on current behavior.

**Comment by Castavo** [comment]
Regarding your second point, you can add any electrification type you want to a RS, thus you don't need to have an infra with electrification to create a RS

**Comment by bougue-pe** [comment]
To make it short: Indeed, you are right the 2nd question doesn't stand, only the 1st.

I thought the front was preventing it, I just didn't get it right from UX, my bad 🙏
It looks like the "default" traction mode options in front are tied to both RS and infra, which is OK.

I don't know if it's an issue for electrical-profiles in RS, but it looks like front restricts options. I guess it's another feature if there is a need.

**Comment by bougue-pe** [comment]
After discussion, we have 2 options:
1. DISMISSED: create all electrifications listed in OSM. This is closer to reality but will lead to warnings in infra and is not well handled by OSRD currently.
2. ACCEPTED: create only one electrification among the ones listed in OSM (with priorities based on the main electrifications in Germany, then main ones in France, then confidential ones in Germany, then confidential ones in France : 15000 > 25000 > 1500 > 750 > 800 > 850 > 3000 ... Then the bigger is more prioritized). This will lead to a bit less realistic but more usable infra in OSRD.

**Comment by louisgreiner** [comment]
To be sure, a voltage given like this : `"600;1500;3000;15000;25000"`
should be then return like this : `"15000V"`

Since it is the first of our priority list `["15000", "25000", "1500", "750", "800", "850", "3000"]` ?

**Comment by flomonster** [comment]
Why the first option was dismissed?
The targeted behavior is:
- Core support overlapping electrification
- Editoast warn overlapping electrification (only when they're of the same type)
- OSM import should handle overlapping electrification

If we agree on that, then the best thing to do is to create all electrification listed in OSM and handle the other issues as major or critical bugs.

**Comment by Castavo** [comment]
@flomonster core does not support overlapping electrification: if there are several it will keep only one, randomly, and not consider that it's electrified with both
