### ISSUE TITLE
front: sort station (operational point) search by CH code

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#5958]
### Who would benefit from this feature?

End users

### What is this feature about?

- Sorting namely the operational point with no CH code at the top and the others by alphabetical order
- (extra fabulous overkill) Gather the search results with same CI code in one result, and have a dropdown to select a CH code

### Why is this feature valuable?

This feature matters because it:
- would make using the search more efficient: most of the time, we're only looking for the operational point with no CH code

### A bit of UI/UX

- when CH is in ['', '00', 'BV'] the OPs should be in top of the list, by default (because they are more used rather than other CH, those are the stations)
- filtering by CH have to be done in front only without a new request (data is already here)
- a switch is necessary to filter and only display the stations, when CH is in ['', '00', 'BV']
- sorting is in order: by label/name, then by CH

The form layout should be like:
```
______________________________ ________________  
| Label/trigram to search... | | CH filter... |  (O ) BV only
------------------------------ ----------------
```

**Comment by Castavo** [comment]
The non-sorting also yields this 
![image](https://github.com/osrd-project/osrd/assets/47494402/f8dd3781-3495-4cfd-96f0-0f2c8a53632f)

**Comment by nicolaswurtz** [comment]
_removed_
