### ISSUE TITLE
front: project/study/scenario card tags are not well displayed

### ISSUE THREAD

**Issue by Yohh** [OpenRailAssociation/osrd#5963]
### What happened?

tags are not well displayed, and when to many tags are added they overflow outside of the card
![image](https://github.com/osrd-project/osrd/assets/20640252/358e04bc-3995-4094-8948-2a41fb88c11c)
![image](https://github.com/osrd-project/osrd/assets/20640252/566c9e71-04a2-406e-a8c4-3c9f0b7731a2)

### What did you expect to happen?

- font-weight and padding need to be refine (f-w: 500, p-y: 0,25rem and p-x: 0,5rem)
- a tag should be a unique small word, not a sentence or several tags in one
- we need to find a way to display the tags without overflowing, according to the imposed design system

### How can we reproduce it (as minimally and precisely as possible)?

create a project, study or scenario with many long tags including several words and see the card associated

### What operating system, browser and environment are you using?

- **Browser**: Firefox v120
- **OS**: Nixos
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

1232858

**Comment by axrolld** [comment]
In my opinion we should aim for a quick fix right now. Ellipsis on tags that are too long, and if there are too many tags. This feature isn't meant to be used a lot for the coming months, we will have to to think the tags expected behavior and implement something cleaner.
What do you think ?

**Comment by nicolaswurtz** [comment]
Tags should be more than one word IMO.
We could put a fixed size of tags zone, with `overflow: auto`, that'll put a scrollbar if needed. Not so elegant, but acceptable, no?

**Comment by axrolld** [comment]
Horizontal or vertical scrollbar ?
There used to be a verical scrollbar appearing before but that was very ugly...

**Comment by Yohh** [comment]
`overflow: auto` will set it vertical, we can force it to be horizontal, each way seems ugly.. but it works
and we loose elipsis

**Comment by axrolld** [comment]
I'd rather have ellipsis and hide some tags than a super tiny vertical scrollbar.
The reason for this is that in both case we won't be able to see all the tags at once. But the scrollbar is ugly, while ellipsis aren't (in my opinion 😁).
Tags can be searched anyways, even hidden, which to me is one of the main feature linked to them.

**Comment by thibautsailly** [comment]
Tags are étiquettes : they're not supposed to be read as much as quickly recognised at a glance. It's a hidden navigation system, and just as road signs, indicators should be kept short to remain effective.
As an example `Ligne Charleville-Mézière Bellegarde-sur-Valserine` isn't an effective tag, `Charleville > Belgarde` is.

Ideally, tags should have a character count restriction, and allow multiple short words. If users _want_ to add 20 of them, let them do so and suffer the consequences. If they _need_ to add 20 of them, tags are not the solution to their problem. But we won't know about it before they start using them.

As mentioned, we should find a quick and dirty way for now and move on. The ellipsis, complemented with a `<title>` to display the full content should be enough. Adding scrollbars within a tag will ask too much cursor precision to be manipulated, it will be close to impossible on tough interfaces, while preventing users to view the full content at once.

**Comment by Yohh** [comment]
so we have to determine if we add a scrollbar the tag list, or if we choose not to display the whole list

**Comment by axrolld** [comment]
Totally agreed with @thibautsailly ! I forgot to mention it but when there used to be the tiny scrollbar it was indeed impossible to use it correctly because it was way too small.
