### ISSUE TITLE
Wrong projection with big timetable

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#5970]
### What happened?

All the trains in the GET are projected on the path of the first train (here just 1 km); When we choose another projetcion,nothing happend
![image](https://github.com/osrd-project/osrd/assets/55697888/f9fe4fac-05f3-435d-9e0d-4c302f24e33d)

### What did you expect to happen?

The GET must change if I choose another projetction

### How can we reproduce it (as minimally and precisely as possible)?

Go to : https://rec-osrd.reseau.sncf.fr/operational-studies/projects/1/studies/13/scenarios/9
Choose another protection
See what happend

### What operating system, browser and environment are you using?

- **Browser**: Chrome 119.0.6045.159 
- **OS**: Sonoma v14.1
- **Env**: rec-osrd.reseau.sncf.fr

### OSRD version (top right corner `Account` button > `Informations`)

3df6fbc612598438ceeb068dd43a379554bccf90

**Comment by Khoyo** [comment]
Big timetables aren't supported by the front.

On a local setup it works at bit better, but it still is painful.

See https://github.com/orgs/osrd-project/projects/12/views/4?pane=issue&itemId=31869102 which was postponed multiple times

**Comment by bloussou** [comment]
PM team must create multiple features/enablers tickets to add support for this kind of timetable if necessary

**Comment by flomonster** [comment]
Should be fixed with train schedule V2

**Comment by flomonster** [comment]
Train schedule V2 is here 🎉
