### ISSUE TITLE
[TS] Create Manuel Doc: Components in OSRD Simulation Front module

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#598]
- [ ] Projected Refacto with HOC
- [ ] Tree of components 
- [ ] funcs used in helpers
- [ ] Write an action plan
- [ ] Do a storybook demo with an actual component

**Comment by alexandredamiron** [comment]
React front is nice but too monolithic. Components should be able to be rendered without a Context or Store, or with mocked one. 
Data sync should be moved to HOCs
Components with default props should run into StoryBook
In that case, E2E tests are also possible.
Performances are far more tracables and improvables.

Components isolation is a major issue which need an action plan

**Comment by flomonster** [comment]
legacy
