### ISSUE TITLE
front: train doesn't appear on the map in the first 10 seconds

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#5983]
### What happened?

When hitting the "play" button and looking at the map, the blue train icon takes 10 seconds to appear (on normal speed)
https://github.com/osrd-project/osrd/assets/115472753/45270f05-5f53-45ec-8bdd-1c4a90cf997b

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to study and create a train
2. Scroll down to the map
3. Hit the play button in the top bar
4. Look at the train not showing on the map for the first 10 seconds

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 119.0.6045.199
- **OS**: Windows 11
- **Env**: https://rec-osrd.reseau.sncf.fr/

### OSRD version (top right corner `Account` button > `Informations`)

staging 3df6fbc

**Comment by clarani** [comment]
This bug has been already solved ✅
