### ISSUE TITLE
front: missing unit in "real-time" train bar

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#5984]
### What happened?

This box, which value serve to multiply the display speed of the train, has no unit, its use is thus unclear
![image](https://github.com/osrd-project/osrd/assets/115472753/ee71f538-b1f6-48e3-a75e-e7e23045a592)

### How can we reproduce it (as minimally and precisely as possible)?

1. go to study & create a train
2. look at the top bar

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 119.0.6045.199
- **OS**: Windows 11
- **Env**: https://rec-osrd.reseau.sncf.fr/

### OSRD version (top right corner `Account` button > `Informations`)

staging 3df6fbc

**Comment by nicolaswurtz** [comment]
Thx! I think add an `x` before value should be enough.

**Comment by clarani** [comment]
This ticket is not relevant anymore because we will create a new component, following the mock-up


![Image](https://github.com/user-attachments/assets/3b6cd4f0-48b7-412a-a05d-09ce7b29f8fb)
