### ISSUE TITLE
[meta] Move editoast model to V2

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#6033]
Currently editoast `Model` is using a macro. We created a new version of it with more features and better safety.  We should move the existing model to the new one.

## How to adapt

See an example here: https://github.com/osrd-project/osrd/pull/5033/commits/5a65ca381663aa6e0f04483a5168e5a2340dd497

- Create the model in modelsv2
- Make it derive `ModelV2`
- Replace all occurrences of the old model with the new one (removing unwraps)
- Remove the old model

## List of models to adapt
- [x] #6710
- [x] #6778
- [x] #6739
- [x] #6712
- [x] #6350
- [x] #6319
- [x] #6323
- [ ] Infra #6975 
- [x] OperationalPointModel @leovalais #6537 
- [x] Catenary(Model) @leovalais #6537 
- [x] TrackSectionModel #5973 
- [x] Document (model ok, tests to do) #6162 

## List of models not to be adapted

Some models will be part of a big code refactoring (check out [this](https://github.com/osrd-project/osrd-confidential/issues/248))

- [ ] ~Scenario~
- [ ] ~Timetable~
- [ ] ~SimulationOutputChangeset~
- [ ] ~SimulationOutput~
- [ ] ~TrainSchedule~
- [ ] ~TrainScheduleChangeset~
- [ ] ~Pathfinding~
- [ ] ~PathfindingChangeset~

**Comment by leovalais** [comment]
- [ ] OperationalPointModel
- [ ] TrackSectionModel
- [ ] Pathfinding
- [ ] PathfindingChangeset
- [ ] LightRollingStockModel
- [ ] RollingStockSeparatedImageModel
- [ ] Scenario
- [ ] Study
- [ ] Timetable
- [ ] TrainScheduleChangeset
- [ ] SimulationOutputChangeset
- [ ] SimulationOutput
- [ ] TrainSchedule
- [ ] RollingStockModel
- [ ] RollingStockLiveryModel
- [ ] Project
- [ ] Infra
- [ ] ElectricalProfileSet
- [ ] Document

**Comment by axrolld** [comment]
What should be done on each model exactly ? I think this issue could be a bit more detailed.

**Comment by leovalais** [comment]
Thanks everyone to carry on the migration :) Here's a little recap of the ressources you might need.

# Rust
## Setup
- Rust on stable
- rust-analyzer lsp
- rustfmt and cargo clippy on save
- Checkout editoast's README for more info
- Bind these commands to expand derive macros ![image](https://github.com/osrd-project/osrd/assets/20309655/eb484d35-cd33-41f5-a1d6-68e924b850a3)


## The language
- Rustbook: https://doc.rust-lang.org/stable/book/
- Rust by example: https://doc.rust-lang.org/rust-by-example/
- Rustlings: https://github.com/rust-lang/rustlings

## Important rust parts for ModelV2
- Traits
- Derive macros
- Modules and imports

# Diesel

- Low-level ORM
- https://diesel.rs/guides/
- The Changeset part (updates and creates) is really important to understand why we're moving to ModelV2

# ModelV1

- Trait definitions in `src/models/mod.rs`
- 4 traits Retrieve/Update/Create/Delete that `#[derive(Model)]` generates an implementation for
- The reasons on why we're moving away from it are explained in details there: https://github.com/osrd-project/osrd/issues/4184#issue-1724344418
> [!IMPORTANT]
> The ModelV2 API shown in the issue is incorrect

# ModelV2

- Trait definitions in `src/modelsv2/mod.rs`
- Trait relations: https://github.com/osrd-project/osrd/pull/5033#issue-1893415324
- Generates two structs, one for reading a row, one to act as a changeset
- The `Model` hides the manipulations of these structs, which should be considered as implementation details
- Create a model via its changeset
- 3 ways of updating an object
  1. Via a `changeset()`, in which case `update` needs an id
  2. Via a `patch()` which can be `apply`ed. Takes a mutable reference to the model instance, which is updated at the end of the `apply`
  3. Directly edit the model and `save()` it. Requires a mutable reference.

# Migration method

> [!NOTE]
> This is just a suggestion, do what works for you.

1. Comment out the old model
2. Rewrite it using `ModelV2` discarding `Options<>` and useless `#[diesel()]` annotations
3. Solve the compilation errors
  - if you encounter a `match` on the result of a model operations, better replace it by `operation_or_fail`
  - **KEEP IN MIND THAT TRAITS MUST BE IMPORTED TO BE USED!!!**
  - ModelV1 and ModelV2 traits conflict, to solve that import the ModelV2 next to its usage, we'll clean that up afterwards.
4. Move the model into `src/modelsv2`, and fix the imports (a DnD from VSCode may refactor this automatically, but I may be lying so who knows?)
5. Mark your PR as `Ready` and hope for the best...

# Side notes

> [!CAUTION]
> Don't take the `Infra` model!!!!!

> [!CAUTION]
> Don't refactor anything related to train schedules

> [!IMPORTANT]
> You'll likely change unit tests as well. The `Fixture<>` object is compatible with ModelV2. It helps keep the database clean by removing test objects from it whether the test succeeds or fail. 
> Rely on these, don't manually delete stuff. If you spot a test where things are deleted manually without a valid reason, better rewrite the test. If you're not confident on that, or whether or not you should do it at all, call your favorite editoast maintainer.

> [!TIP]
> I like these boxes.
