### ISSUE TITLE
Map background does not appear, only terrain shadow instead

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6037]
### What happened?

I tried to create a new train on one of my scenario but the map appeared like this, with no background, no tracks, only 3D.
![image](https://github.com/osrd-project/osrd/assets/86296016/5786aaa9-b402-482a-b030-f938ffb5385e)

Even though my 3D setting is at zero and the OSM background is active.
![image](https://github.com/osrd-project/osrd/assets/86296016/bcb9699d-fac2-423d-97a6-a58e8e42a09c)

If i untick and tick again the OSM background button it works, but the 3D is still there though i didn't ask for it :
![image](https://github.com/osrd-project/osrd/assets/86296016/95f7ea6b-73d1-4748-8fb9-5f2dd16f4c3f)
![image](https://github.com/osrd-project/osrd/assets/86296016/ee793495-30f8-4a0f-bf5a-27569e2f7021)

### What did you expect to happen?

The map should display what the settings ask for.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Try to create a new train
3. Go to Itinerary
4. Check the map

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

f3abe90

**Comment by flomonster** [comment]
Fixed by https://github.com/osrd-project/osrd/pull/6039
