### ISSUE TITLE
Rolling stock list not filtered after saving a rollingstock

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6074]
### What happened?

I filtered my list to find a 27000. I duplicated this 27000 and saved it after some modifications.
After saving my new rolling stock (the 27000 that i updated), i get back to an unfiltered list, even though the "27" is still as an input.

![image](https://github.com/osrd-project/osrd/assets/86296016/c8bb1997-3970-43ca-921b-319e092694e1)

### What did you expect to happen?

I expect the list to still be filtered as long as i don't remove the `27`. That way i can visualize easily the rolling stock that i just saved.

### How can we reproduce it (as minimally and precisely as possible)?

1. Reproduce the description

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging sncf

### OSRD version (top right corner `Account` button > `Informations`)

b59698b

**Comment by axrolld** [comment]
Linked bug : the selected rolling stock is not even visible : the scroll goes back to the top of the list.

I think it would make sense to bring the scroll down to where the rolling stock is after being sorted.

**Comment by emersion** [comment]
Seems like the filters are reset on purpose when duplicating a rolling stock, but that wasn't reflected in the UI.
