### ISSUE TITLE
The positions of some detectors don't match the origin / destination markers

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#6076]
---

### EDIT: see the last comment for a more accurate description of what happens

---

### What happened?

Some detectors aren't displayed. See screenshot, just west of VSX: a detector is placed between the origin and destination, but isn't displayed. 
![2023-12-07_15-12-1701960970](https://github.com/osrd-project/osrd/assets/3882074/ee435b2e-778d-459f-ac48-964eb3c1cc52)

### How can we reproduce it (as minimally and precisely as possible)?

Go to the location of the screenshot, west of VSX. Look for a path going south on the eastmost track. There is an area with no block, it's not directly visible but we can't find any path if the start location is placed there. There is a detector at the border of this block, but it's not visible. 

### What operating system, browser and environment are you using?

- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

e78edcf

**Comment by Tguisnet** [comment]
@eckter I tried to reproduce it, but all detectors on the specified are visible, and I couldn't find any invisible detector (editoast side I mean)
If you have some time, could you check if this bug is still here ?

**Comment by eckter** [comment]
Turns out it's not hidden, just misplaced: the missing detector is the one a little below (0+225). In this screenshot, as seen by core, the green dot and the detector are just next to each other. The green/yellow dots may also be the ones that are misplaced, it's not necessarily the detector. 


![image](https://github.com/osrd-project/osrd/assets/3882074/59117775-1139-4f78-9a9d-906c5bd1a9c9)

**Comment by eckter** [comment]
Can't reproduce anymore, it seems to be fixed
