### ISSUE TITLE
Lock infra editor tools when infra in locked

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6077]
# Description

When selecting a locked infra on the infra editor, all the tools are still available, leading to some bugs, on top of a very weird UX.

# Goal

Make clear that a user cannot edit a locked infrastructure.

# AC

- [x] A clear indicator must be indicating the user that the selected infra is locked (indicator tbd with @thibautsailly)
- [x] The map should be working normally and the user should be able to select/view objects
- [x] The button to save is disabled

**Comment by thibautsailly** [comment]
Here is a proposition to make it quick, before we work on the redesign:
- change the icon colour
- change the icon to a fill one, not outlined (react icons fa6/FaLock)
- add a warning message telling no change will be saved

<img width="544" alt="image" src="https://github.com/osrd-project/osrd/assets/870509/bb110bb5-a2c3-4340-940c-4444c3b10ee4">

**Comment by axrolld** [comment]
The proposal seems fine in terms of warning the user but won't prevent bugs from happening. We need to either disable the save buttons to avoid sending modifications to a locked infra, or disable the tools on the left of the app, which makes more sense to me. What do you think ?

**Comment by thibautsailly** [comment]
That would be ideal, but from what I understood it is more costly in terms of dev effort. Disabling the save button would be a first step; not ideal in terms of experience, but probably good enough while we work on the next version.

**Comment by axrolld** [comment]
As long as saving is locked that's fin by me, the idea is mostly to prevents bugs from happening.

So depending on the effort on the dev side, either disable the tools, or if not possible disable the save buttons.
