### ISSUE TITLE
front: unclear what the  "rollercoaster" emoji in the GET is for 

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#6080]
### What happened?

Before the name of one train of the GET, there is a rollercoaster emoji.
I don't understand what it is supposed to mean, it seems to change when a train is selected but not systematically ?
[unclear rollercoaster.webm](https://github.com/osrd-project/osrd/assets/115472753/8781f49c-b5d1-45b2-8833-6ed41000e8df)

### What did you expect to happen?

not sure

### How can we reproduce it (as minimally and precisely as possible)?

1. go to studies
2. create two trains
3. look at the GET and look at the rollercoaster emoji

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 119.0.6045.199
- **OS**: Windows 11
- **Env**: https://rec-osrd.reseau.sncf.fr/

### OSRD version (top right corner `Account` button > `Informations`)

staging b59698b

**Comment by nicolaswurtz** [comment]
Hi! Rollercoaster are cool.
But here, it indicates which train path is used as projection. It could be explained in a documentation, or improved: and that's the case, with the future new GET.
I close the issue for now because it will completely change and be irrelevant in a near future.
