### ISSUE TITLE
Change departure time of train can result in a different travel time

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#6090]
### What happened?

Sans bouger le train 
![image](https://github.com/osrd-project/osrd/assets/55697888/89202c20-899d-46f5-a991-69e0d64071ba)
Après avoir bougé le premier train du GET
![image](https://github.com/osrd-project/osrd/assets/55697888/49106062-7aea-4ec3-a4c1-2927a5ef773b)

### What did you expect to happen?

Le temps de parcours ou l'inclinaison ne doit pas changer quand on bouge le train

### How can we reproduce it (as minimally and precisely as possible)?

Créer un train assez long 
Le dupliquer pour pouvoir le comparer 
Déplacer le premier train depuis le GET  de quelques minutes
Constater le changement d'inclinaison du train

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: [Local](https://osrd.dev.dgexsol.fr/)

### OSRD version (top right corner `Account` button > `Informations`)

381f900

**Comment by clarani** [comment]
Reproduced: try to move a train imported with margins

When we move it, we lose the margins info and that's why the train is suddenly straighter. It will be solved by trainSchedule v2

**Comment by flomonster** [comment]
Fixed with train schedule v2. Now we handle schedule points correctly
