### ISSUE TITLE
Display neutral section in the linear

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#6114]
## Description

More information can be added to the linear.
- Donner à l'utilisateur des informations plus claires sur les zones BP/CC de l'infra 

## AC

- [ ] Code refactoring zone names
- [ ] Display in linera the zone between the execution sign and the ending (not REV)

### Quels nouveaux noms pour les zones ?

Section neutre : neutral section
Baissez panto : lower pantograph execution sign
Coupez courant : switch-off power execution sign
Fin de caténaire : end of overhead

**Comment by clarani** [comment]
## Refine technique (by Baptiste & Clara)
- [ ] editoast: update data model to add REV track_ranges
- [ ] dags: update import to get the REV track_ranges
- [ ] editoast: create a new endpoint to return all the following information of the path: catenaries, electrical profiles and neutral sections.
  - query: path_id, rolling_stock_id or power_restrictions, list of the queried information
  - return only queried information
- [ ] front: when changing the selected train, call the endpoint to retrieve the neutral sections and display it in the GEV
- [ ] core+editoast: cleaning, return only effort curve conditions

Evaluation: 2-2.5 sprints

**Comment by bloussou** [comment]
Il manque les DoR

**Comment by axrolld** [comment]
This is done in the new GEV
