### ISSUE TITLE
[meta] Scalable async RPC between editoast and core

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#6117]
### Description and goal

To address the scalability and memory constraint issues faced by the stateful core workers, which require loading comprehensive infrastructure data to process requests, a new architecture using async RPC is proposed

In this refined approach, a custom-made core-controller component dynamically orchestrates core workers, ensuring that requests are directed a specialized Core that only works on this infrastructure. 

This method significantly enhances the system's ability to handle multiple infrastructure concurrently by leveraging a distributed processing model, where each core worker is specialized.

Those modifications aim to eliminate the bottleneck of single-worker memory limitations.

### Tasks

- https://github.com/osrd-project/osrd/issues/6679
- https://github.com/osrd-project/osrd/issues/6680
- https://github.com/osrd-project/osrd/issues/6681

**Comment by celine-sncf** [comment]
Done by @ElysaSrc : design + test. 
@ElysaSrc should continue on this task during PI10.
