### ISSUE TITLE
Multiple OP seem to be selected instead of just one in the vias modal window

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6120]
### What happened?

I've selected one via operationnal point but two others appear with a `-` even though they're not selected:
![image](https://github.com/osrd-project/osrd/assets/86296016/64736fce-8d25-425d-8841-0020e3f54b74)

### What did you expect to happen?

There should be a `+` next to every unselected OP.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario on France infra
2. Use the rocket pathfinding tool to go from MSC to BX train stations
3. Add some vias

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging dgex sol

### OSRD version (top right corner `Account` button > `Informations`)

ff14422

**Comment by SharglutDev** [comment]
The bug is caused by the fact that some operational points have the same id because of issues in the datas we use. Instead of selecting those by something else than the id, it has been decided to removed the duplicates id and keeping the first one.
