### ISSUE TITLE
OP list when updating vias is unconsistent 

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#6136]
### What happened?

In the suggested vias modal, when checking an OP, sometimes the OP's number in the list is changing. Some are removed and some new are added.

https://github.com/osrd-project/osrd/assets/113104137/8023a187-1f3f-4bde-ae54-30da0714361f

  

### What did you expect to happen?

The list should remain the same all the time

### How can we reproduce it (as minimally and precisely as possible)?

See video

### What operating system, browser and environment are you using?

- **Browser**: Firefox v118
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 1ae0dec

**Comment by flomonster** [comment]
This is probably because the PF doesn't find the same path. It should be fixed with the new model system.

**Comment by flomonster** [comment]
Legacy train schedule v1.
