### ISSUE TITLE
Can't select track in infra editor when speed limits layer is active

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6158]
### What happened?

I tried to create myslef a new track to go home for Christmas. I added speed limits and i wanted to add electrification but i could not click on the track because of the speed limit layer:
![image](https://github.com/osrd-project/osrd/assets/86296016/1d78b1ad-6d89-4491-b424-5e61893c1717)

When desactivating it it works fine again:
![image](https://github.com/osrd-project/osrd/assets/86296016/c9015b24-6ca8-4b4e-8ff9-2610f54c76d1)

### What did you expect to happen?

I'm expecting to be able to select a track even if the speed limit layer is active.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a track
2. Add some speed limit to it
3. Try to add electrification without desactivating the speed limit layer.

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

faae221

**Comment by clarani** [comment]
This ticket was actually closed by another PR several weeks ago.
