### ISSUE TITLE
New signals cannot be searched

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#6163]
### What happened?

Creating a new signal in the infra editor doesn't update the search cache.

### What did you expect to happen?

The search cache should be updated.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a signal on a track section
2. Look at `search_signals`
3. It's not there
4. Cry in despair

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Mac
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev

---

# Cause 

Since editoast handles the sprites of signals, we introduced a `JOIN infra_layer_signal` in the triggers generating `search_signal`. However there is no atomicity in the edition of infra objects: they're updated first, and then the layer is regenerated. So when the trigger is called, the layer entry doesn't exist yet, therefore the query inserts nothing in `search_signal`. 

There should be a desynchronization between an edited signal and its information coming from the layer in the search cache as well.

**Comment by flomonster** [comment]
Can't reproduce. I think this was fixed.
