### ISSUE TITLE
The train displayed on the map should be the selected one

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6183]
### What happened?

The map always displays the selected train's path, which is the wanted behavior. However, the train only appears if the projection is on it. So the map displays the path but not the train, most of the time.

### What did you expect to happen?

The train displayed on the map should be the selected one, not hte one used for the projection.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario with multiple trains
2. Project one one train, select it, and chekc the is is visible on the map
3. Select another train without projecting on it, and notice that it disappeared from the mpa, even though the green path have changed

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging internal

### OSRD version (top right corner `Account` button > `Informations`)

66a103d

**Comment by clarani** [comment]
I can't reproduce this bug anymore, can you check @axrolld ?

**Comment by axrolld** [comment]
Same ! Looks like it's fixed :)
