### ISSUE TITLE
Incorrect message for rigid transit on route edition

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#6188]
### What happened?
In the route edition we can pass from not rigid to rigid transit but we can not do the opposite. This is becouse in "not rigid"  case the route contains the list of release_detectors. 
However the message says the opposite : 
![Image](https://github.com/osrd-project/osrd/assets/55697979/4fa384ec-8d77-4f44-a58e-cb14bf150a2c)

Moreover when we not select the rigid transit ,the new route gets the detectors list in the `release_detectors` property.  This is actually the behavior of the non rigid transit. 

### What did you expect to happen?

The rigid transit is not active by default. In this case the font should send the route with the realised detetors list. The user can tick the checkbox and activate the rigid transit. In this case the font should send the route without the realised detetors list. A message is diplayed saying "This property can not be disabled after saving"

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to route edition creation
2. Try to tick the rigid transit 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**:  windows
- **Env**: recette

**Comment by flomonster** [comment]
Fixed
