### ISSUE TITLE
Discontinuity in the search space on a Paris-Grenoble train

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6190]
### What happened?

I got a `discontinuity in the search space` error when trying to compute a train between Paris and Grenoble.

![image](https://github.com/osrd-project/osrd/assets/86296016/731af9bb-284a-4195-b99f-c07572345189)

Inputs :
- Rolling Stock : TC64700
- Path : `PLY SXA GE` using the rocket
- Margins : 5% standard
- Simulation parameters : MA100

### What did you expect to happen?

The running-time calculation algorithm is supposed to work on this itinerary.

### How can we reproduce it (as minimally and precisely as possible)?

1. Try to create a train with the inputs listed above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging internal

### OSRD version (top right corner `Account` button > `Informations`)

ea45fc5

**Comment by Morgane-SJK** [comment]
similar to #6386

**Comment by eckter** [comment]
Can't reproduce with the exact same parameters, the fuzzer couldn't reproduce it either. I'll close it for now
