### ISSUE TITLE
Wrong display on via point + white text on light grey background

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6191]
### What happened?

I have a train going from Perrigny to Miramas.
I'm setting a via on V1 in Crêches-sur-Saone between Paris-Lyon and Marseille-St-Charles :
![image](https://github.com/osrd-project/osrd/assets/86296016/2703636f-36c3-4b93-ae7d-7342a09b9d65)

Leads to this display after pathfinding running :
![image](https://github.com/osrd-project/osrd/assets/86296016/ea7f798c-34db-4cd8-a842-7a1f67ea7948)

The text is white on a grey background so we can't see much. But what's displayed is `V2 Ligne de Savenay à Landerneau`, which is in Bretagne ! It's very strange...

### What did you expect to happen?

I'm expecting the info displayed after PF to be the same that before setting the via point.
Also the text should be readable, not white on grey.

### How can we reproduce it (as minimally and precisely as possible)?

1. Reproduce the descritpion

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: stagin internal

### OSRD version (top right corner `Account` button > `Informations`)

ea45fc5

**Comment by bloussou** [comment]
Moving this to PI9 as it is major and still assigned to @RomainValls

**Comment by axrolld** [comment]
I'm not sure the severity was correctly understood : the problem isn't the with text on light grey background, but it's V1 that became V2 on its own.
My bad for opening one issue for two different bugs.
