### ISSUE TITLE
front: incorrect error message when not enough traction

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#6193]
### What happened?
The error is
```json
{
    "status": 400,
    "type": "impossible_simulation",
    "context": {
        "url": "http://osrd-rec-core.osd-rec01.svc.cluster.local/standalone_simulation"
    },
    "message": "The requested train stopped before reaching its destination (not enough traction)"
}
```
but the message says :

![Image](https://github.com/osrd-project/osrd/assets/55697979/412fee58-7b16-469a-9174-e4e6e3576d8a)

### What did you expect to happen?
Display the correct message

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a RS without traction force
2. Try to run running time calculation  

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**:  windows
- **Env**: recette

**Comment by clarani** [comment]
This will be fixed with the new feature which enables the translation of the error messages
