### ISSUE TITLE
front: train update impossible

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#6288]
### What happened?

In a scenario, when trying to update a train, the console sends an error : 

![image](https://github.com/osrd-project/osrd/assets/113104137/82a2f5ec-266c-4adb-927e-9d308754d397)

It comes from `SubmitConfUpdateTrainSchedules.tsx` : 

![image](https://github.com/osrd-project/osrd/assets/113104137/3c5171e0-9e78-49ea-80e4-363cd9af422f)

The selectors calls between the async function should be done of it with the others above.

### What did you expect to happen?

Update a train should work

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Try to update a train

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev c0a3242

**Comment by axrolld** [comment]
Had a similar problem. No error in front end, clicking the edition button did nothing, but i got htis in console :
![image](https://github.com/osrd-project/osrd/assets/86296016/43df5629-3f42-4f4d-85a2-4e723249a049)

Don't know if it's exactly the same problem but it might be related.
