### ISSUE TITLE
Focus in title input when creating Project/Study/Scenario

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#6312]
### Who would benefit from this feature?

End users

### What is this feature about?

Currently when creating a Project/Study/Scenario there is not focus on the title input. It could be the case since title are mandatory for study Project/Study/Scenario

We have do this for the search and it is very nice !

### Why is this feature valuable?

- Make it easier and faster for the end user

### Anything else people should know?

.

**Comment by axrolld** [comment]
Closed by https://github.com/osrd-project/osrd/pull/6597
