### ISSUE TITLE
Block stairs are not following the curve

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6314]
### What happened?

With allowances :
![image](https://github.com/osrd-project/osrd/assets/86296016/c7889e98-27dc-4658-a62b-c4035b68d125)

Without :

![Image](https://github.com/osrd-project/osrd/assets/86296016/1740c4c4-9301-4c0b-9528-fff038666148)

### What did you expect to happen?

The blocks are supposed to follow the green curve if there's one, the blue curve if not.

### How can we reproduce it (as minimally and precisely as possible)?

This does not always happen but i had this bug on train 876401 [here](https://rec-osrd.reseau.sncf.fr/operational-studies/projects/2/studies/31/scenarios/202).

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: internal staging

### OSRD version (top right corner `Account` button > `Informations`)

3a2b863

**Comment by shenriotpro** [comment]
From @Khoyo : we should probably try to reproduce locally, so we can attach a debugger and check if it's a standalone simulation issue, or related to signals.

**Comment by shenriotpro** [comment]
While reproducing with @axrolld we noticed 2 things:

1. trains imported from private data don't seem to sync well with the editor, e.g. for stops durations (should probably be a separate issue)
2. the (blue) curve actually seems to be the issue: it apparently ignores stops durations (effectively considers 0)

The good news from 2. is that we can reproduce easily by creating a train and adding a (non-null) stop

**Comment by shenriotpro** [comment]
One issue is that we "miss" the first stop, I put logs below for an example on small_infra where the position and stop position are never equal. https://github.com/osrd-project/osrd/blob/2a2abf970bd562137ce7ff3389ae5fa83219d50f/core/src/main/java/fr/sncf/osrd/standalone_sim/EnvelopeStopWrapper.java#L57
Note that in this case the first stop has duration 0 (station is not a "via").

```
2024-01-30 11:08:37 623.0183612728907
2024-01-30 11:08:37 653.636
2024-01-30 11:08:37 false
2024-01-30 11:08:37 667.2696211639147
2024-01-30 11:08:37 653.636
2024-01-30 11:08:37 false
```

Checking all stops (instead of just the next one) could fix the issue, but the problem seems deeper.

**Comment by shenriotpro** [comment]
From @eckter: we should probably check we are passed the stop, instead of at the stop.
