### ISSUE TITLE
Trains created with POST `/timetable/{id}` are showing stops with `0s` and no allowances

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#6315]
### What happened?

See 
![image](https://github.com/osrd-project/osrd/assets/32448554/4047ec62-39ce-4a54-8205-2488e8571e09)
and
![image](https://github.com/osrd-project/osrd/assets/32448554/cb5b518b-316f-4af7-b98c-563755047318)
(space time chart show that the train is stopping multiple times)

### What did you expect to happen?

Have correct duratio of stops in the edit window and nos `0s`

### How can we reproduce it (as minimally and precisely as possible)?

1. import a train with stops and consult a timtable imported from BASIC and try to edit a train.

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109

### OSRD version (top right corner `Account` button > `Informations`)

staging 3a2b863

## ⏬ Allowances as well ⏬ 
See comment below, bug reproduced on staging 218b6fb

**Comment by bloussou** [comment]
Should be fixed by train schedule v2 : https://github.com/osrd-project/osrd-confidential/issues/248

**Comment by axrolld** [comment]
There is the same bug with allowances. Here on a train near Toulouse :


![Image](https://github.com/osrd-project/osrd/assets/86296016/27155e69-f8b6-4dcd-8927-4fa512d459ef)

When trying to edit the train, the allowances are at zero :


![Image](https://github.com/osrd-project/osrd/assets/86296016/c2255550-4f35-4413-8b1f-7b67229ba9dd)

**Comment by axrolld** [comment]
Fixed by TSV2
