### ISSUE TITLE
front: scenario with long names are not readable in STDCM window to select scenario

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#6316]
### What happened?

See
![image](https://github.com/osrd-project/osrd/assets/32448554/a8a047da-0c8f-450a-b57a-e77fa98be6b4)

### What did you expect to happen?

Be able to read titles

### How can we reproduce it (as minimally and precisely as possible)?

1. create multiple scenarios with very long names

### What operating system, browser and environment are you using?

.

### OSRD version (top right corner `Account` button > `Informations`)

staging 3a2b863

**Comment by nicolaswurtz** [comment]
Thx for reporting! A simple ellispsis would be enough imo (avoid to change design, there's no much place here).
