### ISSUE TITLE
Create specific class for stdcm pathfinding 

### ISSUE THREAD

**Issue by SarahBellaha** [OpenRailAssociation/osrd#6335]
### Description and goal

See comment below:
https://github.com/osrd-project/osrd-confidential/issues/306#issuecomment-1883131947

### Acceptance criteria

- [x] All constraints are applied by `InfraExplorer`
- [x] Add a priority queue in `STDCMPathfinding`
- [x] Add the actual exploration loop, including exit condition
- [x] Clean `Pathfinding.kt` by removing all STDCM-specific features

**Comment by shenriotpro** [comment]
STDCMPathfinding https://github.com/osrd-project/osrd/blob/51f3ce3d8997ebffc02b2b85f8a6c04df446165b/core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/STDCMPathfinding.kt
Pathfinding https://github.com/osrd-project/osrd/blob/51f3ce3d8997ebffc02b2b85f8a6c04df446165b/core/src/main/kotlin/fr/sncf/osrd/graph/Pathfinding.kt

**Comment by shenriotpro** [comment]
InfraExplorer https://github.com/osrd-project/osrd/blob/stdcm-signaling-integration/core/src/main/kotlin/fr/sncf/osrd/stdcm/infra_exploration/InfraExplorer.kt

**Comment by shenriotpro** [comment]
WIP branch https://github.com/osrd-project/osrd/tree/sba/core/stdcm-pathfinding-class

**Comment by shenriotpro** [comment]
We're making good progress: unit tests pass, and CI tests pass.
We found a slight difference with the fuzzer, due to a step in the middle of an edge (used to be "no path found", now we can find one), @eckter said it's a good thing (recent bug).

**Comment by shenriotpro** [comment]
TODO: assert the last step is a stop, to simplify for now (core), and adapt the fuzzer accordingly (change https://github.com/osrd-project/osrd/blob/dev/tests/fuzzer/fuzzer.py#L226 similar to https://github.com/osrd-project/osrd/blob/dev/tests/fuzzer/fuzzer.py#L478)
