### ISSUE TITLE
Add new field in rolling stock editor to select supported signalling systems (TVM) + adapt payload

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6356]
### Description

Our rolling stock model should now present information about compatibility with BAL, TVM 300 and TVM 430. Users needs to be able to visualize this information in the rolling stock summary card and in the editor, as well as modify it.

## Goal

Keep the RS editor up to date with the data model.
Help end user to quickly visualize if a rolling stock is compatible with a given rignalling system.

## Acceptance Criteria

- [ ] The payload has been adapted (need details here)
- [ ] In the rolling stock editor, the list `BAL, BAPR, TVM 300, TVM 430` must appear with checkboxes, following this design :

![Image](https://github.com/osrd-project/osrd/assets/86296016/9807bd9b-f1ff-4a10-8f03-4331b76ae616)

**Comment by axrolld** [comment]
Is the display in the summary card doable in time ?
Something like this: 


![Image](https://github.com/osrd-project/osrd/assets/86296016/864624e2-0514-453c-b7f3-08b7fc1bd091)


With alignments this way:


![Image](https://github.com/osrd-project/osrd/assets/86296016/3bf9d32c-0cd9-412e-837e-e5c603ec67c6)

**Comment by thibautsailly** [comment]
<!-- Uploading "Screenshot 2024-01-17 at 16.57.58.png"... -→

**Comment by thibautsailly** [comment]
Signal systems can be arranged as a grid of checkboxes:
![Image](https://github.com/osrd-project/osrd/assets/870509/a113b22a-259a-4b66-8f81-6e9efbd466b8)

By using a smaller font-size (12px) it's possible to get 2 rows instead of three:
![Image](https://github.com/osrd-project/osrd/assets/870509/d36ff9f3-1fa7-4fe0-b0d9-ff079e026723)
