### ISSUE TITLE
front: STDCM result panel overlapping itinerary buttons from stdcm config panel

### ISSUE THREAD

**Issue by Math-R** [OpenRailAssociation/osrd#6364]
### What happened?

![image](https://github.com/osrd-project/osrd/assets/25245040/4c1cce01-70f0-42f3-9df5-ce606fa29a97)

When the screen is in low resolution the itinerary buttons are not wrapping and got overlap by the result view

### What did you expect to happen?

The button must wrap

### How can we reproduce it (as minimally and precisely as possible)?

Go to sdcm 
Resize the window 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v120
- **OS**: Ubuntu 22.04
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

9488d42

**Comment by nicolaswurtz** [comment]
Thx for reporting!
This is a global responsive problem of the STDCM page but easy to solve: test on a wide screen to reduce window's width and change the value of the cols (it should change to 6/6 more sooner for example). I (Nicolas) am available to discuss about it.
