### ISSUE TITLE
Operational point search does not yield all possible results

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#6373]
### What happened?

When searching for operational points on infra France, search with the keyword "Paris" yields only 25 results while there many more. 
Also, only 2 results regarding "Paris-gare-de-lyon" are given, while there are many more if you search directly "paris-gare-de-lyon"

### What did you expect to happen?

I expect to have the full list of operational points available to me

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map tool
2. Select the "France" locked infra
3. Search for "Paris" in the station search tool
4. Witness the 25 results
5. Search for "paris-gare-de-lyon"
6. Witness the 10 results

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Ubuntu
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

dev dcf73de

**Comment by axrolld** [comment]
Same problem here, looking for `Lyon-Part-Dieu` train station. It doesn't appear here.
![image](https://github.com/osrd-project/osrd/assets/86296016/77ff1ddf-13fa-4bf6-9e18-b99b5df1cd14)

**Comment by flomonster** [comment]
I think this is a front-end-related issue: See https://github.com/osrd-project/osrd/pull/6675#pullrequestreview-1891108060
