### ISSUE TITLE
Can't create a STDCM train with a via with duration

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#6386]
The error I get:
```
{"status":500,"type":"allowance_convergence","context":{"url":"http://osrd-rec-core.osd-rec01.svc.cluster.local/stdcm"},"message":"Failed to converge when computing allowances because of a discontinuity in the search space"}
```

You need to have this setup:

![image](https://github.com/osrd-project/osrd/assets/32448554/fe94ce8b-2c11-475a-aaab-2a299337a25f)

With this timetable : 
https://rec-osrd.reseau.sncf.fr/operational-studies/projects/2/studies/42/scenarios/251

Without margin it works properly.

Version: `staging 39c05f1`

**Comment by bloussou** [comment]
Cannot reproduce

**Comment by bloussou** [comment]
Reopening

**Comment by axrolld** [comment]
Recannot reproduce
