### ISSUE TITLE
Example infra and rolling stock loading scripts fail

### ISSUE THREAD

**Issue by gaelhameon** [OpenRailAssociation/osrd#6434]
### What happened?

I followed the instructions given in the [Getting started](https://github.com/osrd-project/osrd#getting-started) section of the home page.
I've been able to build and run OSRD, but I have errors when running the scripts that load the example infrastructure and rolling stock files: 

```
C:\Users\8808412L\dev\osrd [dev ≡]> ./scripts/load-railjson-rolling-stock.sh tests/data/rolling_stocks/fast_rolling_stock.json

C:\Users\8808412L\dev\osrd [dev ≡]> [20468:0124/142712.997:ERROR:cache_util_win.cc(20)] Unable to move the cache: Acc�s refus�. (0x5)
[20468:0124/142712.997:ERROR:disk_cache.cc(205)] Unable to create cache
                                    ./scripts/load-railjson-infra.sh small_infra tests/data/infras/small_infra/infra.json     

C:\Users\8808412L\dev\osrd [dev ≡]> [5128:0124/143219.041:ERROR:cache_util_win.cc(20)] Unable to move the cache: Acc�s refus�. (0x5)
[5128:0124/143219.042:ERROR:disk_cache.cc(205)] Unable to create cache
```

I've worked around the problem by loading the infrastructure file manually through the GUI, but I don't find a way to load the rolling stock file.

### What did you expect to happen?

I guess I was hoping that the files would be copied in the right places and loaded in the app.

### How can we reproduce it (as minimally and precisely as possible)?

1. Clone the project, then run: 
docker compose up -d --build
./scripts/load-railjson-infra.sh small_infra tests/data/infras/small_infra/infra.json

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

Running OSRD Locally on a Windows 11 Pro PC, using Rancher Desktop instead of Docker

### OSRD version (top right corner `Account` button > `Informations`)

local build from commit 3650cc67d9e73719a461035b076b0e0aec74beae

**Comment by multun** [comment]
Hello!

The scripts in the readme are shell scripts, so you have to run those in a terminal which runs a shell interpreter. 
I believe you ran these commands from the VSCode command line pane, is that correct?

The errors you're seeing are from VSCode, or rather from electron's [chrome component](https://github.com/chromium/chromium/blob/main/net/disk_cache/cache_util_win.cc). I think there's some kind of unrelated permissions issue with your VSCode setup.

Can you try to run these commands from a shell interpreter? Here are examples of shell interpreters for windows:

- the [git for windows](https://gitforwindows.org/) CLI allows running shell scripts in vanilla windows
- WSL runs shell scripts within a virtual machine, which might not work out as you expect in your case, as I'm not sure rancher goes through the trouble of making its docker socket available in WSL

I also don't think this setup was ever tested with rancher. **If** rancher supports all the docker compose API, it might work just fine.

**Comment by gaelhameon** [comment]
Hello!
I did run them in PowerShell through the VSCode terminal pane.

I just tried using the git bash terminal and it worked fine.

Thanks!
