### ISSUE TITLE
Editor: Form for composition code looses the focus for each character

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#6453]
### What happened?

When we try to create a speed limit with a composition code, each time we do an input on the form for composition code, the form looses the focus, and we have to click again on it to enter another character

![image](https://github.com/osrd-project/osrd/assets/27173221/28a29861-6164-4109-9d48-67639082267f)

### What did you expect to happen?

We could enter a complete composition time in a one shot

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. try to create a speed limit with a composition code

### What operating system, browser and environment are you using?

OS: Windows
Env:int-osrd.reseau.sncf.fr

### OSRD version (top right corner `Account` button > `Informations`)

v0.2.1 ff14422

**Comment by flomonster** [comment]
Fixed by #6428
