### ISSUE TITLE
Zoom in button on map brings me to the center of France

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6458]
### What happened?

I'm viewing Geneva on the map.
![image](https://github.com/osrd-project/osrd/assets/86296016/574d19dd-6344-493f-8fc0-fdc7aea50971)

Clicking the `zoom in` button on the map bring me near Tours, which isn't where i was initally.
![image](https://github.com/osrd-project/osrd/assets/86296016/d37091ce-a899-487a-b820-61d570864aad)

### What did you expect to happen?

I'm expecting the `zoom in` button to zoom where I am.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map on France infra
2. Anywhere on the map
3. Zoom in

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: stagin internal

### OSRD version (top right corner `Account` button > `Informations`)

f062f1f

**Comment by loic-hamelin** [comment]
😈
