### ISSUE TITLE
Display on a via point disappears after editing destination 

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#6459]
### What happened?

I created a train from Plombieres les Dijon to Beaune
I added a via point in Dijon, the via point was created with the display
![image](https://github.com/osrd-project/osrd/assets/156183612/a5791ab9-c6a0-4170-b1d9-5accc029c8b9)

Then I changed slightly the destination in Beaune
The via point display disappeared

![image](https://github.com/osrd-project/osrd/assets/156183612/d464ae52-742f-4f80-b61e-5d03182e0ec2)

### What did you expect to happen?

I expected the display to be present after changing the destination

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce the description above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: Staging internal

### OSRD version (top right corner `Account` button > `Informations`)

f062f1f

**Comment by SharglutDev** [comment]
Can't reproduce the bug. @maelysLeratRosso could you check again please ?

**Comment by maelysLeratRosso** [comment]
Could not reproduce
