### ISSUE TITLE
Remove the snapping of objects for the edges in the editor

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#6505]
### What happened?

When we try to place an object near an edge of a track, the object is snap to the extremity of the edge automatically.
(we are talking about the snapping for the edges only, not the one which sticks an object and a track together if they are close to each other)
Exemple : for a track of a length equal to 500, if we try to create a buffer stop between 0 and 3 or between 497 and 500, its offset will be automatically set to 0 or 500

### What did you expect to happen?

No snapping for the edges

### How can we reproduce it (as minimally and precisely as possible)?

1. go to the editor
2. try to place an object near an edge

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: All

### OSRD version (top right corner `Account` button > `Informations`)

ef4a364

**Comment by SharglutDev** [comment]
To clarify the bug, the object point is not snapped on the map when placing it close to the edge, it's just the position which is snapped to track min or max length when placing it.
