### ISSUE TITLE
Speed effort curves edition can be invalid

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#6506]
### What happened?

When editing a speed-effort curve we can end up with invalid curves saved in the application.

A speed-effort curve should have strictly increasing speed values. Currently the form sorts entries but doesn't handle duplicate speed values.

### What did you expect to happen?

We should only be able to save valid curves:
- The front should only send valid curves (enforce the input always to be valid)
- Editoast should enforce the validity of the payload

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the the Rolling Stock Editor
2. Create a new rolling stock (or edit one)
3. Go to the speed-effort curves
4. Create a curve with two rows with the same speed
5. Save the rolling stock

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: All

### OSRD version (top right corner `Account` button > `Informations`)

ef4a364

**Comment by kmer2016** [comment]
Apart from the fact that it has duplicate values, are there any other cases where the curves can be said to be invalid ?
