### ISSUE TITLE
format for the intervals are incorrect

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#6507]
### What happened?

If we see an interval in the interface, for exemple if we have an error, we should have brackets in the format of the interval.

![test2](https://github.com/osrd-project/osrd/assets/27173221/f2f75bb4-1bb5-4428-bb0d-2bc05e51d014)

### What did you expect to happen?

Intervals should have brackets **[**0,500**]**

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to  the editor
2. place an object out of range
3. check the error invalid value

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: All

### OSRD version (top right corner `Account` button > `Informations`)

ef4a364

**Comment by axrolld** [comment]
Isn't the displayed string an error message from backend ?

**Comment by sim51** [comment]
@axrolld nop, you can find it in the i18n files https://github.com/osrd-project/osrd/blob/dev/front/public/locales/en/translation.json#L128
