### ISSUE TITLE
`Electric traction` weird behavior in speed time chart

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#6540]
On a combustion engine path currently it is not possible to select or deselect the `Electric traction` display. If you first select `electric traction` in a train with electric traction and then switch to a `combustion engine` train : you cannot remove the `electric traction` info:

https://github.com/osrd-project/osrd/assets/32448554/e389862c-af31-4939-a2f8-308ce5d6a070

# Solution:

- Always allow `Electric traction` to be selected

Version `staging e220992`

**Comment by RomainValls** [comment]
Seems to be fixed ? When I'm on an electric train and check the electrical traction, if I move to a combustion engine train, the checkbox is automatically disabled and unchecks itself. 
Should we still allow electrical traction to be checked on combustion engine trains?

**Comment by RomainValls** [comment]
In the case where we always allow Electric traction to be selected : 
- if the checkbox is checked on an electrical train and that we switch to a thermal train, should the checkbox remain checked or should it be unchecked ? 
@axrolld

**Comment by SharglutDev** [comment]
Can't reproduce the bug. Is there a specific pattern @bloussou ?

https://github.com/osrd-project/osrd/assets/113104137/2b79898f-fa8a-4499-8bc0-2cf73b6c1762

**Comment by bloussou** [comment]
There is no need to deactivate the electric traction for thermal RS. It is too much logic and makes it painfull for the user:
You miss click on a thermal rolling stock in the list while checking electricity then the button is deactivated. so when you are back on an electric RS you have to click again on the button. IMO the user must be the only one to choose whether electric traction is displayed or not, no logic must to be done in the front

**Comment by thibautsailly** [comment]
The electric traction checkbox could be moved to the end of the list, displayed when a train using an electric engine is selected from the list, hidden when a train without an electric engine is selected.
Ideally, checkbox checked status should be saved for a given user.

**Comment by RomainValls** [comment]
@thibautsailly In case the checkbox status is saved : 
If the user wants to uncheck electric traction on a thermic train and it's hidden, he has to go back to an electrical train to uncheck it. 
Should we just let the checkbox visible at anytime ?

**Comment by clarani** [comment]
Not relevant anymore with the new GEV
