### ISSUE TITLE
Copy paste an excel board in the RS efforts curves editor is not working properly

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#6545]
### What happened?

From the user : 
When the user try to fill the effort curves, he could copy/paste an excel board with all the values he wanted.
However, when he click outside the board for curves on osrd, an empty line could appear at the position 2.
(an empty line is normal at the end of the board because it allows the user to fill antoher values,
here we're talking about an additional empty line)

when I try to reproduce it :
When I try to reproduce this, the unexpected behavior I observed was that the copy of the board copy one more cell (additionnal line) than the cells selected

### What did you expect to happen?

A normal behavior

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the RS Editor
2. edit some effort curves
3. copy a board from an excel

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: all

### OSRD version (top right corner `Account` button > `Informations`)

e220992

**Comment by Akctarus** [comment]
The bug I was able to reproduce is as follows: pasting an empty cell adds a second empty cell to the list below.

See : 

![Image](https://github.com/osrd-project/osrd/assets/80635161/9c2a7ce6-fd6c-418b-b2b5-615f705a10d1)

So in the fix I've made it impossible to paste an empty value alone

**Comment by SharglutDev** [comment]
The bug happens only when copy/pasting an empty cell from google sheets

**Comment by Akctarus** [comment]
Should be closed by #6788
