### ISSUE TITLE
Add a `*` for mandatory fields when creating a rolling stock

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#6548]
There is a lot of fields to fill here :

![Image](https://github.com/osrd-project/osrd/assets/32448554/581dc6fa-a2ad-4205-a103-40227a20c057)

Only some are mandatory, we could maybe show them with a `*` Like `Name*` instead of `Name`, `Length*` instead of `Length`, `Mass*` instead of `Mass`, ...

**Comment by axrolld** [comment]
I think this view will change soon with the new design.

**Comment by maelysLeratRosso** [comment]
Je vous ping car je sais pas comment github vous notifie @RomainValls @clarani 
![image](https://github.com/user-attachments/assets/d8661b08-a02b-494b-a110-d7e07dc107dd)
 
Two remarks / questions : 
- the speed effort curve seems to be mandatory, should we also add a "*" here ?
- for long names, the "*" goes on the 2nd line, which is a bit weird

[EDIT] Created this issue https://github.com/OpenRailAssociation/osrd/issues/8370 for these two points
