### ISSUE TITLE
Fine tuning of pathfinding and simulation timeouts

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#6558]
### Description and goal

We are currently waiting way too much time before considering pathfinding or simulation wont work. This leads to very long time of train imports.

100 correct trains takes 10s
220 trains with 40% failing takes 8min

### Acceptance criteria

Run https://github.com/osrd-project/osrd-dags/pull/170/files and adapt timeout values without decreasing import performances.

**Comment by shenriotpro** [comment]
Possibly relevant code: https://github.com/osrd-project/osrd/blob/472bff2dac2eb2ffcc3ff38121463626b21ea4b8/core/src/main/kotlin/fr/sncf/osrd/graph/Pathfinding.kt#L330

**Comment by shenriotpro** [comment]
Somewhat disappointing results for preliminary tests: changing the timeout to 30s leads to unexpected failures, it may be worth investigating 
![image](https://github.com/osrd-project/osrd/assets/142150521/f11d413b-1543-4b71-8424-e7b8764db400)

**Comment by shenriotpro** [comment]
The numbers above were not accounting for recent perf improvements.
I now have a payload that takes more than 60s and less than 120s (on my machine), I'll try and investigate further (this shouldn't happen, according to @eckter ).

**Comment by shenriotpro** [comment]
I discussed a bit with @Erashin: the long duration is probably related to the number of waypoints (around 100). There's no short-term plan to optimize core so it makes sense to customize the timeout for now.

**Comment by shenriotpro** [comment]
Somewhat related: https://github.com/osrd-project/osrd/blob/1372f0a0ab8ab9043e7fe10f554428de0f20d6b8/core/src/test/kotlin/fr/sncf/osrd/stdcm/PerformanceTests.kt#L18

**Comment by shenriotpro** [comment]
![image](https://github.com/osrd-project/osrd/assets/142150521/2930ea5b-d1d3-4ce9-9208-2ba84220815b)

It looks like 15s would be somewhat safe in our case. Interestingly enough, new errors start to appear on smaller payloads first.
