### ISSUE TITLE
docker compose up -d --build gives an error

### ISSUE THREAD

**Issue by keigezellig** [OpenRailAssociation/osrd#6563]
### What happened?

I am trying to compile and run the entire stack as per the readme by executing `docker compose up -d --build` but it gives the following error message:

services.core.build Additional property additional_contexts is not allowed

### What did you expect to happen?

A working and running OSRD stack

### How can we reproduce it (as minimally and precisely as possible)?

1. Checkout the repository
2. Execute the command `docker compose up -d --build`

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Ubuntu v22.04
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

v0.2.5-11-gbe27c8adc

**Comment by nicolaswurtz** [comment]
Hi! Thx for reporting.
I think our readme is outdated.
Could you try replacing `docker compose` command by ours (containing environment setup) `./scripts/osrd-compose.sh`?

**Comment by keigezellig** [comment]
I did but it still doesn't work, when i run the following command: `./scripts/osrd-compose.sh up` i got the following errors
`WARN[0000] The "OSRD_GIT_DESCRIBE" variable is not set. Defaulting to a blank string.` 
`WARN[0000] The "OSRD_GIT_DESCRIBE" variable is not set. Defaulting to a blank string.` 
`services.core.build Additional property additional_contexts is not allowed`

So the last error message is actually the same i got in the beginning

**Comment by nicolaswurtz** [comment]
As a workaround — if you don't need to explicitly "build" the project — you could `pull` the project:
- `./scripts/osrd-compose.sh pull`
- `./scripts/osrd-compose.sh up -d`

(we'll figure it out, but I can't reproduce the error for now: with a fresh ubuntu 22.04 install, build is working)

**Comment by flomonster** [comment]
We cannot reproduce this error. Please do not hesitate to reopen this issue with more details if the problem persists.
