### ISSUE TITLE
No translation when deleting electrical_profile or power_restriction_code in rolling stock editor 

### ISSUE THREAD

**Issue by Akctarus** [OpenRailAssociation/osrd#6589]
### What happened?

<img width="1470" alt="Capture d’écran 2024-02-07 à 11 27 24" src="https://github.com/osrd-project/osrd/assets/80635161/92b6d1db-6a22-48f5-989c-7aabc9a6084a">

<img width="1470" alt="Capture d’écran 2024-02-07 à 11 27 53" src="https://github.com/osrd-project/osrd/assets/80635161/e36cc1ae-3510-4316-9fc0-c52e9eb22e4a">

### What did you expect to happen?

Have a translation instead 

### How can we reproduce it (as minimally and precisely as possible)?

Go to rolling stock editor, select one, modify it and try to delete an electrical profile or a power restriction code

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 6f0dcea

**Comment by clarani** [comment]
Duplicated with https://github.com/osrd-project/osrd/issues/6912, cannot reproduce it now
