### ISSUE TITLE
front: can't add traction mode when we don't have traction modes available

### ISSUE THREAD

**Issue by SarahBellaha** [OpenRailAssociation/osrd#6608]
### What happened?

When you create a new rolling stock with no available traction modes returned by the backend, the add button is disabled and keeps you from creating a new mode.

### What did you expect to happen?

We should be able to add a new traction mode

### How can we reproduce it (as minimally and precisely as possible)?

1. Run an empty database application
3. Go to the rolling stock editor
2. Create a new rolling stock
3. Add a new traction mode

### What operating system, browser and environment are you using?

- **Browser**: Chrome

### OSRD version (top right corner `Account` button > `Informations`)

6b9dca7

**Comment by SharglutDev** [comment]
Possible solution : don't disable button when the traction mode list is empty
