### ISSUE TITLE
Driver train schedule is not correctly updated after adding a stop

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#6609]
When you create a train without a stop, then modify it by adding one, the driver train schedule displays inconsistent timetables for the points following this stop.

See : 
<img width="1470" alt="Capture d’écran 2024-02-12 à 14 39 15" src="https://github.com/osrd-project/osrd/assets/80635161/3f120630-bd9a-4141-84b1-1f6b1c511bc7">

The bug occurs on dev eee07b8.

**Comment by flomonster** [comment]
Note: This was not only for updated train schedules but for all of them.
