### ISSUE TITLE
Train projection causes `Impossible to compute running time: undefined` error

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6653]
### What happened?

On this scenario https://rec-osrd.reseau.sncf.fr/operational-studies/projects/2/studies/21/scenarios/79, projecting on train 154813 causes this:
https://github.com/osrd-project/osrd/assets/86296016/c8385f4c-9df1-46ab-ba9c-3d5617422b2a

### What did you expect to happen?

The projection should work.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the scenario linked above
2. Try to project on train 154813

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: internal staging

### OSRD version (top right corner `Account` button > `Informations`)

218b6fb

**Comment by flomonster** [comment]
Legacy train schedule v1
