### ISSUE TITLE
Send OTEL from editoast to Datadog

### ISSUE THREAD

**Issue by RomainValls** [OpenRailAssociation/osrd#6660]
Derived from https://github.com/osrd-project/osrd-confidential/issues/275.

- [ ] support sending OTEL with OTLP protocol
- [ ] support sending OTEL with Datadog client

Criteria of acceptance
- [ ] can observe OTEL in a Jaeger
- [ ] can observe OTEL in Datadog

**Comment by woshilapin** [comment]
Moving to `tracing` first with:
- https://github.com/osrd-project/osrd/pull/6649 
- https://github.com/osrd-project/osrd/pull/6650
