### ISSUE TITLE
Incorrect number of speed section issues in infrastructure editor

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#6664]
### What happened?

I opened the small_infra infrastructure in the infrastructure editor, 2 issues are reported : overlapping of speed limites between speed sections 1 and 0, and speed sections 2 and 0. In fact, there is also an overlapping between sections 1 and 2. 
![image](https://github.com/osrd-project/osrd/assets/156183612/e5007fc6-fc36-450f-b044-9764aebd2e59)

When I duplicated small_infra (small_infra_maelys_2) and added another track section, the number of issues became 3, and the overlapping between sections 1 and 2 was well reported.

### What did you expect to happen?

I expected to have 3 issues and not only 2. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to small_infra : 2 overlapping speed section issues are reported
2. Duplicate small_infra : 2 overlapping speed section issues are reported
3. Add a new track section anywhere : 3 overlapping speed section issues are reported

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**:  W11
- **Env**: Staging internal 

### OSRD version (top right corner `Account` button > `Informations`)

218b6fb

**Comment by flomonster** [comment]
Can´t reproduce
