### ISSUE TITLE
Train schedule travel time isn't updated in timetable when adding margin

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#6695]
### What happened?

In a scenario, when adding margin to a train, the travel time of this train and the time arrival in the timetable aren't updated accordingly.

### What did you expect to happen?

The travel time and arrival time should be updated when adding a margin.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Toggle the timetable trains details by clicking on the eye icon at the top and check the travel time
3. Modify a train and add some margins
4. Check again the travel time and arrival time of the train, it hasn't changed

### What operating system, browser and environment are you using?

- **Browser**: Firefox v123
- **OS**: macOS Sonoma
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev f7339f1

**Comment by axrolld** [comment]
This is a bigger problem in this part of the project : we keep considering the fastest drive as the reference, which in my opinion should not be the case. I want to make sure this is actually the case, and if so create an issue accordingly :)

**Comment by bgiuliana** [comment]
I aggree with you. The reference should be the travel time including margins. In addition, being this modifications proposed by users, I suggest to fix it at least for the timetable part. We will check the other parts of the application later.

**Comment by SharglutDev** [comment]
Actually, it seems to be a back issue. The get timetable endpoint returns the arrival time based on the base simulation.

**Comment by axrolld** [comment]
I suggest fixing this also, if you think it's relevant to do it now:
![image](https://github.com/osrd-project/osrd/assets/86296016/932baa08-2cb9-4c85-8e76-ec731abaa153)

The default should be `ECO` if some margin is added. And actually `ECO` isn't quite the right naming. Could we name it `MARGIN` ?
