### ISSUE TITLE
STDCM fails to find a solution in scenarios where an obvious one exists.

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#6717]
### What happened?

I created a simple scenario with two trains.

![Image](https://github.com/osrd-project/osrd/assets/62556370/f0972d6c-6fc4-4b63-9d98-ab56fef4a7cd)

I tried to find a solution with STDCM, but I encountered an error.

![Image](https://github.com/osrd-project/osrd/assets/62556370/b3f2e405-afc9-436a-8788-a6432044c28e)

### What did you expect to happen?

Finding a solution.

### How can we reproduce it (as minimally and precisely as possible)?

I created a simple scenario with two trains.

RS: 27000

![Image](https://github.com/osrd-project/osrd/assets/62556370/8417557f-aa60-4611-9edc-79f21773c658)

Pathfinding:
Start: Perrigny - triage 13 (V1bis)

![Image](https://github.com/osrd-project/osrd/assets/62556370/d24a3b73-ce25-4323-bd3b-19f107d1194e)

Arrival: miramas (V1)

![Image](https://github.com/osrd-project/osrd/assets/62556370/2f75421c-1e80-4fe8-a3c4-535622b168f5)

The result: 
1st train starts 07:47:37
2nd train starts 09:36:38

![Image](https://github.com/osrd-project/osrd/assets/62556370/7980cbae-3cc9-4777-9f7a-928f4fec4750)

I moved to the STDCM module and selected the same starting and arrival points, along with the same RS with a time window (08:00:00 - 12:30:00).

![Image](https://github.com/osrd-project/osrd/assets/62556370/3402895b-7d80-49ef-b0dd-f7819b77a29c)

  

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 121.0.6167.161
- **OS**: Windows 10
- **Env**: Recette

### OSRD version (top right corner `Account` button > `Informations`)

staging 840a7a0

**Comment by eckter** [comment]
I couldn't reproduce the "erreur de calcul de sillon de dernière minute", but I had other errors. In my case the STDCM request succeeds but projecting the timetable to the new path fails (`/api/train_schedule/results/`).

On the client side the only error is `Failed to connect to host: Internal error: connector has been disconnected`. The logs report this:

```
panic: called `Option::unwrap()` on a `None` value
  File "panicking.rs", line 645, in rust_begin_unwind
  ?, in editoast::views::train_schedule::simulation_report::project_head_positions
  ?, in editoast::views::train_schedule::simulation_report::create_simulation_report::{{closure}}
  ?, in actix_web::handler::handler_service::{{closure}}::{{closure}}
  ?, in actix_web::resource::Resource<T>::register::{{closure}}::{{closure}}
...
(29 additional frame(s) were not displayed)```
