### ISSUE TITLE
Pathfinding launched two times when adding a via

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#6719]
### What happened?

When adding a via via the modal or by clicking on map, the pathfinding is fired 2 times.

### What did you expect to happen?

It should be fired only once.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Add a train and launch a pathfinding
3. Open the network tab and clean the history
4. Add a via 
5. You should see two pathfinding call in the network tab

### What operating system, browser and environment are you using?

- **Browser**: Firefox v123
- **OS**: macOS Sonoma
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 1482e8c

**Comment by Castavo** [comment]
Still there 


Uploading Enregistrement de l'écran 2024-10-03 174437.mp4…
