### ISSUE TITLE
Adding a via is deleting other vias

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#6720]
### What happened?

When adding a via with the vias suggested modal, its deleting all the other vias (except the first one) if they has been added by clicking on the map.

Tips to fix : when opening the vias suggested modal, only the first "map selected" via is displayed on the list

### What did you expect to happen?

There shouldn't be any via deleted

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Chose an itinerary with at least 2 vias selected on the map
3. Open the vias suggested modal and add a via from there
4. All the map selected vias have been removed except the first one

### What operating system, browser and environment are you using?

- **Browser**: Firefox v123
- **OS**: macOS Sonoma
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 840a7a0

**Comment by Castavo** [comment]
Can't reproduce
