### ISSUE TITLE
Core: DistanceRangeMap.putMany() doesn't merge equal values for consecutive intervals

### ISSUE THREAD

**Issue by bougue-pe** [OpenRailAssociation/osrd#6726]
### What happened?

See tests in https://github.com/osrd-project/osrd/compare/peb/core/fix_distance_range_put_many
The merge when extremities and values are the same is not done by `putMany()`, leading to a different behavior than expected, and than `put()`.

### What did you expect to happen?

Have `putMany()` merging consecutive ranges with identical values.

### How can we reproduce it (as minimally and precisely as possible)?

Use tests available in `peb/core/fix_distance_range_put_many` branch

### What operating system, browser and environment are you using?

- WSL
- Gradle
- Java 17

### OSRD version (top right corner `Account` button > `Informations`)

dfcbaad3d49b68c917642fb4eaad0f05605d10f3

**Comment by shenriotpro** [comment]
IMO the main issue is that putMany considers equal bounds separately https://github.com/osrd-project/osrd/blob/ac93bc8040d8e558a2f5350ad022ee347772df2e/core/kt-osrd-utils/src/main/kotlin/fr/sncf/osrd/utils/DistanceRangeMapImpl.kt#L60

We could use mergeAdjacent for a quick fix, but I think it would be more efficient/readable to group bounds in putMany.
We may also want to split the logic in two parts: e.g. the first part handles groups (removes empty intervals) and the second part merges adjacent intervals with the same value.
