### ISSUE TITLE
TS2:  Adapt frontend studies to the new scenario model

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#6745]
### Description and goal

A study should now allow a user to create/list/delete/get Scenarios v2.

### Acceptance criteria

- [ ] Add a "button" (or something else) to access to Studies to access Scenario v2
- [ ] This option should be disable depending a environment variable (to disable this feature in production)
- [ ] User can create a Scenario v2 (using a form)
- [ ] User can only list the v2 scenarios (using `get editoast/v2/project/{project_id}/study/{study_id}/v2/scenarios/{scenario_id}` when needed
- [ ] User can delete a v2 scenario 
- [ ] User can update a v2 scenario

**Comment by flomonster** [comment]
Outdated, to see the new design look here: https://github.com/osrd-project/osrd-confidential/issues/337
