### ISSUE TITLE
Changing a circulation's train to a modified one makes it invalid instantly

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#6790]
### What happened?

When changing a circulation's train to a modified one, it makes the circulation invalid instantly (with "rolling stock modified")

### What did you expect to happen?

It should not make the circulation invalid

### How can we reproduce it (as minimally and precisely as possible)?

1. Ensure that you have a train which you modified (you can clone one and edit its values once or twice)
2. Make a circulation with a train which was never modified
3. Click on the "edit" button (pen) of the circulation, and change the train to your modified train.
4. Confirm your changes
5. The train is invalid

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Windows 11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

dev e25652d

**Comment by Castavo** [comment]
I feel like it's simply that we do not update the `train_version` stored in the train_schedule when we change the train. However I don't know if it's in the front or the back of the app.

**Comment by SharglutDev** [comment]
Front doesn't have access to the train_version. We just have an invalid_reasons ('NewerRollingStock' | 'NewerInfra') given by the timetable endpoint. And when updating a train with a new rolling stock, we provide only the rollingstock id. 
So I guess the issue comes from the back or am I missing something ?
