### ISSUE TITLE
Wrong label for objects in the error list view

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#6807]
### What happened?

When opening the error list modal, it says 
![image](https://github.com/osrd-project/osrd/assets/47494402/2cd2a478-7c47-4c61-a414-7e2533b74cd5)
5890 errors found, even though I asked for warnings ! 
When I select "errors", it says 0 errors found. When selecting "all", it says 5890 errors found.

It just says error for everything

### What did you expect to happen?

I'd expect at least that when selecting "Warnings", it shows "5890 warnings ~problems~".

Ideally too, when selecting "all" it would say "0 errors and 5890 warnings" or if easier "5890 items"

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the France infrastructure
2. Toggle the infra error layer 
3. Click on the errors count to display the list
4. Move the selector from "All" to "Warnings"

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Windows 11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

dev b1f8892

**Comment by RomainValls** [comment]
@maelysLeratRosso should we turn "errors" into "warnings"  (in 5890 "errors" found)

**Comment by maelysLeratRosso** [comment]
> @maelysLeratRosso should we turn "errors" into "warnings" (in 5890 "errors" found)

@RomainValls Yes I would say "warnings" when the filter is "Warnings", "errors" when the filter is "Errors" and "errors and warnings" when the filter is "All" ?
