### ISSUE TITLE
Map settings don't disappear when clicking the map settings button again

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6813]
### What happened?

When the map settings are open :
![image](https://github.com/osrd-project/osrd/assets/86296016/b7586532-cd2b-4392-97b6-2009daf48f8a)

Clicking on the map settings button again does nothing :
![image](https://github.com/osrd-project/osrd/assets/86296016/b77af01f-a3a2-4d57-8a4c-a800073fc758)

### What did you expect to happen?

It should close the settings window, as it is the case for the search button and the legend button.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any instance of the map
2. Open the settings
3. Try to close them by clicking the settings button again

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging internal

### OSRD version (top right corner `Account` button > `Informations`)

1f27b88

**Comment by RomainValls** [comment]
I can't reproduce the bug (tried on every maps) ?

**Comment by axrolld** [comment]
Can't reproduce either.
