### ISSUE TITLE
Changing margin/allowance unit erases the input value

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6814]
### What happened?

I want to set 4.5mn/100km margin, so i'm starting with a 4.5 input first :
![image](https://github.com/osrd-project/osrd/assets/86296016/dcc64b94-22bb-470b-ac49-13c1d3d7d465)

Then selecting the unit:
![image](https://github.com/osrd-project/osrd/assets/86296016/b9513931-4778-493e-9905-44949ea1fbc4)

But it erases my input :(
![image](https://github.com/osrd-project/osrd/assets/86296016/73677ef2-d7e4-40a9-8331-a120abe112c8)

> [!WARNING]
> **Same behavior with STDCM !!**

### What did you expect to happen?

I'm expecting my input to remain the same. Specifically because it makes more sense to me to set the value first, then the unit (left to right navigation).

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the train creation window
2. Reproduce the steps in description

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: stagin internal

### OSRD version (top right corner `Account` button > `Informations`)

1f27b88

**Comment by axrolld** [comment]
This bug seems to be sloved for some reason, even though the PR has not been merged 🤔

**Comment by clarani** [comment]
I agree, the bug seems to be solved :+1:
