### ISSUE TITLE
Improved indication of axis units in profile chart

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#6873]
For example, the units and values on the left-hand axis corresponding to the histogram are shown in blue, while the units and values on the right-hand axis corresponding to the curve are shown in orange.

![Image](https://github.com/osrd-project/osrd/assets/55697979/b4bd7103-f8e5-42f7-9bb2-f2531aa30fff)

**Comment by flomonster** [comment]
Won't do. We're waiting for the GEV revamp currently under design.
