### ISSUE TITLE
stdcm: in the speed chart, display the speeds the train would have with no allowance

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#6895]
### Who would benefit from this feature?

Both

### What is this feature about?

When core returns a successful stdcm response, only the actual train speeds are included. We could have a speed chat with as much information as in the standalone module.

### Why is this feature valuable?

It would be much easier to see at first glance where the engineering allowances are located. It's normally hard to tell and near impossible when the MRSP gets complex.

### Anything else people should know?

It would be easy to implement on the back-end side of things, but I don't know about the front-end side, I don't even know if there's anything to do there.

The train should not be duplicated in the space-time chart.

**Comment by eckter** [comment]
Could be made much easier if we implement https://github.com/OpenRailAssociation/osrd/issues/7653 first

**Comment by flomonster** [comment]
Maybe we should wait for the code refactor so that STDCM endpoint returns a train schedule.

**Comment by axrolld** [comment]
This is now part of https://github.com/osrd-project/osrd-confidential/issues/643.
Should we close this issue ?

**Comment by flomonster** [comment]
Duplicate
