### ISSUE TITLE
Impossible to save a new signal without changing the default side of the signal

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#6898]
### What happened?

When creating  a new signal, the side of the signal is set to left and it is not indicated as a mandatory property. However when we try to save we have : 

![Image](https://github.com/osrd-project/osrd/assets/55697979/ecac3fbe-d063-4869-90ab-a8aaf2c389c3)

### What did you expect to happen?

If the side is set by default, we should be able to save

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. Signals tool
3. Create a signal without changing the side
4. Save it 

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows
- **Env**: Recette

### OSRD version (top right corner `Account` button > `Informations`)

staging 75bf2e9

**Comment by Castavo** [comment]
Can't reproduce !
