### ISSUE TITLE
Projection of the space-time chart (GET) on a train fails 

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#6901]
### What happened?

I opened this scenario
https://osrd.dev.dgexsol.fr/operational-studies/projects/12/studies/12/scenarios/15

And tried to project the space-time chart on the "Dijon Paris" train.

I got the following response : 

```
{
    "status": 500,
    "type": "unknown_error",
    "context": {
        "url": "http://osrd-team-dev-core.osrd-team-dev.svc.cluster.local/project_signals",
        "message": "Couldn't find first chunk on the block path",
        "exception_type": "class java.lang.RuntimeException",
        "stack_trace": [
            "ScheduleMetadataExtractor.kt:530",
            "SignalProjection.kt:69",
            "SignalProjectionEndpoint.java:64",
            "FkRegex.java:153",
            "FkRegex.java:217",
            "FkChain.java:72",
            "TkFork.java:98",
            "TkFallback.java:84",
            "TkFallback.java:66",
            "TkWrap.java:58",
            "TkSlf4j.java:110",
            "BkBasic.java:123",
            "BkBasic.java:99",
            "BkSafe.java:46",
            "BkWrap.java:51",
            "BkParallel.java:81",
            "ThreadPoolExecutor.java:1136",
            "ThreadPoolExecutor.java:635",
            "Thread.java:840"
        ]
    },
    "message": "An unknown exception was thrown"
}
```

### What did you expect to happen?

I expected the projection to work

### How can we reproduce it (as minimally and precisely as possible)?

Go to the scenario in the description and try to project on the "Dijon Paris" train.

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

650963b

**Comment by bloussou** [comment]
tsv1 so not planned
