### ISSUE TITLE
Linesearch resets when clicking on the map in Itinerary

### ISSUE THREAD

**Issue by RomainValls** [OpenRailAssociation/osrd#6950]
### What happened?

In Itinerary, when you search for a line and select it, the line is highlighted on the map. 
After clicking anywhere on the map, the search resets and the line isn't highlighted anymore. 

### What did you expect to happen?

The search shouldn't reset and the line should stay highlighted. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a scenario, add a train.
In Itinerary, search for a line. 
Then, click anywhere on the map.
The search resets after adding one. 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Ventura v13.5
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

bff6e6c

**Comment by axrolld** [comment]
This is the wanted behavior, for any search, PR included. Clicking anywhere else de-selects the object. Before this objects remained highlighted until another object was searched, which wasn't great.

However drag & drop does not de-select the object.
