### ISSUE TITLE
`marginsAndPowerRestrictions` unintelligible warning message when changing path

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#6963]
### What happened?

I changed the path for my train while a margin was set, and got this warning message that is not clear at all, neither in english nor in french :
![image](https://github.com/osrd-project/osrd/assets/86296016/b2a7ff19-ddeb-4cfc-b0a2-0bd3b4c02cc1)

I assume it's telling me that my margins have been reset because the path has changed.

### What did you expect to happen?

I'm expecting the error message to be intelligible.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a train with margin
2. Edit it
3. Change its path
4. Notice the error message

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: stagin internal

### OSRD version (top right corner `Account` button > `Informations`)

36d0e3c

**Comment by clarani** [comment]
I can't reproduce this bug, can you ?

**Comment by axrolld** [comment]
Nope, closing this now.
