### ISSUE TITLE
Use Redux Thunk to persist any change on the Simulation Slice

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#697]

**Comment by alexandredamiron** [comment]
The solution is to write an thunk with redux-thunk which will recieve the projected new state, compute the diff, call respective api
a thunk is a function with recieve (dispatch, getState) as basis

so func in this style

function persistentUpdateSimulation(projectedSimulation) {
    return async function persistentUpdateSimulationParts(dispatch, getState) {
         // compute the diff with factorized funcs with projectedSimulation
         // do the rest logic
        // dispatch to updateSimulation
    }
}


.... instead of making dispatch(updateSimulation(simulation))
dispatch(persistentUpdateSimulation(simulation))

**Comment by alexandredamiron** [comment]
![diffToAPI](https://user-images.githubusercontent.com/765626/161006198-7cf54aaa-8fd5-4694-95b6-781407a2d03f.png)

**Comment by flomonster** [comment]
legacy
