### ISSUE TITLE
front: useless request are sent on the infra editor

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#6971]
### What happened?

When I move my mouse on the editor map, some api calls are sent to fetch the infra, the switch types and the errors

### What did you expect to happen?

No api calls

### How can we reproduce it (as minimally and precisely as possible)?

1. Open the network tab
2. Move your mouse on the editor map

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by sim51** [comment]
When using RTK `useLazyQuery`, the given `fetch` function is a RTK query that handles its traditional cache, so we need to unsubscribe to avoid useless queries

Moreover, if the infraID not doesn't change, we don't need to recall it.

I created a hook named `useInfra` (& `useCurrentInfra`) in the editor application, but perhaps its place should be inside the infra module.
