### ISSUE TITLE
Migration was not done for tests/data/rolling_stocks

### ISSUE THREAD

**Issue by aiAdrian** [OpenRailAssociation/osrd#6989]
### What happened?

Loading any JSON files from : https://github.com/osrd-project/osrd/tree/dev/tests/data/rolling_stocks doesn't work - ends up in error! 

..... /osrd$ ./scripts/load-railjson-rolling-stock.sh tests/data/rolling_stocks/short_fast_rolling_stock.json
Loading example rolling stock
Successfully copied 3.58kB to osrd-editoast:tmp/stock.json
2024-03-27T06:44:19.446503Z ERROR editoast: invalid type: string "G1", expected i16 at line 11 column 23

### What did you expect to happen?

The file have to be loaded when calling :  ./scripts/load-railjson-rolling-stock.sh 

### How can we reproduce it (as minimally and precisely as possible)?

**The JSON files in loading_gauge is 'G1' instead of integer value (e.g. 0)**

see : https://github.com/osrd-project/osrd/blob/dev/editoast/migrations/2024-03-18-141345_change_loading_gauge_to_smallint/up.sql

UPDATE rolling_stock
SET loading_gauge = CASE
        loading_gauge
        WHEN 'G1' THEN 0
        WHEN 'G2' THEN 1
        WHEN 'GA' THEN 2
        WHEN 'GB' THEN 3
        WHEN 'GB1' THEN 4
        WHEN 'GC' THEN 5
        WHEN 'FR3.3' THEN 6
        WHEN 'FR3.3/GB/G2' THEN 7
        WHEN 'GLOTT' THEN 8
    END;
     

**Next missing Meta data - metadata ** --> https://github.com/osrd-project/osrd/blob/ce982622116cbeff3d6b045b0d60eda4cdb6f2d8/editoast/src/schema/rolling_stock/mod.rs#L112
Example:
 metadata: {
    detail: 'BB 64700',
    family: 'LOCOMOTIVES',
    type: 'Locomotives thermiques',
    grouping: 'Locomotives diesel',
    series: 'BB 64700',
    subseries: '',
    unit: 'US',
    number: '1',
    reference: '',
  },

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

ce98262

**Comment by aiAdrian** [comment]
I strong suggest integrate ./scripts/load-railjson-rolling-stock.sh into aumated tests - this is key because there is for users testing OSRD no undertanding how it gets started => see getting started

**Comment by leovalais** [comment]
Thanks a lot for reporting this bug. We're currently fixing it.
The CI check is definitely a good idea, [we'll work on that as well](https://github.com/OpenRailAssociation/osrd/issues/7244).

**Comment by aiAdrian** [comment]
all contributions are welcome - OpenSource is when everyone works together - even if only by reporting a bug.
