### ISSUE TITLE
STDCM sheet: Creation of the data sheet using available data

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#6992]
### Description and goal

The aim is to obtain a clear STDCM path simulation sheet, with information on the RU, the path, the convoy, the simulation results and the path map.

### Acceptance Criteria

- [x] The document display takes advantage of the display surface on the railway undertakings' workstations.

- [x] The document is immediately identified as a route proposal to be checked, and not as a validated path.

- [x] An export button must be present in the case of a valid STDCM simulation. This button exports the simulation sheet as described in the model.

- [x] The simulation number must be generated with MMAA-XXX-XXX, with XXX randomly generated.

- [ ] Information not yet available (RU info, scheduled date, reason, conventional sign, towed equipment, ATE, path to be duplicated) is not required in this first implementation. => rolling stock information will be used instead of convoy information as long as the latter is not available

- [ ] The form complies with the attached template

[STDCM-2403-256-512.pdf](https://github.com/OpenRailAssociation/osrd/files/15167200/STDCM-2403-256-512.pdf)

**Comment by Tguisnet** [comment]
Use rolling stock information instead of "convoy" information
