### ISSUE TITLE
create a source extension for infra objects

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#6997]

**Comment by sim51** [comment]
Linked to

Ticket : 
- https://github.com/osrd-project/osrd-confidential/issues/384
- Enabler of https://github.com/osrd-project/osrd-confidential/issues/343

PR : 
- OSRD: https://github.com/OpenRailAssociation/osrd/pull/7249
- DAGS: https://github.com/osrd-project/osrd-dags/pull/273
