### ISSUE TITLE
back: add the missing information to the STDCM endpoint

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#7004]
## Description

Update STDCM endpoint to retrieve missing data that are required by STDCM sheet

## AC 
We must add those data to the editoast `/stdcm` endpoint :

- [ ] `max_speed` of the RollingStock
- [ ] `mass` of the RollingStock
- [ ] `reference` or `name` or `series` of the RollingStock ?
- [ ] `length` of the RollingStock
- [ ] List of `operational_points` through the path with their `ch` code

**Comment by Tguisnet** [comment]
Already present in the STDCM Endpoint (for the rolling stock information, the convoy information will come later)
