### ISSUE TITLE
Add interaction in STDCM UI v2

### ISSUE THREAD

**Issue by SarahBellaha** [OpenRailAssociation/osrd#7014]
### Description and goal

We need to add a toggle button, to switch between the two version of STDCM, and an interaction to move the user directly on the simulation results section after the simulation is completed

### Acceptance criteria

- [x] Toggle button added in the user settings
- [x] Automatic scroll at the end of the page, on the results section

**Comment by celine-sncf** [comment]
It will be done in another issue
