### ISSUE TITLE
Change TrainSchedule model for arrival on stop signal

### ISSUE THREAD

**Issue by woshilapin** [OpenRailAssociation/osrd#7042]
## Description and goal

Depends on OpenRailAssociation/osrd-website#188 

The arrival on stop signal must be configurable, and therefore, must appear in the TrainSchedule model. See the [design documentation](https://osrd.fr/en/docs/reference/design-docs/timetable/#modifiable-fields) for how it should be done.

## Acceptance criteria:

- [x] the model can take the instruction on a stop
- [x] the option (arrival on stop signal) should only be enabled on full stops, not route points (otherwise, request is rejected) #7272

**Comment by bougue-pe** [comment]
Done in https://github.com/OpenRailAssociation/osrd/pull/7322

**Comment by woshilapin** [comment]
Both frontend and backend seems to enforce a duration when `stop_signal` is checked. It's more difficult to actually test it on the backend (you would need to forge an HTTP request). Here is an example.

![Image](https://github.com/OpenRailAssociation/osrd/assets/2520723/efa4879b-46a1-4e50-b04a-7ebf14bcba53)
