### ISSUE TITLE
core: pathfinding: find the fastest path (instead of the shortest)

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#7058]
### Who would benefit from this feature?

EVERYBODY

### What is this feature about?

When running the pathfinding, we return the *shortest* path in terms of distance.

There are situations (possibly in *all* situations) where we would want to use the fastest path instead. 

### Why is this feature valuable?

The returned paths would generally make more sense because tracks are slower in their opposite direction, this would be closer to the paths that are actually used. It would also make the high-speed lines prevail (_e.g._ Paris-Rennes)

When importing timetables, lots of trains can't go fast enough to match their scheduled times, I suspect this is because we use slower (but shorter) paths. This change would fix some error cases.

### Anything else people should know?

The implementation itself should be mostly straightforward (tweak both the cost function and heuristic).

(note: this would just account for the MRSP and ignore the speedup / slowdown phases)

The heuristic would be a little less efficient.

**For proper route-specific speed limits**, requires https://github.com/OpenRailAssociation/osrd/issues/6784 to be implemented first

---

**There are things to refine and decide beforehand**. Mostly if and how we want to change the API. Do we just change the global pathfinding behavior, or would we add an extra parameter? (Changing the behavior globally would be *much* easier, but we need to make sure it doesn't have any unexpected side-effects)

**Comment by axrolld** [comment]
Pas eu le temps de m'en occuper 😞 
Je me désassign si un.e autre PO veut prendre le sujet pendant mes vacances.

**Comment by axrolld** [comment]
Discussed today:

Having the **fastest** as a **default** seems a good idea, and keeping the option to compute the shortest path too.

If we change the behavior it would be a good idea to implement it as an extra parameter for futher features.

**Comment by eckter** [comment]
We won't parametrize it for now, just change the behavior globally. If we want to add a flag later on, we can always change it
