### ISSUE TITLE
Impossible to add a specific waypoint

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#7064]
### What happened?

When we try to add Narbonne to the waypoints list it does not appear in the list.

https://github.com/osrd-project/osrd/assets/55697979/01daf06f-a72b-4cc5-a1d9-0bc937659381

### What did you expect to happen?

The list should be updated with the new via and a new path shoul be calculated. The new waypoint appears in the map.

### How can we reproduce it (as minimally and precisely as possible)?

See video

### What operating system, browser and environment are you using?

- **Browser**: ??
- **OS**: windows
- **Env**: int

### OSRD version (top right corner `Account` button > `Informations`)

v0.2.7 39f807b

**Comment by bloussou** [comment]
tsv1 won't fix
