### ISSUE TITLE
`Raise pantograph time` and `power recovery time` are not saved until an electric traction curve is created

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7091]
### What happened?

When creating a new rolling stock from scratch, i naturally filled all the fields from the first tab, then went over to the speed-effort curve tab.
When saving my rolling stock i got this error message even though i had set some values:
![image](https://github.com/osrd-project/osrd/assets/86296016/f2121e78-527e-4b06-bbf9-af92ec148344)

Actually what happens is that `raise pantograph time` and `power recovery time` are not saved until an electric traction curve is created.

### What did you expect to happen?

If i set a value in those fields i'm expecting them to be saved. Even if it doesn't really make sense to have some of those values for a diesel train it would be better than erasing them silentely when switching to the other tab in my opinion.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a rs from scratch
2. Set values in `raise pantograph time` and `power recovery time`
3. Switch to the speed-effort tab
4. Come back to the general features tab

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging internal

### OSRD version (top right corner `Account` button > `Informations`)

550477c

**Comment by Castavo** [comment]
Still relevant

**Comment by Castavo** [comment]
Can't reproduce
