### ISSUE TITLE
Assert error when placing start position at the beginning of the track

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#7092]
### What happened?
In STDCM request, if we try to insert a train starting from the beginning of a track an assertion error appears. 

If the train is between Djon and Macon, we have the same behavior when using the rocket button because it places the train at the beginning of the track.

![Image](https://github.com/osrd-project/osrd/assets/55697979/4fba64a4-dc21-404f-bec7-6cab683ae2d8)

### What did you expect to happen?
We should be able to insert the train into the timetable, even if the tail of the train is out of the existing path. 
We manage to performe running time calculation on the same path in time table creation mode. 

### How can we reproduce it (as minimally and precisely as possible)?

1.  Go to STDCM to try to insert a train between Djon and Macon in a timetable 
2.  Select the begin of the path to the begining of the track 37 at Dijon or by using the rocket
3.  Try to performe the calculation
4.  An assertion error appears 

### What operating system, browser and environment are you using?

- **Browser**: Microsoft Edge
- **OS**:  Windows 
- **Env**: recette

### OSRD version (top right corner `Account` button > `Informations`)
staging 550477c

**Comment by eckter** [comment]
More context: the error is in the spacing resource generator, when we instantiate the path that goes toward the buffer stop (i.e. a 0-length path). We can filter that out.
