### ISSUE TITLE
Train schedule result silently fails with specific paths

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#7179]
### What happened?

After a train has been created and added or modified, the simulation results remain empty (or are not updated).

No error is reported to the user, only a **502** error appears in the console `Failed to connect to host: Internal error: connector has been disconnected` for the `https://osrd.dev.dgexsol.fr/api/train_schedule/results/` endpoint.

Refresh page do the same

### What did you expect to happen?

Have an error message (at least) or functional trainschedule result.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a train, with a path between SG and MZL (no matter which rolling stock)
2. Click on "add a train"
3. See the success popup 
4. Close the view of train creation
5. No simulation result is seen, no fail popup

### What operating system, browser and environment are you using?

- **Browser**: Firefox 125.0b8
- **OS**: Archlinux latest
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

dev a42cad3

**Comment by flomonster** [comment]
This bug is related to train schedule v1.
