### ISSUE TITLE
Update the labels after the study creation FR and ENG

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#7270]
### What happened?

The field label in the form of study creation is not the same when the study is created 
![image](https://github.com/OpenRailAssociation/osrd/assets/17015973/2d8e289b-4c93-4285-80c4-7fa5c2fef6df)
![image](https://github.com/OpenRailAssociation/osrd/assets/17015973/01e5d5b6-ab74-43cc-bd1e-92b19dfb5d03)

### What did you expect to happen?

The same label is displayed in both the form and the study details
In the study détails we should have : 

- **Service code** instead of **GEREMI CODE**
- **Business code** instead of **AFFAIR CODE**
- **Real ending** instead of **REAL END**

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to an Project
2. Click on "Create a study"
3. Set the fields Name , Service code, Business code and Real ending
4. Click on create the study

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

1482e8c

**Comment by Castavo** [comment]
Still relevant
