### ISSUE TITLE
Many zeros after setting the initial velocity in a scenario

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#7271]
### What happened?

The value setted for the field inital velocity has many zeros
![image](https://github.com/OpenRailAssociation/osrd/assets/17015973/16b28a31-0d6e-4995-99fe-2b0bf0b660c0)

### What did you expect to happen?

Round the value at 0.1 km/h

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Click sur "Add"
3. Select a rolling stock and set the Route
4. Set a name for the train
5. Set the value of "initial velocity" field to 120
6. Click on "Add one or several trains"
7. Click on "Go back to simulation results"
8. Click on "Edit" for the added train and observe the field "initial velocity"

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: Rec

### OSRD version (top right corner `Account` button > `Informations`)

b0b88cf

**Comment by clarani** [comment]
Validated ✅
