### ISSUE TITLE
stdcm : wrong suggested waypoints

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#7292]
### What happened?

When we have a result for stdcm, all waypoints are set to "true".

### What did you expect to happen?

Waypoints should be set to true only if the waypoints came from the user.

### How can we reproduce it (as minimally and precisely as possible)?

Use STDCM request (on a large path to have some waypoint), and observe the response.

### What operating system, browser and environment are you using?

- **Browser**: Firefox v110
- **OS**: Nixos v22.11
- **Env**: DevDGEX

### OSRD version (top right corner `Account` button > `Informations`)

dev da749b8

**Comment by Castavo** [comment]
@Tguisnet there is no path in stdcm output, is this correctly formulated ?

**Comment by axrolld** [comment]
I don't really understand this bug : are all the waypoints displayed as "principal" in the results ?

**Comment by Tguisnet** [comment]
It's "fix"
Its happens with the previous simulation sheet, where all the waypoints were marked as stops.
It was not a bug front, my issue was badly written, the response to observe is the response from the backend.
I close this because it seems fix with the actual simulation sheet.
