### ISSUE TITLE
Solution not found in STDCM even if possible

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#7316]
### What happened?

STDCM does not find the solution in the created timetable even if it is possible. 
![image](https://github.com/OpenRailAssociation/osrd/assets/55697979/fe7a8da4-1867-4cbc-935a-1a16f88c3cdc)
An assert is displayed : 
![image](https://github.com/OpenRailAssociation/osrd/assets/55697979/fb5613a7-109d-4db2-96ec-e752b34ccc46)

### What did you expect to happen?

find a solution between 8:00 and 8:30

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM
2. Select the scenarios  https://rec-osrd.reseau.sncf.fr/operational-studies/projects/14/studies/38/scenarios/140
3. Search a path between Lyon Part Dieu et Miramas between 8:00 and 10:00

### What operating system, browser and environment are you using?

- **Browser**: Microsoft Edge
- **OS**: Windows
- **Env**: Recette

### OSRD version (top right corner `Account` button > `Informations`)

staging 11da135

**Comment by Erashin** [comment]
Seen with @bloussou. Cannot reproduce (study/scenario doesn't exist) and error does not exist anymore in core.
