### ISSUE TITLE
Scroll down on the editor page

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#7317]
### What happened?

When we select an locked infra, we should not be able to scroll down on the editor main page. On some screens and if we select the tiny infra, we can even see a small 0 at the bottom of the page.
We should also check the html of the page and look for some 0.
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/8aeda433-642f-4b98-9fda-f96782cdf584)

### What did you expect to happen?

- [ ] no scroll on the editor main page

### How can we reproduce it (as minimally and precisely as possible)?

1. Select a locked infra
2. Scroll on the page

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

staging 11da135

**Comment by louisgreiner** [comment]
![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/12362f51-8868-46c9-98fa-dcd50bb39d78)

Firefox v115
Windows 11
osrd.dev.dgexsol

On dev 6b648d8

**Comment by clarani** [comment]
Problem solved ✅

**Comment by maelysLeratRosso** [comment]
Still here on staging internal
Resolution :  

![image](https://github.com/user-attachments/assets/afb1fa99-8d8b-426c-baf2-51e6f54cacf3)


![image](https://github.com/user-attachments/assets/67cdbd49-a831-4ba3-a4ef-f389f1bfcffb)

**Comment by clarani** [comment]
Validated ✅
