### ISSUE TITLE
front: crash when hitting the user settings

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#7318]
### What happened?

When hitting the user settings button on Home page or Rolling stock editor page, the app crashes

### What did you expect to happen?

No crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Home
2. Click on user settings

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev 11da135

**Comment by louisgreiner** [comment]
![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/98818034-8130-478e-ba98-965fe7bcdb9d)

**Comment by emersion** [comment]
The settings button is now disabled on the Home page. The crash can still be triggered from the rolling stock editor. Should we gray out the settings in the rolling stock editor as well? Or, would it make sense to wrap `HomeRollingStockEditor` with `OsrdContextLayout` (I'm guessing it doesn't)?

Seems like `OsrdContext` is used for `updateScenarioID()`, `updateTimetableID()` and `updateInfraID()`, I'm guessing we could probably skip these if we are in the homepage or in the rolling stock editor?

One way to resolve this would be to add a way to grab these helpers without throwing an error when `OsrdContext` is unavailable, or wrap into a try/catch, or add a helper function to check whether `OsrdContext` is available.

**Comment by clarani** [comment]
Yes, agree.

Another solution would be to retrieve directly the actions to reset the scenario, the timetable and the infra in the store (for both stdcm and operationalStudies), without using useOsrdConfActions.

**Comment by emersion** [comment]
Yeah, would work too… That would require exporting `osrdContext` (note the lower-case first letter) to be able to `useContext(osrdContext)` from `UserSettings`.
