### ISSUE TITLE
TS2: Add editoast stdcm endpoint

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#7333]
## Description

Implementation of the `POST` `/v2/timetable/{timetable_id}/stdcm?infra=X` endpoint.

## AC

- Uses the existing core endpoint
- Uses the same input and output
- Uses timetable V2

**Comment by Tguisnet** [comment]
duplicat of https://github.com/OpenRailAssociation/osrd/issues/7346
