### ISSUE TITLE
Collection of dead sections causing Simulation Errors

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7359]
### What happened?

Errors caused by stops between dead sections announcements and exe:

SAG – VRB 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/d12eb24e-41d2-4f11-83cc-0032ae911470)

LWA – LGK 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/e186dfad-9a4b-44c2-a7f5-60826c847128) 

RUX – BIA 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/e66cc8d5-b351-4904-a8c9-192734c67315)

DEE- SNG 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/0f0472f0-4734-4b23-9cb0-a638838770e1)

**Comment by axrolld** [comment]
# Other errors caused by dead sections

## PPO – SMA 

No error with PPO SMA 
Error with MSC PPO SMA with a stop in PPO. 

Cause : pantograph raise time converted into distance for the effective resumption of traction: 650m. 
The La Pomme operational point (PPO) is located in this zone. 

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/7b3036fd-d8d1-4dc9-9b24-2feec748d409)


## SOS – LEG 

Error with SOS LEG 

Error with PCL SOS LEG with or without stop  SOS 

Cause: panto raise time converted into distance potentially too long  
OR wrong speed limit on this zone (40km/h) which means that the train loses too much speed.

Overall BP/CC on a 40km/h zone, so if we are too pejorative the train stops.

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/8d69e24c-fa74-4b91-aee8-1c2eb513cd5a)

## ??? VCV 

??? = Nîmes Pont du Gard (no trigramm) 

No error on ??? VCV 

Error on MHV ??? VCV if stopped at ??? 

Cause :  
panto raising time converted into distance too long (for BPCC before station) 
And potentially 2nd error afterwards: BP warning sign just before the station 
 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/fddfed73-d7e8-41b7-82bb-62e0682bf81a)


## SQF SPR 

No error on SQF SPR 

Error if VEI SQF SPR with stop on SQF 

Cause: fork between the announcement sign and the exe sign: the train sees the announcement sign then changes track before exe, and therefore does not catch the BP. The running calculation considers that it has caught a small part of the PO. 

 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/d833930d-f205-4b27-8090-9dc026d44a3e)


## SGO QUX 

No error on SGO QUX 

Error if VVN SGO QUX with stop on SGO 

Cause: Stopped just after the BP zone, i.e. during the extension of the pan up time. 

 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/d9897b68-6395-44a6-bc13-b84d19ac91a3)


## DNV – SVI 

No error on DNV SVI 

Error on BN DNV SVI if stopped on DNV 

Cause: stop just after the REV sign, therefore potentially within the 5s of power recovery transformed into distance. 

 
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/cdd10576-6c07-49a4-9b65-081cf05c9bd9)


## STE FRN 

No error on STE FRN 

Error on AGD STE FRN if stopped on STE 

Cause: STE located just behind two BPs. 

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/fefc8f32-811d-4f11-ac3c-a0294f59d051)


## DEL – DEL 

Error between Delle (BV) and Delle (XS) 

Cause: DEL (BV) is in the middle of a BP zone. 

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/91c50f42-1fba-4712-b4cc-7cdc28d4d7bc)

**Comment by axrolld** [comment]
Fix suggestion :
- shut down traction at exe
- retreive traction 20m after the end of the zone

**Comment by bloussou** [comment]
We should even drop the 20m as it won't changed the simulated time and add a useless complexity. As said yesterday in a meeting it has probably no impact.

**Comment by multun** [comment]
Fixed by #7413
