### ISSUE TITLE
Failed to invert matrix while modifying a route

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#7361]
### What happened?

Working on a merged France+Germany infrastructure, I tried to link in the editor tool a route that starts in France and another one in Germany

![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/bb0068b2-26b8-4509-9d5e-3b7c7c6592ce)

### How can we reproduce it (as minimally and precisely as possible)?

I cannot reproduce it, but I think it is mainly due to the big size of the infrastructure edited

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Windows 11
- **Env**: Local, up to date with dev

### OSRD version (top right corner `Account` button > `Informations`)

can't see because of https://github.com/OpenRailAssociation/osrd/issues/7318

**Comment by louisgreiner** [comment]
Happened once more, right after using the magic wand after deleting tracks and detectors linked to routes

![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/eb892610-d739-4c86-99bb-e8b3050e3b57)

And even after using the magic wand (so it crashed), some errors remain : 

![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/a160bfa8-479e-444a-8d10-e5b9240f0752)

**Comment by maelysLeratRosso** [comment]
cannot reproduce
