### ISSUE TITLE
Pathfinding triggers "on coord must be GeoJSON Point or an Array of numbers"

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#7363]
### What happened?

![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/06e229ba-02b8-4bfa-9b9a-c830538a6284)

On a custom infrastructure : [link to the railjson](https://sncf.sharepoint.com/:u:/r/sites/OSRD644GrpO365/Documents%20partages/Donn%C3%A9es/0-OSRD%20Dumps/Raw%20Infra/%5Binfra%20for%20issue%20%237363%20(GeoJson)%5D%20France_Germany.zip?csf=1&web=1&e=TIVbkf).

When trying to select begin (in France) and end of a path (in Germany) in operationnal studies panel,

### How can we reproduce it (as minimally and precisely as possible)?

1. import infra from above link
2. create a scenario on this infra
3. try create a path around Saarbrücken (North East of France, on the german border side) from a start in France on track `636d9144-6667-11e3-81ff-01f464e0362d` to an end in Germany on track `111536933-0` or further

Something like that (but select a different track, on which path can not be found) : 
![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/e819c5ce-74a0-4666-8426-07f2cb0a3623)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Windows 11
- **Env**: Local, up to date with dev

### OSRD version (top right corner `Account` button > `Informations`)

can't see because of #7318

**Comment by sim51** [comment]
I had the same issue today.
In my case (and I think it's the same for you), it's due to the `nearestPointOnLine` which allows `Line` but not `MultiLines`.
