### ISSUE TITLE
Simulation fails even though pathfinding is successful

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#7410]
### What happened?

On a [custom infrastructure (France+Germany)](https://sncf.sharepoint.com/:u:/r/sites/OSRD644GrpO365/Documents%20partages/Donn%C3%A9es/0-OSRD%20Dumps/%5Binfra%20for%20issue%20%237409%20and%20%237410%5D%20FR+DE_3.id9.railjson.zip?csf=1&web=1&e=24UhXE), when trying to add a train in operational studies, the simulation fails without a clear error message :

`Assertion échouée à ScheduleMetadataExtractor.kt:60: Assertion failed`

The issue can be reproduce at many many places in Germany, it seems that the above infrastructure has created routes on signal that should be turned on the other direction of the track.

![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/a4caab17-a482-4867-b4d2-f36cb06214eb)

### What did you expect to happen?

Not fail, or at least explicit the error message

### How can we reproduce it (as minimally and precisely as possible)?

1. Load above infra
2. Create a train from Kaiserlautern to Landstuhl (see above screenshot) (note that the trains in Germany have to be set on the track on the right of a line)
3. Add train and notice bug

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Windows 11
- **Env**: Local, up to date with dev

### OSRD version (top right corner `Account` button > `Informations`)

OSRD version field is empty

**Comment by flomonster** [comment]
Can´t use this infra anymore (legacy format). We did a lot of bug fixes on this so it's probably fixed.
