### ISSUE TITLE
core: linear margin: Fail to import train because of discontinuity in the search space

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#7426]
### What happened?

|Train number|Path|Allowance (linear)|RollingStock|
|--------------|--|--------------------|------------|
|9826|LEW MPL|1800s|1TVDUPL|
|5354|LPR NS|1800s|1TVDUPL|
|4758|MSC BX|3600s|22200BM|
|17702| | | |
|4502| | | |
|7834| | | |
|9866| | | |
|9736| | | |
|814322| | | |
|4661| | | |
|4504| | | |
|4306| | | |

### What did you expect to happen?

above trains to be simulated

⚠️ Ok with mareco margins ⚠️ 

### How can we reproduce it (as minimally and precisely as possible)?

use informations in the table to reproduce

### What operating system, browser and environment are you using?

- latest dump from @shenriotpro 

### OSRD version (top right corner `Account` button > `Informations`)

21906b8

**Comment by bloussou** [comment]
REopening as it introduces a lot of new 
```
"130737": {
    "SimulationError": {
      "cause": {
        "message": "Core error 500: error sending request for url (http://osrd-core:8080/standalone_simulation)",
        "status": 500,
        "type": "editoast:coreclient:GenericCoreError"
      }
    }
  }
```

**Comment by Maymanaf** [comment]
Recette QA : 17/05
Test : OK pour les 3 exemples 

- Ticket bloqué en raison de la présence de régressions lors de l'importation d'autres trains.

**Comment by eckter** [comment]
Closing: the new bug was unrelated, and is now fixed by https://github.com/OpenRailAssociation/osrd/pull/7466
