### ISSUE TITLE
front: on the signal editor, side is filled but marked as missing

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#7445]
### What happened?

When trying to create a signal, the side select is filled, but when I click on save, the form is invalid because side is apparently missing
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/5b804103-e89c-4a88-9586-eabe37a035fe)

### What did you expect to happen?

Side should no be missing: either initialize it to LEFT or do not fill the select by default

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor and select an infra
2. Click on the signal tool
3. Fill the form without modifying the side input
4. Click on save

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev c231679

**Comment by emersion** [comment]
Seems to be an issue in react-jsonschema-form: the JSON schema has a default set to CENTER, but this isn't reflected in the `<select>`, and the `fromData` passed to `onChange` in `EditorForm` is missing the prop. Marking `side` as required in the JSON schema doesn't help (results in a form validation error rather than a server error).

**Comment by emersion** [comment]
I believe this is the upstream bug: https://github.com/rjsf-team/react-jsonschema-form/issues/3599

Minimal reproducer with the playground: https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ2YWx1ZXNJbkZvcm1EYXRhIjp7InNpZGUiOiJSSUdIVCIsImV4dGVuc2lvbnMiOnsic2lkZSI6IlJJR0hUIn19LCJub1ZhbHVlc0luRm9ybURhdGEiOnsiZXh0ZW5zaW9ucyI6e319fSwic2NoZW1hIjp7InRpdGxlIjoiU2NoZW1hIGRlZmF1bHQgcHJvcGVydGllcyIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InZhbHVlc0luRm9ybURhdGEiOnsidGl0bGUiOiJWYWx1ZXMgaW4gZm9ybSBkYXRhIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvZGVmYXVsdHNFeGFtcGxlIn0sIm5vVmFsdWVzSW5Gb3JtRGF0YSI6eyJ0aXRsZSI6Ik5vIHZhbHVlcyBpbiBmb3JtIGRhdGEiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9kZWZhdWx0c0V4YW1wbGUifX0sImRlZmluaXRpb25zIjp7ImRlZmF1bHRzRXhhbXBsZSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJleHRlbnNpb25zIjp7ImFsbE9mIjpbeyIkcmVmIjoiIy9kZWZpbml0aW9ucy9FeHRlbnNpb24ifV19LCJzaWRlIjp7InRpdGxlIjoiRGlyZWN0IHNpZGUiLCJhbGxPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvU2lkZSJ9XSwiZGVmYXVsdCI6IkNFTlRFUiJ9fX0sIkV4dGVuc2lvbiI6eyJwcm9wZXJ0aWVzIjp7InNpZGUiOnsiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL1NpZGUifV0sImRlZmF1bHQiOiJDRU5URVIiLCJ0aXRsZSI6IkV4dGVuZGVkIHNpZGUifX0sInR5cGUiOiJvYmplY3QifSwiU2lkZSI6eyJlbnVtIjpbIkxFRlQiLCJSSUdIVCIsIkNFTlRFUiJdLCJ0eXBlIjoic3RyaW5nIn19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6eyJwb3B1bGF0ZSI6InBvcHVsYXRlIiwibWVyZ2VFeHRyYURlZmF1bHRzIjpmYWxzZX0sImFsbE9mIjoic2tpcERlZmF1bHRzIiwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==
