### ISSUE TITLE
front: adapt simulation results v2

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#7484]
Refers to #7023 

### Description and goal

Adapt simulation results with the new train schedule v2 endpoints

### Acceptance criteria

- [x] when a train in the timetable is selected, we can see its simulation results
- [x] the time buttons at the top of the page is still visible and dynamic
- [x] the space time chart is still visible with all timetable trains according the projected train
- [ ] for trains running in 2 days, we should display the new date in the time axe at midnight in the space time chart
- [ ] we can still move a train on the space time chart
- [x] the speed space chart, space curves slopes chart, the driver train schedule table and the map are still visible depending on the selected train
- [x] we can still toggle the same settings in the speed space chart
- [x] the driver train schedule should use the new time and stops interface ?
- [ ] there is still a cursor synchronizer when hovering any chart in the simulation

**Comment by bgiuliana** [comment]
This issue is still open to fix some bugs (link the bugs here)
