### ISSUE TITLE
Error "Given index doesn't exist" occurs when updating the Start and End fields for Power restriction.

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#7496]
### What happened?

When modifying the default value of the field "Start," the value is reset, and upon repeating the action, the app crashes
![image](https://github.com/OpenRailAssociation/osrd/assets/17015973/dbf317cf-b31e-4bcf-991a-0946569fc8f7)

The erreur 
![image](https://github.com/OpenRailAssociation/osrd/assets/17015973/a4ef32f5-c474-410c-875b-9bd8c542564d)

### What did you expect to happen?

The field value has been successfully modified

### How can we reproduce it (as minimally and precisely as possible)?

1. Modify a train in a scenario for operational studies.
2. Go to the tab "Simulation Settings."
3. Select an interval for Power restriction.
4. Modify the value of the field labeled "Start."
5. Modify the value of the field again.

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows
- **Env**: staging.dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

3f7ff32

**Comment by Akctarus** [comment]
I can't reproduce it, I think it's already been corrected

**Comment by Castavo** [comment]
Can't reproduce either (though there are other bugs)
