### ISSUE TITLE
Neutral sections cannot be selected in the infrastructure editor

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#7497]
### What happened?

When I want to select a neutral section in the infrastructure editor, the over never loads : 
![image](https://github.com/OpenRailAssociation/osrd/assets/156183612/1d05cb88-2cd7-4536-92f8-dae157cf239c)

Then I cannot select the neutral section.

### What did you expect to happen?

I expected the over to show the information about the neutral section, and to be able to select it.

### How can we reproduce it (as minimally and precisely as possible)?

As above

### What operating system, browser and environment are you using?

- **Browser**:  Chrome
- **OS**: W11
- **Env**: Staging dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

3f7ff32

**Comment by Castavo** [comment]
Can't reproduce
