### ISSUE TITLE
front: wrong label size for STDCM margins

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#7498]
### What happened?

The margin's label should be wider to display in one line
![image](https://github.com/OpenRailAssociation/osrd/assets/6003856/8fabf9cc-4d96-4783-bfb4-ddffb4db5c09)

### OSRD version (top right corner `Account` button > `Informations`)

staging 3f7ff32

**Comment by Castavo** [comment]
Can't reproduce since interface was overhauled
