### ISSUE TITLE
Trainschedule simulation summary endpoint returns data of only one train

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#7516]
### What happened?

In a scenario timetable, if there are trains with various paths, the endpoint returns information of only one of them : 

<img width="337" alt="Capture d’écran 2024-05-26 à 22 03 16" src="https://github.com/OpenRailAssociation/osrd/assets/113104137/ae8c3511-1ee5-4e46-bf6b-581aae21b482">

### What did you expect to happen?

Each train should have its own informations in the endpoint response.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Add at least 2 trains with different paths
3. Open the train details by clicking on the eye icon at the top and look at the infos

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: macOS Sonoma 14.5
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 4b0f2d6

**Comment by younesschrifi** [comment]
Fixed
