### ISSUE TITLE
Adding a via when setting a train itinerary doesn't update its schedules

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#7517]
### What happened?

In a scenario, when adding vias by clicking on map, by the suggested vias modal, or via the rocket, it doesn't update the schedule property of the train. On the example below, the St Malo trains have 2 vias each so it should show at least 2 steps in the details (3 if we count the destination ? Ask a PO for that).

<img width="471" alt="Capture d’écran 2024-05-26 à 22 25 45" src="https://github.com/OpenRailAssociation/osrd/assets/113104137/bea82315-38aa-40d4-bd8d-5c131b9b128b">

### What did you expect to happen?

Even if we can't set any duration with this features, it should update the train `schedule` property by setting the `duration` property at null in the PathStep store. This will result to a valid information of the steps in the timetable when opening the train details.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Add a train with at least 1 or 2 vias
3. Open the train details by clicking on the eye icon at the top and see that it still shows 1 step.

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: macOS Sonoma 14.5
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 4b0f2d6

**Comment by SharglutDev** [comment]
Might be fixed by #7427

**Comment by axrolld** [comment]
Vias without proper stop shouldn't increase the stop counter, however the counter isn't right with TSV2. If a stop is added, the destination isn't considered as a stop anymore.
Hence :
- If no stop is specified : 1 stop displayed (the destination)
- If n stop(s) is/are specified (n >= 1): n stop displayed (destination excluded) 

Destination should always be taken into account when counting stops.
