### ISSUE TITLE
TSv2: When adding a train, the space time chart is created but remains empty

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#7590]
### What happened?

![image](https://github.com/OpenRailAssociation/osrd/assets/113104137/526b6fe6-b42a-4f93-abf0-548093dd55ff)

The only way to display the chart is to press on the left button on the cart (the one to resize on trains)

### What did you expect to happen?

The chart should be displayed when adding a train or opening a scenario.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario with trains and see the empty chart
2. or Go to an empty scenario, add a train and see the empty chart

### What operating system, browser and environment are you using?

- **Browser**: Firefox v116
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 625d185

**Comment by achrafmohye** [comment]
The issue seems to be resolved, likely due to the refactoring done by @SharglutDev. I will close the ticket for now.
