### ISSUE TITLE
Electrification wrong display (1500VV...)

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#7594]
### What happened?

In operational studies panel, when choosing a rolling stock, the electrifical profile of the RS displays 2 times "V"

![image](https://github.com/OpenRailAssociation/osrd/assets/57864277/4c2ae82f-5748-482f-b589-0521df49cf0b)

### What did you expect to happen?

Display "1500V" instead of "1500VV"

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce on dev
1. Open a scenario
2. Open RS selector
3. Notice bug

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev 625d185

**Comment by bougue-pe** [comment]
Probably relates to previous work : https://github.com/osrd-project/osrd-dags/issues/135
