### ISSUE TITLE
Error STDCM simulation : error trying to connect: tcp connect error: Connection refused (os error 111)

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#7595]
### What happened?

I tried to simulate a train with the following inputs : 
- DN MAS
- 27000UM
- 4.5min/100km
- ME100

I received the following error 

```
{
    "status": 500,
    "type": "editoast:coreclient:GenericCoreError",
    "context": {
        "url": "http://osrd-team-dev-core.osrd-team-dev.svc.cluster.local/stdcm",
        "raw\_error": "error sending request for url (http://osrd-team-dev-core.osrd-team-dev.svc.cluster.local/stdcm): error trying to connect: tcp connect error: Connection refused (os error 111)",
        "status": null
    },
    "message": "Core error 500: error sending request for url (http://osrd-team-dev-core.osrd-team-dev.svc.cluster.local/stdcm): error trying to connect: tcp connect error: Connection refused (os error 111)"
}
```

### What did you expect to happen?

I expected the simulation to succeed

### How can we reproduce it (as minimally and precisely as possible)?

As above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: Staging internal

### OSRD version (top right corner `Account` button > `Informations`)

9417f7a

**Comment by younesschrifi** [comment]
After investigating, I noticed that core was shut down at the time of this error. 
Locally, the request work (waiting for the fix that will be merge in this PR)
We need to give core a bit more ram (in progress)

**Comment by younesschrifi** [comment]
Fixed by increasing Core RAM.
