### ISSUE TITLE
Signal search in cartography doesn't work

### ISSUE THREAD

**Issue by Morgane-SJK** [OpenRailAssociation/osrd#7605]
### What happened?

I want to research a Signal but the search doesn't work -> no results
- the search with Line doesn't work (whereas it's working with the main Line search)
- the search with Signal doesn't work

![image](https://github.com/OpenRailAssociation/osrd/assets/95025398/c0952e32-7f84-42f1-ab68-838e3b765317)
![image](https://github.com/OpenRailAssociation/osrd/assets/95025398/47a43b13-b2ee-4dcf-aefc-45f18ebdd1ba)

## Whereas search with main Line search is working : 
![image](https://github.com/OpenRailAssociation/osrd/assets/95025398/95bc127c-b3e5-41fe-93cb-2ef3fb91d953)

### What did you expect to happen?

There should be some suggestions of lines and signals

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Cartographie
2. Click on Rechercher 
3. Click on Signal
4. Tap something in the Line or Signal input field

### What operating system, browser and environment are you using?

- **Browser**: Chrome version 124.0.6367.202
- **OS**: Windows
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

staging 625d185

**Comment by emersion** [comment]
At first glance seems to be an editoast bug, the query (below) returns an empty array.

```json
{"object":"signal","query":["and",["=",["infra_id"],1],true,true,true,["search",["label"],"S"]]}
```

**Comment by emersion** [comment]
Even with a query which accepts all signals:

```json
{"dry":false,"object":"signal","query":true}
```

the server always returns zero results. The generated SQL:

```sql
WITH _RESULT AS (
            SELECT (sig.infra_id) AS "infra_id", (sig.data->'extensions'->'sncf'->>'label') AS "label", (search_signal.signaling_systems) AS "signaling_systems", (search_signal.settings) AS "settings", (search_signal.line_code) AS "line_code", (track_section.data->'extensions'->'sncf'->>'line_name') AS "line_name", (ST_AsGeoJSON(ST_Transform(lay.geographic, 4326))::json) AS "geographic", (search_signal.sprite_signaling_system) AS "sprite_signaling_system", (search_signal.sprite) AS "sprite"
            FROM search_signal
            
        INNER JOIN infra_object_signal AS sig ON sig.id = search_signal.id
        INNER JOIN infra_object_track_section AS track_section ON track_section.obj_id = sig.data->>'track' AND track_section.infra_id = sig.infra_id
        INNER JOIN infra_layer_signal AS lay ON lay.infra_id = sig.infra_id AND lay.obj_id = sig.obj_id
            WHERE TRUE
            LIMIT 25 OFFSET 0
        )
        SELECT to_jsonb(_RESULT) AS result
        FROM _RESULT -- binds: []
```

**Comment by emersion** [comment]
Seems like the `search_signal` table is empty. Looks like a `search_signal__ins_trig_fun` trigger bug, inserting a new row into `infra_object_signal` doesn't reflect the change in `search_signal`.

**Comment by emersion** [comment]
More findings: indeed this is a `search_signal__ins_trig_fun` trigger bug: the trigger performs an `INNER JOIN infra_layer_signal`, dropping it from the trigger makes things work again. I'm guessing the insert on `infra_object_signal` happens before the insert on `infra_layer_signal`.

For reference, the full trigger:

```sql
CREATE OR REPLACE FUNCTION search_signal__ins_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "search_signal" (id, label, line_name, infra_id, obj_id, signaling_systems, settings, line_code, sprite_signaling_system, sprite)
        SELECT "infra_object_signal".id AS id, osrd_prepare_for_search(infra_object_signal.data->'extensions'->'sncf'->>'label') AS label,
    osrd_prepare_for_search(track_section.data->'extensions'->'sncf'->>'line_name') AS line_name,
    (infra_object_signal.infra_id) AS infra_id,
    (infra_object_signal.obj_id) AS obj_id,
    (ARRAY(SELECT jsonb_path_query(infra_object_signal.data, '$.logical_signals[*].signaling_system')->>0)) AS signaling_systems,
    (ARRAY(SELECT jsonb_path_query(infra_object_signal.data, '$.logical_signals[*].settings.keyvalue().key')->>0)) AS settings,
    ((track_section.data->'extensions'->'sncf'->>'line_code')::integer) AS line_code,
    (layer.signaling_system) AS sprite_signaling_system,
    (layer.sprite) AS sprite
        FROM (SELECT NEW.*) AS "infra_object_signal"
        
            INNER JOIN infra_object_track_section AS track_section
            ON track_section.infra_id = infra_object_signal.infra_id
                AND track_section.obj_id = infra_object_signal.data->>'track'
            INNER JOIN infra_layer_signal AS layer
            ON layer.infra_id = infra_object_signal.infra_id
                AND layer.obj_id = infra_object_signal.obj_id;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_signal__ins_trig
AFTER INSERT ON "infra_object_signal"
FOR EACH ROW EXECUTE FUNCTION search_signal__ins_trig_fun();
```
