### ISSUE TITLE
`Discontinuity in the search space` when looking for a STDCM between Vienne and Valence

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7612]
### What happened?

This :
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/e8b8e3ea-a66e-480f-984e-2f8ceb308a95)

### What did you expect to happen?

I'm expecting the computation to work between those two cities.

### How can we reproduce it (as minimally and precisely as possible)?

1. Fill in the form as it is on the screenshot

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

cb12000

**Comment by axrolld** [comment]
On former STDCM interface and with another scenrio, i got a `No path could be found` error:

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/c22bce92-0c64-4886-82b0-e26fd73244f5)

**Comment by axrolld** [comment]
The running time calculation between VIE and VCE doesn't work on TSV2 (assert fail but i can't get more details) but works fine on TSV1 🤔

**Comment by eckter** [comment]
I'll have a look this afternoon

Side-note,

> assert fail but i can't get more details

You can get a lot more details by pressing F12 and checking the request result. I thought I made a fix to display the details in the front-end, but apparently not
