### ISSUE TITLE
Add data sources and licenses 

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#7621]
### Who would benefit from this feature?

End users

### What is this feature about?

Add a section in "About" crediting the authors and sources of open data used and the licenses of use.
- Terrain https://registry.opendata.aws/terrain-tiles/
- IGN https://geoservices.ign.fr/services-web-experts-ortho
- Train pictures http://www.mlgtraffic.net/index_fr.html 
- Open data SNCF for train import 

### Why is this feature valuable?

Open source good practice & respecting regulations

### Anything else people should know?

... has to be taken into account

**Comment by louisgreiner** [comment]
Validated but opened a bug about this : https://github.com/OpenRailAssociation/osrd/issues/9010
