### ISSUE TITLE
Wrong space-time chart display when zooming in/out

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#7643]
### What happened?

The selected train moves when I zoom in/out

https://github.com/OpenRailAssociation/osrd/assets/62556370/c24f13f8-13c1-43ef-9ebc-0a2b314d87e3

### What did you expect to happen?

Zooming does not impact the trains display on the space time chart

### How can we reproduce it (as minimally and precisely as possible)?

Create two trains. Move one of them to create a conflict. Zoom in or out.

### What operating system, browser and environment are you using?

- **Browser**: google chrome
- **OS**: windows 10
- **Env**: osrd.dev.dgexsol.fr

### OSRD version (top right corner `Account` button > `Informations`)

ba931aa

**Comment by flomonster** [comment]
Can't reproduce with the new space-time chart
