### ISSUE TITLE
No result charts after importing trains (tsv2) from open data

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7654]
### What happened?

I imported train from open data, they are in the list but i have no charts to analyse the results.
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/db6d029b-07ea-4770-8bac-eebe51f6278f)

### What did you expect to happen?

I'm expecting all the usual charts and results.

### How can we reproduce it (as minimally and precisely as possible)?

1. Select TSV2
2. Create a scenario on France locked
3. Import trains between Lyon Part Dieu and Marseille Saint Charles
4. Delete all invalid trains
5. Try to get the results

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

b9c43e4

**Comment by axrolld** [comment]
It appears that the results are displayed after refreshing the page.
But the bug remains IMO

**Comment by clarani** [comment]
Not relevant anymore, the bug is solved ✅
