### ISSUE TITLE
core: return wrong electrifications on path (trainSchedule v1)

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#7655]
### What happened?

The electrification seems not correct, see image below. The first part of the path in not electrified, however in the backend response, the 25000 electrification starts at 0
![image](https://github.com/OpenRailAssociation/osrd/assets/45000526/1e42bd66-0505-4c47-8c2d-6da3758a67c7)

### What did you expect to happen?

The electrification should be correct and nothing should be returned for portions of path where there is no electrification

### How can we reproduce it (as minimally and precisely as possible)?

1. Add a train with a B81500 bimode and a BEH - SAD path with rocket

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by Castavo** [comment]
In the picture you added, the non-electrified part seems to be near the end of the path rather than its beginning.

**Comment by flomonster** [comment]
Legacy (train schedule v1)
