### ISSUE TITLE
When cloning an infra, the BP/CC are not displayed anymore on the map

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#7663]
### What happened?

I clone France infra (which has neutral sections). I can not see neutral sections on the cloned infra.

### What did you expect to happen?

I should be able to see the neutral sections if they have been correctly cloned.
If they have not, then they should be correctly cloned.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the reference map
2. Select infra france locked and display neutral sections (you should see them)
3. Clone infra france
4. The neutral sections are not displayed

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by Castavo** [comment]
Could be related to #6716
