### ISSUE TITLE
core: stdcm: post-processing: when we can ajust departure time, move it to the specified times

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#7690]
When we reach the destination with a "max departure time delay" higher than 0, we can adjust the departure time within an interval. When that happens, we should look for expected passage times for all points and pick the time that fits the most.

When there are several points with specified times, we may go for the simplest solution

**Comment by Erashin** [comment]
We could build a curve `sumForEachNode(abs(relativeTimeDiffOfPlannedNode(delayAdded))`, and then take the added delay that minimises this curve, but this is a tad complex, and we don't know if this really is the wanted behaviour.

~~For now, we'll use a simpler solution: at the earliest departure time, find the node having the maximum negative relative time diff (i.e. the train arrives before specified time, and it's the highest relative time diff), and add delay to minimise it.~~
Another solution would have been to minimise the delay of the first possible specified time only => solution kept in the end, seen with @axrolld.
