### ISSUE TITLE
front: highlight trains that do not keep to their timetables

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#7738]
### Description and goal
In the trains list in the time table, we should highlight the trains that do not manage to keep to their planned timetable.

![Image](https://github.com/OpenRailAssociation/osrd/assets/86296016/44097824-1359-4b5b-b466-70cee332fc80)

### Acceptance criteria
 - [ ] Trains that don't stick to the timetable are marked with an icon and a color corresponding to:
     - Display in warning30, opacity 100%, and clock icon trains where the requested time is different from the actual time on at least one point
     - Display in warning30, opacity 50%, and route icon trains where the requested margin is different from the actual time on at least one point
 - [x] They can be filtered using those two new properties like invalid trains

**Comment by flomonster** [comment]
The feature was updated:

- Trains that don't honor scheduled points should be marked in red
- Trains that don't honor margins should be marked in orange
- We should be able to filter the list of trains with these two news properties
