### ISSUE TITLE
Convert train schedules/runs from OSRD to NGE, basic version

### ISSUE THREAD

**Issue by emersion** [OpenRailAssociation/osrd#7739]
### Description and goal

Third part of https://github.com/OpenRailAssociation/osrd/issues/7538

Write and integrate a converter from OSRD train schedules/runs to NGE. Only basic details such as the start time and departure/arrival stations are converted.

### Acceptance criteria

OSRD train schedules/runs show up in NGE with correct basic metadata.

**Comment by louisgreiner** [comment]
We can start to think about train frequency at this point.

Train frequency is not a concept well used in OSRD as well as it is in NGE, however this is a key concept to understand how to work with these two level of detail.

A train frequency helper will have to be implemented on OSRD side, a service that will "translate" a trainrun in NGE into a serie of train schedules in OSRD.

When a serie of train schedules that have the same attributes enough to be interpreted as frequenced train schedules (same rolling stock, slight variation of name (i.e., "{trainrun.name}-{hourOfDeparture}), same path, evenly shifted in time (every hour / 2 hours...)), it will have to let to display only a single trainrun in NGE (frequency depending on the frequence pattern observed) 

Fyi, on the other hand, when computing operations from NGE to OSRD, if a trainrun, with a trainrun frequency of 1 hour, is created, it will result in the creation of X (to be defined, maybe 24) train schedules in OSRD, with a very close name (i.e., "{trainrun.name}-{hourOfDeparture}), all shifted from 1 hour, using the same rolling stock, same minute of departure, same path etc...
