### ISSUE TITLE
error 500 POST v2/train_schedule/project_path?infra=4&ids[]=1

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#7766]
### What happened?

On Infra france, after creating a train and running the simulation, the GET disappears after editoast panicked and returned a 500:

```
osrd-editoast  | thread 'actix-rt|system:0|arbiter:3' panicked at src/views/v2/path/projection.rs:40:13:
osrd-editoast  | assertion failed: track_index.insert(&track_range.track_section, index).is_none()
```

### How can we reproduce it (as minimally and precisely as possible)?

use the payload shared

### What operating system, browser and environment are you using?

- **Browser**: chrome 125.0.6422.141
- **OS**: debian 
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

40bba33cef3345dc8f6896cd513123d62d0fc4ec

**Comment by younesschrifi** [comment]
Can't reproduce the bug. 
The error was caused by a dupplicated track section in the path
Seems to be fixed.
