### ISSUE TITLE
TSV2 : pointer on the space time chart is not on the curve when margins are included 

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#7801]
### What happened?

When you create a train with margins or by fixing some passing times, the pointer in the space time chart follows the basic curve (the fastest one) which is not visible

### What did you expect to happen?

The pointer should follow the real train curve 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a projet/study/scenario
2. Create a train by fixing at least a margin or a passing time 
3. Go to simulation results
4. Move the mouse on the space time chart

### What operating system, browser and environment are you using?

- **Browser**: Edge
- **OS**: windows
- **Env**: recette

### OSRD version (top right corner `Account` button > `Informations`)

dev c57458e

**Comment by emersion** [comment]
Personal notes:

- `updatePointers()` is responsible for updating the vertical trace dot.
- The vertical trace and the top banner are fed by `ChartSynchronizerV2`.
- TSv2 doesn't make use of `SimulationTrain.eco_*` fields, these are set to the same values as the regular fields.
- This is reflected in `drawTrain()` where a null `currentAllowanceSettings` means TSv2, and `eco_*` fields are ignored for TSv2.
- The data passed to `createTrainV2()`  accounts for margins, the data passed to `ChartSynchronizerV2.setTrainData()` does not.
