### ISSUE TITLE
Refresh of elements problem in map viewer and infra editor

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#7802]
#### Track sections
I created a new track section
Then I zoom in or out, and the track section disappears (both in map viewer and infra editor)

Example : 1 / I see the line
![image](https://github.com/OpenRailAssociation/osrd/assets/156183612/3a3d9da2-28ba-4cf2-a5ae-754dc81f0e8b)
2/ I zoom in, and the line disappears

![image](https://github.com/OpenRailAssociation/osrd/assets/156183612/2dd50744-99d0-4c18-a594-cbd4261b7801)

#### Switch

I deleted a switch, and I can still see it in the map/infra editor, but I cannot select it (expected, since it doesn't exist anymore)

![image](https://github.com/OpenRailAssociation/osrd/assets/156183612/f7d16f3d-2266-4e3c-b7ae-cfceb7776ee9)

### What did you expect to happen?

I expected to see the line all the time
I expected not to see the switch

### How can we reproduce it (as minimally and precisely as possible)?

as above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: Staging internal

### OSRD version (top right corner `Account` button > `Informations`)

c57458e

**Comment by bloussou** [comment]
Issue with the invalidation opf the map layers in redis propbably

**Comment by flomonster** [comment]
Can't reproduce. This is probably a deployment issue.

> [!IMPORTANT]
> When we load a backup the redis cache must be clear
