### ISSUE TITLE
TSV2 : text about arrival time in train list out of the box 

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#7803]
### What happened?

![image](https://github.com/OpenRailAssociation/osrd/assets/55697979/8f4812b7-756d-4115-a141-525324634449)

### What did you expect to happen?

the text should be inside the box 

### How can we reproduce it (as minimally and precisely as possible)?

- Create project/study/scenario
- Create a train
- Go to simulation results 

### What operating system, browser and environment are you using?

- **Browser**: Edge
- **OS**: Windows
- **Env**: Recette

### OSRD version (top right corner `Account` button > `Informations`)

dev c57458e

**Comment by Tguisnet** [comment]
List of trains was reworked
