### ISSUE TITLE
Space-Speed chart has 3 curves after asking for margin + specific time in tsv2

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7804]
### What happened?

With this path:
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/41330771-cfc2-49af-8f0a-b7c760592701)

And these inputs in the times and stops table:
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/8bbee69a-dafc-47f7-9b3f-8672005f2451)
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/42b9e2fa-dfb1-44af-9787-9dd356b78ea7)

I got this space-speed chart:
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/f6ed04dc-a1a7-4bb8-8846-0eea2b0c3800)

### What did you expect to happen?

I'm expecting only 2 curves in the chart.

### How can we reproduce it (as minimally and precisely as possible)?

1. Reproduce the description

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

c57458e

**Comment by Tguisnet** [comment]
It seems to be fix now
