### ISSUE TITLE
Drag & drop doesn't work in times and stop input table tsv2

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7806]
### What happened?

https://github.com/OpenRailAssociation/osrd/assets/86296016/61950c1c-cd09-412a-9716-cd292015bf13

### What did you expect to happen?

I'm expecting the value to be copied and pasted in every cell inside the zone i dragged the cursor

### How can we reproduce it (as minimally and precisely as possible)?

1. On any itinerary, try to drag & drop like in the video

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

c57458e

**Comment by flomonster** [comment]
There is no need to drag & drop. Maybe it should be completely disabled? 
We already discuss this with @bgiuliana . Do you remember the conclusion of our discussion?

**Comment by bgiuliana** [comment]
the drag and drop is not needed.  The value of the margin should be put only at the begin of the range where the margin is applied and that value of margin is applied till the next operational point or the next line of the table where a value is pecified. This means that not so many values are supposed to be specified on this table.
