### ISSUE TITLE
"Invalid date" displayed in operational studies

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#7836]
### What happened?

When creating a project / study / scenario the front displays "updated on invalid date" / "modifiée le invalid date". 

See:
![image](https://github.com/OpenRailAssociation/osrd/assets/47494402/cde6be58-fc4a-48a2-99f1-7cefd3c23d22)

### What did you expect to happen?

I would expect it to display a normal date, or no date at all

### How can we reproduce it (as minimally and precisely as possible)?

1. Create any project, study or scenario ?

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Windows 11
- **Env**: osrd.dev.dgexsol.fr

### OSRD version (top right corner `Account` button > `Informations`)

24485e2

**Comment by emersion** [comment]
Hmm seems like I can't reproduce this locally…

**Comment by Castavo** [comment]
Can you reproduce it on the deployed env ?

**Comment by emersion** [comment]
Weird, can't reproduce there either.

**Comment by Castavo** [comment]
Just checked it out on microsoft edge, it works there.
Tried clearing the cookies and local storage of firefox, the bug is still there.
