### ISSUE TITLE
Opening a big tsv2 timetable crashes - URI Too large

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7860]
### What happened?

Opening this scenario with 1900+ trains lead to a page with no train:

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/598026c1-dfe3-485f-8e09-3c97226ebcca)

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/f22a8024-a437-4575-8991-b7e58525b9ff)

After a while the conflicts appeared:

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/e5faaa6a-4e93-48b2-97fe-d6542e07947c)

### What did you expect to happen?

I'm expecting the app to survive, even if the space time chart is known broken for the moment.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a big tsv2 timetable

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

d9655c0

**Comment by bloussou** [comment]
We have changed the database size and now we get :
![image](https://github.com/OpenRailAssociation/osrd/assets/32448554/124f74bb-6390-426f-85f8-a31ff9d2a8e6)
on firefox
