### ISSUE TITLE
Unintelligible error message on pathfinding : `not_found_in_blocks`

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7862]
### What happened?

Pathfinding in the Alpes wih 1TGVDUPL:
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/1fb404af-8265-4b13-9a85-f522848acffc)

### What did you expect to happen?

I'm expecting a clear error message. I think there's no path here so "no path could be found" should be the right message i guess.

### How can we reproduce it (as minimally and precisely as possible)?

1. Reproduce the steps above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

d9655c0

**Comment by eckter** [comment]
> I think there's no path here so "no path could be found" should be the right message i guess.

We specifically moved away from "no path found" and that's a change that has been asked of us, as part of the whole "explain what went wrong" feature.

It's not translated and displayed properly and that's a problem. But if we need to move back to "no path found" we'd have wasted some time.

**Comment by clarani** [comment]
Validated :white_check_mark: 
![image](https://github.com/user-attachments/assets/23f55251-7a56-446d-945d-cb6230b62d40)
