### ISSUE TITLE
tsv2: no more default stops at the end of the train runs

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7863]
### What happened?

My train does not stop at the end anymore 😢 I'm affraid the passengers won't be able to hop on anymore
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/9a1179e3-9ee5-42db-94ac-882f3058b729)

### What did you expect to happen?

I'm expecting the train to stop automatically at the end as it was the case before.

This implies having a `0` in `Stopping time` on the last line of the times and stop table AND a cross to delete this stop if the user wants to :
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/409d9e30-00cd-48ba-a657-b9624154d673)

> [!WARNING]
> Don't do this before [this bug](https://github.com/OpenRailAssociation/osrd/issues/7868) is fixed !

### How can we reproduce it (as minimally and precisely as possible)?

1. Compute any train

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

d9655c0

**Comment by SharglutDev** [comment]
If we add the cross again, the user will be able to remove the destination without any possibilty to add it back here. Are we sure we want to be able to do that on this tab ? @bgiuliana told me the opposite when I changed this behavior a few days ago.
