### ISSUE TITLE
front: correcting spelling and translation errors

### ISSUE THREAD

**Issue by JulesPeignier** [OpenRailAssociation/osrd#7875]
### Description and goal

The aim is to correct spelling and translation errors in the application. 

Errors that have been missed can be added below.

### Error list

- [x] "limitations de vitesses" --> "limitations de vitesse" 
- [x] "Outil 'Itinéraires'" --> "Outil 'Itinéraire'"
- [x] "Outil 'Ligne'"--> "Outil 'Voie'" (car Track Tool en anglais) **(à faire valider)**
- [x] réécrire description Outil Ligne -->  'Une section de voie est un objet géographique linéaire défini par les coordonnées géographiques de ses points (extrémités et points intermédiaires). L'ensemble des sections de voie constitue le réseau ferroviaire'
- [x] Remplacer TIV partout --> Section de voie
- [ ] "Ralentissements 30-60" --> utiliser le document Céline
- [ ]  Ajouter/reformuler avec la notion de TIV mobile **(à revoir)**, vitesse limite etc
- [x] "Électrifications" --> "Électrification"
- [x] "Kp" --> "Kilometric point of the detector" !!pas milestone!!

**Où: Outil 'Vitesse limite'**
 - [x] "des aiguillages et leur positions" --> "des aiguillages et leur position"

**Où: projets/uriel/study/démo import v2**
 - [x] "Pas de profils électriques" --> "Pas de profil électrique"
 - [x] "grille horaires" --> "grille horaire" ou "grilles horaires" **(à revoir)**

**Où: Outil 'Aiguillages'**
- [ ] Confusion entre parfois "aiguilles" et parfois "aiguillages", "aiguilles" et "groupe d'aiguilles" --> nœuds, les nœuds permettent de relier les sections de voie entre elles.

**Où: Outil 'Signal'**
- [x] "Id" --> "Identifiant" *oui
- [x] "ajout de vias" --> ce n'est pas un nom, --> "point de passage"/"étape" (a été modifié apparemment)

**Où: Outil 'Ligne'**
- [x] "son id unique" --> "son identifiant unique" ok

**Où: Outil 'Fusée'**
- [x] "Entrez les trigrammes des points remarquables par lesquels vous voulez que l'itinéraire se fasse, séparés par un espace." --> "Entrez la liste des trigrammes des points remarquables composant l'itinéraire souhaité" 

**Où: Éditeur de matériel roulant**
- [x] "1 résultats trouvés" --> "1 résultat trouvé" (à voir si la faute est aussi présente pour 0 résultat)

**Où: Fiche train**
- [x] "Masse 132T" --> "Masse 132t" (a été corrigé apparemment)

**Où: Gev**
- [x] Le M de l'unité devrait être minuscule (a été corrigé apparemment)
- [x] Il manque l'unité sur l'axe vertical (a été corrigé apparemment)

**Comment by celine-sncf** [comment]
![Image](https://github.com/OpenRailAssociation/osrd/assets/115472753/1ccac6f1-6c3e-4740-9a7e-8fc522383365)

dans les types d'avertissements de l'éditeur d'infra

**Comment by celine-sncf** [comment]
[Définition des vitesses limites](https://sncf.sharepoint.com/:p:/r/sites/OSRD644GrpO365/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B7b6b84d7-5fe6-4b71-88fe-68cd4ce251bb%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1724940357641&web=1) pour utiliser les termes corrects

**Comment by celine-sncf** [comment]
https://github.com/osrd-project/osrd-confidential/issues/231
PR en cours pour remplacer "aiguilles" par "nœuds de voie"

**Comment by celine-sncf** [comment]
https://osrd.fr/fr/docs/explanation/models/data-models-full-example/
pour traduire les types de nœuds de voie

**Comment by JulesPeignier** [comment]
- [x]  Object vide --> Objet vide
- [x] catenaire --> caténaire

**Comment by JulesPeignier** [comment]
https://sncf.sharepoint.com/:p:/r/sites/OSRD644GrpO365/Documents%20partages/Donn%C3%A9es/1-Sources%20de%20donn%C3%A9es/05-VLIM%20enrichissement/documentation/[DATA_CHA_VLIM_V1.pptx](https://sncf.sharepoint.com/:p:/r/sites/OSRD644GrpO365/Documents%20partages/Donn%C3%A9es/1-Sources%20de%20donn%C3%A9es/05-VLIM%20enrichissement/documentation/DATA_CHA_VLIM_V1.pptx?d=w7b6b84d75fe64b7188fe68cd4ce251bb&csf=1&web=1&e=BWfzW9)?d=w7b6b84d75fe64b7188fe68cd4ce251bb&csf=1&web=1&e=BWfzW9
