### ISSUE TITLE
Change variable name from French to English

### ISSUE THREAD

**Issue by ghost** [OpenRailAssociation/osrd#7891]
### What happened?

A variable name is in French but should be in English

<img width="791" alt="Screenshot 2024-06-29 at 9 06 46 AM" src="https://github.com/OpenRailAssociation/osrd/assets/161963553/712ea1c8-54ab-4f96-8301-14b0ceee0e6d">

### What did you expect to happen?

The variable name should be changed from `searchMateriel` to `searchMaterial`

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the codebase
2. Search for `searchMateriel`

### What operating system, browser and environment are you using?

VS Code

### OSRD version (top right corner `Account` button > `Informations`)

current

**Comment by emersion** [comment]
Fixed in #7893
