### ISSUE TITLE
editoast: gateway timeout on simulation_summary for a senario with 1400 trains

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#7914]
### What happened?

Go on this [scenario](https://rec-osrd.reseau.sncf.fr/operational-studies/projects/4/studies/52/scenarios/133) 

### What did you expect to happen?

No timetout

### How can we reproduce it (as minimally and precisely as possible)?

1. Same as #

### What operating system, browser and environment are you using?

- **Browser**: Firefox 

### OSRD version (top right corner `Account` button > `Informations`)

60ae156

**Comment by flomonster** [comment]
Duplicate of #7913
