### ISSUE TITLE
Delete "curves" field on TrackSections

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#7935]
### Who would benefit from this feature?

Both

### What is this feature about?

Curves are not used for any kind of calculation in OSRD. 
They can be seen on the map if needed.
They should be deleted from the data model and the infra editor + any other place where it is shown.

### Why is this feature valuable?

Better understanding of how OSRD works for the users.
Less useless code.

### Anything else people should know?

... has to be taken into account

**Comment by celine-sncf** [comment]
it is used in the runtime calculation

**Comment by Castavo** [comment]
Not planned fits best
