### ISSUE TITLE
500 `core: unknown_error` when looking for STDCM with tsv2

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#7945]
### What happened?

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/e2281f01-b104-4e6a-960f-733b5a3b55ad)

### What did you expect to happen?

No 500

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM debug interface
2. Activate TSV2
3. Any scenario should work (the path has nothing in common with the 6 trains in my scenario)
4. I tried a few rolling stocks andthey seem to trigger the same bug
5. Same for composition code
6. Same for itinerary (`FL U TE` on my screenshot)
7. No other modification
8. Compute STDCM

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

dc11fc8

**Comment by bloussou** [comment]
fixed by https://github.com/OpenRailAssociation/osrd/pull/7933
