### ISSUE TITLE
front: editor: toggle for plateform's data doesn't work properly, layer are not visible on the map

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#7947]
### What happened?

When we try to see the plateform's data, the toggle seems to not work properly, because the layer is always visible on the map. you can't switch off this layer.

### What did you expect to happen?

We expect to see the layer with the datas when we want to see it

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the Editor
2. Try to activate/desactivate the plateform's layer

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows 11
- **Env**: recette

### OSRD version (top right corner `Account` button > `Informations`)

staging dc11fc8

**Comment by SharglutDev** [comment]
Duplicate with https://github.com/OpenRailAssociation/osrd/issues/7492
