### ISSUE TITLE
TSV2 : incorrect standard margin distribution in case of specified passing point

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#7950]
### What happened?

When we put a value of standard margin in the input table, the correspondent margin with this value is inserted till the following passing point 

### What did you expect to happen?

When we put a value of standard margin in the input table, the correspondent margin with this value should be inserted till the following point where a new value of standard margin is specified  

### How can we reproduce it (as minimally and precisely as possible)?

Go to a scenario TSV2
Chose the rolling stock and a path with a passing point 
Put 5% value of standard margin
Look the margin distribution in to the speed space graph

### What operating system, browser and environment are you using?

- **Browser**: Edge
- **OS**: Windows
- **Env**: Recette

### OSRD version (top right corner `Account` button > `Informations`)

staging 4698a66

**Comment by axrolld** [comment]
Another example [here](https://github.com/OpenRailAssociation/osrd/issues/7965)
