### ISSUE TITLE
TS v2, adding  points by clicking on the map creates bugged time stops

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#7955]
#### Add 1 starting point near Nézel and 1 end point near Épône by clicking on the map:

![Screenshot_20240704_220730](https://github.com/OpenRailAssociation/osrd/assets/24652545/0f6214cc-aa5b-49be-afa1-209d63f9a0c6)

#### 2 phantom vias are created when looking in the time stops input table

![Screenshot_20240704_220755](https://github.com/OpenRailAssociation/osrd/assets/24652545/1fe83296-4711-422c-88fe-c63abca5a4e0)

#### After the train is created, the path shown the simulation result on a completely different point than the select starting point
The train goes from Beynes to Épône, even though we started at Nézel.

![download](https://github.com/OpenRailAssociation/osrd/assets/24652545/21cf4d42-b2af-4877-bf33-103d4e8ef4fc)

### What did you expect to happen?

- Should just create the starting and ending point, no extra vias
- the starting point on simulation result should be the same as the one selected by the user

### How can we reproduce it (as minimally and precisely as possible)?

—

### What operating system, browser and environment are you using?

- **Browser**: chrome 125
- **OS**: debian
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

e69ecb131cd1f909e4d42a66166da615fe228252

**Comment by clarani** [comment]
Duplicated with #8026
