### ISSUE TITLE
Simplify ci build etl-basic

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#7973]
## Description

Since we're importing work schedules, etl-basic needs osrd-dags. At present, the process requires a great deal of manipulation to enable etl-basic to be built.

## Implementation plan

Etape 1: Transformer le jenkinsfile (pipeline basic) en pipeline gitlab : construire une image docker à partir du dockerfile dans l'etl-basic
Etape 2: Se passer du repo build-dags rajouter une step pour clone osrd_dags et qui build la wheel python d'osrd-dags puis la pousse sur artifactory
 pour ca : crée un token github pour clone osrd-dags
Ajouter le token
1. Create a github token that can pull the osrd-dags repo
2. Create a jenkins script that syncs github -> gitlab repos in cron every 30min (Script can be directly in jenkins job)
3. Transform the osrd-dags mirror repo into a real mirror (remove the jenkins script and put it directly into the job)
4. When the job is updated, it must sort the existing jenkins pipeline

**Comment by Tguisnet** [comment]
Done
