### ISSUE TITLE
Simulation summary endpoint is called unnecessarily

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#7989]
### What happened?

When a scenario is already open, if the user changes the project of the space-time chart the front re-calls the `simulation_summary` endpoint.

### What did you expect to happen?

The `simulation_summary` endpoint should be called only when the timetable is loaded.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario with multiple trains
2. Open the browser debugger (network tab)
3. Change the train schedule used for the projection

### What operating system, browser and environment are you using?

- **Browser**: Firefox v127
- **OS**: Nixos v24.05
- **Env**: All

### OSRD version (top right corner `Account` button > `Informations`)

3a4069c

**Comment by clarani** [comment]
Validated ✅
