### ISSUE TITLE
Name of the electrical profile set chosen for the scenario isn't displayed

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8002]
### What happened?

As you can see on the screenshot, when you pick an electrical profile set or a scenario, only the ID is displayed and not the name. 

This happens only in V2 not V1

![image](https://github.com/OpenRailAssociation/osrd/assets/47494402/aa77d812-6a44-4ca9-aabd-1da07c4ce568)

### What did you expect to happen?

I would expect to see the name next to the infrastructure

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a V2 scenario with an electrical profile set
2. In the train creation page, see that no name is displayed

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Windows 11
- **Env**: osrd.dev.dgexsol.fr

### OSRD version (top right corner `Account` button > `Informations`)

803e0d1

**Comment by bloussou** [comment]
not fixed: https://rec-osrd.reseau.sncf.fr/operational-studies/projects/95/studies/548/scenarios/1057
![Image](https://github.com/user-attachments/assets/b4677083-ace2-418e-b694-fd037841d130)

**Comment by bloussou** [comment]
an issue with translation, it's fixed
