### ISSUE TITLE
TSv2: The power restriction components electrification display is messed up

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8018]
### What happened?

Paris Montparnasse-Rennes with a 1TGVDUPL.

I got this power restriction component with 1500V being too long compared to the actual length of the zone:
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/8af1a311-b1e8-47c4-8401-4d574b6e4d3c)

And when zooming with the mouse scroll the 1500V ends up being displayed all along the component :
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/de870b1c-509f-4f92-aa01-c3d27fb30492)

### What did you expect to happen?

I'm expecting the electrification display to follow the reality
If the zone is too short, i'd say try ellipsis or display nothing, both are good in my opinion

### How can we reproduce it (as minimally and precisely as possible)?

.

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

de8ada8

**Comment by clarani** [comment]
Can't reproduce anymore ✅
