### ISSUE TITLE
TSV2 : theoretical margin distribution

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#8022]
### What happened?

We insert a theoretical margin value at a certain PR1. We insert the same theoretical margin value for a different PR2 on a following line of the table. The results are the same for the margin distribution, as if we had not set the second margin value.

### What did you expect to happen?

In this case, the margin value should be distributed between the PR1 and the PR2, and between PR2 and the end of the path. This is not the same as distributing the value between the PR1 and the ned of the path. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario TSV2
2. Create a train
3. Insert a theoretical margin value of 5% at a certain PR1 in the times and stops table
4. Insert the same theoretical margin value of 5% for a different PR2 on a following line of the table
5. Go to simulation results and compare with a train without the 5% in the line of PR2

### What operating system, browser and environment are you using?

- **Browser**: Edge
- **OS**: Windows
- **Env**: Recette

### OSRD version (top right corner `Account` button > `Informations`)

staging de8ada8

**Comment by Castavo** [comment]
The desired behavior is:

If the user inputs in the table either group of the same color:
![20240715_103907](https://github.com/user-attachments/assets/5e7ed919-d256-45b0-ba50-8364d39225f0)
It should correspond to this margin repartition, for the same color:
![20240715_103912](https://github.com/user-attachments/assets/b06ccdd1-19f5-4e08-a6f0-82e5c414ff2d)
