### ISSUE TITLE
TSv2: Pathfinding from map seems to snap my origin/destination points to OP

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8026]
### What happened?

I asked for a path somewhere random on the map, but the output seems to have snapped my origin and destination to the nearest operational point or something:
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/a5af1934-7092-435a-b6ea-0a025ead249f)

The output displays the new points, not the one that i selected;
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/a2dc8654-8f5c-4133-b44e-4e23a912b20c)

Also the info in the train details aren't correct:
![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/dbf01a71-c548-47c7-94fe-3ecdf95e766b)

### What did you expect to happen?

I'm expecting my path to remain the same after computation

### How can we reproduce it (as minimally and precisely as possible)?

1. Find any path that doesn't start nor end at an OP, using the map

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

de8ada8

**Comment by axrolld** [comment]
Also the speeds end up wrong at origin and destination : they're not at zero

![image](https://github.com/OpenRailAssociation/osrd/assets/86296016/1e63d850-da19-4c7e-a9f2-5b685d779ed3)

**Comment by bougue-pe** [comment]
Not sure: it may be the difference between the travelled-path (real path) block-path (full blocks, even the first and last that are complete).
