### ISSUE TITLE
editoast: error pathfinding_not_found has not the details provided by core

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#8038]
### What happened?

The error is not has precise has the one provided by core

### What did you expect to happen?

We should be able to have this :
![image](https://github.com/user-attachments/assets/271d98eb-3799-4477-82fa-4374bead79de)

### How can we reproduce it (as minimally and precisely as possible)?

1. not sure

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging de8ada8

**Comment by bloussou** [comment]
Looks like the issue is here: https://github.com/OpenRailAssociation/osrd/blob/dev/editoast/src/views/v2/train_schedule.rs#L646

**Comment by bougue-pe** [comment]
As discussed with @hamz2a and @flomonster, the solution will be:
Split PathfindingResult enum in an "enum-tree":
```
PathfindingSuccess,
PathfindingInputError (InvalidPathItem, NotEnoughPathItems, RollingStockNotFound),
PathfindingFailed, # internal core PF error to comment
PathfindingNotFound (the other enums: NotFound and IncompatibleConstraints),
```
Make it compatible with core without changing core (serde), and adapt front.
Then reuse those variants (except success) directly in SimulationSummaryResult, and adapt front.
