### ISSUE TITLE
Front: "Power restrictions reset" warning too frequent

### ISSUE THREAD

**Issue by bougue-pe** [OpenRailAssociation/osrd#8041]
### What happened?

When the path of a circulation is updated, a warning on "power restrictions have been reset" is printed.
![image](https://github.com/user-attachments/assets/03105b18-1243-4579-8cf9-72914bee9bab)
This is the case even if no power restriction was created before and makes the user ignore the message.

### What did you expect to happen?

Have the warning only when a manual power restriction was actually reset

### How can we reproduce it (as minimally and precisely as possible)?

1. open a scenario
2. add a train (fully)
3. try to add a second train, the warning is displayed
4. change the path, the warning is displayed again

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

45b2718

**Comment by clarani** [comment]
Duplicated with [#8017](https://github.com/OpenRailAssociation/osrd/issues/8017)
