### ISSUE TITLE
front: stdcm: add available simulation message

### ISSUE THREAD

**Issue by Akctarus** [OpenRailAssociation/osrd#8056]
The message should appear when the simulation has finished loading, and it disappears when the user interacts with one of the elements of the proposed result, or when he modifies the form inputs.

![Image](https://github.com/user-attachments/assets/1262e2df-4442-42a1-b9b8-0274f87568ce)

**Comment by axrolld** [comment]
The message in the green box now should be `Calculation complete` after discussion with @thibautsailly @SarahBellaha @kmer2016. This will be done in another PR i think.
