### ISSUE TITLE
Cannot add a margin of 0%

### ISSUE THREAD

**Issue by emersion** [OpenRailAssociation/osrd#8066]
### What happened?

When adding a 0% or 0min/100km in a margin, right now we get an editoast error : 

![Capture d’écran 2024-07-16 à 11 30 40](https://github.com/user-attachments/assets/dd68ad5a-c9fb-4e64-996a-1914e4d2529d)

### What did you expect to happen?

- It should be possible to add a 0% margin to reset any previous margin.
- Remove "none" from possible value in margin values (and so editoast now accepts 0% or 0min/100km)
- set the origin default's margin to 0% after a pathfinding

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to "Times and stop" tab
2. Add a 0% margin

### OSRD version (top right corner `Account` button > `Informations`)

65e7f5b2411c04690f5457712de980b68d842a22

**Comment by SharglutDev** [comment]
Updated issue expectations after exchanges with PO's and UX : 
- remove "none" from possible value in margin values (and so back now accepts 0% or 0min/100km)
- set the origin default's margin to 0% after a pathfinding
