### ISSUE TITLE
Create an endpoint that lists the train schedules a rolling stock is used in

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#8078]
### Description and goal

We used to have such a mechanism that prevented a rolling stock from being deleted if it was used in some train schedules. We did that because `TrainSchedule` V1 used to reference a rolling stock using a foreign key. So removing it also deleted the associated train schedules.

Since TSV2, rolling stocks are loosely referenced using their name. If the rolling stock doesn't exist, the train schedule is deemed invalid but still exists. We still want to warn the user that deleting a rolling stock might invalidate some train schedules though.

We therefore need a new endpoint `GET /rolling_stock/:id/usage` that can retrieve the list of `TrainSchedule` (v2) in which the rolling stock is used. The response could be typed like this:

```ts
type Response = {
    project_id: number,
    project_name: string,
    study_id: number,
    study_name: number,
    scenario_id: number,
    scenario_name: string
}[]
```

> [!NOTE]
> The front-end part can be done separately.

### Acceptance criteria

- [ ] The endpoint exists and works with Train Schedule V2
- [ ] Unit tests

**Comment by Khoyo** [comment]
Response format changed after discussion with @flomonster and @leovalais
