### ISSUE TITLE
Edition of imported trains doesn't work properly

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#8104]
### What happened?

The times and stops table is not filled when editing an imported train schedule (from open data or a file).

Example: 
This train schedule contains a lot of **scheduled points** and **stops**.
![image](https://github.com/user-attachments/assets/228cfa04-144c-4d10-a970-921608b7cb53)

### What did you expect to happen?

The table should be filled with the values.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Import this [example_train.json](https://github.com/user-attachments/files/16281391/example_train.json)
3. Edit the `831701` train
4. Go to times and stops
5. The table is empty

### On which environments the bug occurs?

Local

### OSRD version (top right corner `Account` button > `Informations`)

67d50c4166542bd74e2303c4aa285b858882047f

**Comment by clarani** [comment]
Validated ✅
