### ISSUE TITLE
Front: Projection doesn't refresh when margins are applied multiple times 

### ISSUE THREAD

**Issue by Math-R** [OpenRailAssociation/osrd#8107]
### What happened?

When modifying the margins of a train multiple times the SpaceTimeChart doesn't refresh every time

### What did you expect to happen?

I expect the projection to be refresh on the graph every time the margin were updated

### How can we reproduce it (as minimally and precisely as possible)?

1- Select a train and apply some margin and save
2- Contast the projection changes
3- Reselect the train and change the previous margin an save
4- See that the projection doesnt change
5- Reload your browser, and see thaht the projection doesnt change neither
6- Select the train go to margin and see that the margin is still set
7- Click sur modify and the projection will change

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

bc52bb6908b78f4b609be9742559b0543e54b040

**Comment by SharglutDev** [comment]
Might be fixed when this [PR](https://github.com/OpenRailAssociation/osrd/pull/8271) is merged.

**Comment by clarani** [comment]
Solved by #8271
