### ISSUE TITLE
Power restriction ranges edition fails

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8119]
### What happened?

After entering a value for start or end, the fields disappear by themselves

https://github.com/user-attachments/assets/65d35f39-a051-4a9c-909c-954b14998cb3

### What did you expect to happen?

I expect the fields to not disappear on their own

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to train creation interface
2. Select a train and a path
3. Go to simulation settings tab
4. Click on a range
5. Edit a field (double click to select all, then enter 10, or delete a number from the end field)
6. Witness the fields disappear

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

580140d

**Comment by axrolld** [comment]
Cannot reproduce
