### ISSUE TITLE
stdcm: trains jump around in the space-time graph after moving them

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#8137]
### What happened?

[Screencast from 19-07-2024 11:31:04.webm](https://github.com/user-attachments/assets/7ee1cc63-e5cd-4484-889a-844b4e6261c5)

### What did you expect to happen?

Trains should remain static

### How can we reproduce it (as minimally and precisely as possible)?

Not 100% sure what is exactly the cause, but that seems to reproduce it:

For a given path `A -> B -> C`:

1. Create a timetable (tsv2)
2. Add two trains: one going `A -> C` and one `B -> C`
4. Switch to stdcm tab (debug version)
5. Look for a path over `A -> C`
7. In the resulting graph, move trains around
8. At this point trains will jump around on any graph update

Extra info:

* Refreshing the page won't fix
* It happens when the train is moved "by hand" in the graph directly
* It also happens when the trains are moved in the study tab
* The graph in the study tab don't have glitched trains

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

f2d6885f07a7361047d9cb52669eb85775126545

**Comment by flomonster** [comment]
Can't reproduce cause I got this error: https://github.com/OpenRailAssociation/osrd/issues/8189

**Comment by eckter** [comment]
It's very likely related to the old version of the space-time chart anyway, the issue is likely outdated.

In fact we can't even move trains by dragging them now, so it can't be reproduced in any case. Closing this (at least for now)
