### ISSUE TITLE
front: display the via added by click on the map in the manchette

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#8174]
### What happened?

> When the train path doesn't cover at least two operational points, nothing is displayed. It's an edge case but it feels wrong

This is because the vias added by clicking on the map are not displayed on the chart. We should add them with the operational points.

### What did you expect to happen?

- [ ] the via added by clicking on the map are displayed
- [ ] if a train doesn't cover 2 operational points, the space time chart is displayed

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario v2
2. Add a train by clicking on the map, set the origin and destination on the same track (try to choose a track without any op)
3. Visualize the results of the simulation: the space time chart is not displayed

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by SharglutDev** [comment]
As requested by @thibautsailly, the waypoints added by map click should be named `request point (x)` / `point demandé (x)` with no capital case and in parenthesis the number of "map clicked waypoint" (not depending if there is a constraint on it or if it's just a waypoint). 

The parenthesis is, for now, to "simulate" a circle to stay close to the behavior in the itinerary tab in operational studies where we have a dashed circle before each waypoints.
![Capture d’écran 2024-09-06 à 14 50 41](https://github.com/user-attachments/assets/93621720-32a1-4642-9e4a-8e4b12ff651c)

**Comment by Tguisnet** [comment]
I think the bug is not completly fix : 
- [x] "if a train doesn't cover 2 operational points, the space time chart is displayed" is not fully functionnal
If we have 0 OPs, the space time chart is not display
