### ISSUE TITLE
front: in English, date formats aren't always consistent

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#8180]
### What happened?

See screenshot:

![image](https://github.com/user-attachments/assets/c01ec0ad-5338-4cc0-88f5-da4a910dcc90)

It's not ambiguous in this example, but with a day <= 12 it would be a mess

### What did you expect to happen?

Consistency

### How can we reproduce it (as minimally and precisely as possible)?

Compare dates in the two locations in the screenshot above. I haven't checked more dates than this.

It happens when the UI is in English, I haven't checked what happens in French.

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

3e6b07141b5b570fbebbbf2d619f65eaf71e2730

**Comment by anisometropie** [comment]
Issue doesn’t exists anymore
