### ISSUE TITLE
stdcm: add waypoint isn't disabled when searching for a solution

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8192]
### What happened?

https://github.com/user-attachments/assets/e4e5f2f2-e4de-4bfa-8790-3886b9871cc7

### What did you expect to happen?

I expect all components linked to editing the path to be disabled when we are searching for stdcm solutions.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to stdcm page
2. Selected a packed timetable, so that searching a solution takes some time, and you can click on the add waypoint button

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

7faec4a

**Comment by Akctarus** [comment]
This bug doesn't exist anymore
