### ISSUE TITLE
TSV2 :  incoherent calculated arrival time in the output table

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#8193]
### What happened?

When you create a train starting at a departur time from a point on the track, 
![image](https://github.com/user-attachments/assets/47c317b7-1c29-43d2-9beb-40acbb0fb260)
in the otuput table the calculated time does not correspond to the one on the time space graph and on the train sheet
![image](https://github.com/user-attachments/assets/5147dccd-601f-44f6-9b13-9c2f8b2518ae)
![image](https://github.com/user-attachments/assets/6d73101f-bb1c-4d63-87e3-0accc7f8405a)
In addition the line is orange as if the train does not respect the scheduled time. This is the first point of the table. In addition the first point of the table is the first opeartional point and not the waypoint I had chosen. 

### What did you expect to happen?

- [x] The first point of the output table should be the waypoint I had chosen as departure point.  (fixed in https://github.com/OpenRailAssociation/osrd/pull/8858)
- [x] The output table should display the same arrival time as in the time space graph and in the inputs (fixed in https://github.com/OpenRailAssociation/osrd/pull/8211)

### How can we reproduce it (as minimally and precisely as possible)?

Activate TSV2
Go to the page of creation of a train
Add a train from a point near to Bordeaux St Jean and a point near to Marseille St Charles
look at output table on the page of results 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

staging 7faec4a

**Comment by Castavo** [comment]
Could be linked to #8833

**Comment by anisometropie** [comment]
This Needs a more global rework of waypoints added manually.

@clarani @SharglutDev what’s been done so far ?

**Comment by SharglutDev** [comment]
Seems to have been fixed by this PR : https://github.com/OpenRailAssociation/osrd/pull/8858

![image](https://github.com/user-attachments/assets/459e4b07-c2f3-4184-b5d6-fbe0033d8288)

So I'm closing this issue
