### ISSUE TITLE
stdcm: simulation pdf map does not contain the path

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8196]
### What happened?

When getting a path, the train sheet output looks like such:

[STDCM-0724-102-563.pdf](https://github.com/user-attachments/files/16378569/STDCM-0724-102-563.pdf)

The path is not present in the map included in the report.

On another note: the whole pdf is surprisingly grainy, especially the map...

### What did you expect to happen?

I expect the path to be included in the map

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM page
2. Pick any path (I picked Paris-Dijon, in a 1000 train scenario)
3. Run a simulation
4. Download the pdf result
5. Witness

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

7faec4a

**Comment by clarani** [comment]
Duplicated with #8016

**Comment by Castavo** [comment]
Indeed
