### ISSUE TITLE
TSV2 : train edition create invalid train without changing any path input

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#8199]
### What happened?

I create a train and then I try to modify it.
I changed the theoretical margin. The train becames invalid with an error path finding failed. Despite this, the path is displayed on the map.
![image](https://github.com/user-attachments/assets/125d84c0-7f6b-48ee-94ae-ceeee6056a41)
here the invalid circulation : 
[train_schedules.json](https://github.com/user-attachments/files/16378755/train_schedules.json)

### What did you expect to happen?

The train should be modified with the new value of theoretical margin.

### How can we reproduce it (as minimally and precisely as possible)?

Create a train in TSV2
Click to edit
Go to the "time ans stops" and change the theretical margin
Go to the results page 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

staging 7faec4a

**Comment by flomonster** [comment]
Fixed!
