### ISSUE TITLE
stdcm: the page jumps if you click on the input map, if the output map is present

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8201]
### What happened?

If you have both input and output map visible in the stdcm page, clicking somewhere on the input map makes the page jump to show this point but into the output map

https://github.com/user-attachments/assets/89fa0a31-5885-4992-984d-8b263d22f0d1

### What did you expect to happen?

I expect the map not to jump to the output map, and stay focused on the input map

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM page
2. Create a simulation successfully so the output map appears
3. Click somewhere on the input the map 
4. Witness

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

7faec4a

**Comment by flomonster** [comment]
> [!NOTE]
> We should not be able to add origin/destination points using the map in STDCM view.
