### ISSUE TITLE
TSV2: Error when deleting a route and the scenario is no longer accessible

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#8216]
### What happened?

Error when deleting a route, and the scenario is no longer accessible

https://github.com/user-attachments/assets/98809e19-cdb1-40c0-bc6f-82f1db2d34bd

### What did you expect to happen?

Can successfully delete the route

### How can we reproduce it (as minimally and precisely as possible)?

Check video

### On which environments the bug occurs?

Dev (DgexSol)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

dba683b

**Comment by maelysLeratRosso** [comment]
Same error for me on any scenario, with any infrastructure, without having done anything : I just try to open scenarios and get this error

**Comment by emersion** [comment]
Sorry, I reproduced independently but didn't realize this was filled as an issue. Here's a fix: https://github.com/OpenRailAssociation/osrd/pull/8228

Workaround for users: open the edit form of any train in another scenario.
