### ISSUE TITLE
Loading a new railjson from the front is not working properly

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#8270]
### What happened?

To be completed by @younesschrifi 

### How can we reproduce it (as minimally and precisely as possible)?

To be completed by @younesschrifi 

### OSRD version (top right corner `Account` button > `Informations`)

To be completed by @younesschrifi

**Comment by flomonster** [comment]
Fixed by https://github.com/OpenRailAssociation/osrd/pull/9042
