### ISSUE TITLE
GEV: Reticular isn't precisely on the curve when snapped at PR

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8288]
### What happened?

![image](https://github.com/user-attachments/assets/0b3b996a-9d2d-4e06-96ff-d26f5f724c42)

### What did you expect to happen?

To be on the curve

### How can we reproduce it (as minimally and precisely as possible)?

Zoom a lot horizontally to be able to spot the difference

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by flomonster** [comment]
Fixed!
