### ISSUE TITLE
1TGVDUPL livery is weird in the tab

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8289]
### What happened?

Don't know what's going on here:
![image](https://github.com/user-attachments/assets/7365e52f-8420-450a-aa1e-8608ee4c785a)

### What did you expect to happen?

The livery

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0f97f32f7509cc9722a1a33bec7462ee22009e82

**Comment by axrolld** [comment]
Same in STDCM
![image](https://github.com/user-attachments/assets/5572d1ae-7e7a-4945-af94-b59da1ebf8bf)

**Comment by flomonster** [comment]
@thibautsailly How this should be handled? Should we wait for the new interface?

**Comment by thibautsailly** [comment]
It seems the image is forced to fit in its entire width into a container that has a fixed value.
There should be a gradient mask below the card title, z-axis speaking, covering the image which would be aligned right in the card's header.
It must be the case for other long trains representations.

**Comment by Akctarus** [comment]
![Image](https://github.com/user-attachments/assets/79710935-dcac-432d-9422-7177d8919964)

@thibautsailly something like that ? 
Also, do you prefer: 
- a wider gap between the card title and the train image ? 
- more gradient (here it's set at 80%) ?

**Comment by axrolld** [comment]
I'd say a little bit more space or a shorter gradient, but I'll leave the bottom line to @thibautsailly ;)
Looks very nice though !!

**Comment by thibautsailly** [comment]
That's quite close, and Alex has a good eye too!
Right padding of 12px and a gradient of 40px width from alpha1 to alpha 0.
