### ISSUE TITLE
TSV2 : Editing a train with a point with time constraint (but no stopping time) creates a 0s stopping time constraint

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#8291]
### What happened?

1.I created a train with a time constraint (but no stopping time constraint) in Lantenay
![image](https://github.com/user-attachments/assets/efe32a7d-ba74-401e-b06d-efb3390c0581)
2. The train is created, and there is no stop in Lantenay (correct)
![image](https://github.com/user-attachments/assets/2a9df8a5-ce7a-4589-a776-2ef487c48eda)
3. I click on "edit" to open the edition mode and then on "edit train" (without changing anything) -> The train now stops in Lantenay : a 0s stopping time was added (problem)
![image](https://github.com/user-attachments/assets/38092325-4ebc-4f3e-9768-96ca87a1c07d)

If I reopen the editition mode, I can see that a 0s stop was indeed added : 
![image](https://github.com/user-attachments/assets/470486d4-da19-44e8-8f84-d6d2c1f7230d)

### What did you expect to happen?

I expected no stop to be added

### How can we reproduce it (as minimally and precisely as possible)?

as above

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by clarani** [comment]
~I can't reproduce it anymore 🤔~
I reproduced it :white_check_mark:

**Comment by maelysLeratRosso** [comment]
I still reproduce it (on dev-osrd), I can show you :)
