### ISSUE TITLE
The rolling stock selector list in OP is not updated 

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#8295]
### What happened?

-A new create rolling stock is not displayed in the selector
![image](https://github.com/user-attachments/assets/bff515db-3331-4a8d-a8ba-4d6af12a2279)

- Searching for deleted or updated rolling stock display an error 
![image](https://github.com/user-attachments/assets/2aa4e2d7-78e7-47c4-9291-d5ea69abe36c)

### What did you expect to happen?

The list of rolling stock is the same in the rolling stock editor 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create ,update or delete  rolling stock 
2. From a created scenario try to modify the rolling stock and search for the new RS

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by Akctarus** [comment]
Can't reproduce it :/

**Comment by theocrsb** [comment]
Same for me

**Comment by Maymanaf** [comment]
Closed : The issue is not reproducible
