### ISSUE TITLE
GEV: ticks disapear when zooming a little too much

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8298]
### What happened?

Here i have about 20km range and all the ticks are displayed:
![image](https://github.com/user-attachments/assets/a600d8a1-99a0-4796-b518-3328da566add)

But if i zoom once more they all disappear:
![image](https://github.com/user-attachments/assets/0efa1eb5-8c7e-448b-b4f8-5465f49cd53e)

### What did you expect to happen?

There's still room to display many ticks, i'm expecting them to stay

### How can we reproduce it (as minimally and precisely as possible)?

Zoom on the GEV

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by Castavo** [comment]
Can't reproduce on 512fe9a
Was fixed by https://github.com/OpenRailAssociation/osrd-ui/pull/436

**Comment by Castavo** [comment]
Can't reproduce on https://github.com/OpenRailAssociation/osrd/commit/512fe9aa001c7b3145575f15f748791fdadd4b97
Was fixed by https://github.com/OpenRailAssociation/osrd-ui/pull/436
