### ISSUE TITLE
GEV: electrification found in tooltip is incorrect

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8300]
### What happened?

PLY MSC with 1TGVDUPL.

At 15.0km the electrification displayed in the tooltip is 25000V: 
![image](https://github.com/user-attachments/assets/d14b5a1e-512d-4d78-859e-7dce78960be8)

And at 14.0 it's at 1500V:
![image](https://github.com/user-attachments/assets/aad33ff7-f858-4fde-83ea-7d4c26f6e990)

While the electrification changes between 13 and 14 km according to the map and the dead section present in the GEV:
![image](https://github.com/user-attachments/assets/130bc269-e02f-4549-9407-f3215d875d50)

### What did you expect to happen?

I'm expecting the different electrification infos to be consistent.

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce the description.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by anisometropie** [comment]
Data is looking good on the speed space https://github.com/user-attachments/assets/f66859a9-0699-43b9-a4c1-1f8464d620fc
closing
