### ISSUE TITLE
The power restriction is splited automaticlly

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#8303]
### What happened?

https://github.com/user-attachments/assets/74128403-3b06-457a-9073-b89c3b639f52

can be realted to this bug : https://github.com/OpenRailAssociation/osrd/issues/8119

### What did you expect to happen?

The range of the power restriction doesn't change 

### How can we reproduce it (as minimally and precisely as possible)?

1. Add Power restriciton for a train
2. Save the changes
3. Check the added power restriction 

https://rec-osrd.reseau.sncf.fr/operational-studies/projects/39/studies/142/scenarios/264

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by axrolld** [comment]
Cannot reproduce
