### ISSUE TITLE
Can't edit invalid routes

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#8304]
### What happened?

When a route has an invalid reference we can't select it and edit it.

I suspect this [commit](https://github.com/OpenRailAssociation/osrd/commit/4070d784c756e38dfcad3cd4ac8adbec09fdcbd7) to be the source of the issue.

### What did you expect to happen?

We should be able to edit an invalid route. If the geometry cannot be computed we should still be able to see the edition form.

### How can we reproduce it (as minimally and precisely as possible)?

1. Download and import this infra: [infra_route_bug.json](https://github.com/user-attachments/files/16457315/infra_route_bug.json)
2. Go to the editor
3. Click on "5 issues"
4. Select the invalid reference
5. It's loading forever

You can also craft url to access the invalid route: https://osrd.staging.dgexsol.fr/editor/INFRA_ID?selection=Route%7Ert.DA4-%3Ebuffer_stop.2

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by clarani** [comment]
Validated ✅
