### ISSUE TITLE
Failed to add more than one power restriction

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#8306]
### What happened?

https://github.com/user-attachments/assets/ee22e0bd-1b4e-4d9e-b75a-f2975be83038

### What did you expect to happen?

Can add the power restriction successfully 

### How can we reproduce it (as minimally and precisely as possible)?

1. Edit a train 
2. Add more than one power restriction 
3. Click on "Edit train"
https://rec-osrd.reseau.sncf.fr/operational-studies/projects/39/studies/142/scenarios/264

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by axrolld** [comment]
Cannot reproduce, @achrafmohye do you manage to reproduce this bug ?
