### ISSUE TITLE
Cannot open scenario on specific infrastructure and with specific timetable

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#8308]
### What happened?

I created a scenario with this infra
[small_infra_copy_maelys.id56.railjson.json](https://github.com/user-attachments/files/16457706/small_infra_copy_maelys.id56.railjson.json)

And added the following train 
[bug ralen 30 60.json](https://github.com/user-attachments/files/16457715/bug.ralen.30.60.json)

I get the following error and cannot open my scenario : 
![image](https://github.com/user-attachments/assets/3c1f8405-03db-426a-bedd-2459d41bc69c)

Note : don't know if it is related, but I created a speed restriction (ralen 30 60) on my infra and created a train using this route. Also, importing the train on France infrastructure doesn't create the bug, only an invalid train (which is correct)

### What did you expect to happen?

I expected to be able to open my scenario

### How can we reproduce it (as minimally and precisely as possible)?

Create a scenario with the infrastructure above and importe the above circulation

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

**Comment by flomonster** [comment]
Can't reproduced. Assume fixed.
