### ISSUE TITLE
 GEV: ‰ unit not sticky on top of right ticks

### ISSUE THREAD

**Issue by Yohh** [OpenRailAssociation/osrd#8312]
> [!NOTE]
> ui-core related [issue](https://github.com/OpenRailAssociation/osrd-ui/issues/385).

### What happened?

the ‰ unit follows the height scale when we use the enlarger button
https://github.com/user-attachments/assets/a295824b-1c45-46d3-bd5f-8429ae4bffcd

### What did you expect to happen?

it should be sticky on top-right of the right-ticks layer, and follow the axact representation of the mockup
<img width="104" alt="Capture d’écran 2024-08-02 à 10 39 14" src="https://github.com/user-attachments/assets/c8e7ba08-b4ce-407b-97c7-ad53fd06b2a5">

### How can we reproduce it (as minimally and precisely as possible)?

1. create a scenario with trains
2. enable declivities
3. see the ‰ while enlarging the GEV

### On which environments the bug occurs?

Dev (DgexSol)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev 34c0b8e

**Comment by clarani** [comment]
UI-core related issue: https://github.com/OpenRailAssociation/osrd-ui/issues/385

**Comment by louisgreiner** [comment]
Re-open, since osrd-ui is not at the right version in osrd

**Comment by louisgreiner** [comment]
Closed by https://github.com/OpenRailAssociation/osrd/pull/8863
