### ISSUE TITLE
Front: branch speed-limit source to speed-space chart in OpStudies and STDCM

### ISSUE THREAD

**Issue by bougue-pe** [OpenRailAssociation/osrd#8328]
The goal is to plug back output to `core-ui` once all is available, to have the feature fully implemented.

Depends on https://github.com/OpenRailAssociation/osrd/issues/7717 and https://github.com/OpenRailAssociation/osrd/issues/7732 (part of https://github.com/osrd-project/osrd-confidential/issues/364)

AC: In the end, we should have the speed-limit sources (tags) available in osrd as designed in https://github.com/osrd-project/osrd-confidential/issues/364 (except maybe for the long names that should disappear with https://github.com/OpenRailAssociation/osrd/issues/7977)

Related idea (postponed, to be decided if relevant): https://github.com/OpenRailAssociation/osrd-ui/issues/428

**Comment by flomonster** [comment]
I found two small bugs:

### Tags are overlapping each other

![image](https://github.com/user-attachments/assets/cc4d96fd-1df9-491f-8576-a4138fdbddf4)

----------

### The speed tags are blinking when zooming

Zoom in and zoom out and observe the blue line blinking.

**Comment by SharglutDev** [comment]
There are a few other ui issue with this layer, there is an enhancement ticket here (validated by @thibautsailly) : https://github.com/OpenRailAssociation/osrd-ui/issues/194

For the blinking issue, I think we need to open an issue, it's already on the component in storybook : https://openrailassociation.github.io/osrd-ui/?path=/story/speedspacechart-rendering--speed-space-chart-default

**Comment by flomonster** [comment]
I've created the issue https://github.com/OpenRailAssociation/osrd-ui/issues/427. The blinking effect seems more important on the integrated version of the component though.

**Comment by bougue-pe** [comment]
A new issue is created about a rendering bug, relating to this feature: https://github.com/OpenRailAssociation/osrd-ui/issues/429 (this may be split if it's actually 2 bugs).

**Comment by bougue-pe** [comment]
Also added an issue to the main description : https://github.com/OpenRailAssociation/osrd-ui/issues/428
(to be decided if it's a must-have or an enhancement)

EDIT: it's just an idea, not even sure we want that.
