### ISSUE TITLE
Wrong start time displayed after import train with open data

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#8331]
### What happened?

After importing train with open data, when editing the train, the start time displayed is not the good one.

### What did you expect to happen?

It should display the real start time of the train.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Import any train from open data and remember one of the train departure (as another bug prevents to display the start time in the timetable)
3. Edit this train and check the start time

### On which environments the bug occurs?

Dev (DgexSol)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev a72b88b

**Comment by clarani** [comment]
Validated ✅
