### ISSUE TITLE
Front: Speed space chart is broken when there is no stop at the end

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#8333]
### What happened?

When we put no stop at the end, the GEV is broken : 

![Image](https://github.com/user-attachments/assets/b69f449d-1c7b-4301-b196-97c17fe6793e)

### What did you expect to happen?

We should have a correct GEV

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a TrainSchedule
2. Remove the stop at the end

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

staging 0a34296

**Comment by clarani** [comment]
osrd-ui needs to be released, see https://github.com/OpenRailAssociation/osrd/pull/9125

**Comment by clarani** [comment]
Validated ✅
