### ISSUE TITLE
Can't create new RS with Air conditionning curves

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#8371]
### What happened?

An error is displayed when trying to create a train with Air conditionning comfort

![image](https://github.com/user-attachments/assets/27c3285f-2d1a-42fe-a69d-7d4524e2f319)

### What did you expect to happen?

The rolling stock is created successfully 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a new rolling stock.
2. Add data curves for the standard mode.
3. Add air conditioning comfort and fill in the curves data.
4. Click on Confirm to create the train.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

3fd2fd0

**Comment by Akctarus** [comment]
Need TSV1 to be dropped before fixing this bug
