### ISSUE TITLE
Frontend crash: operationalPoints[0] is undefined

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#8376]
### What happened?

When opening a specific scenario I got the following error page:

![image](https://github.com/user-attachments/assets/854b9594-46a0-4844-bc4c-42fc9e33b1bf)

### How can we reproduce it (as minimally and precisely as possible)?

1. Import this [infra.json](https://github.com/user-attachments/files/16548976/infra.json)
2. Create a scenario with this infra
3. Import this [schedule.json](https://github.com/user-attachments/files/16548983/schedule.json)

Observe the error

### On which environments the bug occurs?

Local, Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

02781caf6fb315732a9067daebf49f1548d38415

**Comment by axrolld** [comment]
I tried to test the bugfix but got this error when hovering on the space-speed chart:


![Image](https://github.com/user-attachments/assets/277db4c2-00fd-4700-abb5-6ca4e7c5921a)
