### ISSUE TITLE
Front crash when edit input table for a specific scenario 

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#8377]
### What happened?

I get this error when edit the table : 

https://github.com/user-attachments/assets/46ed2768-db28-4e5d-b952-c0545d881bda

### What did you expect to happen?

The front don't crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Import the [train_schedules.json](https://github.com/user-attachments/files/16549370/train_schedules.json)
2. Edit a train
3. Set any value in Times and stops table 
4. Save the modification 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

02781ca

**Comment by anisometropie** [comment]
81dc8ed334d7a023680ff305ca47aa768fa411fa assertion failed but input table edition works

**Comment by anisometropie** [comment]
this all happens in `src/modules/trainschedule/components/TimetableV2/hooks.ts`.

I am logging an array in the first query and another array in the second query that are supposed to have the same length.

It looks like if i remove the throw new Error that crash immediately if they don’t have the same length, it’s resolving slowly. 

The first query is called in a render, we get the new length 7, then after a few renders, the 2nd is called, and the new length is updated as well.

This might just be the way rtk-query invalidates tags and refetch the new data.

![Image](https://github.com/user-attachments/assets/0a7f12b3-1d81-45ee-9a2f-f9442126b7c4)
