### ISSUE TITLE
Warped map doesn't display trains anymore

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#8390]
### What happened?

Since the migration to trainschedule v2, the warped map displays only the path but not the trains anymore.

This is because it uses the old model to catch the trains datas.

When designing the tsv2 model, it has been decided that the warped map won't display all trains of the timetable anymore but only the selected one.

When [dropping tsv1](https://github.com/OpenRailAssociation/osrd/pull/8382), to prevent some errors in the warped map components, some temporary variables have been added. They should be replaced by the new tsv2 ones. A tag `TODO: fix warped map` has been added close to them to simplify the process.

### What did you expect to happen?

- [ ] Warped map uses the simulation results of the `final_output` from tsv2 endpoint `getV2TrainScheduleByIdSimulation`
- [ ] It displays only the selected train
- [ ] It is still synchronized with the TimeButtons at the top of the simulation results (when we play start, we can see the train moving on the warped map)

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario with a train
2. Open the warped map at the left of the space time chart
3. You should only see the path but no train, even when launching the time button

### On which environments the bug occurs?

Dev (DgexSol)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev a72b88b

**Comment by flomonster** [comment]
This feature was dropped. We're wainting a new design for this.

**Comment by SharglutDev** [comment]
Should we drop the related code in the codebase then (it's commented since the tsv2 migration) ?
