### ISSUE TITLE
GET: TER Bretagne on a Grenoble-Chambéry manchette

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8451]
### What happened?

I created a fex train between Grenoble and Chambéry, then imported some train from open data between RES ands QR. The imported trains appeared on the GET but they're really not supposed to be here.

![image](https://github.com/user-attachments/assets/16f742f5-8286-444d-93b3-354871fcb31e)

### What did you expect to happen?

I'm expecting the GET to display only the trains between Grenoble and Chambéry

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

ab7706e

**Comment by flomonster** [comment]
Fixed!
