### ISSUE TITLE
Design and implement new route API that handles reservations

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#847]
RailML has a combined route model: https://wiki3.railml.org/wiki/IL:combinedRoute, which seems necessary to safely operate
We need to discuss how this concept is used to implement safe bidirectional single track lines

On these lines:
 - What's the default state of signals when no train is incoming either way?
 - How comparable are combined and atomic routes?
 - Where to find this data?
 - How is this concept used to ensure safety of bidirectional single track lines?

**Comment by eckter** [comment]
This is a dump of notes from a meeting (sorry about the French):


Un itinéraire est détruit quand :
	- Le train est rentré dans le premier canton
	- Le premier canton a été libéré

Itinéraire en conflit :
	Pour chaque canton dans l'itinéraire :
		- Réservé pour la même direction
		- + Si aiguille : Même position

Pour pouvoir former un itinéraire :
	- Pas d'itinéraire sécant (qui traverse) / convergeant / en sens contraire
	- enregistré (pré réservation) ou formé (réservé) ou en cours d'utilisation
	
En dehors des carrés qui protègent des aiguilles : que de l'espacement (sémaphore et pas carré, vert par défaut)

La réservation se fait en partant de l'origine (les humains font dans l'autre sens pour l'ergonomie)

Pour nous : on peut re-réserver un truc déjà réservé si les conditions sont respectées (même sens, même position d'aiguille)

**Comment by eckter** [comment]
![IMG_20220425_171700](https://user-images.githubusercontent.com/3882074/165120130-fe665e0b-7e12-4aaf-90ba-534bc8223b61.jpg)
