### ISSUE TITLE
STDCM configuration problem

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8481]
### What happened?

![image](https://github.com/user-attachments/assets/63885f93-7c37-4f3c-b888-417216e5ec72)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open STDCM new interface

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

f25fc61

**Comment by Castavo** [comment]
This is a deployment / running config issue rather than a code issue

(And the config issue has been fixed now)

**Comment by Castavo** [comment]
This is a deployment / running config issue rather than a code issue

(And the config issue has been fixed now)
