### ISSUE TITLE
NGE Trainrun bugged when updating departure time from OSRD

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#8518]
### What happened?

![image](https://github.com/user-attachments/assets/64eb0580-953d-4c59-a994-5195aecd6515)

### What did you expect to happen?

No creation of all station CHs

### How can we reproduce it (as minimally and precisely as possible)?

1. create train in osrd with "SG PE"
2. change departure time in nge
3. go back to osrd and update departure time
4. notice bug in nge

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

**Comment by emersion** [comment]
Seems to be caused by the frontend dropping `secondary_code` from path steps when editing a train schedule.
