### ISSUE TITLE
front: can't import timetable file if it doesn't have .json extension

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#8539]
### What happened?

![image](https://github.com/user-attachments/assets/30885599-f966-4505-9133-2d7712092b3a)

The file is actually a valid json. I don't think this check should be done on the extension itself

In fact, we could *maybe* just paste json text here

### How can we reproduce it (as minimally and precisely as possible)?

Try to load a valid json file that isn't named something.json

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

77ed9b9e027aaad67ad2b9a049675f53226e9be8

**Comment by emersion** [comment]
Hmm. In the future we want to support more formats such as XML, so I'm not sure we'd want to always assume JSON here…

**Comment by clarani** [comment]
Duplicated with https://github.com/OpenRailAssociation/osrd/issues/8115
