### ISSUE TITLE
front: space-time-chart: when train path overlap in several distinct areas, we wrongly fill the gaps

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#8540]
### What happened?

When projecting a train onto a path, the train path may intersect with the projection path in several distinct areas. For example it may use the same track at the start, then move to a different track, then go back to the original path.

When this happens, we should display two different lines in the chart. The train shouldn't be displayed in places where the path is different.

But we actually display one single long line, showing that the train is at a place where it isn't. 

Note: back-end returns two different lines, the issue is on the front-end side

### What did you expect to happen?

Different lines for each distinct path overlaps

---

### How can we reproduce it (as minimally and precisely as possible)?

On small infra: schedule two trains starting and ending on the same points:

![image](https://github.com/user-attachments/assets/bb760ae1-c772-45db-b7a9-62b474abc833)

Then use intermediate points to make them take either the north or south track. The two path will be the same at the start and end, but different inbetween.

The space time chart should show a full line for the train used in the projection, and two partial lines for the other.

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

77ed9b9e027aaad67ad2b9a049675f53226e9be8

**Comment by bloussou** [comment]
closing this at it is fixed
