### ISSUE TITLE
Tsv2: Stop not located at a specific PR doesn't appear in the output table

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8546]
### What happened?

I created a freight train with a 20mn stop on a manually placed via, and it doesn't appear in the output table:

Input:
![image](https://github.com/user-attachments/assets/9dc7f424-8860-4503-8688-d1285738205f)

Output:
![image](https://github.com/user-attachments/assets/3c795a7c-a436-4948-a495-da37c83ad8ad)

### What did you expect to happen?

I'm expecting the stop to be horizontal and highlighted the same way as the other stops.

### How can we reproduce it (as minimally and precisely as possible)?

Inputs:
![image](https://github.com/user-attachments/assets/008c49f9-c4be-4acd-bd70-e3427ed784ab)

With a manual via point here in Redon and a 1200s stop on that point:
![image](https://github.com/user-attachments/assets/dd71ab05-5cb5-40a5-985b-b5af78ca591a)

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

c885d29

**Comment by Maymanaf** [comment]
Fixed : 
![image](https://github.com/user-attachments/assets/04215845-1a01-48f5-a059-1e29035e9e9b)
