### ISSUE TITLE
GET: The different trains seem to be displayed quite randomely sometimes

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8551]
### What happened?

My time table has a few TGV, lots of TER, and one freight train a long stop in Redon. When i edit my freight train, or when i refresh the page, the train that has the stop in the GET changes randomely:
https://github.com/user-attachments/assets/4d8f17d0-22da-472b-b41b-faf5d5237e48

Sometimes i have this:
![image](https://github.com/user-attachments/assets/27ea93f1-8604-477c-8178-d2f506a9e1bd)

Then i refresh, i get this:
![image](https://github.com/user-attachments/assets/34aa2114-bc90-4556-95a0-44d32fead020)

And then again:
![image](https://github.com/user-attachments/assets/591b691f-c638-4322-8fdd-734cd956aa21)

I also had the bug when deleting all TERs and the freight, my TGVs appeared like TERs, with all the stops...

### What did you expect to happen?

I'm expecting the GET to display the real behavior of the trains

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a timetable with many different trains
2. Try deleting some trains, editing some, etc
3. Watch the GET

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

1482e8c

**Comment by Maymanaf** [comment]
Fixed , only issue issue with refresh when update values : https://github.com/OpenRailAssociation/osrd/issues/8562
