### ISSUE TITLE
Weird outputs and many bugs with my Nantes-Clisson train

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8558]
### What happened?

I created this train
[nantes-clisson.json](https://github.com/user-attachments/files/16725810/nantes-clisson.json)

![image](https://github.com/user-attachments/assets/379719be-4e31-4887-b74b-f4b69ce5ba01)

Called `ter` [in this scenario](https://rec-osrd.reseau.sncf.fr/operational-studies/projects/19/studies/199/scenarios/364)

Both departure and arrival are manually set on the map, no specific OP. But for some reason i have no output, all the charts are empty or wrong...

The GET:
![image](https://github.com/user-attachments/assets/97af988b-4b37-40eb-b6a7-b318ed7dff42)

The GEV is wrong, the distance is much greater than that and it's really not supposed to look like this:
![image](https://github.com/user-attachments/assets/e1483d92-74da-4cfa-b47e-5c6b5cd4b7ac)

Also when i hover the GEV i get this crash:
![image](https://github.com/user-attachments/assets/94ef2b2e-9894-4740-b2fa-ddab8f65325c)

And the output table and declivity graph look like this:
![image](https://github.com/user-attachments/assets/624e570e-5358-467c-bc14-b9279630b3d3)

Overall many weird things happening for that one single train, i don't really know what's happening and i hope the bug is understandable...

### What did you expect to happen?

I tried to create another train with manual points on the map and it works fine, i'm expecting this one to work the same way

### How can we reproduce it (as minimally and precisely as possible)?

I gave my json file and my scenario in the description

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

f0a220a

**Comment by Castavo** [comment]
This actually feels like a data problem, it looks like the length of the track section is waaay different from its actual length

**Comment by Castavo** [comment]
Yup, that's definitely a data problem 
![image](https://github.com/user-attachments/assets/19181157-e94d-4f67-a871-d60061019192)

**Comment by axrolld** [comment]
Wow, that's some serious data issue, such a weird bug. Maybe it should be 502km ?

**Comment by Castavo** [comment]
This is an issue which will not be solved by changing the code of osrd, moving it to our private data managing repo in https://github.com/osrd-project/osrd-dags/issues/483
