### ISSUE TITLE
Route deletion not working in operationnal studies

### ISSUE THREAD

**Issue by theocrsb** [OpenRailAssociation/osrd#8560]
### What happened?

Text entered in the search bar is not deleted when you click on the trash icon.

### What did you expect to happen?

When you click on the trash icon, the text entered in the bar must be deleted

### How can we reproduce it (as minimally and precisely as possible)?

go to operationnal studies
make a pathfinding 
and delete it

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

pr 8555 (merge of cni/8453-fix-output-table-op-via-schedule@60df759 into dev@b7142db)

**Comment by Maymanaf** [comment]
This issue is no longer relevant
