### ISSUE TITLE
Arrival time, space-time diagram, and energy consumed are not updated until refresh

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#8562]
### What happened?

1. I have a train with 5% margin, arrives at 14:27
2. I change the margin to 10% : the popup tells me that the train is updated, and if I go in the edition mode, my 10% is present
3. BUT the arrival time is still 14:27 in the list and in the spacetime diagram
4. If I refresh my page, I have the correct time : 14:42
5. Same problem with the energy consumed

https://github.com/user-attachments/assets/e8bea0b3-c017-4bab-a023-9f7948d0fc3c

### What did you expect to happen?

I expected the new time to be displayed everywhere without refreshing

### How can we reproduce it (as minimally and precisely as possible)?

as above

### On which environments the bug occurs?

Dev (DgexSol)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

1482e8c

**Comment by Maymanaf** [comment]
The issue remains unresolved

**Comment by Uriel-Sautron** [comment]
I think this bug is solved.
Can you confirm this @maelysLeratRosso.

**Comment by maelysLeratRosso** [comment]
@Uriel-Sautron Yes it seems solved for me too :)
