### ISSUE TITLE
Synchronize OSRD/NGE locale

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#8569]
### Who would benefit from this feature?

End users

### What is this feature about?

Synchronize locale (language) for the Microscopic (OSRD) and Macroscopic (NGE) windows

Currently, NGE changes the locale like that : 
![image](https://github.com/user-attachments/assets/a2735731-732f-42ca-b935-05aba9a87597)

- html : https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/ab2dded6346e8f142055f898573658bb26ab47c6/src/app/app.component.html#L14
- ts : https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/ab2dded6346e8f142055f898573658bb26ab47c6/src/app/app.component.ts#L60

The idea would be to trigger this function as soon as the OSRD locale is initialized / updated

The work has to be done on this repo, on a branch from this one : https://github.com/osrd-project/netzgrafik-editor-frontend/tree/standalone

### Why is this feature valuable?

User doesn't need to configure language twice

We can also remove 1 button from NGE UI (see screenshot)

### Anything else people should know?

After this PR, finish the work started here to remove the header in NGE : https://github.com/osrd-project/netzgrafik-editor-frontend/tree/lgr/remove-sbb-header-lean

**Comment by clarani** [comment]
Closed by https://github.com/OpenRailAssociation/osrd/pull/9760
