### ISSUE TITLE
Changing the rolling stock to make an invalid train valid does not exit the pathfinding debug interface

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#8570]
### What happened?

1. I start creating (WITHOUT SAVING) a train which is invalid due to constraints (PLY-DN with electric 25000V rolling stock) -> I enter the debug interface
2. I change the rolling stock to have a valid train (a thermic rolling stock) and go back to the itinerary tab -> I am still in the debug interface

Also seems to be the case the other way around : valid train (normal itinerary tab) -> invalid train (does not trigger the pathfinding debut)

### What did you expect to happen?

I expected the itinerary tab to be updated without the debug interface when I use a correct rolling stock

### How can we reproduce it (as minimally and precisely as possible)?

as above

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

1482e8c

**Comment by Maymanaf** [comment]
![image](https://github.com/user-attachments/assets/81eca035-527b-4ae3-b003-84b5d4a50358)
