### ISSUE TITLE
editoast: can't send work schedules by batch and the payload for 2 days is too large

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#8572]
### What happened?

When the etl-basic is sending work-schedules for two days, it gets:
```log
[2024-08-23 13:21:33,324] [DEBUG] - Error loading planches: HTTPError('413 Client Error: Payload Too Large for url: http://osrd-rec-editoast.osd
```

### What did you expect to happen?

We shoudl be able to post multiple payloads to a wrokschedule group id

### How can we reproduce it (as minimally and precisely as possible)?

1. lauch the etl-basic in the rec environnement

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6d020d86930318a09b9ca7b0d947ce1678055e65

**Comment by flomonster** [comment]
- It works locally
- A work schedule payload for two days is 100ko large

**Comment by flomonster** [comment]
It seems to be working again. I didn't quite understand what the problem was.
I suppose there must have been a problem on a particular day when there were usually a lot of work schedules.
