### ISSUE TITLE
nge: operational studies: oppositeNode.getPortOfTrainrunSection(...) error

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#8580]
### What happened?

When opening this scenario https://rec-osrd.reseau.sncf.fr/operational-studies/projects/4/studies/203/scenarios/377 and switching to the macroscopic tab I got this screen:
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/e76a53b6-0d1f-4fab-b6e6-5b83179acc0e">

### What did you expect to happen?

The frontend not to fail

### How can we reproduce it (as minimally and precisely as possible)?

1. go to this page: https://rec-osrd.reseau.sncf.fr/operational-studies/projects/4/studies/203/scenarios/377
2. switch to macroscopic tab

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

b7142db

**Comment by Maymanaf** [comment]
Fixed
