### ISSUE TITLE
Selecting float budget gives unreadable error

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8607]
### What happened?

https://github.com/user-attachments/assets/0509e2b0-7616-4a73-89c8-2ed5c4640010

### What did you expect to happen?

I expect the field to be highlighted in red, with a clear message stating that float numbers are forbidden

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to operational studies page
2. Open project creation form
3. Enter the name and a floating point budget
4. Click on save, witness

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

 1482e8c

**Comment by Maymanaf** [comment]
The issue remains unresolved 
![image](https://github.com/user-attachments/assets/841e7b8b-520c-4f0d-9ba8-133f4a6fd9a1)

**Comment by clarani** [comment]
Validated ✅
