### ISSUE TITLE
Missing lazy loader info in STDCM GET

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8610]
### What happened?

This info is missing in STDCM GET
![image](https://github.com/user-attachments/assets/9d44e308-3d54-4967-8a18-ea5a5620f64d)

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

1482e8c

**Comment by Maymanaf** [comment]
The issue remains unresolved
