### ISSUE TITLE
Object search isn't resilient to operational points with no ch code

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8616]
### What happened?

https://github.com/user-attachments/assets/f78a057c-6df0-450b-a7df-342df7efc963

### What did you expect to happen?

I expect the search to not crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Select Germany infrastructure (or any infra which has operational point with no CH code)
2. Open the search window
3. Start typing witness

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

1482e8c

**Comment by Maymanaf** [comment]
The issue remains unresolved

**Comment by clarani** [comment]
Validated ✅
