### ISSUE TITLE
Missing `Engin de ref` in STDCM outputs

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8617]
### What happened?

![image](https://github.com/user-attachments/assets/2db8c6f2-1701-4113-88eb-9b3f191a469b)
![image](https://github.com/user-attachments/assets/37b4accf-6001-47c9-a214-f9fa080dcc81)

### What did you expect to happen?

The name of the rolling stock used

### How can we reproduce it (as minimally and precisely as possible)?

1. Get a STDCM simulation

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

80973c5

**Comment by Akctarus** [comment]
Fixed
