### ISSUE TITLE
Departure time not displayed in input table

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#8618]
### What happened?

I create a train and write a departure time in the input table (without writing an arrival time)
![image](https://github.com/user-attachments/assets/b4e4dcf7-db33-45e9-8f8b-1ea6651e0a9a)

If I exit the cell, I can't see my departure time anymore
![image](https://github.com/user-attachments/assets/2e5d3430-6928-4dd3-b632-f0b5949a431c)

If I click on the cell, it is still here

### What did you expect to happen?

I expected to see my departure time

### How can we reproduce it (as minimally and precisely as possible)?

As above

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

80973c5

**Comment by louisgreiner** [comment]
Looks like it's fixed somehow ?

**Comment by axrolld** [comment]
I'm closing this beause it became an enabler here : https://github.com/OpenRailAssociation/osrd/issues/8894.
Feel free to re-open if you disagree
