### ISSUE TITLE
The waypoint multi-select modal is dynamic

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#8628]
### Description and goal

Now that we can display the waypoints modal, we should be able to save the changes and update the manchette accordingly.

### Acceptance criteria

- [x] By default, the manchette should only display waypoints with these CH codes : "BV", "00", "" and vias added by map click (no ch)
- [x] In proportional mode, hiding a waypoint shouldn't change their position in the manchette
- [x] In linear mode, hiding a waypoint moves the following ones towards the previous one
- [x] The configuration should be saved in local storage so that when coming back to the same scenario/train, the displayed waypoints are the same
- [x] When deleting a (or multiple) project/study/scenario, the localStorage should be cleaned for keys containing the corresponding timetable id's
- [x] The space time chart should still resize according how many waypoints are displayed in the manchette

**Comment by Tguisnet** [comment]
The main work is done,
however there is still a strange behavior for the linear case, hiding the first or last points (required),
and the warning when we only have 2 points could hide some points (optionnal)

**Comment by Tguisnet** [comment]
To be more precise : 
If we hide the first, or the last points, we should truncate the results.
It means we should have a normal GET on the path of the manchette (with the beginning and the end of the line, with the train name, ...)
We should not see a line in the GET going outside the path of the manchette.
The behavior should be the same in linear or proportionnal mode.

**Comment by emersion** [comment]
Eh, is this really the intended behavior? Even if previous OPs are hidden, it's not like the train starts at the first visible OP. Makes much more sense to make this clear by showing the continuation of the path past the first/last visible OP.

**Comment by Castavo** [comment]
After #9513 and #9592, it is done 😁
