### ISSUE TITLE
Identify unrecognized PR in the infrastructure

### ISSUE THREAD

**Issue by Caracol3** [OpenRailAssociation/osrd#8652]
### Description and goal

In Operational Studies > Route, use the endpoint created in issue #8636 to:
- Mark unrecognized PRs in red in the list.
- Ensure that valid PRs are displayed on the map.

Part of: https://github.com/osrd-project/osrd-confidential/issues/632

### Acceptance criteria

- [ ]  Unrecognized PRs are now displayed in red in the Itinerary component list.
- [ ]  Unrecognized PRs are no longer visible on the map.
- [ ] The number of each PR on the map remains the same, even if some PRs are withdrawn.
- [ ]  Valid PRs are still displayed in black.
- [ ]  If the origin is not recognized, it is not replaced by the next point on the map.

**Comment by flomonster** [comment]
>     * Ensure that these PRs are no longer displayed on the map.

You mean ensure valid PRs are displayed on the map?

**Comment by Caracol3** [comment]
> > ```
> > * Ensure that these PRs are no longer displayed on the map.
> > ```
> 
> You mean ensure valid PRs are displayed on the map?

Yes, totally what i mean 😇
