### ISSUE TITLE
Modify STDCM endpoint to take a train consist instead of a rolling stock

### ISSUE THREAD

**Issue by woshilapin** [OpenRailAssociation/osrd#8670]
Today, the STDCM search request expect a rolling stock as an input information for the physics of the train. But we will need to make that endpoint evolve in order to provide:
- a locomotive
- a towed rolling stock
- a total length
- a total weight
- a "code composition"
- a gabarit

Once this new API is exposed, `editoast` must also transform all this information into the physical information that `core` need to resolve the STDCM request.

**Comment by maelysLeratRosso** [comment]
https://github.com/OpenRailAssociation/osrd/pull/9383

**Comment by axrolld** [comment]
Bug found on dev environment:
https://github.com/OpenRailAssociation/osrd/issues/9530
