### ISSUE TITLE
Weird glitch on the STDCM map

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#8693]
### What happened?

![image](https://github.com/user-attachments/assets/f9b279ad-e44a-4cbf-a875-bde709a3358d)

Weird grey dots appear on the map (only in the STDCM display)

### What did you expect to happen?

No weird dots

### How can we reproduce it (as minimally and precisely as possible)?

1. go to STDCM interface
2. look at the map
3. zoom on the dots

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging 80973c5

**Comment by celine-sncf** [comment]
Seems linked to the relief layer.
Maybe change the default setting in STDCM for a quick fix?

**Comment by celine-sncf** [comment]
![image](https://github.com/user-attachments/assets/ba8ab0c7-0106-4250-8771-aa80c90c4254)

**Comment by axrolld** [comment]
@celine-sncf this seems fixed now. Can i let you close this issue if that's the case ?

**Comment by celine-sncf** [comment]
can't test as the map server is down, I will reopen later if necessary
