### ISSUE TITLE
Import trainSchedules from a Viriato file

### ISSUE THREAD

**Issue by RomainValls** [OpenRailAssociation/osrd#8718]
### Description and goal

Related to https://github.com/osrd-project/osrd-confidential/issues/570
We should be able to import trainSchedules in the OSRD timetable, from a Viriato file. 

### Acceptance criteria

- [x]  Pouvoir déposer un fichier Viriato à l'aide du bouton d'import de circulation déjà présent dans les scénarios OSRD (le même bouton sera utilisé pour les imports json et xml, et le format sera reconnu pour savoir de quel type d'import il s'agit)
- [x] Les circulations importées depuis Viriato sont présentes dans OSRD, avec (cf plan d'implem pour savoir quel attribut du fichier xml utiliser) :
Le nom
L'heure de départ
La fréquency (sous forme de label) : cette fréquence est lue dans Viriato comme l'écart entre les 2 premiers trains du trainGroup. S'il n'y en a qu'un, on met 1h par défaut
La catégorie (sous forme de label)
Les points de passage
Les horaires aux points de passage
Les temps d'arrêt aux points de passage

**Comment by louisgreiner** [comment]
Excellent work, some work left to do later:
- better matching for rolling stocks (including rolling stock category) (https://github.com/osrd-project/osrd-confidential/issues/698)
- frequencies (https://github.com/osrd-project/osrd-confidential/issues/731)
