### ISSUE TITLE
front: bad length passed to formatSuggestedOperationalPoints()

### ISSUE THREAD

**Issue by emersion** [OpenRailAssociation/osrd#8725]
### What happened?

In `front/src/modules/timesStops/hooks/useOutputTableData.ts`, `path.length` is passed to `formatSuggestedOperationalPoints()`. This is then passed to `getPointCoordinates()`. However that function expects a position in millimeters, not an index.

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

.

### OSRD version (top right corner `Account` button > `Informations`)

53bd1e9cf713

**Comment by axrolld** [comment]
@emersion how severe is this bug ?

**Comment by emersion** [comment]
After further investigation it seems like `path.length` is actually a distance in mm instead of an array length. Sorry for the noise!
