### ISSUE TITLE
Waypoints displayed with only the operational point id, not the operational point name

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8742]
### What happened?

https://github.com/user-attachments/assets/174ca494-340b-4cb5-9813-f0c5d0a67c09

### What did you expect to happen?

I expect the waypoint labels on the map and in the time sheet to be displayed with their name (like Paris Gare de Lyon and Marseille Saint Charles here)

### How can we reproduce it (as minimally and precisely as possible)?

1. Upload [ply_mas.json](https://github.com/user-attachments/files/16868759/ply_mas.json) to a scenario
2. Edit the train and witness

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

4a5c4bc

**Comment by clarani** [comment]
Still here :cry:

**Comment by Castavo** [comment]
Can't reproduce anymore (on 9e75ce2)
