### ISSUE TITLE
Users and groups management endpoints

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#8752]
### Description and goal

Part of https://github.com/OpenRailAssociation/osrd/issues/8749

Create endpoints to expose users and groups management. 

From the [design document](https://osrd.fr/en/docs/reference/design-docs/auth/#group-and-role-management-api):

```
GET /authn/me (*)
GET /authn/user/{user_id} (*)
POST /authn/group
POST /authn/group/{group_id}/add
POST /authn/group/{group_id}/remove
DELETE /authn/group/{group_id}
```

`(*)`: the roles are not to be returned and will be managed separately.

### Acceptance criteria

The endpoints exist.

**Comment by celine-sncf** [comment]
postponed waiting for a permission system
