### ISSUE TITLE
Setup new repo osrd-images with 4 categories

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#8783]
Create a new repository osrd-images
Add images and the json file (that list all available images)
Add a Dockerfile running a nginx image
Add the service to osrd-chart
Adapt docker-compose.yml for devs
Bump SNCF chart

CF: https://github.com/osrd-project/osrd-confidential/issues/513

**Comment by younesschrifi** [comment]
CR réunion @thibautsailly @younesschrifi 18/09

Thibaut va définir une proportion d'image. 
La prévisualisation et l'utilisation de l'image dans OSRD se fait dans ce format. 
Ou le faire ? front ou osrd-images ?
Si quelqu'un importe un png de 500ko: on essaye de compresser l'image en jpeg si c'est plus petit que.

A ajouter au README : Il faut faire un check qui vérifie la taille des images et si + de 500ko ca fail.

Description d'images ? Comment faire ?

**Comment by Tguisnet** [comment]
Done
