### ISSUE TITLE
Speed space chart: Some speed limit tags are displayed in light gray

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8806]
### What happened?

In the speed space chart's speed limit tag linear view, some tags are displayed in light gray rather than the usual darker gray.

![image](https://github.com/user-attachments/assets/c0b9b6b8-1ee4-4d79-af32-48658eefea1f)

### What did you expect to happen?

I expected the tags to have the same grey as the others:
![image](https://github.com/user-attachments/assets/618eea68-cfb1-40f2-8632-84d1c3ad5dbc)

(in the screenshot, some are light too...)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Upload this [train_schedule](https://github.com/user-attachments/files/16931344/train_schedules.4.json)
3. Open the speed space chart
4. Tick the  box to show speed limit tags
5. Witness

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

72cd833

**Comment by Castavo** [comment]
I added the `severity:major` label because it makes the tags pretty hard to read (at least when you have poor screen contrast)

**Comment by clarani** [comment]
It was fixed by @flomonster in a recent PR
