### ISSUE TITLE
Core: operational-studies: amend MRSP to consider safety speed of approach & short slip distance

### ISSUE THREAD

**Issue by bougue-pe** [OpenRailAssociation/osrd#8810]
Main part of https://github.com/osrd-project/osrd-confidential/issues/305

Depends of #8809 

Lower MRSP speed to 30 km/h 200m before signal if on closed signal.
Also lower to 10 km/h 100m before signal if short slip distance is triggered.

~Trigger the 2 limitations automatically before a buffer stop.~ see #9283 

+ tests

**Comment by Castavo** [comment]
> Trigger the 2 limitations automatically before a buffer stop.

Done in #9283
