### ISSUE TITLE
front: output table - reception on closed signal checkbox doesn't match payload content 

### ISSUE THREAD

**Issue by Morgane-SJK** [OpenRailAssociation/osrd#8817]
### What happened?

I imported this [timetable_payload.json](https://github.com/user-attachments/files/16944049/timetable_payload.json)

We have on_stop_signal = True for the first stop (Tain l'Hermitage) but the checkbox "reception on closed signal" is not checked 
![image](https://github.com/user-attachments/assets/a00dc1bb-940d-49f8-be57-fba70fb8ab10)

### What did you expect to happen?

The checkbox "reception on closed signal" should be checked in the line 5

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Operational Studies
2. Create a Project - Study - Scenario
3. Click on"Import" and then on the Upload button, to upload the payload above
4. Go to simulation results

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

staging ef82519

**Comment by clarani** [comment]
Can't reproduce, this bug must have been solved lately :white_check_mark:
