### ISSUE TITLE
Train can't respect it's schedule even though only one margin is set for the whole path

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8833]
### What happened?

When simulating [this train](https://github.com/user-attachments/files/17260143/train_schedules_cant_respect.json), which contains one margin and some stops, the scheduled points aren't respected. 

For example:
![image](https://github.com/user-attachments/assets/85b650ac-5861-4f78-8ee4-f7cdccc8c2e4)

### What did you expect to happen?

I expected the train to be able to follow its schedule, with or without stops

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario on a large infra like France
2. Load the train I linked in description
3. Witness the lateness displayed
4. (you can remove all the stops while leaving the waypoints to see that there aren't lateness problems then)

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

ef349bf

**Comment by Castavo** [comment]
I mark this as critical because we're building a simulation tool. If the simulation isn't accurate (at least accurately displayed), we're no good

**Comment by clarani** [comment]
Still here :cry:

**Comment by kmer2016** [comment]
Can be fixed by #9737

**Comment by Castavo** [comment]
This has been fixed

Some somewhat strange behavior remains, but it's tracked here https://github.com/OpenRailAssociation/osrd/issues/9737#issuecomment-2520959280
