### ISSUE TITLE
Rename occurences of mrsp to speed_limits

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#884]
MRSP now refers to the max speed a train can have on a certain path, with accelerations being allowed when the tail of the train left the speed section.

Speed limits, on the other hand, refer to the actual speed restrictions on the infrasctructure + the max speed of the train, without taking into account the train length. The speed limit should be displayed in front end, not the MRSP.

**Occurences of mrsp in api and front files should be renamed to speed_limits**, as well as "vmax" in standalone_simulation_report.py, which is french.

A migration needs to be created as the TrainSchedule model will be changed.

EDIT : we found some occurences of **mrps** instead of mrsp, rename them into speed_limits as well.

**Comment by SaumyaBhushan** [comment]
Can you please assign this to me?

**Comment by axrolld** [comment]
Hi,
I assigned you to the issue. You need to fork the project then create a PR.
Good luck with this issue, and thanks a lot for your help ! :)

**Comment by SaumyaBhushan** [comment]
>> "A migration needs to be created as the TrainSchedule model will be changed." Can you please tell me how can I create a migration?

**Comment by eckter** [comment]
Start the containers (`docker-compose up --build` at the root of the repo)

Then run `docker exec -it osrd-api python manage.py makemigrations`

This should generate a file in `api/osrd_infra/migrations/`, something like `0009_auto_change_train_schedule_model.py`. Rename it to something more meaningful like the other files, then git add it.

Please let me know if it doesn't work, I could have forgotten a setup step. [More info on migrations](https://docs.djangoproject.com/en/4.0/topics/migrations/)

**Comment by SaumyaBhushan** [comment]
Ok, Thanks
