### ISSUE TITLE
front: The first line of the output table is orange when there is a clicked via before

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#8848]
### What happened?

On the output table of a simulation, the first line is orange if the first real via is a clicked via on the map (meaning we are late, but it's not true)

I add a VIA just before the OP on a Paris-Marseille train
![image](https://github.com/user-attachments/assets/e1fe22dc-1809-4691-8371-6c0a50599226)

the first line of the output table is orange
![image](https://github.com/user-attachments/assets/cedb4880-e34e-42f0-8b0e-5e13dc4f526b)

### What did you expect to happen?

we should see the via in the output table (there is an other issue for this)
and the first line should not be orange if we are not late

### How can we reproduce it (as minimally and precisely as possible)?

1. go to a scenario
2. create a train with a clicked via for the start of the schedule
3. check the output table after the simulation

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

bc8b913

**Comment by clarani** [comment]
Still here :cry:
