### ISSUE TITLE
Space time chart: Changing the projection several times ends up freezing the tab

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#8849]
### What happened?

https://github.com/user-attachments/assets/f6c00947-7e3c-4dcb-adc7-bb126c549e10

When you click on different circulations, to chose them for projection, after 5 or 6, you end up freezing the tab

### What did you expect to happen?

I expect the tab to never freeze

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to to a timetable with a decent amount of trains (here around 140)
2. Click on several trains for projection
3. Witness death

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

bc8b913

**Comment by clarani** [comment]
I can't reproduce this bug, can you @Castavo ?

**Comment by Castavo** [comment]
I would like to try on a deployed env but they're down at the moment

**Comment by Castavo** [comment]
Couldn't reproduce ! Neat !
