### ISSUE TITLE
front: Speed-limit tags not properly displayed on speed-space chart

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#8853]
### What happened?

https://github.com/user-attachments/assets/b8e7ab52-6048-48e7-a850-ac7e55b149a4

Many bugs for speed limit tags on speed space chart:
- blinking
- overlapping white zones

https://github.com/OpenRailAssociation/osrd/issues/8328#issue-2447943365

This issue might be duplicate of other bug issues related to the GEV

### How can we reproduce it (as minimally and precisely as possible)?

1. Create train schedule with speed-limit tag
2. Notice bug on speed-chart

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

c62c9db6

**Comment by Castavo** [comment]
Also tracked in https://github.com/OpenRailAssociation/osrd-ui/issues/427

**Comment by Synar** [comment]
Blinking issue is solved by [ui-speedspacechart: fix speedlimittags layer blinking OpenRailAssociation/osrd-ui#633](https://github.com/OpenRailAssociation/osrd-ui/pull/633)

I don't understand what you meant by "overlapping white zones" though

**Comment by louisgreiner** [comment]
I meant the multiple overlaping layers, i guess the warnings should be displayed on top of all of them. But i think we can close this issue anyway

**Comment by Synar** [comment]
Ok thanks! I guess we can open an issue for this in osrd-ui?

**Comment by louisgreiner** [comment]
I can't repro it anyway, no need for now i would say
