### ISSUE TITLE
front: tooltip on the speed-space chart doesn't work on extremities

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#8855]
### What happened?

When we try to have the tooltip on one of the extremity of the GEV, there is no infomartion
it may be correlated to the fact that we have a via clicked on extremities.

on the left : 
![image](https://github.com/user-attachments/assets/1e17c072-763f-49dc-bcad-f92e16f5d3e4)

on the middle : 
![image](https://github.com/user-attachments/assets/304b0f94-a554-419e-842b-aae9eb3c36b3)

ont the right : 
![image](https://github.com/user-attachments/assets/ba16cd2d-51dd-4a5e-ad2a-a4c253db3827)

### What did you expect to happen?

The tooltip should be always displaying the right infos

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scneario
2. create a valid train schedule with a starting point, and an arrival point clicked on the map
3. try to see the tooltip on the gev ont the extremities

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

bc8b913

**Comment by axrolld** [comment]
Duplicate with https://github.com/OpenRailAssociation/osrd/issues/8293
