### ISSUE TITLE
STDCM date selector does not use the search environment variables

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#8877]
### What happened?

When selecting a departure (or arrival) date. The component proposes invalid dates.
However, selecting an invalid date does nothing.

![image](https://github.com/user-attachments/assets/454b8173-fe5d-4154-b9d3-bd1448dc6a58)

In this example, only the 17th and 18th are valid dates.

### What did you expect to happen?

Only valid dates should be selectable. To know what dates (and times) are legit, the frontend should use the configuration returned by the search environment endpoint.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM (new interface)
2. Try to select a departure date

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6ea7e5609cfa77d9854d34043a10707adc504fa5

**Comment by Castavo** [comment]
Are you sure it's not the environment that has the wrong date ?

**Comment by flomonster** [comment]
> Are you sure it's not the environment that has the wrong date ?

Since selecting an invalid date does not work, I think so.

**Comment by kmer2016** [comment]
> Are you sure it's not the environment that has the wrong date ?

Yes, it looks like the environment dates are correct. Here's the data from the backend.
```json
{
    "id": 20,
    "infra_id": 88,
    "work_schedule_group_id": 171,
    "timetable_id": 544,
    "search_window_begin": "2024-09-17T00:01:00",
    "search_window_end": "2024-09-18T23:59:00"
}
```
~~However, I can't reproduce it in my local environment~~.
It's okay, I can reproduce it now.

**Comment by younesschrifi** [comment]
![image](https://github.com/user-attachments/assets/4f54f8d6-df6a-46d0-b096-784f6538092f)

I re-open this ticket after testing STDCM this morning : only 2 and 3 october should be available.

**Comment by Maymanaf** [comment]
Le correctif n'était pas en recette.
Après le déploiement : 
![image](https://github.com/user-attachments/assets/ecaacb94-b2c3-45a7-9763-917fded4b2b5)
