### ISSUE TITLE
When using suspense with i18n, simulation page isn't correctly displayed.

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#888]
Simulation view is not correctly displayed, all charts are way too big when page refresh.
It seems to be related to use of suspense with i18n in i18n.js and can be corrected with setting suspense false for i18n : 
```
react: {
  useSuspense: false,
},
```
But we see page loading with artefacts instead.

**Comment by flomonster** [comment]
Done
