### ISSUE TITLE
bug: when trains are created, the reservation of first route is forced

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#89]
https://github.com/DGEXSolutions/osrd-core/blob/dev/src/main/java/fr/sncf/osrd/infra_state/RouteState.java#L131-L141

This was a workaround not to make trains appear on non-reserved routes, but it can cause bugs when a train is created after t=0 as we also force switch positions with no delay.

**Comment by multun** [comment]
@eckter does it still make sense?

**Comment by eckter** [comment]
outdated
