### ISSUE TITLE
editoast (+front?): forbid the creation of a RS effort curve with only one point

### ISSUE THREAD

**Issue by bougue-pe** [OpenRailAssociation/osrd#8906]
### What happened?

RS editor was unreachable as editoast responded a 500 error "effort curve should have at least 2 points." on `osrd/api/light_rolling_stock?page_size=1000`.

### What did you expect to happen?

This is probably OK to enforce >=2 points in effort curves, but it should be enforced everywhere especially as input, more than as output (no way to fix it once triggered).
Maybe it shouldn't block any other use/display of RS.
Maybe editoast should prevent the use of the wrong RS more than the display.

### How can we reproduce it (as minimally and precisely as possible)?

To be determined how it was triggered, more details (private) are available on https://matrix.to/#/!OFgKOGqOogHLDtUerJ:osrd.fr/$aEWkCBKw_XL_hI115bm8sgFR6kPpicF7edOmbIrzvLU?via=osrd.fr&via=matrix.org.

### On which environments the bug occurs?

Integration (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

v0.3.2 6ea7e56

**Comment by Sh099078** [comment]
I could not reproduce the bug by calling the endpoint locally on the current dev branch or on the integration environment.

The curve minimal length is already checked upon creation in the create endpoint and also when deserializing a rolling stock from the railjson format. There is already a related test `create_rolling_stock_with_invalid_effort_curve` in the rolling stocks view and a unit test `test_effort_curve_invalid_due_to_single_point` in `schemas`, both passing.

I have not found yet anything in Editoast that allows to create a rolling stock with an invalid effort curve. Maybe it was due to some semantically invalid entry in a DB dump ?

**Comment by bougue-pe** [comment]
## As for the precise bug at hand
I still don't know how we got to the situation where only one point was in a given effort curve.

But to me the consequences of the current behavior are way too important compared to the functional problem at hand: a broken train data leads to nobody being able to use RS editor until someone accesses and correct PG by hand, AFAIK.


## "Side-bug"
but related locally on commit 8ed63d0be19b1c29158544c6593ac37c83086a41 (current `dev`) on Firefox:
* I try to copy a RS (`15000`) and edit one of its effort curve (`20000V`) to have a single point.
* ✅ End up with a correct "invalid curve" error on confirm, so cancel
* ❌ I try to completely remove the curve and get this same error on confirm
* ❌ I try to just change the name of the RS, and get the same error
* ✅ I can edit another RS correctly, ❌ but going back to that first RS, I always get the error
* When I empty the cache ✅ I can edit the name, ❌ but not remove a curve (which is probably wrong) or ✅ get it to a one-pointer (which is good)


## Conclusions and propositions
1. I think it's worth another opinion (@flomonster ?) on the original issue to see if we should reconsider:
  a. we try to be more resilient to the case (reopen)
  b. or if we wait for it to happen again (keep closed) hoping that it never happens or if it happens we will be reactive enough to unlock users and we will be able to understand how we got to that situation
2. Probably open a separate issue for the side-bug detected (will do it once reproduced/considered worthy by someone else)

**Comment by bougue-pe** [comment]
As previously discussed, reopening this as the closing was too rushy.
Triage (@flomonster ?) is still required: see 'conclusion' above on this ticket and a possible second one.

**Comment by bougue-pe** [comment]
As discussed with @flomonster : no further work on the main issue for now, considering that it's probably a PG manip that broke OSRD, a PG manip is a solution considered OK to bring it up again.

I could not reproduce the "side-issue" (either no bug from the start, or already fixed), so not opening additional issue either.
