### ISSUE TITLE
stdcm: unnecessary check on unscheduled point triggers an error

### ISSUE THREAD

**Issue by SarahBellaha** [OpenRailAssociation/osrd#8915]
### What happened?

When you try to run a simulation with a scheduled destination, the date validity check is also performed on the starting point, which is not necessary.

### What did you expect to happen?

The departure point doesn't need to be checked if it's the destination we want to schedule.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM (new interface)
2. Set arrival time for departure point to 00:00 then change to “as soon as possible”.
3. Set an arrival time for destination.
4. Run the request and see the error pop-up.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6ea7e56

**Comment by bloussou** [comment]
Reopening and bumping this to critical as it is not fixed:
I have done the step 1 2 and 3 and I get:

![Image](https://github.com/user-attachments/assets/9a17d980-5f18-4e1d-a12c-675b227605c4)
even if my date is correct
