### ISSUE TITLE
STDCM: Arrow icon is displayed in the Select dropdown

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#8927]
### What happened?

![image](https://github.com/user-attachments/assets/3eaef329-4a0a-4fc4-af68-7fbe70cb6cb0)

![image](https://github.com/user-attachments/assets/821bdc1c-775e-422f-a3e2-f762434e7c7d)

### What did you expect to happen?

https://www.sketch.com/s/15e0909c-f17d-4200-a770-b9fc1154fa7e/a/uuid/6A7DDAAA-7220-4462-BED8-ECB57ECA3DFE

### How can we reproduce it (as minimally and precisely as possible)?

Check screenshots

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

fbf8e3e

**Comment by bougue-pe** [comment]
Problème confirmé avec un élément supplémentaire sur Firefox 130.0.1 Windows, `staging fbf8e3e`
La police des listes (CH ou Horaire précis) ne sont pas identiques à celle sélectionnée :
![image](https://github.com/user-attachments/assets/27ab493e-02bf-438d-b0c7-d109160b885f)

**Comment by bougue-pe** [comment]
Hello @kmer2016
Je confirme que la flèche est OK, mais je constate toujours le souci de police (en local sur `48fa0f65264b36bf691a73c553bf5c74c8b4551c`)

Pour `horaire précis` :
 ![image](https://github.com/user-attachments/assets/fc079e5e-f4f4-4e0f-93b6-b7d03dc29329)
Et également pour le `CH` :
![image](https://github.com/user-attachments/assets/12f1922d-0b2e-47e1-9fd9-a6a22ed0e5a2)
(le `CI` est OK ✅)

Je peux décaler ça dans une autre issue si ça aide.

**Comment by bougue-pe** [comment]
Font issue moved in a dedicated issue https://github.com/OpenRailAssociation/osrd/issues/8988
