### ISSUE TITLE
GET and manchette horizontal lines for operational points are not in sync

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8930]
### What happened?

In many cases, Km or Linear, the lines from the machette aren't aligned with the horizontal blue lines of the GET:
![image](https://github.com/user-attachments/assets/00839791-4e17-4bb8-af5a-0c31ab33e265)

Same here with a lot of zoom:
![image](https://github.com/user-attachments/assets/9abd0d55-2cac-497f-816d-dbbcdb59e6a3)

And in a case of a very unzoomed view, there are too many horizontal lines in GET:
![image](https://github.com/user-attachments/assets/5052e778-204d-4a93-b85d-16be2d31609f)

### What did you expect to happen?

I'm expecting the lines to be in sync.

### How can we reproduce it (as minimally and precisely as possible)?

1. Manipulate the GET

### On which environments the bug occurs?

Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

68e0513

**Comment by axrolld** [comment]
Another example on a Paris-Nice:
![Image](https://github.com/user-attachments/assets/4f50677f-a7da-4d11-8384-b5f6c7d0f12d)

**Comment by Castavo** [comment]
https://github.com/OpenRailAssociation/osrd-ui/issues/497 in osrd-ui
