### ISSUE TITLE
STDCM: The selected value is cleared if there is more than one suggestion in the autocomplete field

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#8934]
### What happened?

https://github.com/user-attachments/assets/34e107e6-6b24-4feb-9ff6-38296493116b

### What did you expect to happen?

**The selected value remains intact since this issue doesn't occur when there is only one suggestion**

### How can we reproduce it (as minimally and precisely as possible)?

1. Select a CI from the autosuggest field
2. Click on the field
3. Click outside

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

fbf8e3e

**Comment by SarahBellaha** [comment]
It's not a bug, it's the expected behavior of this component. 
The user tests are coming soon, and we'll be able to get some feedback on that.
Then we can discuss it again with @thibautsailly :)

**Comment by bougue-pe** [comment]
This is also cleared if no value was selected before (like typing, then misclick or focus change or notification).
This felt like a bug when I used it: I wanted to check in another window the exact spelling, and I had to type it all again.

**Comment by axrolld** [comment]
Cannot reproduce

**Comment by bougue-pe** [comment]
cc @axrolld I think there are still some problems (even more `minor` than the original one IMO)

## As for the original clearing bug
I can't reproduce exactly either (local firefox, on commit 8ed63d0be19b1c29158544c6593ac37c83086a41).
But it has evolved and now the prompt changes (from `Miramas` to `MAS Miramas`) on the first focus change (maybe not the actual value used)
https://github.com/user-attachments/assets/54e9b3f2-ad0f-4536-b9b5-5fd2a4f60671

## As for the behavior I mentioned when losing focus before selecting a value
I have the same kind of weird prompt not matching the actual behavior: prompt is emptied, but the list matches previous input
On the following video, I was able to "chain" the 2 issues:
https://github.com/user-attachments/assets/659b83e6-737f-4c6a-ba12-54661e93f60d

**Comment by bougue-pe** [comment]
As discussed with @axrolld , those 2 side-bugs are tracked already.
