### ISSUE TITLE
Wrong train name in my GET

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8935]
### What happened?

Might be linked to https://github.com/OpenRailAssociation/osrd/issues/8551

I have a timetable with 2 trains : ter, going from Rennes to Quimper, and baba, on a totally different itinerary.

My GET is displaying the ter (the manchette goes from Rennes to Quimper), but the name "baba" is displayed. baba shouldn't even be on this GET because it shares absolutely no itinerary with ter.
![image](https://github.com/user-attachments/assets/1ca39b84-ddcb-4d53-b5d3-0b13709c91e6)

And it's not just about the name being displayed: the train appears in black when ter is selected, and in blue when baba is selected. So it's really considering that this train is baba.

### What did you expect to happen?

I'm expecting the GET to display the right train name and having the selected train in blue.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to https://dev-osrd.reseau.sncf.fr/operational-studies/projects/9/studies/10/scenarios/110

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

68e0513

**Comment by eckter** [comment]
Likely related (possibly duplicate) with https://github.com/OpenRailAssociation/osrd/issues/8537

**Comment by anisometropie** [comment]
This was fixed by https://github.com/OpenRailAssociation/osrd/pull/8954

The trains were given a random redis cache key, which was causing both this issue and https://github.com/OpenRailAssociation/osrd/issues/8952
