### ISSUE TITLE
Infinite pathfinding loading even after waiting for the infra to load

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8945]
### What happened?

![image](https://github.com/user-attachments/assets/a1e5f319-8e1a-4258-b8fc-d67a22c6577d)

Also had this bug after looking for a path on a recently edited infra so it seems related to infrastructure loading but since the front doesn't display it anymore i don't know what's going on...

But the bug remains on `int`, even after hours waiting for the infrastructure to load.

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

Try a pathfinding on `int`

### On which environments the bug occurs?

Recette (SNCF), Integration (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

6ea7e56

**Comment by axrolld** [comment]
Bug caused by the infrastructure loading and core being down sometimes. It will be fixed when we'll get back the info of the infrastructure loading.
The cores crashing should be investigated in any case.

**Comment by bloussou** [comment]
Fixed
