### ISSUE TITLE
Make STDCM simulation sheet lighter

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8978]
### What is this feature about?

STDCM simulation sheet weights ~500ko/1Mo. This might be a bit heavy, it would be nice to be able to reduce this wigth by at least one order of magnitude.

This can be done by working on the map image, trying to make it lighter.
If it has a huge impact the map could pententially even be removed.

### Why is this feature valuable?

This feature matters because it will not overwhelm the train slot command software.

**Comment by Maymanaf** [comment]
OLD STDCM simulation sheet for Valence - Miramas = 1214ko
New STDCM simulation sheet for Valence - Miramas = 207ko
