### ISSUE TITLE
STDCM: font changes in the Select dropdown for `CH` and `precise time`

### ISSUE THREAD

**Issue by bougue-pe** [OpenRailAssociation/osrd#8988]
### What happened?

For `precise time` :
 ![image](https://github.com/user-attachments/assets/fc079e5e-f4f4-4e0f-93b6-b7d03dc29329)
Also for `CH` :
![image](https://github.com/user-attachments/assets/12f1922d-0b2e-47e1-9fd9-a6a22ed0e5a2)
(`CI` is OK ✅)

Follow-up on https://github.com/OpenRailAssociation/osrd/issues/8927

### What did you expect to happen?

Have the same font in dropdown than in the field.

### How can we reproduce it (as minimally and precisely as possible)?

Firefox 130.0.1 - Windows - dev 2d53fc9 :

1. Trigger STDCM new interface
2. Go to STDCM
3. Add "VCE Valence" as CI
4. Clic the dropdown for "CH" and "precise time"

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

2d53fc9

**Comment by clarani** [comment]
Unrelevant now ✅ 

Tracked in #9173
