### ISSUE TITLE
fix size, spacing and size in new stdcm interface 

### ISSUE THREAD

**Issue by Akctarus** [OpenRailAssociation/osrd#8991]
### What happened?

Some component have weird padding or placement, it should be pixel perfect based on the mock-up. We should also transform all the "px" to "rem"

other issue : https://github.com/OpenRailAssociation/osrd/pull/8656#discussion_r1774104322

- padding-left in cards body suggestions is wrong (must be 24px)

- paddings in feedback are wrong

- Spacing between the 3 elements doesn't seem to respect to respect the mockup (16px) : 

![image](https://github.com/user-attachments/assets/490f4313-1fa3-4f1e-92e0-1bd50cf0dd66)

### What did you expect to happen?

I expect the page to be pixel perfect

### How can we reproduce it (as minimally and precisely as possible)?

Go to the new interface and check the style

### On which environments the bug occurs?

Local, Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

81bb69a

**Comment by clarani** [comment]
Seems unrelevant now ✅
