### ISSUE TITLE
STDCM: The inputs are not aligned in the Consist

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#9013]
### What happened?

![image](https://github.com/user-attachments/assets/4e5c3ba4-e267-40f9-a850-b6cd972d4042)

### What did you expect to happen?

Should be the same as in the sketch
![image](https://github.com/user-attachments/assets/e15d00fe-e3af-4395-aeb9-a501df071717)

### How can we reproduce it (as minimally and precisely as possible)?

See screenshot

### On which environments the bug occurs?

Dev (SNCF), Recette (SNCF)

### OSRD version (top right corner `Account` button > `Informations`)

a5e9ca2

**Comment by axrolld** [comment]
This is fixed now, i'm closing this

**Comment by clarani** [comment]
Validated ✅
