### ISSUE TITLE
editoast: can't connect to rabbitMQ

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9014]
### What happened?

When loading an infra, web console prints this:

![image](https://github.com/user-attachments/assets/26c767a0-af0c-446f-b608-6c32248ff3e9)

### How can we reproduce it (as minimally and precisely as possible)?

1. create scenario and load a new infra
2. open console

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging a5e9ca2

**Comment by flomonster** [comment]
Can't reproduce
