### ISSUE TITLE
core: 2 same trains are no longer in itinerary conflict

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9022]
### What happened?

Tried this test : https://github.com/osrd-project/osrd-tests/issues/48

### What did you expect to happen?

2 conflicts detected:
- spacing
- itinerary

### How can we reproduce it (as minimally and precisely as possible)?

1. https://github.com/osrd-project/osrd-tests/issues/48

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging a5e9ca2

**Comment by bougue-pe** [comment]
Just tested it on a single track section (Clisson - Cholet) and the behavior seems to be the one expected:
* 2 trains in opposite directions (the first part of the test) lead to both spacing and routing conflicts
* 2 identical trains lead to a spacing conflict but no routing conflict (the route established for one is OK for the other)

So to me, the test should be adjusted to a **single-track section** and maybe less ambiguous names (PLY and LYD are easy to mix... Which might also be the case for CLI and CHT?)

**Comment by louisgreiner** [comment]
Updated the test case, thanks, and closing this issue.
