### ISSUE TITLE
stdcm: front: Changing CH code on via point resets the stop

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9025]
### What happened?

I have A 10mn stop in Chambéry BV:
![image](https://github.com/user-attachments/assets/22d2deb0-533b-44ba-868d-e7659a43b676)

And i decide to change the CH:
![image](https://github.com/user-attachments/assets/ffdd25a1-3085-4216-8211-7d02e85937a6)

The type of via is back to "passage".

_________

Actually a similar bug exists on the origin point : changin the CH resets the tolerances

### What did you expect to happen?

I'm expecting my stop to remain even if i change the CH code.

### How can we reproduce it (as minimally and precisely as possible)?

1. Reproduce the description

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

a5e9ca2

**Comment by clarani** [comment]
Not relevant anymore, validated by @axrolld ✅
