### ISSUE TITLE
front: input schedule table keeps OPs marked bold if we delete a stop

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9026]
### What happened?

See video

https://github.com/user-attachments/assets/8746c41c-4edc-44e7-8d69-8eac80c91cd0

### What did you expect to happen?

Delete the stops for good

### How can we reproduce it (as minimally and precisely as possible)?

1. like the video

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging a5e9ca2

**Comment by SharglutDev** [comment]
It's kind of the same issue that has been reported many times. When adding a constraint on a waypoint/op, it's considered as a path step and we can't know the difference if it was a required waypoint or not. Until we chose a way to differentiate these 2 kinds of points, I'm not sure we will be able to find a good fix. (@axrolld)

**Comment by louisgreiner** [comment]
Understood, I try to find the answer and then come back to you

**Comment by maelysLeratRosso** [comment]
It is the expected behavior (for now)
