### ISSUE TITLE
Display conflicts between trains.

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#903]
## User

- [X] Study officer
- [ ] Manager
- [ ] Other (please write it here)

## Description

When planning multiple standalone trains, conflicts can appear due to signalling (among other things). The user must be warned if the planned time table has some conflicts.

## Goal

Help the user locate conflicts in order to produce better time tables.

## Acceptance criteria

_To be re-defined._

- [ ] Conflict(s) must appear clearly in the space-time chart, with overlapping zones easily indentifiable 
- [ ] Every train with conflict(s) must stand out with a clear error indicator when unfolding the train list
- [ ] When the user generates a conflict, a warning pop-up must appear in the bottom right corner of the screen
- [ ] This pop-up must dissapear automatically after a short amount of time
- [ ] The message should be "Le train n° [train_number_1] est entré en conflit avec le train n° [train_number_2]"
- [ ] If there are any, a list of conflicts should be displayed just below the train list, unfoldable the same way 
- [ ] Each item of the list must be composed of the two trains in conflict and where the conflict took place (pk)

## Additional content

This is the first mockup for conflict detection. Need update from @carolnvg, work in progress.

![Conflits_v2_capture](https://user-images.githubusercontent.com/86296016/169254806-af9a233a-7cfe-4643-9825-00201b334d6b.PNG)

**Comment by alexandredamiron** [comment]
A proposal for showing Conflicting aspects (zones) 
[Flinking Glowing Show-Off](https://codepen.io/marcorale/pen/OJQmaNz)

<img width="247" alt="Capture d’écran 2022-05-19 à 17 15 47" src="https://user-images.githubusercontent.com/765626/169331316-b44fdb2f-dda1-4505-8bb7-8e3e83656150.png">

The route_aspect collection provided by the TrainSchedule API should specify if a zone is is conflict, an fx rectangle will be happened for these ones

**Comment by axrolld** [comment]
Deleted form PI board because conflicts need more refinement.

**Comment by flomonster** [comment]
Done
