### ISSUE TITLE
Infinite infra loading

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9030]
### What happened?

I'm stuck here
![image](https://github.com/user-attachments/assets/bd870bbb-7789-4ef3-8f5f-777742f003cb)

On France:
![image](https://github.com/user-attachments/assets/d97eb5d5-0c1a-4014-8e48-c858d2665d44)

On small infra:
![image](https://github.com/user-attachments/assets/57a54ffb-0ad8-4618-953e-046f0c207f0d)

Also, `dev` can't find any infra, idk if it's related:
![image](https://github.com/user-attachments/assets/46e048f3-e582-4f8c-b4f8-fce35a6a00dc)

### What did you expect to happen?

The infra to load

### How can we reproduce it (as minimally and precisely as possible)?

1. Open any scenario

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

a5e9ca2

**Comment by Khoyo** [comment]
Could not reproduce (on rec), does it still happen?

**Comment by axrolld** [comment]
Seems fixed

**Comment by axrolld** [comment]
The bug's back on this scenario:
https://rec-osrd.reseau.sncf.fr/operational-studies/projects/19/studies/199/scenarios/693

I duplicated the France infra and created a scenario with it but the infra doesn't load

**Comment by Khoyo** [comment]
It does, it's just slow

**Comment by axrolld** [comment]
Ok my bad it remained at 0/7 for a while i thought it was blocked
