### ISSUE TITLE
nge: newly created node position isn't persisted after search this node in infra

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9031]
### What happened?

If we create a node in NGE, create a trainrun with it, go back to micro then macro again, because the node has changed (if it's found in the infra), the position is not persisted.

### What did you expect to happen?

Position is shared from created node to found one when search

### How can we reproduce it (as minimally and precisely as possible)?

1. open macro
2. create node that your localstorage don't know (let's say VCE for Valence)
3. draw a trainrun from it to another one (let's say LYD)
4. go back to micro
5. go back to macro
6. notice that the nodes have been found, because they now have a `ch` code, but because they are new nodes, their positions are not persisted from before

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging a5e9ca2

**Comment by emersion** [comment]
Probably not worth spending too many cycles on this given we're going to overhaul how node positions are saved pretty soon.

**Comment by louisgreiner** [comment]
Postponed waiting for https://github.com/osrd-project/osrd-confidential/issues/597 to be release
