### ISSUE TITLE
STDCM new interface : some stop types bugs

### ISSUE THREAD

**Issue by Akctarus** [OpenRailAssociation/osrd#9097]
### What happened?

- [x] a blank page may appear when we try to save the simulation (when we select the driver switch without changing the stop time)
- [x] the stop type is not defined on the reloaded page 
- [x] the OP with the stop may appear as “=” if it has the same name as the previous OP. 
- [x] the “passage” stop type does not appear in the results of the simulation table (image 1)
- [x] the “passage” stop type does not appear in blue on the simulation report sheet table (image 2)

![Image](https://github.com/user-attachments/assets/61d9f060-8c5f-47d4-b18f-421212afbcaf)

![Image](https://github.com/user-attachments/assets/ef37b216-9b3c-429b-814d-106b5e0e6570)

### What did you expect to happen?

all work well

### How can we reproduce it (as minimally and precisely as possible)?

Go to the new STDCM interface and add vias 

### On which environments the bug occurs?

Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

a5e9ca2

**Comment by Castavo** [comment]
@Akctarus the stop type is still not saved when refreshing the page
