### ISSUE TITLE
[US] As study officer, I'd like to edit the tracks, in order to create or modify them in to the infrastructure model.

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#914]
## Acceptance criteria
- [ ] I can draw a track from a starting point to an ending point, the positions of these points and the lenght of the track will be automatically set
- [ ] I can read and modify in a text format :  
       - the lenght of the track,
       - the position of starting or ending points,  
       - the ID of the track,
       - the list of the slopes (begin position, end position, gradient in ‰),
       - the list of the curves (begin position, end position, radius of the curve in m)
       if some values are irregulars some warnings/errors will be displayed
- [ ] I can delete a selected track. Two options of selection are proposed :
       - macroscopic selection : all the elements of the deleted track will be deleted
       - microscopic selection : none of the elements of the track will be deleted and an error for each element referencing the deleted track will be dispalyed in the list of errors 

## Difficulty

This user story is difficult

**Comment by flomonster** [comment]
Done
