### ISSUE TITLE
front: stdcm: can't remove intermediate OP fields when they're empty

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#9155]
### What happened?

When we accidentally add an intermediate waypoint and want to remove it, we need to fill it first. Otherwise we can click the "remove" button but it's not actually removed.

### What did you expect to happen?

Clicking the "remove" button should remove the "intermediate OP" block

### How can we reproduce it (as minimally and precisely as possible)?

On the stdcm page, add an intermediate point and try to remove it

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

efce7b7a4bb0342c8f3ba1d05eb64326c893c013

**Comment by Maymanaf** [comment]
Duplicated with #9107
