### ISSUE TITLE
Incorrect location of the conflict list

### ISSUE THREAD

**Issue by theocrsb** [OpenRailAssociation/osrd#9171]
### What happened?

<img width="465" alt="image" src="https://github.com/user-attachments/assets/c6415edb-92d8-4fe3-bbd4-d4c5b529df6a">

### How can we reproduce it (as minimally and precisely as possible)?

Go to scenario
Add 1 train
See the problem

### On which environments the bug occurs?

Local, Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

dev 0f97f32

**Comment by clarani** [comment]
Valiated ✅
