### ISSUE TITLE
stdcm: date picking does not show right days (d+3 instead of d+6)

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#9199]
### What happened?

When inputing parameters for a stdcm search, the dates should be day+6 and day+7 only. Tested as today, the available dates are d+3 and d+4. 
![image](https://github.com/user-attachments/assets/28b41b88-fc09-484d-a984-5e142b271bf1)
It seems stucked on the 7th of october.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to stdcm interface
2. Click on the "date" field picker

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging 1482e8c

**Comment by Maymanaf** [comment]
The dates are inaccurate due to BASIC being down for several days
