### ISSUE TITLE
A train is conflicting with itself

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#9298]
### What happened?

When I create a train Paris - Rennes, he is conflicting with itself
it should be impossible.

this is the schedule I use : [train_schedules_bug_conflits.json](https://github.com/user-attachments/files/17329235/train_schedules_bug_conflits.json)

I was on infra 94 on recette env

### What did you expect to happen?

It should have 0 conflict

### How can we reproduce it (as minimally and precisely as possible)?

1. create a scenario with infra france 94
2. Import the train schedule I join in this issue

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

96c960e

**Comment by Castavo** [comment]
Also encountered it on 7451939, happened when editing a train

**Comment by bougue-pe** [comment]
Probably the same bug as the one detected in https://github.com/OpenRailAssociation/osrd/issues/9389 (to be confirmed)

**Comment by eckter** [comment]
Confirmed, closing, duplicate of https://github.com/OpenRailAssociation/osrd/issues/9389
