### ISSUE TITLE
stdcm computation is running for more than 2mn

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9304]
### What happened?

I've been stuck here for about 5mn now, i don't really know why the timeout isn't triggered:
![Image](https://github.com/user-attachments/assets/d993d706-d662-468b-be73-298204014de8)

### What did you expect to happen?

The algorithm should timeout if no solution is found.

### How can we reproduce it (as minimally and precisely as possible)?

Here are my inputs :
![Image](https://github.com/user-attachments/assets/1d6e4bd6-2e2a-4b7b-9b46-e5658b02102d)

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

96c960e

**Comment by bloussou** [comment]
Current timeout is 5 minutes. I think it is the first step in term of performances. We will see if it is a huge issue but it should be ok
