### ISSUE TITLE
Maps are synchronized in stdcm and should not be

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9312]
### What happened?

https://github.com/user-attachments/assets/227edb00-1c60-4404-b43f-195155e669dc

### What did you expect to happen?

The bottom map should remain focus on the result and display the path if one is found.

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

96c960e

**Comment by clarani** [comment]
Not relevant anymore ✅
