### ISSUE TITLE
Can't import trains from openData

### ISSUE THREAD

**Issue by RomainValls** [OpenRailAssociation/osrd#9315]
### What happened?

We can't create trainSchedules from openData imported trains anymore. 

How to resolve : 

- create a new prop for Viriato imported files, so that don't check invalid ch when trains are imported from openData. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Click import
3. Enter an origin and destination - Search for trains
4. Import the trains

### On which environments the bug occurs?

Recette (SNCF), Dev (SNCF), Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by clarani** [comment]
LGTM ✅
