### ISSUE TITLE
NGE: add stop time after trainrun modification in NGE

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9332]
### What happened?

![Image](https://github.com/user-attachments/assets/0112f5df-1c5c-42c6-8ff1-0735ebf26a13)

![Image](https://github.com/user-attachments/assets/1ce2dd9c-5ef0-45a2-b483-7ed15db3c609)

Trainrun modified in NGE triggers a recalculation of the nodes involved. It then results as a creation of another PR in the input timetable. The problem is that 2 differents items exist for the same PR, resulting in weird behavior:
- different stop times can be set for the same node (PR)
- the route of the trainrun is ****ed
- the input timetable doesn't work anymore

![Image](https://github.com/user-attachments/assets/7a70972f-c64d-455e-a323-192dcb148b71)

https://github.com/user-attachments/assets/626d7929-a95d-45a9-b2b4-f0e10933f254

### What did you expect to happen?

Nodes modified in NGE should result in creating a new PR in the input table

### How can we reproduce it (as minimally and precisely as possible)?

It can be triggered after setting / un-setting a stop at a node for a trainrun in NGE, then look at the input table (bugged), then in macro again (bugged)

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging e66e534

**Comment by emersion** [comment]
Might be fixed by https://github.com/OpenRailAssociation/osrd/pull/9680 - can you check?

**Comment by louisgreiner** [comment]
@emersion 
After testing, it indeed seems to be fixed by #9680

**Comment by emersion** [comment]
Cool! Lets' close this then :)
