### ISSUE TITLE
Can't run a stdcm simulation

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#9335]
### What happened?

When trying to run a simulation, I get this even with different rolling stocks or paths

![Image](https://github.com/user-attachments/assets/e1d53344-c548-43f3-be17-41820f027b0f)

### What did you expect to happen?

stdcm works

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to stdcm
2. run a simulation

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by clarani** [comment]
Not reproduce recently, it seems not relevant anymore ✅
