### ISSUE TITLE
Design train reactions to signals

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#935]
Create an API which acts as a framework for programming the reaction of trains to signals.
The end goal is to have generic signaling modules control both how signals behave and how trains should behave regarding to signals

## Acceptance criteria

- [ ] Documentation is up to date on OSRD website
- [ ] The design must work for any signaling system
- [ ] The design must not be incompatible with trains catching up

## Difficulty

This user story is difficult.

**Comment by flomonster** [comment]
Legacy
