### ISSUE TITLE
front: space time chart: display occupancy blocks

### ISSUE THREAD

**Issue by Akctarus** [OpenRailAssociation/osrd#9365]
For the result of a simulation, the user must be able to view the occupancy blocks and their different types. The user must be able to choose which block to display.
BAL or BAPR signal status:

Green: lane free
Red: semaphore
Yellow: warning

**Comment by Castavo** [comment]
Found some problem for [this train](https://github.com/user-attachments/files/17507202/train_schedules.20.json): BAPR doesn't seem to be handled, we have some very large blocks instead

**Comment by Tguisnet** [comment]
The work is done.
There is maybe a bug, but it's seems to be back.

There is a follow up issue here : https://github.com/OpenRailAssociation/osrd/issues/9551
To pass states instead of colors, and to specify a signaling system to display in the get
