### ISSUE TITLE
front: the times in the conflict cards are incorrect

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#9454]
### What happened?

I created a train which leaves at 12h. I duplicated, the 2nd train also leaves at 12h.
I should see a conflict starting at 12h, but it starts at 10h:
![Image](https://github.com/user-attachments/assets/dcd1db2f-26a4-4262-adf7-3eeaa36a7cd2)

### What did you expect to happen?

I should see a conflict starting at 12h.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Create a train, which leaves at 12h
3. Create a second train without changing any inputs.
4. Display the simulation results, open the conflicts tab

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by bloussou** [comment]
Not fixed
![Image](https://github.com/user-attachments/assets/6dc08fef-20e5-44bf-ad43-8c5c72c894f3)
version: `staging 6d9ed21` on rec environment

**Comment by bloussou** [comment]
with a refresh it looks ok

**Comment by Maymanaf** [comment]
Fixed ![Image](https://github.com/user-attachments/assets/386177a6-92a6-4ce2-a4f1-dc8271801188)
