### ISSUE TITLE
stdcm: button to edit the op list should not be displayed

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9457]
### What happened?

This button does nothing in STDCM debug mode:
![Image](https://github.com/user-attachments/assets/15aff33a-73d6-49f8-ad8e-f3eb74e7be82)

### What did you expect to happen?

I should be able to edit the OP just like the operationnal studies mode.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM
2. Activate the debugging mode
3. Get a result
4. Try to edit the manchette

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

7451939

**Comment by clarani** [comment]
Fix: the button which allows the user to modify the ops list should be hidden (validated by @axrolld)
