### ISSUE TITLE
flake: should we use nixfmt-rfc-style instead of alejandra?

### ISSUE THREAD

**Issue by sofiedotcafe** [OpenRailAssociation/osrd#9473]
### How can we help?

Hey,

In the Nix flake, flake: should we use `nixfmt-rfc-style` instead of `alejandra`, since
> The RFC and by that `nixfmt-rfc-style` is very close to FCP and is going to make its formatting both official and enforced for Nixpkgs, so we expect that it become the community default. Minor changes to the formatting are still happening, and there are still bugs, but it’s very close.

Kind regards,
jh-devv

**Comment by flomonster** [comment]
Hi @jh-devv,

Thanks for your in interest in OSRD. We can migrate from `alejandra` to `nixfmt-rfc-style`. 
Would you like to make a PR for this change?
