### ISSUE TITLE
STDCM Space time chart time is UTC

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#9477]
### What happened?

All the time displayed in the space time chart is UTC

for example `/stdcm` request returns
![Image](https://github.com/user-attachments/assets/fe7525ba-c6ad-48a1-8d7a-d85d541d4ebb)

it is display as is, directly in UTC.
![Image](https://github.com/user-attachments/assets/8eca7884-8270-49f7-87c5-4c2800a36164)

### What did you expect to happen?

it should be displayed in user local timezone

### How can we reproduce it (as minimally and precisely as possible)?

do Any stdcm request and look at debug interface

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

86ad6408b1b1a567b691882dc1c3d543b4df9112

**Comment by clarani** [comment]
Can't reproduce it on dev and recette, maybe it's not relevant anymore

**Comment by anisometropie** [comment]
> Can't reproduce it on dev and recette, maybe it's not relevant anymore

yes, I resolved the issue with that locally as well. closed !
