### ISSUE TITLE
I can visualize BAL3 dynamic signals being modified when trains travel on the map

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#948]
## Acceptance criteria

A clear and exhaustive list of acceptance criteria that goes with this US.
- [ ] When the head of the train passes by a detector on the map, the BAL3 signal must turn red
- [ ] When the tail of the train passes by a detector on the map, the previous BAL3 signal must turn yellow
- [ ] When the tail of the train passes by a detector on the map, the 2nd previous BAL3 signal must turn green

## Difficulty

This user story is normal.

**Comment by elzinko** [comment]
@axrolld depends on accuracy bug #1365

**Comment by elzinko** [comment]
@alexandredamiron we cannot effort estimate this without you so we are removing this from the iteration board for now

**Comment by flomonster** [comment]
Legacy
