### ISSUE TITLE
Hide the `simulation-sticky-bar` until it's redesigned

### ISSUE THREAD

**Issue by theocrsb** [OpenRailAssociation/osrd#9511]
### Description and goal

For the moment, the bar has no real use and doesn't match the design. 
So we'll have to hide it for the time being.

**Comment by Castavo** [comment]
It looks like it's actually always visible now ![Image](https://github.com/user-attachments/assets/008d737b-632f-4f6a-80b3-e2383880f3e4)

I move the issue back in Todo just so we talk about whether it's linked to this one

**Comment by theocrsb** [comment]
On dev I don't see this bar when I edit a train:
![Image](https://github.com/user-attachments/assets/0efeae68-6a7a-42bf-8d4f-678323242221)

**Comment by Castavo** [comment]
Fixed in the latest recette, sorry for the noise (just wanted to make sure)

**Comment by clarani** [comment]
Validated ✅
