### ISSUE TITLE
STDCM: Arrival and departure time are not displayed in simulation sheet for VIA

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#9532]
### What happened?

In the simulation sheet:
![Image](https://github.com/user-attachments/assets/2735f606-bd80-4b44-bd63-477327743569)

In the simulation table:
![Image](https://github.com/user-attachments/assets/b8e8098e-61da-44ac-a0e9-a95c8e9366d0)

### What did you expect to happen?

Arrival and departure time are filled 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a STDCM simulation with intermediate OP
2. Retain the simulation
3. Download  the simulation sheet and verify

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

6d9ed21

**Comment by axrolld** [comment]
It should be like this actually
![Image](https://github.com/user-attachments/assets/e3017335-99ea-4fb0-9a9a-a4128f6c0add)

**Comment by axrolld** [comment]
The simulation table shows the outputs of the computation, while the header of the simulation sheet show the user input. It's normal that they're not the same :)
