### ISSUE TITLE
Path projection endpoint fails

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#9534]
### What happened?

Path projection fails with specific train schedules.

### What did you expect to happen?

The path projection should be successful.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario with this [trains_fails.json](https://github.com/user-attachments/files/17589075/trains_fails.json)
2. Observe the path projection call fail

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6d9ed21

**Comment by louisgreiner** [comment]
Another repro is : https://rec-osrd.reseau.sncf.fr/operational-studies/projects/62/studies/387/scenarios/930?selected_train=609080&projection=609080
