### ISSUE TITLE
Import Osrd menu in Last minute request app header

### ISSUE THREAD

**Issue by Math-R** [OpenRailAssociation/osrd#9569]
### Description and goal

What's this task about, and what is it for?

This task is about to implement the osrd's user menu in the last minute request header.

### Acceptance criteria

A list of conditions which define when this task shall be considered complete

- [ ] The component OSRDMenu must be reused
- [ ] The component must be display in the top right corner as in the [sketch](https://www.sketch.com/s/15e0909c-f17d-4200-a770-b9fc1154fa7e/p/A7A31C07-D8E9-42FE-B457-95C3C4F8BC21/canvas) next to the debug button
- [ ] the debug button is visible solely for the users who have the "super-user" role
- [ ] The public menu's options are the following : "Aide" and "disconnection"
- [ ] If the user has the "super-user" role, it can access to the "A propos" menu's option

**Comment by axrolld** [comment]
Latest mockup doesn't require this anymore, im' closing this issue
