### ISSUE TITLE
front: time fields already present in origin and destination when arriving on stdcm page

### ISSUE THREAD

**Issue by Erashin** [OpenRailAssociation/osrd#9575]
### What happened?

The fields `precise time`, `date`, `time` and `tolerance` are present in the `Origin` box.
The field `as soon as possible` is present in the `Destination` box.

### What did you expect to happen?

These fields should appear only once a CI is filled in the corresponding box (see https://github.com/osrd-project/osrd-tests/issues/76, Steps 9 and 14).

### How can we reproduce it (as minimally and precisely as possible)?

Open the STDCM page, and see the fields.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6d9ed21

**Comment by axrolld** [comment]
The test case isn't up to date anymore, actually the current behavior is the one we want, so that the interface is more stable
