### ISSUE TITLE
front: issues in the consist box in the stdcm page

### ISSUE THREAD

**Issue by Erashin** [OpenRailAssociation/osrd#9578]
### What happened?

1) When refreshing the page, the consist values are reset and not cached like the other values in the stdcm page. This causes an additional pb: if you reload, and try to launch a simulation without reselecting an engine, nothing happens, but you don't really know why.

2) What's more, the rolling stock's other characteristics (i.e. length, tonnage and max speed) are not filled in when selecting the traction engine, even though they seem to have default values, as can be seen in the pdf report generated once we have done a simulation.

### What did you expect to happen?

1) I expected the values to be cached. Please check with a maintainer/po, I don't know if this is wanted, but it seems weird.

2) I expected the default values to be filled in, as it seems they indeed exist. Same, check with a maintainer/po.

### How can we reproduce it (as minimally and precisely as possible)?

Fill a traction engine in the consist box. Refresh the page: no more traction engine.

Fill a traction engine in the consist box: the length, max speed and tonnage have no default values. Do a simulation, generate the pdf report: the length, max speed and tonnage have values.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6d9ed21

**Comment by axrolld** [comment]
Will be fixed by https://github.com/osrd-project/osrd-confidential/issues/815, i'm closing this
