### ISSUE TITLE
front: simulation button disappears

### ISSUE THREAD

**Issue by Erashin** [OpenRailAssociation/osrd#9581]
### What happened?

Tried a simulation. It failed: `Calcul non abouti`. While scrolling up, or maybe due to opening the browser console, `Calcul non abouti` disappeared, as well as the button to relaunch a simulation: i was stuck. Had to refresh the page.

### What did you expect to happen?

To keep seeing the simulation failed box and be able to launch another simulation.

### How can we reproduce it (as minimally and precisely as possible)?

Go to the stdcm page.
Try a set up that will fail (or make it fail with a timeout, works as well :D)
Simulation fails: `calcul non abouti`.
Hope scrolling or opening the console makes the result + simulation button disappear.
If they do, hope you understand why :)

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6d9ed21

**Comment by axrolld** [comment]
The idea behind this was that it was pointless to launch another simulation with the same inputs, so you need to change one input to make the button appear again, but i agreee this can be improved

**Comment by Erashin** [comment]
Duplicates https://github.com/OpenRailAssociation/osrd/issues/8533
