### ISSUE TITLE
Passing points have disappeared in the GUI

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#959]
**Describe the bug**
passing points have disappeared in the GUI

**To Reproduce**
1. Go to 'Home tab'
2. Add starting point and ending point on the map
3. Add passing point on the map

**Expected behavior**
Should see the passing point in the tab on the left side of the screen in order to add dwell time for example

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Firefox & Chrome

**Comment by alexandredamiron** [comment]
No more
