### ISSUE TITLE
Viriato import with 0 OP matched

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9594]
### What happened?

From a Viriato file import, if a train has no OCP matched with an OP (= we do not match every OP in our infra), the import is should not work.

See all "-1":
![Image](https://github.com/user-attachments/assets/7adf4758-f2dc-47c8-9e2f-fc2f90c077ac)

I also break the Macro mode, but it is rather a consequence that will be solved by the above bug

Linked to this [bug](https://github.com/OpenRailAssociation/osrd/issues/9610)

### What did you expect to happen?

When no stop is matched for a train, simply do not import it and console log it

### How can we reproduce it (as minimally and precisely as possible)?

Download the Viriato file ("MSC-AIX...") from this [folder](https://sncf.sharepoint.com/:f:/r/sites/OSRD644GrpO365/Documents%20partages/Donn%C3%A9es/3-Fichiers%20Viriato?csf=1&web=1&e=tsLWf3)

line 17 of this file, we see the OCP that is not match in our infra, used by the `trainPart id="tp_3_1975735"`

- import in operational studies
- notice 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev 95c1305

**Comment by maelysLeratRosso** [comment]
I could not see the red dots to show that there is only one point so I reopen the bug @RomainValls

**Comment by louisgreiner** [comment]
Did you try with the same file ? ("MSC-AIX...") @maelysLeratRosso

**Comment by maelysLeratRosso** [comment]
yes
I talked about it with @RomainValls , we'll talk about it on monday :)
