### ISSUE TITLE
MARECO not displayed on the speed-space graph

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#960]
**Describe the bug**
MARECO not displayed on the speed-space graph

**To Reproduce**
1. create a train
2. Add a allowance
3. see MARECO calculation'

**Expected behavior**
The MARECO curve has to be displayed on the Speed Space graph

**Comment by alexandredamiron** [comment]
It is because non automatic refresh

**Comment by axrolld** [comment]
I think this issue is deprecated. If not feel free to re-open it.
