### ISSUE TITLE
Can't access anything on `dev` anymore

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9612]
### What happened?

Most likely due to the roles that have been implemented. I guess the features works well but we all need the `super_user` role now.
![Image](https://github.com/user-attachments/assets/5bb727b5-5805-490f-92ac-11e2cf587ada)

### What did you expect to happen?

The OSRD Team should have acess to the entire app.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to https://[dev](https://dev-osrd.reseau.sncf.fr/)-osrd.reseau.sncf.fr/

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

pr 9602 (merge of fam/fix-user-identity@1e971f6 into dev@bfa5205)

**Comment by flomonster** [comment]
Not a bug, you have to ask for access
