### ISSUE TITLE
stdcm - times in the pdf simulation sheet are not correct

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#9626]
### What happened?

I created a simulation (see pdf below to see the asked OPs).
The simulation works so I export the pdf file.
But in the file, one can see that the train goes from Iwuy to Caudry in 0 minutes (21:12 for all points in between). But in reality, when I compute the travel time between these 2 points, it is 14 minutes. 

[STDCM-1124-671-555.pdf](https://github.com/user-attachments/files/17660515/STDCM-1124-671-555.pdf)

### What did you expect to happen?

I expected to have the real times

### How can we reproduce it (as minimally and precisely as possible)?

create a simulation with the input of the attached pdf file

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

pr 9602 (merge of fam/fix-user-identity@1e971f6 into dev@bfa5205)

**Comment by Arthur-Lefebvre** [comment]
Here a simulation with the described beaviour :
Project Imports BASIC
Study : Import entre 6 Nov 2024..
Grid : Grille STDC... 4290

![Image](https://github.com/user-attachments/assets/fd426ac0-dc1a-425d-b5ee-0174dfda43b4)

[STDCM-1124-777-300.pdf](https://github.com/user-attachments/files/17663367/STDCM-1124-777-300.pdf)
