### ISSUE TITLE
Towed rolling stocks with max speed at `0km/h` mess up the consist building

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9637]
### What happened?

The consists are build with the formula:
`max_speed = min(max_speed_traction_engine, max_speed_towed)`

but when there's no data for the max speed towed the value is actually 0km/h, so the consist has a 0km/h value ⚙ 

### What did you expect to happen?

We should not take into account max_speed of towed rolling stocks if they are at 0km/h

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Recette (SNCF), Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

b74fd59

**Comment by woshilapin** [comment]
I'm not entirely sure I agree with the reasoning. The problem not taking 0 km/h as a value is that, we then can take 0.000000001 km/h as a value, which is probably as much problematic. But then comes the question of "which threshold is reasonable, is it 0.001, 0.1, 10?". I can understand rejecting negative values, but the zero, not so sure. Unless we're capable to prove that for some threshold value, we won't have simulation problems, I'd rather not try to be smart and stick with "zero is fine in the backend, we can display a warning in the frontend". What do you think?

**Comment by bougue-pe** [comment]
> Context: max-speed is an implicit upper boundary for some ETCS braking curve in undergoing work, and I'm willing to understand if this is a bad idea (not handling towed rolling stock so far, but this is a legitimate future target).

@axrolld Does it make functional sense to have a towed rolling-stock without a max-speed?
If not, then I suggest another way to handle that bug: make our data processing more resilient, not our data model more lenient (and less realistic) and opt for infinity value instead of 0 when no data is provided.

**Comment by axrolld** [comment]
Some of our towed rolling stocks are just a model and are not representing a physical wagon, so they have a 0km/h max speed because they don't actually have a max speed. It means they are not modifying the max speed of the consist. I guess the max_speed field of towed rolling stock should be optionnal.
