### ISSUE TITLE
Input table doesn't display all OPs if we drag the scroll bar

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9651]
### What happened?

on this [scenario](https://rec-osrd.reseau.sncf.fr/operational-studies/projects/62/studies/387/scenarios/937?selected_train=609455&projection=609455)

If we drag the scroll bar, the op list is not complete, we need to scroll

https://github.com/user-attachments/assets/a7819bed-08e4-4384-acfa-9070f938d5be

### What did you expect to happen?

can be able to see everything with dragging the scroll bar

### How can we reproduce it (as minimally and precisely as possible)?

1. open https://rec-osrd.reseau.sncf.fr/operational-studies/projects/62/studies/387/scenarios/937?selected_train=609455&projection=609455

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging cd4cdfb

**Comment by theocrsb** [comment]
I couldn't reproduce the bug on the linked scenario

**Comment by Castavo** [comment]
Neither can I (I'm on windows with firefox)

**Comment by louisgreiner** [comment]
Can't repro and seemed to be fixed on my side also
