### ISSUE TITLE
Selecting float budget gives unreadable error in project

### ISSUE THREAD

**Issue by Akctarus** [OpenRailAssociation/osrd#9662]
### What happened?

Float budget gives error

### What did you expect to happen?

I expect the field to be highlighted in red, with a clear message stating that float numbers are forbidden

### How can we reproduce it (as minimally and precisely as possible)?

Go to operational studies page
Open project creation form
Enter the name and a floating point budget
Click on save, witness

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

f05eecf

**Comment by clarani** [comment]
Validated ✅
