### ISSUE TITLE
lmr: front: shorten the composition code list by only using the ones from the LMR infrastructure

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9682]
# Description

Currently the composition code list in LMR is composed by all codes in OSRD, including all the ones from all the infrastructures. Only the ones associated to the infrastructure LMR is using are relevant in that case.

# AC

- [ ] The composition codes visible and selectable in LMR are the ones from the infrastructure LMR is based on

**Comment by bougue-pe** [comment]
@axrolld :
To make it more explicit, the choice done in associated PR is to show the fixed list of validated composition codes relevant for STDCM.
Short tags are the only one kept as:
* there is a fallback hierarchy available for them (not for long tags, so it would be misleading)
* any up-to-date infra is using only short tags (using outdated infra will lead to using no speed-limit tags at all, but it's not much worse than no hierarchy)

Short tags are all kept without caring about what is in infra, as:
* the fallback hierarchy works for those not present in infra
* filtering to match long/short following what's in infra would be a bigger logical deal, deemed unworthy given the gain (not supposed to use outdated infra, and no hierarchy for long tags)
