### ISSUE TITLE
stdcm: "Sillon antérieur" and "Sillon postérieur" are not disabled during calculation

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9711]
### What happened?

https://github.com/user-attachments/assets/38b40a65-47b3-4577-b478-cbb46e1981f7

### What did you expect to happen?

disable these buttons while calculation

### How can we reproduce it (as minimally and precisely as possible)?

1. start a simulation

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging cd4cdfb

**Comment by axrolld** [comment]
Duplicate with #9807 (my bad i opened that one after and didn't see the duplication)
