### ISSUE TITLE
All entries of input table are bold

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9732]
### What happened?

Everything is in bold in the input table

![Image](https://github.com/user-attachments/assets/a8430071-cf00-491b-88d2-76faa20f4ff9)

### How can we reproduce it (as minimally and precisely as possible)?

1. create any train schedule
2. open input table

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

rec

**Comment by clarani** [comment]
Validated ✅
