### ISSUE TITLE
front: pathfinding error not handled

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9762]
### What happened?

[train_schedules.json](https://github.com/user-attachments/files/17803344/train_schedules.json)
 
When editing the first train "X", this error occurs

![Image](https://github.com/user-attachments/assets/5adeb23a-2773-417b-84d8-df497df1bc04)

### What did you expect to happen?

Translate the error and deal with the error

### How can we reproduce it (as minimally and precisely as possible)?

1. import file
2. open 'X'

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev

**Comment by RomainValls** [comment]
The path doesn't seem to correspond to the json. And can't reproduce the bug, I only see a pop up in the top left. 
![Image](https://github.com/user-attachments/assets/f773a68b-b909-4563-863a-4f289f176ade)

**Comment by louisgreiner** [comment]
Can't repro (might be fixed by recent work on error messages from front-end), will re-open if happens again
