### ISSUE TITLE
stdcm: deceleration rate doesn't change when changing towed rolling stock

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9806]
### What happened?

I simulated a train between PLF 00 and BGB P1 with a 22200G and different towed rolling stocks. The deceleration doesn't seem to change, though it's supposed to.

Here's the graph for a towed rolling stock RMI2N3M:
![Image](https://github.com/user-attachments/assets/c0c395e5-2727-4420-a363-42f02d93e6ec)

And with MA, that's supposed to have a deceleration rate 3 times lower:
![Image](https://github.com/user-attachments/assets/582cf60d-e07d-47b8-84d9-c96d3b860e31)

### What did you expect to happen?

The consist should have a deceleration rate that's the minimum between the one from the traction engine and the towed rolling stock.

### How can we reproduce it (as minimally and precisely as possible)?

1. try simulating a path with the towed rolling stocks i cited above
2. notice no difference in the deceleration curves

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

6be0604

**Comment by Castavo** [comment]
This is actually a data problem, our towed rolling stocks all have the same deceleration at the moment

**Comment by axrolld** [comment]
Should be completed once https://github.com/osrd-project/osrd-dags/issues/631 is done.
