### ISSUE TITLE
The route between the origin and destination is not properly drawn

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#9809]
### What happened?

The drawn route exceeds the destination marker
![Image](https://github.com/user-attachments/assets/fbdf672f-39f7-4c10-b43f-98f6eac9d6b6)

### What did you expect to happen?

The route should be limited by the destination marker

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to LMR
2. Start a simulation with Miramas as destination 
3. Observe result map

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

6be0604

**Comment by SharglutDev** [comment]
Tried to reproduce it with a Valence - Miramas but it seems to work as expected : 
![Image](https://github.com/user-attachments/assets/4c5bcaa4-1e8b-491a-a3b9-2fcc8f01d9c6)

Do you remember of a special usecase for this issue ? (tried with Miramas 98 but still no issue)

**Comment by Maymanaf** [comment]
You can use this case : 
![Image](https://github.com/user-attachments/assets/8dc7b98d-01fc-4bbc-82b6-5c8b966b4786)

**Comment by SharglutDev** [comment]
Still the same :/ (same with BP & 98)

![Image](https://github.com/user-attachments/assets/f1151ab7-926a-46cd-a915-1f0fb9f582b0)

**Comment by Maymanaf** [comment]
Maybe it's related to RS can you use : BB 26000 (BB 26000) -- 26000US

**Comment by SharglutDev** [comment]
It was already this one I used (you can see it in the result table). @Akctarus couldn't reproduce it either (on dev)

**Comment by axrolld** [comment]
should we close this issue if it cannot be reproduced ? @Maymanaf can you try again and close it if the bug is fixed ?

**Comment by Maymanaf** [comment]
unable to reproduce
