### ISSUE TITLE
Stdcm results table width no matching the mockup

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#9886]
### What happened?

App : 
![Image](https://github.com/user-attachments/assets/db721b23-95e5-4533-92da-25f0ba6e5cbf)

Mockup : 
![Image](https://github.com/user-attachments/assets/7c51eadd-ff90-4c96-98d8-8aaa687139eb)

### What did you expect to happen?

- [ ] Both map should be aligned
- [ ] Table should be shrinked, @thibautsailly will give the column to resize and the values

### How can we reproduce it (as minimally and precisely as possible)?

Go to stdcm page and launch a simulation

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by thibautsailly** [comment]
Here are the dimensions
![Image](https://github.com/user-attachments/assets/58fcaf33-5442-42c1-ba59-8eca7fea4155)
The map behaves just like the one above in width adjustment and viewport stickiness when scrolling the result's OP list (in a future update, clicking an OP will center it in the map).
