### ISSUE TITLE
No CH available after a few seconds when looking for Perrigny-Triage with trigram

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9888]
### What happened?

I looked for Perrigny-Triage typing"DPY" in the combo box. I found the right CI but after a few seconds the CH list disappears and i can't select any CH anymore.
![Image](https://github.com/user-attachments/assets/4ee9e032-4326-42d0-b8e7-5092db2f472f)

### What did you expect to happen?

I'm expecting the CH list to work properly. I don't know if it has to do with the combo boxes bugs but this one's really odd.

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce the steps in the description.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

deac2f4

**Comment by SharglutDev** [comment]
Can't reproduce this. Did you interact with other part of the form before the ch disappeared or you just waited for it ?

**Comment by RomainValls** [comment]
I also can't reproduce the bug

**Comment by axrolld** [comment]
Can't reproduce it either, i'm closing the bug :) Thanks for investigating guys !
