### ISSUE TITLE
stdcm - inputs displayed don't change if several simulations

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#9889]
### What happened?

> [!IMPORTANT]
> This bug does not happen only on the time input. All the inputs from "Origine" seem to behave that way, and probably destination too. See [this comment](https://github.com/OpenRailAssociation/osrd/issues/9889#issuecomment-2523190165).

I have two simulations : 
- A first one which starts at 20h ![Image](https://github.com/user-attachments/assets/1026bbde-aa0d-49bb-97cf-206be87c7900)

- A second one which starts at 21h ![Image](https://github.com/user-attachments/assets/c0185934-29d6-4a3c-b96f-a017ea8f2599)

But when I navigate between the two simulations, the inputs are the same for both (the inputs of the 2nd simulation) : if I go to the first simulation, the departure time is 21h instead of 20h ![Image](https://github.com/user-attachments/assets/1caf92b1-54b5-40bd-b2d9-56fc6866b981)

### What did you expect to happen?

I expected the input to be adapted to the selected simulation

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a 1st simulation which starts at 20h
2. Create a 2nd simulation which starts at 21h
3. Go back to see the first simulation and observe that the time is 21h and not 20h

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

deac2f4

**Comment by axrolld** [comment]
Bug's still here. Actually all the fields from the "Origine" remain when switching simulations, not only the time. The parameters of the consist seem to change correctly though.
