### ISSUE TITLE
front: editing a train with power restrictions resets its power restrictions

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#9902]
### What happened?

When clicking on 'edit' for a train which has power restrictions, the power restrictions are automatically reset.

### What did you expect to happen?

The power restrictions should not be reset when clicking on editing

### How can we reproduce it (as minimally and precisely as possible)?

1. Open a scenario
2. Add a train with power restrictions (you can use a TGV)
3. See the results
4. Click on edit the train
5. See the warning displayed

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

**Comment by axrolld** [comment]
Still present on `staging 6580cfe` with this schedule:
[bug_power_restrictions.json](https://github.com/user-attachments/files/18198448/bug_power_restrictions.json)

Pathfinding seems launched twice, or at least i get two warning messages saying the power restrictions have been reset when editing the train.

Also the weird thing is after saving it i can't see the power restrictions in my space speed chart:
![Image](https://github.com/user-attachments/assets/6ab0a090-0b21-496f-9de6-8b7eae1bda29)
